### ISSUE TITLE
Suggestion: Encyclopedia/Codex

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#10]
The game's pretty in-depth so far, although for some players it would be a bit overwhelming. I for one got a little confused at the new units and the CO unit system (because I've been playing AW2 recently). I also miss the "R" button to check out the units' stats occasionally.Perhaps there should be some kind of in-game database explaining the new units and structures. Perhaps you could also use it to elaborate on the various factions, as well as have more of a lore dump on the COs, both old and new, as well as some of the game mechanics that not everyone knows about.

**Comment by Robosturm** [comment]
My suggestion would be the following.
I would split it up. in 3 features.
* a wiki that can show the infos below + additional texts\wiki entries about armies etc. This one will take a longer and probably some work from others.
* Unit Info -> showing Movement Costs over terrains. Base Damage against all units, normal stats like movement type ammo... some info text like in Advance Wars Series
* Terrain -> some info text like in Advance Wars Series + Movement Costs for all Movement Types

**Comment by GuardianTempest** [comment]
Pretty good, I'm okay with it. For the wiki, don't forget terms that new players might not understand like Luck Range and other stuff that was referenced in CO abilities.

**Comment by Robosturm** [comment]
What do you think of the wiki so far?
[https://github.com/Robosturm/Commander_Wars_Images/blob/master/Gameplay44.png](url)
[https://github.com/Robosturm/Commander_Wars_Images/blob/master/Gameplay45.png](url)

**Comment by GuardianTempest** [comment]
Good work so far. My only nitpick is that the team's current house color makes distinguishing the various urban terrain types a little harder to distinguish. Perhaps for the movement section the buildings could be the unaffiliated white for demonstration purposes. That's just me.

**Comment by Robosturm** [comment]
That's easy i just delete one line of code. :D 
Now it would look like this and i added some basic information as well.
Oh and you can get the information before you build a unit. 
![Gameplay46](https://user-images.githubusercontent.com/48879701/62280520-61a18400-b44c-11e9-80d0-f34e53bdb188.png)

**Comment by GuardianTempest** [comment]
Ooh that's wonderful!

I wonder, is there a new button keyed to this yet?

**Comment by Robosturm** [comment]
Yes the button is "i" for now cause i stands for information.
-> still needs to make it into a tutorial though some for the transport system + probably a thousand other things i don't know or missed. 😃 
You can change that in the option menu though.

**Comment by Koopanique** [comment]
I agree with GuardianTempest, this looks both useful and pretty! Only thing missing is a picture of the unit in question on the right of the screen ^^ With all that empty space next to the stats, it looks like it would fit there.

> "still needs to make it into a tutorial though some for the transport system + probably a thousand other things i don't know or missed."

Thinking about it, a full fledged pdf manual would be an interesting endeavour.

**Comment by Robosturm** [comment]
added some more Terrain Info and added the standing battlesprite to the information about units.
Now it looks like this:
![Gameplay47](https://user-images.githubusercontent.com/48879701/62386749-01e4cf00-b559-11e9-9c90-d352260e94cc.png)
![Gameplay48](https://user-images.githubusercontent.com/48879701/62386750-01e4cf00-b559-11e9-8b5c-18498b6cf118.png)

Well someone would have to do the pdf and i neither have skills nor the motivation to so.
The wiki won't get a whole lot of content from me either.
That needs work from other dudes.

**Comment by Robosturm** [comment]
Added wikipage framework.
Take a look here on how to add pages.
[Ingame-Wikipage-Framework](https://github.com/Robosturm/Commander_Wars/wiki/Ingame-Wikipage-Framework)

![Gameplay49](https://user-images.githubusercontent.com/48879701/62645123-e2c8b180-b94b-11e9-9611-d9f2230c0a80.png)
![Gameplay50](https://user-images.githubusercontent.com/48879701/62645122-e2301b00-b94b-11e9-85a8-e2bbc5543c7a.png)

**Comment by Robosturm** [comment]
I also added that you can get information by pressing i about a certain actions inside a menu.
So what does unloading do again can now be accessed in the game.

@GuardianTempest and @Koopanique Thx for your request and help with this feature
![Gameplay51](https://user-images.githubusercontent.com/48879701/62724713-df98f880-ba13-11e9-821f-efa5bb06bcbc.png)

I'm going to close this request tomorrow. 👍
