### ISSUE TITLE
CO styles: RGB values should update when you click on one of the color boxes

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1000]
Originally brought up by Rephath in the Discord server, when you click on a color box in the CO style edit screen, the RGB values should update accordingly instead of staying at the default value of "255, 255, 255".

This would also make it easier to adjust the shade of a pre-existing color, like if you want to make it darker for example.

**Comment by Rephath** [comment]
I'm Rephath in the Discord and I approve this message.
