### ISSUE TITLE
Several maps have no default win conditions

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1003]
I was playing maps as Sami and I would capture the HQ then defeat all enemy units and still not win. I'm guessing that certain maps made by a specific user don't have any victory conditions checked by default, so unless you're paying attention, you can't win. I'll check to see if that holds up.

**Comment by Rephath** [comment]
Precipitation is an example. You might want to check all of Everglass's maps.

**Comment by Rephath** [comment]
Update: Changed the default options for Precipitation and that did it. I know this isn't the buggiest of bugs, but it's annoying that if you're not carefully interrogating every one of the default options, you can't possibly win. And I bet your players will appreciate your fixing that.

**Comment by Robosturm** [comment]
I won't go through all maps since i don't know which maps are made by Everglass.
Please report the maps affected here

**Comment by Rephath** [comment]
I only remember the one. I was hoping there was some way you could easily
ctrl + F through the code and find everything where things were set to
false where they should be set to true.
