### ISSUE TITLE
Kindle Rockets Crash Game

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1004]
I'm firing on tanks with Kindle rockets on bases. (Yes, I'm base-blocking myself; don't judge.) It's started crashing the game. I have no idea what's causing it, but I have a save file available if you're interested.

**Comment by Rephath** [comment]
Update. A tank attacked my antitank and that also crashes the game.

**Comment by Rephath** [comment]
Update. It seems any unit that destroys a tank crashes game.

**Comment by Robosturm** [comment]
Can you check if in the achievement menu if one more killed tank would grant you an achievement?

**Comment by Rephath** [comment]
Yes. 299/300 on tanks. That would explain.

**Comment by Rephath** [comment]
So, is there a quick fix I can do to bypass that bug for now so I can keep playing?

**Comment by Rephath** [comment]
Is this what you need?
