### ISSUE TITLE
Quality of Life for Newbies

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1005]
I get that there's a lot you're wanting to do and being asked to do. But your game is very intimidating for newbies. You've got tons of options, but there's obvious buttons to press or path to take to start having fun. I had to look around for awhile to figure out how to start a campaign, and for the quick maps, there's a lot of extraneous options. After you mess with it for an hour or three, you start to get the hang of it. But I'm betting you're losing players who don't stick around that long.

**Comment by Robosturm** [comment]
This is something Fairy wanted todo but didn't continue yet

**Comment by Robosturm** [comment]
Initial improvement done
