### ISSUE TITLE
Move Infantry to Point

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1008]
So, this game requires me to build a lot of infantry. Okay, I can live with that. What I'd like is to be able to right-click a point on screen, and the AI automatically moves all unmoved infantry of mine toward that point, rather than me having to click each one. It'd shave some time off my play.

**Comment by Robosturm** [comment]
There's no real solution i can imagine which would work and makes you less clicks.
If you want to move units over multiple turns to a location use the multi-turn-move feature.
But moving multiple units in one turn to a locations ends up in a mess in a tbs game
