### ISSUE TITLE
Julie's SCOP is too cheap

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1009]
Eagle's SCOP allows all non-infantry units to move twice. Julie's SCOP freezes all enemy units, basically having the same effect. Except her infantry can move twice. And it also gives her and her opponent double income, except she can use all her bases twice and the opponent can't. And it weakens her troops but lets them fight as if they were all max health regardless of damage. All for the same price. I don't know how much you're going for balance, but I thought I'd mention it.

**Comment by Robosturm** [comment]
To be honest balance was never an option though i may consider changing the scop cost
