### ISSUE TITLE
The increments to increase Startfunds by arrows should be greater then 1

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#101]
A minor detail, but the increments at which the value under Startfunds in the pre-game set up screen should increase by values of 1000 or 500 when using the arrow widgets. The arrow buttons should be a tool to quickly rise or lower the value amount while alleviating the need to type a more specified value. 
![Startfunds](https://user-images.githubusercontent.com/58909501/71621511-f7bd1000-2b8c-11ea-994a-da5606f6afd4.png)

**Comment by Robosturm** [comment]
Makes sense.
