### ISSUE TITLE
Changing Players in Map Editor Crashes Game

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1010]
I'm making my own campaign map. By default, it had 4 players, but I wanted 2, so I went in and changed it to 2 players. As soon as I hit "ok", it crashed. Booted it up and tried again. Same issue.

**Comment by Rephath** [comment]
Update. Looks like I had a CO in 1st and 2nd position, but units accidentally placed for the 3rd position. Once I resolved that, it stopped crashing. You'll probably want to have an error message instead of a crash.

**Comment by Robosturm** [comment]
It should not crash but remove the units sounds like a surprise feature
