### ISSUE TITLE
Dialog Entry Doesn't Like Ampmersands add filter to prevent inputing special chars to text input

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1012]
When I try and put a & symbol in the dialog, it messes things up. Small fix, not sure if you want to do anything about it.

**Comment by Rephath** [comment]
Specifically it clears and freezes the dialog box and I can't do anything with it except delete it.

**Comment by Robosturm** [comment]
Yes those signs are not supported and are not meant to be used currently no filter to avoid this exists but in any case special chars like that are forbidden.
