### ISSUE TITLE
Victory Conditions Wrong

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1015]
I put a time limit on a map, 15 turns, and set it up so that if the game reaches that time limit, player 1 wins. It functions correctly, but if you look at terms midgame, it says everyone loses. To clarify, the infobox says they'll lose at the end of 15 days when they'll actually win.
![image](https://user-images.githubusercontent.com/22900774/180592435-3f476b06-eb13-4ddf-8541-9e9370716f3b.png)

[Crystal Crater.zip](https://github.com/Robosturm/Commander_Wars/files/9173175/Crystal.Crater.zip)

**Comment by Rephath** [comment]
Also, while you're working on that section of code, there's a typo. It should say "lose" not "loose".

**Comment by Robosturm** [comment]
It's not a typo but my bad english. :D
