### ISSUE TITLE
Automoving Infantry Show Up in Upper-left Corner

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1016]
When I use the move planner to set up how I want infantry to move, sometimes they teleport from somewhere on the map to the upper-left corner for some reason. It's not a big issue, but I thought I'd mention it.

**Comment by Robosturm** [comment]
I think you mean units which have the option to move over multiple tiles warp sometimes right?

**Comment by Rephath** [comment]
Yeah.
