### ISSUE TITLE
Ship Bridges Doesn't Work

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1017]
I can't get ships to move over bridges regardless of what I do. I tried checking the box, unchecking it, lake vs. sea, all sorts of things. Ships can't move over bridges regardless of what I do.

**Comment by Robosturm** [comment]
Which bridge do you use the AW-Dor or AW2-Style?
And do you place them on sea or river?
You need to use the dor-styled bridges on water.

**Comment by Rephath** [comment]
That resolves it. Thank you.
