### ISSUE TITLE
co.getMovementpointModifier function is called on a unit with posX = -1 and posY = -1.

### ISSUE THREAD

**Issue by bajing-jalan-jalan** [Robosturm/Commander_Wars#1018]
**Describe the bug**

When using the A.I. (normal), the co.getMovementpointModifier function would often be called on a "ghost" (?) unit located at (-1,-1). A function call such as map.getTerrain(posX, posY) would return null and sometimes cause ground units to move to sea tiles, thus displaying this error message on the debugger:

NormalAi::moveUnit invalid action calculated

Here's a snippet of the code that would return a null terrain because posX = -1 and posY = -1.

co.getMovementpointModifier = function(co, unit, posX, posY, map)
{
    if (co.getIsCO0() === true)
    {
        if (map !== null)
        {
            if (unit.getOwner() === co.getOwner())
            {
                var terrain = map.getTerrain(posX, posY);
                if (terrain === null)
                {
                    //sometimes a unit at (-1,-1) may occur, resulting in a null terrain
                    GameConsole.print("This should not happen!. Location at (" + posX + ", " + posY + ")", 1)    
                    var units = co.getOwner().getUnits();
                    GameConsole.print("Available units : ", 1)   
                    for (var i = 0; i < units.size(); i++)
                    {
                        var unitx = units.at(i);
                        GameConsole.print("Unit at (" + unitx.getX() + "," + unitx.getY() + ")", 1);   
                     }
                }
       ...etc

Here, the debugger would print the following messages:

This should not happen!. Location at (-1,-1)
Unit at (4,2)
Unit at (4,3)
Unit at (5,2)
Unit at (7,4)

As shown above, the "ghost" unit belongs to the CO being called in the function, but upon listing the CO's units, there is no such unit located at (-1,-1).

**Comment by Robosturm** [comment]
This the correct behaviour e.g. when the ai tries to build a unit it calculates stuff with a dummy/ghost unit which isn't placed on the map. It's a task of the code to check if a given position is on the map or not using the function
map.onMap(x, y)
