### ISSUE TITLE
Script Editor reads conditions check variable and terrain destroyed wrong

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1019]
I thought it was just my mistake but it happened several times in a row now. I'll set up a bunch of different variables with conditions, then save. Then I exit, test the map, come back, only to find that some of my conditions are mashed together or deleted and their content is gone. This kills most scripting functionality as it requires the user to continually recreate their code as sections are lost.

**Comment by Rephath** [comment]
Sorry, here's the actual image (I think) Most of these conditions should be separate and there should be a bunch of stuff under events but that all got deleted.
![image](https://user-images.githubusercontent.com/22900774/181653063-71e3ded3-cb03-45a6-bb8f-1277d87406b9.png)

**Comment by Rephath** [comment]
![image](https://user-images.githubusercontent.com/22900774/181653121-cd3ce845-b8c1-423b-8508-dc6e21f4b2e4.png)

**Comment by Robosturm** [comment]
Please qttach script you saved so i can check it.
The game writes js code and reads it back my guess is that one of the markers is broken but i need the script to find the issue
