### ISSUE TITLE
Deployed the same CO on a second unit after unloading a unit that had the original CO

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#102]
I don't know if this was tied to the lost of the co zone that you've already addressed, but shortly after unloading a unit with my second co in, when choosing to co another unit, that same co was available to use as promotion.
![TwoCOs](https://user-images.githubusercontent.com/58909501/71623404-8f286000-2b99-11ea-8c12-0dd21e7a3771.png)
As seen in the picture, after unloading my anti-tank cannon off my lander, I went to promote my mid. tank and found that I could promote it with the second CO which had already been deployed. I have two units with the CO 2's medal.

**Comment by Robosturm** [comment]
Good you found that one...
This can lead to some really bad and weird interaction.
