### ISSUE TITLE
Script editor building spawn limitations

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1020]
When spawning buildings, I can't choose who owns said building. I also can't change which orientation black cannons have.

**Comment by Robosturm** [comment]
As for the owner this is intentional since you can change the owner of a building on a map via script. The script editor is limited due to the overhead/impossible solution to make everything possible.

**Comment by Robosturm** [comment]
Each of the black cannons represents a different direction. The ui elements are from a time where displaying sprites in the drop down menu wasn't possible.
I'll change that so you can see which item represent which direction.

**Comment by Rephath** [comment]
I tried different black cannons and they all faced the same way.

**Comment by Robosturm** [comment]
Might be a bug related to the old input version i checked the generated code after i changed the code to show icons instead of a text and that is correct.
