### ISSUE TITLE
Script Editor Doesn't Handly Modify Unit Correctly

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1022]
I want to spawn in some units at low HP. The spawning works fine, but I have to modify them after the fact. No problem. Except when I write a list of modifications to implement, it keeps moving the numbers I input lower down. So I'll have the health of each modified by -9 and then save and reload and it'll have ammo -9 on one and fuel -9 on another. I'll send you my script via Discord.

**Comment by Robosturm** [comment]
Once again an issue with the reader. :(
