### ISSUE TITLE
Request: Performance optimization for Windows 11

### ISSUE THREAD

**Issue by Nobelium-Uranium** [Robosturm/Commander_Wars#1023]
While it does indeed run on Win11, the performance leaves much to be desired. If it could be optimized for use in Windows 11, that would be excellent.

I make this request because I recently switched to a computer with Windows 11 installed with no way to go back to Windows 10 (aside from my old computer, but it's a pain to switch between computers whenever I want to comfortably play or make mods for CoW), and thus I have to deal with the reduced performance for the time being.

If you don't have a computer with Windows 11 yourself, I could assist with testing the performance improvements.

**Comment by Robosturm** [comment]
My guess you need to compile it yourself with win 11
Since it works fluent with android my guess it's win 11 problem and nothing will be done here from my end.

**Comment by Robosturm** [comment]
@Nobelium-Uranium What you could check is if a qnti-virus program is running and reducing the performance  since cow calls javascript all the time...
