### ISSUE TITLE
Condition Based on Chosen CO in Script Editor

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1027]
So, I think it'd open up a lot of options in the script editor if I could add things that happened based on which CO the player picked. For example, maybe I could write custom dialogue for each CO and then depending on which CO the player picked as their main or secondary, that dialogue would or wouldn't play. Similarly, I could spawn certain units based on what's appropriate for the CO.

**Comment by Robosturm** [comment]
Technical already possible by writing the codw by hand and done in aw 1 campaign
