### ISSUE TITLE
Teleport Tile Crash

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#103]
It is hard to pinpoint exactly what is causing the crash, but maps that have teleport tiles are now prone to crashing the game, even though they worked crashlessly in the previous Release (0.7.0).

I cannot pin down exactly what the cause of this crash is at this moment unfortunately, but I thought I'd bring it to your attention either way.

**Comment by Robosturm** [comment]
Coud you give me an example map?
Or does it always happen?
