### ISSUE TITLE
Running the game in a console only environment for server hosting

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1033]
**Is your feature request related to a problem? Please describe.**
Currently the game does not run in a console only environment. The suggested steps can be found on the guide here https://github.com/Robosturm/Commander_Wars/wiki/How-to-setup-a-dedicated-server

So  running the game one could do as following:

`./Commander_Wars -noUI -noAudio`

However, the game will still attempt to run GUI calls, despite these parameters, for which reason it isn't possible to run it from the command line, without GUI on the server. 

**Describe the solution you'd like**
Ideally, a new compilation of the game without any GUI calls, should suffice to make it run on server environments. This however would require refactoring or changing the QT components of the game.

**Describe alternatives you've considered**
Most hosting providers, offer Linux servers as the primary ones, which is the reason behind this request. However Windows Servers do exist, which support Graphical User Interfaces. The game server option could be labelled as 'Windows Server exclusive'.

**Comment by Robosturm** [comment]
It's not doing graphic calls as far as i understood you tried to link against the game with static libs which is where the problem occurs from, if ot gets dynamical loaded the game shouldn't load the lib since it's b
not calling those functions.
It's also not possible to remove all ui calls from the compilation....

**Comment by Robosturm** [comment]
@lonewolf19991 could you try using the latest code state?
I've removed opengl and qwindow dependecies from build if the game gets compiled with no graphic support.

**Comment by lonewolf19991** [comment]
I ran the latest build, and a window does not try to open when the parameter is run, I will test it on a real server soon and reopen if anything new related to that should arise.
