### ISSUE TITLE
Change Seamine functionality 

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1034]
Seamines, as they are now, are (in my opinion) not enjoyable at all to play around.

They are both incredibly punishing and incredibly hard to get rid of, as once you run into them, there are very few ways to get rid of them.

In addition, their splash radius also means that sometimes, the person deploying them gets punished.

Furthermore, this big splash and the start-of-turn explosion aren't particularly realistic, either.

Here's my proposal on how to make them more fun:
1 - Instead of exploding at the start of a turn, make them explode if a ship gets trapped by them.
2 - Make the explosion only hurt the unit that got trapped.
3 - If a "minesweeper" unit runs into a Seamine, the Seamine is harmlessly deleted (I propose the Black Boat for this role). Also allow this unit to remove Seamines (both Allied and Enemy)
And optionally:
4 - Make the damage Seamines do based on a weapon rather than flat damage, so different ships suffer differently from running into them.

This would have the following effects:
1 - Knowledge of where seamines are allows you to better play around them, as the spaces around them are now safe, making the sea less clustered
2/4 - Seamines are now a much less OP weapon, dealing a more reasonable amount of damage for how easy they are to use.
3 - Seamines are now easier to fight against, and you can actually clean them up.

**Comment by FranticFairy** [comment]
Personally, I think the Black Boat fits this role better for a variety of reasons.
1 - It's got big claws that I can imagine could be used to remove seamines.
2 - It means that the unit capable of removing mines is not a frontline combat ship, meaning that it will be a seperate investment. Allowing Cruisers to easily clear mines almost entirely defeats seamines since Cruisers are also effective combat units, and something you are likely to have regardless of whether or not you run into mines.

**Comment by Robosturm** [comment]
1 - Realism is no argument. Not in a game that is totally unrealistic in so many ways
2 - Giving the black boat even more utility (capturing, repairing, transporting units is nothing i'm willing to do) --> Cruiser or Canonboats are the only units i think can be considered to do so
3 - Making different damages to different units is nothing i'm going to do. Here simplicity over realism wins in my opinion.
4 - Removing allied seamines also something i'm not going to do simply cause interactions with allied units isn't something done in aw and if you play with an ally he can delete the unit if needed.

**Comment by Robosturm** [comment]
Sea mines now deal 5 damage to all none air units when trapping expect for units which can disable mines currently only cruisers get this action.
No units can attack them however
