### ISSUE TITLE
Request: A function for COs similar to canUseWeapon()

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1035]
I'm not familiar with the canUseWeapon() function found in a unit's .js file yet, so I may be dead wrong, but apparently it allows us to make units with unusual fire ranges (like a unit that can only attack diagonally for example).

Not sure if this is possible, but it would be nice if a similar function exists for COs, so that we can make a CO that modifies the fire range beyond just increasing/decreasing the maximum and minimum range.

**Comment by lonewolf19991** [comment]
I want to follow this thread. However have you looked into the minicanons, black cannons and laser scripts yet?

**Comment by Robosturm** [comment]
This function isn't meant to modify the firerange of a unit in an unusual way.
It's also something that's not supported for units. Units always have a circle as firerange.
It only makes a weapon unusable in certain situations and was only introduced for the ranger unit class and is nothing i really want to extend....

**Comment by XnKradst** [comment]
Hey, sorry I haven't replied to the thread yet. I did look into minicannons and black cannons, but all of those make use of custom actions/commands, and the only way I can make that work for regular units (as part of a CO power) is to do what we've already been trying: edit ACTION_FIRE.js. That may work, but not an ideal solution as it's prone to making other mods incompatible. (Also last I tried I had trouble checking unit positions.)

As for the canUseWeapon() function, I'm aware it's not exactly meant for unusual fire ranges, but it has the potential to be used for that, as I'm pretty sure I've seen a custom unit with an unusual fire range that made use of that function.

To be more specific about what I'm trying to do: a CO whose direct units can attack indirectly BUT only in cardinal directions, so I just need some way to prevent diagonal attacks.

That said, I do understand this might be too much work to be worth the effort for the time being, if it's even possible...

**Comment by Robosturm** [comment]
The main problem is that you can do some hacky things but actually supporting different fire-ranges won't be added to the game.
Since it's nothing required for vanilla aw/CoW and it would require way to much rework for the ai.

So i'll close the issue since i don't think i'll add it.
Just way to messy/hacky to add to the game with to few benefits.
So you'll have to hack the action_fire.js in that case.

Sorry
