### ISSUE TITLE
Standarized Linux build

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1038]
**Is your feature request related to a problem? Please describe.**
Right now, the Linux build does not properly add the necessary qt dependencies to the game. In order to play the game, one must locally install or have installed the latest version of Qt. ideally it would be best if the build actually generated the necessary files and needed no further installations, like it does in Windows.

**Describe the solution you'd like**
A bash script or helping the main dev of the project fine tune the github actions that generate the binaries. Ideally this could also reflect back on the CMakeLists.txt as well. 
**Describe alternatives you've considered**
Another option would be to use the Qt installer framework, so that the Linux builds are generated with that tool instead: https://doc.qt.io/qtinstallerframework/

**Comment by Robosturm** [comment]
The problem is that the github runner have no access to a precompiled qt version.
Hence why it links against sim-links
Compiling qt everytime a dev change or release build should be done is no option. 
So i fear there's no solution for this atm.
Cause bith your solutions require a precomiled linux version of qt.

**Comment by lonewolf19991** [comment]
I am fine with providing the binaries compiled manually. However will give it a priority on making it through github actions. Qt is widely used in the Linux world, so maybe there are options I am missing.

**Comment by Robosturm** [comment]
All i can say that the github actions / commands which provide the qt installation mention that there's no precompiled qt and the action needs to deploy them on the machine.
A way to solve this could be a github repo containing the compiled files....

**Comment by Robosturm** [comment]
Backoog clean up
Closed issue cause no one is working on it and didn't work on it for a long time.
If this changes a new issue should be created.
