### ISSUE TITLE
Unit List in Editor Cannot Scroll

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#104]
**Describe the bug**
Simple, the up and down arrows on the unitlist on the map editor do not work at this moment

**To Reproduce**
1. Activate a mod that adds a bunch of units (Like the Overhaul Mod)
2. Start the Map Editor
3. Try to scroll the unit list

**Expected behavior**
The Unit List scrolls

**Comment by Robosturm** [comment]
They work but the buttons are inverted to the expected behaviour. :(
