### ISSUE TITLE
Standardize Map naming and such

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1042]
Putting this here for the time being to discuss it. This is something for someone with a lot of time on their hands to take a shot at, and not a priority in the slightest.

As it currently stands, the map list is a mess of different naming schemes due to the varying sources from where they came:
![image](https://user-images.githubusercontent.com/51452633/185344819-3d8ebc20-7991-4a82-8d45-b563aee7c098.png)

Perhaps it's worthwhile for someone to, at some point, go through the maplist and standardize the names? Either make it all uppercase (RIVER OF WAR, A LOVE SUPREME) or capitalization (River of War, 60-Zweiter Krieg). Either works, so long as all maps are made like this, to make it more organized.

On a similar note, some older maps might use incorrect default colours from before they were updated, and some AWBW maps use non-standard colours, too (A Love Supreme is grey vs teal). Should these be updated, too? I personally think yes, because then it's easier to see the turn order by looking at the minimap - red > blue > green > yellow > etc

Any other thoughts on this from anyone?

**Comment by Robosturm** [comment]
I think the suggestion is good.
Also removing the beginning player count from the map name, since that gets automatically added since a few releases at the end of the map name.
