### ISSUE TITLE
Playercolors don't save properly

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1047]
Playercolors don't quite seem to save properly. When I save a map with any of the default playercolour options, trying to load it gives colours that are slightly off. See attached images for what it looks like when I start to play the map vs what it looked like when I saved the map.

![image](https://user-images.githubusercontent.com/51452633/185759045-be69b45a-e1b7-4e17-8751-5481be456550.png)
![image](https://user-images.githubusercontent.com/51452633/185759053-3fe22589-5d0a-4815-bbfa-9b2e36f54352.png)

**Comment by Robosturm** [comment]
I can't confirm this.
Both changing colors to different default colors and saving and loading a map.
In playerselection and editor works correctly.
My guess is that you either have an old game version or you have an resource folder which in the exe which isn't up to date

**Comment by Robosturm** [comment]
Also the colors in your first picture are the outdated once from older releases which have been moved to the ones in the second picture.
So both were the default colors at a point in time but the second one are the current ones shown in the player selection etc.

**Comment by FranticFairy** [comment]
Did another test, this only seems to happen on multiplayer!

**Comment by Robosturm** [comment]
This is a visual bug where the internal color used to detect the correct color table from the files isn't mapped to the display color in multiplayer scenarios when receiving data.
Very weird bug.
