### ISSUE TITLE
First Player/Day Change indicator

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1048]
When playing with many players/factions in a map, or when playing a long game in general, it can be hard to see which player is the first player. This can be a bit annoying when it comes to things such as figuring out when the weather will change.

An indicator of some kind in the player list during a game (where you see COs, funds and power gauges) to show at what point there will be a new day would be nice. I'd suggest having it be the icon of the weather it will become on that day if the weather forecast is enabled, and if it isn't enabled, using either the icon for the _current_ weather or that match's _default_ weather.

This way, it will always be clear when the day will change, even when the original first player has been defeated, and you get a reminder of upcoming weather if the forecast is enabled.

**Comment by Robosturm** [comment]
To be honest i know what you want but i don't understand your solution just by reading it.
Would be good if you can add some mock ups and i think about it.

**Comment by FranticFairy** [comment]
![image](https://user-images.githubusercontent.com/51452633/185788388-20d0ffbd-e676-4eb2-9888-0f65d1adecb1.png)

Very rough mockup. It's currently Yellow's turn, and Red is the first player. It will become misty on the next turn, so the next day indicator has the mist icon.

**Comment by Robosturm** [comment]
I don't think that would work since, depending on the screen size and the options several players may get cut off.
So the indicator might not show up.
Leaving you with no additional information unless you have a correct setting setup.
Putting any information in that bar that's not an information for all players is nothing i would do since it has to many situations where the information gets lost in the void.

**Comment by FranticFairy** [comment]
I personally would find it even more useful in situations where a lot of players get cut off. It's what I'm dealing with right now, I can't see the majority of players already because of my screen setting (playing windowed), and so would like extra indicator of when the next turn will be.

If something like this gets added, once it shows up on my screen I would be able to be like. "Ah, right, there's a new day coming soon."

I can't really think of another way to easily indicate when the next turn would be beyond something like this, or an icon added directly to the first player's status bar.

**Comment by Robosturm** [comment]
The problem i have with your solution is that in the situations it's the most useful.
It requires me to at least watch one turn to past before i see it.
So i get that information to late in those situations i would need it.
E.g. after continuing a savegame after a week or so with not much information about the match and now i have to play one turn and i have to watch it so i actively see it.
Those are way to many conditions to make it useful.

I understand the problem and I agree it should get a solution but the proposed solution is way to bad in my opinion to count as a solution

**Comment by lonewolf19991** [comment]
I would suggest a wav different from that of the turn start. Maybe a rooster singing or something similar.

**Comment by FranticFairy** [comment]
> I would suggest a wav different from that of the turn start. Maybe a rooster singing or something similar.

This won't fix it, the point is knowing when the day will change in _advance_ of the actual day change. A different sound effect on the day change won't help you know ahead of time how many players still get to do their turn before another day occurs.

**Comment by Jocrr** [comment]
Maybe add like a star next to the first player

**Comment by TeslaTrooper09** [comment]
i would suggest indenting the active player
![indent](https://user-images.githubusercontent.com/75344715/186955198-bf135b0f-7d38-4ad3-be0a-2bcabdfd28b8.png)

**Comment by Robosturm** [comment]
The active player isn't really the issue.
The issue is knowing which player begins a new day.
And that even if that player isn't visible....

**Comment by Robosturm** [comment]
I'll stick with this solution for now.
This is a 6 player map and only two players are shown.
The next day will be shown at the bottom or middle top depending of the position of the start player
![screenshot+1](https://user-images.githubusercontent.com/48879701/187232748-0926e82a-f1f4-4f58-b996-a0c62d283c51.png)

**Comment by FranticFairy** [comment]
Will it be possible to configure how many players are shown? Similar to how you can configure things like how many turns ahead you can plan your move. This way people with bigger screens can opt to show more than two players.

**Comment by Robosturm** [comment]
@FranticFairy This is possible since 10 or more releases and the default value is infinite. I just changed it to two for demonstration purposes
