### ISSUE TITLE
Game crashes when i'm trying to edit Alexander's CO style

### ISSUE THREAD

**Issue by QuestionMark210** [Robosturm/Commander_Wars#1049]
Commander Wars vVersion: 0.24.2-main Builddate: Aug  7 2022 16:37:54
21 Aug 2022 @ 11:35:46

EXCEPTION_ACCESS_VIOLATION

INFO: 21.08.2022 11:35:35: Enter "help()" for console info.
INFO: 21.08.2022 11:35:35: Starting Game...
INFO: 21.08.2022 11:35:35: Prepare to Fight...
INFO: 21.08.2022 11:35:35: Read this message while waiting...
INFO: 21.08.2022 11:35:35: 
INFO: 21.08.2022 11:35:35: Generating dead undead... Undead dead... uh...
INFO: 21.08.2022 11:35:35: 

Same applies to: Peter (GE), Smitan (GE), Grimm (YC), Rattigan (YC), Lash (BH), Sturm (BH), Epoch (MA), Robo-Andy (MA), Napoleon (MA), Robo-Sturm (MA), Sabaki (AC), Sophie (AC), Ozzy (AC), Mary (AC), Tasha (BD), Forsythe (BD), Adam (BD), Zandra (BD), Minamoto (GS), Xavier (GS), Sanjuro (GS), Meiyo (GS), Mina (PF), Aira (PF), Alexis (PF), Nana (PF), Amy (PF), Waylon (TI), Conrad (TI), Cassidy (TI), Joey (TI), Walter (TI), Melanthe (DM), Julia (DM), Graves (DM), Varlot (DM) and Yukio (DM).

**Comment by Robosturm** [comment]
#1025
