### ISSUE TITLE
Inconsistency when unloading units

### ISSUE THREAD

**Issue by MsDakota13** [Robosturm/Commander_Wars#1050]
There seems to be an inconsistency when using TAG or going to your next turn when it comes to unloading a transport. To demonstrate consider the following two situations:

Situation 1 with TAG:
You load two units on a lander
move the lander
swap CO for TAG
move lander and unload.
Units **cannot** move or shoot or do anything

Situation 2 with new turn:
You load two units on a lander
move the lander
end turn
start of turn
Move lander and unload
Units **can** move, fire, capture

You'd expect the outcome of both situations to be the same. Either in neither situation you can do anything or you can do everything in both cases.

**Comment by Robosturm** [comment]
Nope start of turn and tag power aren't the same.
The rule enabling the refresh of loaded units clearly states that:
If checked: units can move after getting unloaded if the unit had remained in their transporter for more than one turn.
