### ISSUE TITLE
Quality of life multiplayer requests (GUI and UX)

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1055]
**Is your feature request related to a problem? Please describe.**
There are several changes that have been suggested to me by the users, which would improve the user experience:

1. A sound notifying that a user on the multiplayer CO selection screen,  has connected. This would help to notify when one is waiting for the players to connect. 
2. A map preview on the CO select screen when creating an online match.
3. A notification when a user disconnects from an online match.
4. Adding the name of the user(s) against whom a saved match was played against on the 'show my games' interface.

**Comment by Robosturm** [comment]
This are 4 issues so please report them as 4 different ones. Thx.

**Comment by lonewolf19991** [comment]
Got it, will reopen them individually.
