### ISSUE TITLE
Game crashes when opening CO in editor

### ISSUE THREAD

**Issue by NikoPalad67140** [Robosturm/Commander_Wars#1056]
Hey guys!
I want to create an Orange Star CO, but when I want to open the Random CO in the editor, the game crashes. Can someone help me?

**Comment by Robosturm** [comment]
No clue what you try to do.
Please evaluate more detailed what you do and what fails.
In general it's not possible to edit/geberate co's in game.

**Comment by Robosturm** [comment]
Also if you need help modfing the game.
Consider joining the discord server it's the best place to get help.
Github issues are not the way to go in that regard
