### ISSUE TITLE
cometer power state and power levels not saved in multiplayer saves

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1059]
player 1 had power active prior to save, player 2 had power available, after save and restart both were 0
![image](https://user-images.githubusercontent.com/75344715/186797827-db2ca38c-4c4b-4e43-afcf-58f68c4e4ddb.png)

**Comment by Robosturm** [comment]
Please say the next time if a multiplayer match was made via server or a local multiplayer match the next time

**Comment by TeslaTrooper09** [comment]
i believe dolly made it server side
