### ISSUE TITLE
Hovercraft Can't Cross Oceans

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1063]
So, I'm not sure of the exact details, but it seems like hovercraft can only move two tiles from shore. If this is intentional, fine. It keeps hovercraft from dominating land and sea. But if not, I thought I'd bring it to your attention. 
![image](https://user-images.githubusercontent.com/22900774/186994167-5ef98092-ef71-417c-bbee-04720f089202.png)

**Comment by Robosturm** [comment]
This is an intentional design.
Hovercrafts get limited sea access, cause people didn't like that the hovercrafts have to much options to move.
