### ISSUE TITLE
Different Power and Superpower Quotes

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1065]
If you make it possible to do different power and superpower quotes, I'll write them up for all the CO's. Yes, all of them.

**Comment by Robosturm** [comment]
Already possible i've send it to you via discord.

I paste it here as a reference code:

    this.getPowerSentences = function(co)
    {
        switch (co.getPowerMode())
        {
        case GameEnums.PowerMode_Tagpower:
        case GameEnums.PowerMode_Superpower:
            return [qsTr("The look of terror on your face... It's absolutely delicious!"),
                    qsTr("Heh heh heh... I'm going to enjoy breaking you!"),
                    qsTr("Heh heh heh... Can't a guy have a little fun!?"),];
        default:
            return [qsTr("The look of terror on your face... It's absolutely delicious!"),
                    qsTr("Heh heh heh... I'm going to enjoy breaking you!"),
                    qsTr("Heh heh heh... Can't a guy have a little fun!?")];
        }
    };
