### ISSUE TITLE
Aira Change: No Fog

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1066]
Aira doesn't like surprises. She's a weather-based CO who can't change the weather. So, I propose that when she activates her COP or SCOP, she changes the weather to sunny. It's a tiny thing; most maps are always sunny. But it fits her well. In Fog of War, she might dispel the fog for one turn.

**Comment by Robosturm** [comment]
Removing fog of war will never be added to a co. Changing weather to sun however sounds reasonable
