### ISSUE TITLE
Improper font rendering 

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1071]
Since the commit https://github.com/Robosturm/Commander_Wars/commit/e4763fda0b48fdef107fdbba139b9d321858a6ce the rendering of fonts looks like the screen attached.

![Screenshot from 2022-08-31 18-54-34](https://user-images.githubusercontent.com/96459683/187805106-d000e1bc-951f-4851-b64b-c79ba6f140d6.png)

**Comment by Robosturm** [comment]
Fixed problems with windows being an case insensitve filesystem. Ahhhhhhhhhhhhhhhhhhh
