### ISSUE TITLE
Compilation error, unable to create executable in latest master branch

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1074]
**Describe the bug**
Whenever compiling the game with this commit https://github.com/Robosturm/Commander_Wars/commit/eee0fcb43f8f4ef447285f3746970eb8c65d2307

I get the following error:

`/usr/bin/ld: CMakeFiles/Commander_Wars.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x1088): undefined reference to `GameUpdater::launchPatcher()'
/usr/bin/ld: main.cpp:(.text+0x1095): undefined reference to `GameUpdater::launchApplication()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Commander_Wars.dir/build.make:5697: commander_wars] Error 1
make[1]: *** [CMakeFiles/Makefile2:371: CMakeFiles/Commander_Wars.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

I am using:
**CMake 3.23.2**
**Make version 4.3**
**QT 6.3.1**
**Debian Bullseye**

**Comment by Robosturm** [comment]
Only happens if you compile it with -DUPDATESUPPORT=OFF (having no flag is the same)
-DUPDATESUPPORT=ON works fine
