### ISSUE TITLE
multiple font configuration

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1077]
i think it would be pretty handy to be able to have multiple fonts used for various elements of the game.
some fonts may look good in some uses but not in others, it would be nice to have a font for specific elements to help make everything look better.

examples being having a simple blocky font for the UI, a slightly stylized font for in game text, a very thick stylised font for the CO power screen

**Comment by Robosturm** [comment]
@KBraid Would be helpful, if you can make a list of separated fonts you have already in mind. ;)
Since i have some in mind but maybe one you have in mind is missing.

**Comment by KBraid** [comment]
for CO powers i think Bahnschrift Bold Condensed or Impact Condensed might look good and Unispace Bold for UI
