### ISSUE TITLE
Random Perks

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1080]
I'm not entirely sure if this already a thing or not. If it is, I probably missed it.

A way to randomly assign perks would be quite nice to have, especially when playing with many AIs you want to give perks. Ideally simply a button, to give a player (or yourself) random perks, but of course only available ones so this can't be used to get perks you normally cannot select.

**Comment by Robosturm** [comment]
Already possible see here:
![grafik](https://user-images.githubusercontent.com/48879701/188908269-f15a9ad0-cabb-4ac2-a812-79d65c35e37a.png)
![grafik](https://user-images.githubusercontent.com/48879701/188908304-9cee9e73-916f-4de9-91e4-825f06cbed62.png)

Unless you mean something else

**Comment by FranticFairy** [comment]
Welp, I am just completely blind >.>

That's exactly what I mean, yeah, but there are certainly issues with it currently, I will make a seperate ticket to report them.
