### ISSUE TITLE
Random Perk button issues

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1081]
I have noticed a few issues with the 'random perk' button:

- The checkbox does nothing at this time, both with and without it checked the 'random' button fills as many slots as it can
- Selecting random perks for your second CO doesn't show you _which_ perks are selected until you leave the screen and come back (it makes every button 'greyed out' without showing checkmarks)

**Comment by Robosturm** [comment]
The fill checkbox tooltip is wrong it should be:
clicking the 'Random' Button will fill all remaining perk slots instead of replacing all
As for the second part that's the bug you reported here: #1046

**Comment by Robosturm** [comment]
Fixed the description.
