### ISSUE TITLE
PreviewTest11 Crashes on startup

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1083]
The game closes itself when reaching 32%, happens on windows 10 and android.

1. Open the game.
2. Wait for it to load.

Pic before the crash:
![1662654177841](https://user-images.githubusercontent.com/113127747/189176735-1f0de404-3d80-4588-bc43-03a45cc41c2f.jpg)

**Comment by Robosturm** [comment]
It's not a build that is meant to be used. Hence the name and the marker that it's not a release
