### ISSUE TITLE
Unable to connect to Multiplayer Game

### ISSUE THREAD

**Issue by Malkasphia** [Robosturm/Commander_Wars#1086]
**Describe the bug**
I am unable to join a multiplayer game through Join Address option in multiplayer menu. Other players are able to join the host. I have opened ports TCP/UDP 9000-9002

**To Reproduce**
1. I launch the game
2. I select multiplayer
3. I select join address
4. I enter address of host
5. I endlessly try to connect to host until host changes a slot or another player joins, then i get a crash.

**Expected behavior**
I connect successfully to a multiplayer game.

**Screenshots**
![image](https://user-images.githubusercontent.com/40341552/189493894-74ecdb14-ddbc-40f4-bc20-baa6dd352127.png)

**Desktop (please complete the following information):**
Windows 10 Education
 - Version 1803
 - No Mods
**Additional context**

Crash log
Commander Wars vVersion: 0.23.0 Builddate: Jun  6 2022 06:13:58
10 Sep 2022 @ 10:52:08

EXCEPTION_ACCESS_VIOLATION

DEBUG: 10.09.2022 10:48:30: Adding :/resources/music/multiplayer/multiplayer+8.mp3 to play list
DEBUG: 10.09.2022 10:48:30: AudioThread::SlotPlayRandom
DEBUG: 10.09.2022 10:48:30: Buffering music for player: :/resources/music/multiplayer/multiplayer+2.mp3
DEBUG: 10.09.2022 10:48:30: Media status changed for player to 1
DEBUG: 10.09.2022 10:48:30: Leaving Main Menue
DEBUG: 10.09.2022 10:48:30: Playback state changed to 1 for player
DEBUG: 10.09.2022 10:48:30: Media status changed for player to 2
DEBUG: 10.09.2022 10:48:30: Media status changed for player to 5
DEBUG: 10.09.2022 10:48:30: Client is running and connecting to  and port 9002 and the connection is unsecure
DEBUG: 10.09.2022 10:48:30: State changed for 0
DEBUG: 10.09.2022 10:48:30: State is now Lookup.
DEBUG: 10.09.2022 10:48:30: State changed for 0
DEBUG: 10.09.2022 10:48:30: State is now Unconnected.
DEBUG: 10.09.2022 10:48:30: Error catched for 0
CRITICAL: 10.09.2022 10:48:30: The host was not found. Please check the host name and port settings.
DEBUG: 10.09.2022 10:48:30: Media status changed for player to 2
DEBUG: 10.09.2022 10:48:30: Media status changed for player to 5
DEBUG: 10.09.2022 10:48:31: Stopping sound on playing changed.
DEBUG: 10.09.2022 10:48:44: Playing sound: button.wav using cache sound 1
DEBUG: 10.09.2022 10:48:45: Stopping sound on playing changed.
DEBUG: 10.09.2022 10:48:49: Focused object changed
DEBUG: 10.09.2022 10:48:49: Show virtual keyboard
DEBUG: 10.09.2022 10:48:50: Focus lost for object
DEBUG: 10.09.2022 10:48:50: Playing sound: button.wav using cache sound 0
DEBUG: 10.09.2022 10:48:50: Leaving Lobby Menue to join game by adress
DEBUG: 10.09.2022 10:48:50: Entering Map Selection Menue
DEBUG: 10.09.2022 10:48:50: AudioThread::SlotClearPlayList() start clearing
DEBUG: 10.09.2022 10:48:50: AudioThread::SlotClearPlayList() playlist cleared
DEBUG: 10.09.2022 10:48:50: Playback state changed to 0 for player
DEBUG: 10.09.2022 10:48:50: Media status changed for player to 0
DEBUG: 10.09.2022 10:48:50: Unable to locate music folder: resources/music/mapselection
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+0.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+1.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+2.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+3.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+4.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+5.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+6.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+7.mp3 to play list
DEBUG: 10.09.2022 10:48:50: Adding :/resources/music/mapselection/mapselection+8.mp3 to play list
DEBUG: 10.09.2022 10:48:50: MapSelection::changeFolder 
DEBUG: 10.09.2022 10:48:50: MapSelection::changeFolder. Relative Path: maps
DEBUG: 10.09.2022 10:48:50: AudioThread::SlotPlayRandom
DEBUG: 10.09.2022 10:48:50: Buffering music for player: :/resources/music/mapselection/mapselection+2.mp3
DEBUG: 10.09.2022 10:48:50: Media status changed for player to 1
DEBUG: 10.09.2022 10:48:50: Playback state changed to 1 for player
DEBUG: 10.09.2022 10:48:50: MapSelection::updateSelection Loading: :/maps/advance_wars_2_campaign.jsm
DEBUG: 10.09.2022 10:48:50: MapSelection::updateSelection Loading: :/maps/advance_wars_campaign.jsm
DEBUG: 10.09.2022 10:48:50: MapSelection::updateSelection Loading: :/maps/advance_wars_days_of_ruin.jsm
DEBUG: 10.09.2022 10:48:50: MapSelection::updateSelection Loading: :/maps/commander_wars.jsm
DEBUG: 10.09.2022 10:48:50: MapSelection::updateSelection Loading: :/maps/tutorial.jsm
DEBUG: 10.09.2022 10:48:50: MapSelection::updateSelection Loading: :/maps/war_room.jsm
DEBUG: 10.09.2022 10:48:50: Entering Multiplayer Menue
DEBUG: 10.09.2022 10:48:50: Client is running and connecting to 1.157.68.224 and port 9001 and the connection is unsecure
DEBUG: 10.09.2022 10:48:50: Client gets closed
DEBUG: 10.09.2022 10:48:50: TCP Client 0 disconnected.
DEBUG: 10.09.2022 10:48:50: State changed for 0
DEBUG: 10.09.2022 10:48:50: State is now Lookup.
DEBUG: 10.09.2022 10:48:50: State changed for 0
DEBUG: 10.09.2022 10:48:50: State is now Connecting.
DEBUG: 10.09.2022 10:48:50: Media status changed for player to 2
DEBUG: 10.09.2022 10:48:50: Media status changed for player to 5
DEBUG: 10.09.2022 10:48:51: State changed for 0
DEBUG: 10.09.2022 10:48:51: State is now Connected.
DEBUG: 10.09.2022 10:48:51: Client is connected
DEBUG: 10.09.2022 10:48:51: Ignoring map selection change
DEBUG: 10.09.2022 10:48:51: Updating Socket ID to: 1
DEBUG: 10.09.2022 10:48:51: Server Command received: REQUESTPUBLICKEY for socket 1
DEBUG: 10.09.2022 10:48:51: Command not handled in playerselection
DEBUG: 10.09.2022 10:48:51: Server Network Command received: REQUESTPUBLICKEY for socket 1
DEBUG: 10.09.2022 10:48:51: Unknown command REQUESTPUBLICKEY received
DEBUG: 10.09.2022 10:48:51: Stopping sound on playing changed.
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 6
DEBUG: 10.09.2022 10:49:48: Music stopped at position 57939
DEBUG: 10.09.2022 10:49:48: AudioThread::SlotPlayRandom
DEBUG: 10.09.2022 10:49:48: Buffering music for player: :/resources/music/mapselection/mapselection+8.mp3
DEBUG: 10.09.2022 10:49:48: Playback state changed to 0 for player
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 2
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 0
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 1
DEBUG: 10.09.2022 10:49:48: Playback state changed to 1 for player
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 2
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 5
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 2
DEBUG: 10.09.2022 10:49:48: Media status changed for player to 5
DEBUG: 10.09.2022 10:50:53: Media status changed for player to 6
DEBUG: 10.09.2022 10:50:53: Music stopped at position 67735
DEBUG: 10.09.2022 10:50:53: AudioThread::SlotPlayRandom
DEBUG: 10.09.2022 10:50:53: Buffering music for player: :/resources/music/mapselection/mapselection+7.mp3
DEBUG: 10.09.2022 10:50:53: Playback state changed to 0 for player
DEBUG: 10.09.2022 10:50:53: Media status changed for player to 2
DEBUG: 10.09.2022 10:50:53: Media status changed for player to 0
DEBUG: 10.09.2022 10:50:53: Media status changed for player to 1
DEBUG: 10.09.2022 10:50:53: Playback state changed to 1 for player
DEBUG: 10.09.2022 10:50:54: Media status changed for player to 2
DEBUG: 10.09.2022 10:50:54: Media status changed for player to 5
DEBUG: 10.09.2022 10:50:54: Media status changed for player to 2
DEBUG: 10.09.2022 10:50:54: Media status changed for player to 5
DEBUG: 10.09.2022 10:52:08: Network Command received: PLAYERCHANGED for socket 1
DEBUG: 10.09.2022 10:52:08: Remote change of Player 2 with name Open for socket 0 and ai 200

**Comment by Robosturm** [comment]
@Malkasphia i think the issues is that your using different game versions.
The host has most likely Beta 24.2 which uses openssl crypting for passwords and some other commands
While the older game version Beta 23 doesn't know those commands and crashes cause it's failing to receive the crypted data.

**Comment by Malkasphia** [comment]
You are correct! I cant believe we overlooked that. Awesome. Thank you so much for your help.
