### ISSUE TITLE
Rangers can use direct units for indirect attacks

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1090]
**Describe the bug**
If there's a direct unit inside the rangers range it will be chosen for the indirect dmg.

**To Reproduce**
1. Deploy a ranger.
2. Have any direct unit inside the rangers range.
3. See that the option to perform a range attack is avaliable even with no indirects.
4. See that both the ranger and the direct unit have used its turn.

**Expected behavior**
Rangers shouln't be able to use direct units for the indirect attack.

**Screenshots**
Units the Ranger can use the indirect attacks with; infantry, navals and air not shown but they also can.
![RangersDire](https://user-images.githubusercontent.com/113127747/189696585-191df723-aad4-410f-9c6d-a5a11f4a40a7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 24_2
 - Active Mods: None

**Comment by Robosturm** [comment]
Fixed in commit 419dc389b0a7dc9e5054bedd3d26ebde264fea40
