### ISSUE TITLE
expanding naval combat

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1094]
i've had some idea on how to expand naval combat to make it more compelling, mainly introducing new units
all naval units with indirect range can move and attack on the same turn as well as return fire if the target is visible to them

**Gun boat**
cost - 4000
atk range - 1
move - 7
vision - 2
ammo1 - 9 3' naval gun (55 dmg to boat, 35 dmg to frigate, 5 dmg to battleship)
fuel - 60

**missile boat**
cost - 7000
atk range - 1-2
move - 7
vision - 2
ammo1 - 3 anti-naval missile (80 dmg to boat, 65 dmg to frigate, 35 dmg to battleship)
fuel - 60

**black boat**
cost - 7500
move - 6
vision - 1
fuel - 60

**torpedo boat**
cost - 8500
atk range - 1
move - 7
vision - 2
ammo1 - 3 torpedo (30 dmg to boat, 80 dmg to frigate, 40 dmg to battleship - torpedoes are ineffective against boats)
fuel - 60

all boats able to traverse shoals and rivers

**lander**
cost - 8000
move - 6
vision - 1
fuel - 100

**corvette/frigate**
cost - 9000
atk range - 1-2
move - 8
vision - 5
ammo1 - 9 6' naval gun (75 dmg to boat, 55 dmg to frigate, 20 dmg to battleship)
fuel - 100

**destroyer**
cost - 10000
atk range - 1
move - 7
vision - 3
ammo1 - 3 anti-naval missile
ammo2 - 3 watermine
fuel - 100

**cruiser**
cost - 12000
atk range - 1
move - 6
vision - 4
fuel - 100
ammo1 - 9 anti-naval missile
ammo2 - 9 anti-air cannon
fuel - 100

**submarine**
cost - 14000
atk range - 1
move - 6
vision - 3
weapon1 - 6 torpedo
fuel - 70

**battlecruiser**
cost - 18000
atk range - 2-3
move - 5
vision - 3
ammo1 - 6 anti-ship cannon
ammo2 - 9 anti-air battery
fuel - 100

**battleship**
cost - 24000
atk range - 3-5
move - 5
vision - 3
ammo1 - 6 battleship cannon
fuel - 100

**aircraft carrier**
cost - 20000
atk range - 2-6
move - 5
vision - 4
ammo1 - 9 anti-air missile
fuel - 100

**Comment by Robosturm** [comment]
Well i had no time this weekend to respond or else i would have stopped you from doing the work you did already.

While i understand what you're going for there are several things which aren't good.

1. Reducing the movement range of the existing boats is unrealistic + it makes naval maps drag out even longer which might be more realistic but is definetly not fun to play. For that reason any movement reduction won't make it in.

2. Making naval combat an indirect battle, without further changes to the battle system while range ships make it easier to interact with land units, it would again drag ou pure sea battles which is again a bad design. The only solution to solve this would be to give ships the option to counter attack indirect attacks.

3. Before starting to implement something like you did. We should have a damage chart for the sea units as well as a price table and discussions about ammo and fuel etc. and only if everything is designed more clearly i would go for adding it to the game.

At the current state i don't think it's ready to be implemented/ added to the game without further boiling it down.

For that reason i won't merge https://github.com/Robosturm/Commander_Wars/pull/1097 for now

**Comment by KBraid** [comment]
understandable

**Comment by KBraid** [comment]
i did put the movement speed too low thinking about it, and for the weapon ranges i was having real life naval combat in mind, so yeah it would make sense for the ships to be able to counterattack indirectly if they can see the opponent as well as being able to attack and move at the same time.

**Comment by Robosturm** [comment]
I think the submarine should remain at 6 speed or else it gets even less useful of a unit, since you can't hunt down/follow other units. This is mainly a gameplay think from my point of view.

As said the next step would be to get a damage chart and costs for the units as well as ammo parts to see where things should get some changes or not.

Also since you moved the mine laying to the destroyer which is a good change.
I think it's useful to move the capture ability of the black boat to one of the low tier units.
So it's not a i can do everything unit like it is now

**Comment by Robosturm** [comment]
Also i think changing the sea units should also add the amphibious production center to the game. Moving the hoverunits to it.

**Comment by KBraid** [comment]
added full stats for all the units

**Comment by KBraid** [comment]
suggested some features for the submarine to make it more valuable

**Comment by Robosturm** [comment]
The submarine additions are a) hard to implement and make it to complicate in my opinion so i would remove those two points and stick to the direct attack rule / i think the attack part is realized implicit.

I'm a bit biased when it comes to the submarine vision range reduction, i wouldn't alter the orignial units to much and since the dive part is nothing i would add changing it to 5 vision makes sense as a compensation.

I think the battlecruiser should get one less movement range so 5 like the battle ship or else i think it's way to good compared to the battle ship.

Due to some coding limitations the counter vision rule for indirect counter attacks is nothing that is making it into the game.
Here i would go for simplicity over realism etc.

torpedo boat shouldn't do more than 40% damage to battleship types or else they're way to cost effective. (see DoR charts)

**Comment by Robosturm** [comment]
@KBraid Once the sprites are ready i'll go ahead and add the stuff.

**Comment by KBraid** [comment]
i think all the sprites are in, though i feel the boat unit sprites could be a little better but they can be touched up later down the line if need be

**Comment by Robosturm** [comment]
I merged it, though i'll need sometime to add everything.
One sidenote please to not delete files like you did for the rivers. There's normally some logic behind it.
So i reverted that part ;)

**Comment by KBraid** [comment]
yeah i'm not very good at making the unit sprites, it's a lot of work that needs to be put into such a small space

**Comment by Robosturm** [comment]
You can use 32x32 sprites instead of 16 pixel ones. My main concern is that each unit needs some distinguishable feature, so you can remember yeah that's that unit

**Comment by Robosturm** [comment]
So e.g. the boat cabine should look different for each boat

**Comment by Robosturm** [comment]
The default image size is 32x32 pixels anyway

**Comment by Robosturm** [comment]
@GeneralWadaling, @KBraid  What i meant is having different towerparts for each ship for at least the unit sprite.
Cause the canon a lone are to few pixel to see a difference at first glance.
And i would say we go for 32px icons for boats so there's more room to create a different look for each unit.

**Comment by KBraid** [comment]
me and wadling are throwing ideas around
![image](https://user-images.githubusercontent.com/53922323/194542032-ffd9ad80-ef04-4d40-90ad-fbdbb6a4cc12.png)

**Comment by GeneralWadaling** [comment]
![image](https://user-images.githubusercontent.com/57716526/194543681-a392d281-f868-4ffc-a9a0-944118ad811c.png)
How about this @Robosturm

**Comment by GeneralWadaling** [comment]
Hello???

**Comment by KBraid** [comment]
it's the weekend, Robosturm tends to take a break from Commander Wars during the weekend. you'll likely have his opinion come monday

**Comment by Robosturm** [comment]
I think the version of K'Braid is pretty good.
It makes the units distinguishable and also shows which wrapon it will use.
So probably only the destroyer and the battle cruiser need a change the destroyer looks to similar to the cruiser and the battlecruiser has the problem to look like the aw2 battleship which at least for me tends to confuse them

**Comment by GeneralWadaling** [comment]
> So probably only the destroyer and the battle cruiser need a change the destroyer looks to similar to the cruiser
Actually, the Destroyer's weapon is not naval gun, but the ASW missiles that is also used on the gunboats *before naval rework*
> the battlecruiser has the problem to look like the aw2 battleship which at least for me tends to confuse them
For some reason the BC's overworld sprite has ship hull larger than that of BS, that might be the reason it is confusing, but otherwise their tower is pretty distinctive to each other.

**Comment by Robosturm** [comment]
@GeneralWadaling My only concern is that the destroyer sprite looks to similar to the cruiser.
As for the battle cruiser what i meant is not that it's not clearly a difference to the battleship in the game, but that if only a battle cruiser is on the map i think it's a battleship cause it looks like the aw2 battleship so my mind tells me it's a battleship though it isn't. I know that only happens to people who crew up with aw1/aw2 still something that bothers me

**Comment by GeneralWadaling** [comment]
> @GeneralWadaling My only concern is that the destroyer sprite looks to similar to the cruiser. As for the battle cruiser what i meant is not that it's not clearly a difference to the battleship in the game, but that if only a battle cruiser is on the map i think it's a battleship cause it looks like the aw2 battleship so my mind tells me it's a battleship though it isn't. I know that only happens to people who crew up with aw1/aw2 still something that bothers me

For this major concern, we can change the cruiser sprite's weapon into its missile turret.
Roughly like this.
![image](https://user-images.githubusercontent.com/57716526/194754717-a7de45f2-8011-4d93-9e7e-437ae8e4673b.png)

**Comment by Robosturm** [comment]
@GeneralWadaling I would prefer a destroyer sprite change cause the cruiser sprite is known for aw players and it may get confusing for people similar reason as for the battle cruiser sprite,

**Comment by GeneralWadaling** [comment]
> @GeneralWadaling I would prefer a destroyer sprite change cause the cruiser sprite is known for aw players and it may get confusing for people similar reason as for the battle cruiser sprite,

Destroyer uses gunboat missile tubes, which the destroyer will replace the old gunboat - destroyer's actual sprite is the middle one.

The left one is actually frigate.

**Comment by Robosturm** [comment]
@KBraid @GeneralWadaling would be good to get an upgraded version for the overworld unit sprites.
I don't want to make a release with the current overworld sprites since they are to confusing atm.

**Comment by GeneralWadaling** [comment]
Luckily we can have some references to Duel Strike overworld sprites
https://www.spriters-resource.com/fullview/122688/
![image](https://user-images.githubusercontent.com/57716526/197316469-488b308e-c0a2-4a84-afa2-12f1ec8124ad.png)
These are directly available in 32px.

**Comment by TeslaTrooper09** [comment]
@KBraid @GeneralWadaling are there battle animations for the new ships yet?

**Comment by Robosturm** [comment]
@TeslaTrooper09 yes there are battle animations for them.
