### ISSUE TITLE
CO Style list is empty aside from blank COs, DoR Cos, and custom Cos

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1103]
![image](https://user-images.githubusercontent.com/53922323/192340498-6992d430-e6f1-4c1e-a547-01b927a67359.png)
![image](https://user-images.githubusercontent.com/53922323/192340539-1ef7e6c6-59fc-4360-bdd0-eb5a1764b60f.png)

**Comment by Robosturm** [comment]
You need to have them unlocked
