### ISSUE TITLE
Desert terrain bugs

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1105]
Desert terrain gives a -20% FP decrease, when you places ruins of top of it the tile info still says there's a debuff but ingame the FP is normal. also dry riverbeds seem to be glitched as well... desert forests and wastlands are working normal though.

![image](https://user-images.githubusercontent.com/75344715/192611329-54ea7d3f-97e6-4fc6-92d7-8b67cf2ee589.png)

![image](https://user-images.githubusercontent.com/75344715/192611348-57ca03ab-6c43-45ba-96aa-5b8e7320d512.png)

![image](https://user-images.githubusercontent.com/75344715/192613248-ca16a527-dfda-4746-9c7a-71ed3dd9fd80.png)

![image](https://user-images.githubusercontent.com/75344715/192613366-8283a248-84f2-4cf7-82c4-b0d0f7350c22.png)

**Comment by Robosturm** [comment]
Description is wrong for the normal ruin.
The dry river works fine in vanilla for me....
