### ISSUE TITLE
Change username doesn't work properly in Android

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1106]
**Describe the bug**
Change username wont change the nickname to whatever was writen, instead it will change it to numbers.

**To Reproduce**
1. Go to Change username.
2. Write a username to change to.
3. Press Ok and the game restarts.
4. See that the username has changed to some numbers instead.

**Screenshots**
Username to change to:
![Screenshot_2022-09-27-23-10-48-034_org robosturm commander_wars](https://user-images.githubusercontent.com/113127747/192637088-056f2a3b-ad73-403e-bb55-6714deeeb13a.jpg)

Username it changes to (after restart):
![Screenshot_2022-09-27-23-09-02-729_org robosturm commander_wars](https://user-images.githubusercontent.com/113127747/192637223-18b2e432-7b53-4d30-882b-0b86246595f3.jpg)

**Phone (please complete the following information):**
 - OS: Android 11
 - Version: Beta 25_5
 - Active Mods: None

**Additional context**
It works as intended in Windows.

**Comment by Robosturm** [comment]
Can't reproduce this, you definetly did more than just changing the username dunno what though

**Comment by Firewito** [comment]
Screen record of the username change:
https://user-images.githubusercontent.com/113127747/193822223-513c3006-0b30-434f-ab3d-2627514d4695.mp4

**Comment by Robosturm** [comment]
My guess is that you either quit the game to fast or restart the game before it was properly closed.
And thus the ini file wasn't saved yet. 
I tried to reproduce it and i'm unable to do so.
So you're doing something weird in between
