### ISSUE TITLE
Multiplayer Allied HQ Capture

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#111]
**Describe the bug**
The new 'automatically capture if already capturing' system has some.... weird interactions with allies in Multiplayer/Team Games. If I'm capturing an enemy building, and that building then becomes owned by an ally, and I don't do anything with the capturing unit next turn, the auto turn-end capture makes me capture my ally's building.

**To Reproduce**
1. Start a team game
2. Start capturing an enemy building
3. Ally of person capturing enemy building captures enemy HQ
4. Do nothing with the unit mentioned in step 2 and end turn
5. Watch as the building changes owner even though an ally owned it.

**Side-note**
Are there chances of a possible future feature where we can transfer buildings and units to our allies?

**Comment by Robosturm** [comment]
Upps when defeating a player the reset was only done for own units not allied ones. Fixed.

Well at the moment i don't plan on adding transfer buildings.
But you can easily mod that in by adding a general Action similar to CO-Power or Surrendering etc.
Where you have to select the player and unit you wanna transfer.
