### ISSUE TITLE
option to limit units

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Robosturm/Commander_Wars#1110]
**Is your feature request related to a problem? Please describe.**
For new player, who has never play advance wars before, the big counts of units is overwhelming. It is hard to find out the weaknesses and strengths of the units.

**Describe the solution you'd like**
An option to limit the available units would solve this problem. They new player must only deal with a smaller count of different unit and can learn its features easier.
They are also able to play pvp games much faster with this limited count. So you can easier play with a friend how has never play advance wars before.

Predefined profiles as example for all units of the first advance wars games would be nice.

**Comment by Robosturm** [comment]
Already possible. You can ban units for all players or specific players in the co/player slection before a match.
It also contains an option to use the pre defined sets from the aw games + you can save your own preset.

**Comment by LuckyTurtleDev** [comment]
Thanks I have always checked the menu before.
