### ISSUE TITLE
Some UI elements are still cut off

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1115]
Certain UI elements are still cut off on the android version.

Using high DPI setting.
![Screenshot_20221003-193319](https://user-images.githubusercontent.com/85777134/193986009-6f8a4d5f-a505-4a38-8b0f-e0e00cbbcd57.png)

**Comment by Robosturm** [comment]
Note only the given screen will be fixed.

**Comment by TheMasterCreed** [comment]
> Note only the given screen will be fixed.

If I find any other UI errors I will open a new issue.
