### ISSUE TITLE
Automatic Update fails to copy the folder multimedia

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1119]
Warning: could not load multimedia backend "" File:  Line: 0 Function: 
Fatal: QtMultimedia is not currently supported on this platform or compiler. File:  Line: 0 Function:

**Comment by KBraid** [comment]
the problem seemed to stem from the auto-update. manually updating fixed the issue

**Comment by Robosturm** [comment]
Hotfix solution copy the multimedia folder from the update folder to the install folder and everything will work
