### ISSUE TITLE
Reconnecting to a multiplayer match doesn't work properly

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1121]
**Describe the bug**
While using this version of the game https://github.com/Robosturm/Commander_Wars/commit/33d042ac339509b97b818ff3e9ab41e3159db914, the re-connection to a previously created match, leads to a screen reading 'connecting'.

This leads to being unable to rejoin a match. 

**To Reproduce**
1. Go to Multiplayer and create a match
2. Play a few turns and then leave
3. Try rejoining
4. The connection screen shows up but the match doesn't load

**Expected behavior**
Both players being able to load the match again after reconnecting to the game. 

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Version 25.1-main

**Comment by TheMasterCreed** [comment]
Whenever I try to re-launch the game from a savefile on a new server host this screen pops up.
![image](https://user-images.githubusercontent.com/85777134/194446013-ae132ef6-a102-43b0-be19-567a5948c88a.png)

**Comment by Robosturm** [comment]
Are we talking about savegames, loaded onto the server or a private session or something else?
I need a bit more details of the steps cause @TheMasterCreed and @lonewolf19991  your describitions don't match on what you did.

**Comment by TheMasterCreed** [comment]
> 

Saved games loaded onto the server. Lonewolf has a debug log that he should be providing soon.

**Comment by lonewolf19991** [comment]
> Are we talking about savegames, loaded onto the server or a private session or something else? I need a bit more details of the steps cause @TheMasterCreed and @lonewolf19991 your describitions don't match on what you did.

The original error came through the sever connection. I have the local client logs if you want to look at them privately. I believe it might have to do with the functions that handle the sockets of the connection.

**Comment by Robosturm** [comment]
Yes that would help as well

**Comment by Robosturm** [comment]
@TheMasterCreed can you also attach the savegame thx.

**Comment by TheMasterCreed** [comment]
> @TheMasterCreed can you also attach the savegame thx.
Alrighty, I'll get the save file when I get home from work. Do you want me to DM you the file?

**Comment by Robosturm** [comment]
You can dm it or attach it i don't care
