### ISSUE TITLE
AI Crash Caused by MovementCostModifier

### ISSUE THREAD

**Issue by bajing-jalan-jalan** [Robosturm/Commander_Wars#1122]
**Describe the bug**
I made this CO power that increase movement cost by 4 as below (function CO.getMovementCostModifier):

`
    if (co.getPowerMode() === GameEnums.PowerMode_Superpower &&
        co.getOwner().isEnemyUnit(unit) === true)
    {
        if (unit.getUnitType() === GameEnums.UnitType_Naval ||
            unit.getUnitType() === GameEnums.UnitType_Ground ||
            unit.getUnitType() === GameEnums.UnitType_Infantry)
        return 4;
    }
    return 0;
`

This somehow causes the AI to go haywire, e.g. Infantry getting in water like in the image below:

![image](https://user-images.githubusercontent.com/85274227/194562693-e48075c1-c4b2-4df6-8644-f53e45c497ea.png)

When testing the function human vs human, it works just fine.
How to fix this?

**Comment by Robosturm** [comment]
Problems with mods won't be handled here unless you can clearly show it's vanilla game bug.
You may ask for help on the discord channel but issues happening in a mod are nothing i'm trying to figure why it may happen.
