### ISSUE TITLE
Android Version Can't Join A Server With Any Mods

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1123]
![Screenshot_20221006-172047](https://user-images.githubusercontent.com/85777134/194578443-669d90ab-1ae1-422e-b459-8ffed3bb89b7.png)

Self explanatory. The mod version is the exact same version as the host. I double and triple and quadruple checked that they were the exact same file and mod version.

**Comment by lonewolf19991** [comment]
That is my mod, so send me a PM to verify it's not mod specific through discord.

**Comment by Robosturm** [comment]
Where you able to join a game without mods.
Cause i checked the code where the message is created and it may show a wrong message....

**Comment by TheMasterCreed** [comment]
I am able to join and make a game without mods on android. However, I cannot join or make a game with mods, even though they work perfectly fine on the PC.
![Screenshot_20221007-133554](https://user-images.githubusercontent.com/85777134/194627249-d899efbd-10fd-454d-920a-943236b5530d.png)
