### ISSUE TITLE
Android has randomly changing border sizes

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1125]
Android Version 25_1

When opening the application on android, there are 2 different border sizes that can pop up and one glitched screen. Restarting the app over and over on android will get you a random result from one of these possibilities. Just repeatedly open and close the app to get these outcomes.

Screenshot 1: Normal black bar size
![Screenshot_20221007-100024](https://user-images.githubusercontent.com/85777134/194585176-a1661190-0f65-4b50-9e1b-fcea03c9e7d9.png)

Screenshot 2: Slightly increased black bar size, will cut off some UI elements while in-game, but still playable. Look very closely and compare screenshot 1 and 2 for the difference.
![Screenshot_20221007-100011](https://user-images.githubusercontent.com/85777134/194585421-5eb68b1a-105a-4d48-8025-478234ff8161.png)

Screenshot 3: The most notable and also unplayable one.
![Screenshot_20221007-100032](https://user-images.githubusercontent.com/85777134/194585597-cdafddd6-a209-422d-8b3a-540f2a3f8271.png)

**Comment by TheMasterCreed** [comment]
I should work as a playtester for a living 😅

**Comment by Robosturm** [comment]
This is a qt bug nothing i can do here sadly.

**Comment by TheMasterCreed** [comment]
> This is a qt bug nothing i can do here sadly.

Rip

**Comment by TheMasterCreed** [comment]
> This is a qt bug nothing i can do here sadly. Mostlikely introduced with qt 6.4. You may check if it happens in the build with qt 6.3.2 https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_25_5 as well. But i can't do much here

I'll double check that build and let you know.

**Comment by Robosturm** [comment]
I have noticed that the functions for getting the screen resolution are bugged on my phone as well, though i never seen a random swap between resolutions.

**Comment by Robosturm** [comment]
Added a hide show once the loading screen got rendered the first time hoping qt gets the correct screen size the second time

**Comment by Robosturm** [comment]
Could you try this one:
https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_Qt64AndroidFixTest2
Worked for me but as mentioned i never saw your issue.
Note: This is an incomplete version so don't expect support here or everything being polished

**Comment by TheMasterCreed** [comment]
Eh it still does the same thing sadly. You can't expect every app to be universal and work perfectly on each and every phone. Works enough for me so oh well.
