### ISSUE TITLE
Losing vision when continuing from a save

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#113]
**Describe the bug**
If you save and reload after moving a unit (but not before ending your turn), only tiles that are still within vision range are shown. Which means enemies that were revealed along a path, as well as those that were visible before you moved are now hidden again.

**Comment by Robosturm** [comment]
Okay hunted it down.
The savegame contains the correct data for the vision. 
Sadly some compatibilty code for older versions of the savegame overwrtie the vision after the savegame was loaded.
Fixed when this happens.
