### ISSUE TITLE
Android Audio Causes Game Lag

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1130]
Android Version 25_1

When changing the default audio device, the game becomes extremely laggy while playing and/or in menus. Only the option "Default device" does not cause any lag.

![Screenshot_20221009-135457](https://user-images.githubusercontent.com/85777134/194774622-3f83610c-263a-45df-b72a-1392635a7dd0.png)

**Comment by Robosturm** [comment]
Sadly any audio issues that don't happen on pc as well, are a qt bug and there's nothing i can do about that, other than pray it gets fixed by qt in the future.
And at the moment i rolled back to an older version cause the new version contains more bugs. :(
