### ISSUE TITLE
Enable right click actions to check ranges and such when it isn't your turn

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1135]
Title says everything, a simple Quality of Life thing to make multiplayer a little better. Just so you can check unit ranges and such when it isnt your turn

**Comment by Robosturm** [comment]
The technical overhead to achieve this, highly exceeds the benefits, while it sounds easy on paper it's very difficult to achieve in reality.

**Comment by TheMasterCreed** [comment]
rip
