### ISSUE TITLE
setOwner() graphical glitch

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#114]
**Describe the bug**
There's a graphical glitch where if you change a unit's owner with setOwner(), it still displays the old sprite... sort of. It's hard to explain with words, so here's a gif to demonstrate:

![](https://i.imgur.com/9PMwL6q.gif)
In the screenshot, yellow's units originally belonged to purple and blue (except for the Neotank on the upper left), and even though they're using the correct sprites, the "dark overlays" that appear after they've moved are still using the old sprites, and in this case they're clearly facing the opposite direction. The overlay is out of sync with the main sprite too.

I know this isn't really a big deal and it has no impact on gameplay, but thought I should report it anyway. Also, reloading a save does fix the sprites.

**Comment by Robosturm** [comment]
The Wait Sprites aren't unloaded which leads to the ui bug.
