### ISSUE TITLE
Reloading a multiplayer save overwrites any build unit list rules

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1145]
Vanilla version no mods

Loading a multiplayer save with build rules will result in your previous build rules not taking effect.

For example:
1. Ban infantry in a multiplayer game, start the game, you can't build infantry
2. Save the game and then reload
3. Suddenly infantry are available again

**Comment by TheMasterCreed** [comment]
I might even suggest being able to edit the build list when loading a save

**Comment by Robosturm** [comment]
#1121
A savegame is a savegame not meant to be changeable.
You can rename the file to map if you want to change stuff like that.
Savegame and map files have the same file format
