### ISSUE TITLE
Random map editor layout is bugged. UI-Elements overlay each other

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1146]
**Describe the bug**
In the Random Map option, the Create Road % doesnt actually create roads, the % instead determines how close the buildings are to the HQ.

**To Reproduce**
1. Go to Map Editor
2. Click on Random map
3. Select any % of Create Road
4. See that the map result doesnt have any roads despite the %

**Expected behavior**
The map should have roads.

**Screenshots**
0% Road:
![0roads](https://user-images.githubusercontent.com/113127747/197265289-a0c5e572-c8b2-44d6-a877-2a74eeda55e8.png)
 
100% Road:
![100roads](https://user-images.githubusercontent.com/113127747/197265348-bdca7274-0782-4e1e-9e4c-50e13a75e568.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 25_1
 - Active Mods: None

**Comment by Robosturm** [comment]
This is only an ui bug not a functional one. Some ui elements overlap which they shouldnÄt
