### ISSUE TITLE
Suggestion: "Show CO Information" on the "CO Styles" screen.

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#1148]
Minor suggestion, but it would be nice if the "Show CO Info" button from the "CO Selection" screen in a game lobby would also show on the "CO Styles" screen where you choose a CO's color. 

I help a friend with a mod, and sometimes I forget certain CO's stats. So it's kinda annoying having to go to; Singleplayer > New Game > Map x2 > Game Rules Menu > Lobby > and Select CO screen, every time I want to check a CO's information. 
It would be a lot faster and easier if you could just check a CO's Info on the CO Styles screen.

Edit: I completely forgot the wiki existed, but regardless I still think this should be an addition that's made. Simply because you can already see the basic CO information on the CO Styles screen, so I don't see why you can't also include the "CO Information" button there either. Plus the fact that everything between the CO Styles Screen and CO Selection screen is already the same with that one exception. 
Also, it's much nicer to traverse the CO-Selection screen in general as is than it is to type a name and check the CO that way.

**Comment by Robosturm** [comment]
This is a not the place for such an option, b) The ui has not enough place.

**Comment by Seimix** [comment]
> This is a not the place for such an option, b) The ui has not enough place.

uhhhhhmmmm, I mean for the screen where you select the characters _before_  the actual screen where you change colors. The Roster Screen, not the actual "CO Style" screen. Should've specified that before. 
There's plenty of space on the Roster Screen for it, since it's literally the same as the CO-Selection screen in the lobby.
