### ISSUE TITLE
Options: Bind Menu Key

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1149]
currently when you hit the escape key it asks to quit the game... I think it should bring up the menu, but there is no key to select menu to rebind it at this time in options.

**Comment by Robosturm** [comment]
I don't see a point for this.
You already have the confirm key for opening the menu another key doesn't really help.
I agree that the escape key for showing the quit message should be configurable but i won't add a new key for opening the menu,
