### ISSUE TITLE
Symmetric Tile Placement for Map Editor

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#115]
Would be a cool little feature in the map editor that allows you to place tiles symmetrically horizontally or vertically so that it's faster to make some symmetrical map designs.

**Comment by Robosturm** [comment]
Dunno i would say you can create one half of the map and use the rotation, mirror functions to do so.
I don't see a real benefit compared to your suggestion.

**Comment by Everglass** [comment]
Oh my, I didn't even try using the flip features, I figure they'd only reorient the map. I'll try using the features in the future and see if they make map creation easier.

**Comment by Robosturm** [comment]
No problem. They extend the map and mirror, flip the map.
I close the issue. You may reopen it if needed or create a new one.

**Comment by Everglass** [comment]
The only issue I see using a mirror features for make maps is that it isn't possible to be used for making odd number sized maps, only even.

**Comment by Robosturm** [comment]
That's a point.
Hmm maybe i change it to not resize the map but flip half of the map to the other one...
