### ISSUE TITLE
Partisan are missing sounds and animations when attacking.

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1150]
**Describe the bug**
On battle, partisans dont play an animation or any sound when attacking with the Firebomb.

**To Reproduce**
1. Deploy a Partisan
2. Have it attack any target with the Firebomb
3. See that it attacks without moving or making any sound in the battle screen.

**Expected behavior**
It should toss the firebomb and play an explosion sound or something.

**Screenshots**
No sound nor moves:
![menacing](https://user-images.githubusercontent.com/113127747/197780480-906b59e2-f2bc-411a-93f6-420ca2f37c9f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 25_1
 - Active Mods: None

**Comment by Robosturm** [comment]
This is not a bug. Several of the co units are missing artwork.
