### ISSUE TITLE
Move Planner Bugs

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1154]
using the move planner breaks the battle animations, both overworld and detailed.

after toggling out of the move planner the players co theme doesn't restart.

**Comment by Robosturm** [comment]
@TeslaTrooper09  I thought you know the drill. Please for the future one issue per bug. Your two bugs are not connected to each other and one is easy to fix while the other requires a lot more coding changes.

**Comment by TeslaTrooper09** [comment]
my b :P
