### ISSUE TITLE
Zandra mission campaign (brown desert)

### ISSUE THREAD

**Issue by huynhngotony** [Robosturm/Commander_Wars#1158]
**Is your feature request related to a problem? Please describe.**
New campaign map

**Describe the solution you'd like**

[Take and Hold.zip](https://github.com/Robosturm/Commander_Wars/files/10012707/Take.and.Hold.zip)

**Additional context**
First map objective to take and hold the oil field.  Would like to add an additional lose condition if not taking the field (beat player 3) by turn 10 you lose but wasn't sure how to do that.

**Comment by Robosturm** [comment]
@huynhngotony Modified the condition spawning the os army to defeat bd if the 4 oil rigs aren't captured by bd at the beginning of day 11
