### ISSUE TITLE
"Synchronize animations" bug

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1159]
**Describe the bug**
When using "synchronize animations" after playing a game for a while, unloading units from a transport stops working. When unloading, the transport takes the action and makes the unloading sound, but the unit doesn't come out.

1. Turn on synchronize animations 
2. Play a game for a while "anywhere between a couple of turns to however long it takes."
3. Try every turn to load and unload units
4. Eventually it stops working correctly 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 25.1
 - Active Mods: None

**Comment by Robosturm** [comment]
Not reproducable on my end.
Maybe a log with debug level on may show what goes wrong.
But i can't fix something i don't see

**Comment by TheMasterCreed** [comment]
I'll do that when I have some free time.
