### ISSUE TITLE
Scrolling Map with keys being denied by cursor location.

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#116]
As you're trying to scroll the map with arrow keys, the map cursor's location on the map will lock to it's current position rather then following the mouse's cursor. This can cause some headache due to not being able to scroll the map further because the map cursor will kick back in the opposite direction while the cursor is at the edge of the screen.

**Comment by Robosturm** [comment]
Changed it so the mouse isn't warpped around. :)
