### ISSUE TITLE
Commander Wars Movement Mod is glitched in 26.0

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1170]
ALL units can move units through other units.
![image](https://user-images.githubusercontent.com/85777134/204108072-44dfb5b7-1d84-4d8c-9cdd-8e1f44eda351.png)

**Comment by Robosturm** [comment]
![screenshot+0](https://user-images.githubusercontent.com/48879701/204109427-22c4b48d-dea8-4f44-af02-2778aba739a1.png)
You must have other mods or stuff activated using only the vanilla mod works as intended see screenshot.

**Comment by TheMasterCreed** [comment]
I'll double check that

**Comment by TheMasterCreed** [comment]
I accidentally had another mod on so that's my fault.
