### ISSUE TITLE
AI acting on the player's turn with auto end turn enabled

### ISSUE THREAD

**Issue by Brilliand** [Robosturm/Commander_Wars#1172]
**Describe the bug**
In the latest version, the AI will sometimes act on another players' turn, then refuse to do anything when its own turn rolls around.

**To Reproduce**
1. Start a new game (To make the bug more obvious: Player 1 Human, Player 2 AI, no other players)
2. Build units from all bases
3. The AI proceeds to move and build its units, then end your turn for you.  (If you had "Auto End Turn" enabled, the AI will immediately end its own turn so that it can get back to your turn and move and build units on your turn.)
4. Now it's the AI's turn and the AI is waiting for you to end its turn for it.

**Expected behavior**
The AI acts on its own turn, not on the player's turn.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 26
 - Active Mods: None

**Additional context**
After I turned all mods off, it stopped happening.  But then I turned some mods on, then turned all mods off again... and now it's happening every time for me, even with no mods enabled.  Not sure what changed between the first time I turned all mods off and the second.

**Comment by TeslaTrooper09** [comment]
this is also happening with multiple AI in game, after blue takes its turn, green starts moving before blues turn is over then green moved for yellow and the game soft crashed.

![image](https://user-images.githubusercontent.com/75344715/204117163-dee55111-27d8-44bc-ab2d-64c9e2ef48d4.png)

[console.log](https://github.com/Robosturm/Commander_Wars/files/10097417/console.log)

**Comment by Robosturm** [comment]
Workaround for the beginning go to the COmmander Wars ini and set the entry UseAiProcess to false

**Comment by Robosturm** [comment]
Might mostlikely be an issue that more than one CoW subprocess is/was still running.
Could you check how many Commander Wars tasks show up in the task manager.
Thx.

**Comment by Robosturm** [comment]
The issue is completly dependend on the auto end turn feature.
This causes an unwanted action triggered by the ai on the sub process. Completly messing around with the sync of those processes.

**Comment by Brilliand** [comment]
This isn't only with auto end turn enabled.

With auto end turn enabled, the player's turn auto-ends at the right time, then the AI's turn _also_ auto-ends, then the AI immediately takes its action at the start of the following turn, effectively skipping the player's turn (in the 2-player case).

With auto end turn disabled, the AI starts acting when auto end turn would have activated... and thus, effectively auto ends the turn.  However, this is with the "auto end turn" checkbox unchecked.

**Comment by Robosturm** [comment]
Probably is also related to auto capturing and if you have unit to move over more than one turn

**Comment by Brilliand** [comment]
So, which of those are coming into play when I start my first turn as first player and build two infantry on my two bases (with auto end turn disabled)?

**Comment by TeslaTrooper09** [comment]
when i boot mine it shows one, but once it gets to the start menu a second subtask shows up

![image](https://user-images.githubusercontent.com/75344715/204161098-a0eb795c-af17-45c9-82c9-0cf108832d07.png)
