### ISSUE TITLE
Increase ingame menu size for smaller android devices

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1174]
the ingame menu is super small on the note 20, I can barely select move or attack options even with a stylus.

![Screenshot_20221126-192105](https://user-images.githubusercontent.com/75344715/204117480-705ac1a8-f347-4d27-89e6-8b4a8fafb877.jpg)

![Screenshot_20221126-192117](https://user-images.githubusercontent.com/75344715/204117491-ac4bc69c-717b-4c23-8f20-1af1777b3639.jpg)

**Comment by Robosturm** [comment]
Just don't enable/disable the HIgh-DPI Option, which scales the menu size on android
