### ISSUE TITLE
Vanilla mods not updated for the new release?

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1175]
It appears the vanilla mods (AW:DS Units specifically here) haven't been updated for the new version, as the AW:DS Units mod is referring to a weapon that no longer exists.

![image](https://user-images.githubusercontent.com/50599768/204119962-80a3e67a-3022-457a-8834-989eaa3e6a13.png)

I haven't tested it myself, but saw this in a stream, so sorry if this is invalid...

**Comment by Robosturm** [comment]
This only is an oversight on my side forgetting to delete some files.
The AW-Mods don't update units that doesn't exist in those games in several cases
