### ISSUE TITLE
AI can overspend beyond current funds

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1177]
2 days in a row the ai built units that were more expensive than the funds available resulting in negative funds. then they continued to purchase units that it couldn't afford.

![image](https://user-images.githubusercontent.com/75344715/204161374-4909b9f9-8d25-41a5-9315-e8fec2cc87f0.png)

**Comment by Robosturm** [comment]
Which ai are you using?
This looks like the heavy ai which would be activated by accident

**Comment by TeslaTrooper09** [comment]
default ai, sometimes the ai will get farther along in game, in the match displayed it crashed after buying the co1, where as i tried it again and it made it a few turns farther, the ai overspent, but it eventually crashed... all the games I've reported are using default ai

**Comment by Robosturm** [comment]
#1172
