### ISSUE TITLE
crash after ai starts turn with super power

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1178]
![image](https://user-images.githubusercontent.com/75344715/204162974-d56314bc-daa2-47f7-a14c-1487c304d0c2.png)

game ran till day 13 then after the ai had enough stars for the super it crashed

[console.log](https://github.com/Robosturm/Commander_Wars/files/10099336/console.log)

**Comment by Robosturm** [comment]
#1177
