### ISSUE TITLE
Music Loop Cut too early

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1186]
**Describe the bug**
Music without using CO stops to early. Loop not cut at the right time.

**To Reproduce**
Choose a random map proceed to game without changing anything in the game rules and co settings.

**Expected behavior**
The cut of the music loop is later in track.

**Screenshots**
Not possible.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
If someone provides the loop points i'll fix it but i didn't and won't verify or find the loop points on my end

**Comment by UOcelot16** [comment]
Okay. I'll do it. It should be able to fix this with Audacity.

**Comment by UOcelot16** [comment]
F.E. If no CO is selected and you are in the skirmish, the Advance Wars Dark Conflict main menu theme is also played by chance, the abrupt cut can be heard in the second loop.

**Comment by UOcelot16** [comment]
[Advance Wars Days of Ruin OST 15 - First Strike.zip](https://github.com/Robosturm/Commander_Wars/files/10351804/Advance.Wars.Days.of.Ruin.OST.15.-.First.Strike.zip)

**Comment by UOcelot16** [comment]
Maybe you know but I want to to say that currently it is still in the game even if an alternative has been given.

**Comment by UOcelot16** [comment]
Cleanup of backlog.

Topic closed because Rob is not able to fulfill his attitude a human coexistence and wants to enforce his will by all means.
