### ISSUE TITLE
When a spectator fails to join the other players disconnect

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1189]
**Describe the bug**
Whenever someone tries to spectate a game with 0 observers the other players will disconnect.

**To Reproduce**
1. Host a multplayer match.
2. Start the game.
3. Have someone try to spectate.
4. See that the other player disconnects.

**Screenshots**
Screen of the host whenever someone tries to spectate.
![spectate_host](https://user-images.githubusercontent.com/113127747/205088793-508b29d4-1adf-4009-8525-f96030fe4311.png)

Screen of who got disconnected.
![spectate_client](https://user-images.githubusercontent.com/113127747/205091882-29f9f8c6-9f13-4785-8117-862abbcd6bde.png)

**Additional context**
The player who tries to spectate gets no error message instead goes instantly to the multiplayer screen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 26_1
 - Active Mods: None

**Comment by Robosturm** [comment]
Disconnect messages get send to all clients instead of the one who should receive it. 
Whoopsie!
