### ISSUE TITLE
Terrain Image Preview

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#119]
As mentioned on the Discord!
![image](https://user-images.githubusercontent.com/51452633/71916611-9a255680-317e-11ea-9180-a1f356f0cced.png)

**Comment by Robosturm** [comment]
Will look like this
![grafik](https://user-images.githubusercontent.com/48879701/72217546-c7338980-352f-11ea-9766-1425cbbc853f.png)
