### ISSUE TITLE
Updated Design for Damage Calculator

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1193]
**Is your feature request related to a problem? Please describe.**
Not a problem. Just a proposal for a design.

**Describe the solution you'd like**
All proposals are written in the screenshot.

**Picture**
![Damage_Calculator_Proposal](https://user-images.githubusercontent.com/119428442/205365152-efcbaa90-2af2-4aef-acaa-fd857a0eb179.png)

**Comment by Robosturm** [comment]
Centered tiles.
However i'm not adding space cause the ui is already pretty large for a smartphone and adding more space is currently not possible without a proper small screen device solution, which is currently not part of the road map
