### ISSUE TITLE
Damage Calculator Missing Terrain and portrayal of larger buildings

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1194]
**Describe the bug**
On the 16th of November this year SaMantaUwU mentioned about the issue that in the damage calculator is not an option for choosing a city for further Calculations. Yet, in main 0.26.-main this issue still exist. During the map editor it is between the com tower and the first black cannon. But even it is because of other arrangements in this list it cannot be found. Also what can be seen is that larger buildings which are greater than 16x16 its no more clearly what building has been chosen. Maybe it would be an idea to cancel them out in this list or other ideas about that.

**To Reproduce**
For comparison ->Go to the map editor / Go to an ingame random skirmish battle.

**Expected behavior**
I think it is self explanatory.

**Screenshots**
![Damage_Calculator_Missing_Town_and_others](https://user-images.githubusercontent.com/119428442/205367453-82c0208a-4dcd-4b11-8b85-9c0127428a90.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: 0.26.1-main
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Just a sidenote bugs get only fixed, if they get reported on github.
I don't have time to backtrace all discussions on the server and search for possible mentioned bugs.
And SaMantaUwu knows about it. I'm said it a couple of times,

**Comment by UOcelot16** [comment]
a) I have named the person in the description because he/she has found the error and I do not want to adorn myself with things that I have not found myself. That I finally uploaded this via github has not been discussed.

b) This error message was communicated on Github solely because of the fact that it exists. Self-interpretation and personal evaluation were not submitted.
