### ISSUE TITLE
Doubled Maps (checked for AWDS Maps)

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1195]
**Describe the bug**
All current Maps have a double one of itself without a difference from normal or hard campaign. For preventing that it would be practical to Add the Missionnumber before the actual Missionname. F.e. Mission 01: Jakes Trial.

**To Reproduce**
New Game -> Advacne Wars Dual Strike Campaign -> (see Maplist)

**Expected behavior**
Self explanatory.

**Screenshots**
![Doubled_Maps_AWDS](https://user-images.githubusercontent.com/119428442/205371441-4a68de76-e070-441e-b8d0-0baf40d8dbf6.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1.-main
 - Active Mods: Vanilla

**Additional context**
If there is interest in recreating the other maps after M09 I would like to.

**Comment by Robosturm** [comment]
The AW-DS Campaign is currently in an alpha state with no intention to finish it or adding all missing maps.
Reason beeing:
* Double/Tag maps are not supported in CoW and support won't be added.
* There's currently no source for fog of war maps

If someone wants to do something for that that's fine but for now it stays in an incomplete state

**Comment by UOcelot16** [comment]
Cleanup of backlog.

Topic closed because Rob is not able to fulfill his attitude a human coexistence and wants to enforce his will by all means.
