### ISSUE TITLE
2022-12-03 - Feature Request Log

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1197]
**Preamble**
Due to the number of suggestions that can be made, these have been grouped together. As with the error report, if this display does not fit, they can be uploaded individually.

**1. Proposal - Key mapping:**
Options -> Controls

Currently, "Key" is also specified for each key assignment. How about the following design?
![Vorschlag_Tastenbelegung_Design](https://user-images.githubusercontent.com/119428442/205438965-75e280b5-4e60-498d-993b-258f5244357c.png)

**2. Proposal - Gate:**

Terrainpicture for Gate vertical and horizontal. For the black hole factory there will be used gate pictures already. Should be good for using this also on Gates.
![grafik](https://user-images.githubusercontent.com/119428442/205439094-bbd00de4-2430-4c14-b087-18c844edc724.png)

**3. Proposal - Laserrange:**

During the original the small Laser is able to shoot over the whole map in all straight directions. Currently it uses 19 tiles away from the building. Any possibility to change it to inf.?
![grafik](https://user-images.githubusercontent.com/119428442/205439081-190a09ea-20ac-433a-9df2-be33d99a2e2e.png)

**4. Proposal - new arragement settings f.e.:**

More spacing, Scrollbars which are in the same position as checkboxes and others. You can see that the i points are cut off, among other things, because they are too close to each other from a previous line. This also includes k, l, h, b and other letters.
![Screenshot (416)](https://user-images.githubusercontent.com/119428442/205439116-8bde0698-30ca-444e-847d-1452e4544b2f.png)

**5. Proposal - subheadings:**

In the same lettering size as other headings as seen in suggestion 4 above. This concerns:
Options -> Video
	-> Audio
	-> Gameplay
	-> Controlls
	-> Network

**Comment by Robosturm** [comment]
Same split it up please.
3. Won't be changed but can be changed via mods
4. The font size handling is currently a work in progress. Since the final ttf-font file is currently undecided and the font size and positioning is not fixed yet

**Comment by UOcelot16** [comment]
Since you have already partly commented on this entry, which one of them should be rereportet?
1. Proposal - Key mapping: and 2. Proposal - Gate:?

**Comment by Robosturm** [comment]
Both are done
