### ISSUE TITLE
Talon Gun Animation Cut Off

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1199]
![grafik](https://user-images.githubusercontent.com/119428442/205461128-af7e3cb3-8f1d-4705-93fb-2923614e6e81.png)

**Describe the bug**
The animation of the Talon Gun implemented in CW is interrupted too early before it retracts again. Acquired targets are not marked.

Example of how the Animation should look like:
Resonance22Channel Video; https://youtu.be/Bqr0ATsQirg?t=1440

**To Reproduce**
Choose a self created map which has a talon gun. 

**Expected behavior** (Animations)
Targeting -> extend -> Attacking nearby enemy units -> retract

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v.0.26.1-main
 - Active Mods: Vanilla

**Additional context**
If there is interest for task being taken over, please let me know and state in which folder the changes are to be made. Would like to fix it.

**Comment by Robosturm** [comment]
Added a moving in part for the animation
