### ISSUE TITLE
Proposal Restart Button

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1202]
How about an option for restarting a current game in singleplayer mode? The momentary position of this button in screenshot is only for showing how it looks like not where it should be displayed.
![Restart_current_game](https://user-images.githubusercontent.com/119428442/205505899-023be1c8-6919-43cf-9f81-7e4469d57175.png)

**Comment by Robosturm** [comment]
I have been thinking about that button and i found a lot of technical problems which prevent adding this feature.
Especially over savegames, so i decided to not add this feature.

**Comment by UOcelot16** [comment]
Okay.
