### ISSUE TITLE
Proposal for destroyed Gates

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1210]
Own designed Version of Destroyed Gates. If there is something that needs to be changed or needs more pictures I would like to modify it.
![Destroyed_Gate](https://user-images.githubusercontent.com/119428442/205512813-98a10e05-1a15-41bd-8482-3b0adc56b61f.png)

**Comment by Robosturm** [comment]
![screenshot+1](https://user-images.githubusercontent.com/48879701/205673368-71d15e9b-f643-404f-849d-c07ea67875f7.png)

**Comment by UOcelot16** [comment]
Very cool :)

**Comment by UOcelot16** [comment]
I've forgot to ask. Since within the Wiki wasn't a Terrain which said Destroyed Gate (vertical / horizontal) this should be also a task to made.
