### ISSUE TITLE
Proposal for all Icons with fixed scalation

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1214]
The purpose of the revision is to have a format that corresponds to the 16x16 format. The icons occupy 8x8 pixels. This will be the same resolution as the long-existing sprites.

**Contents Icon Folder**
![grafik](https://user-images.githubusercontent.com/119428442/205555993-54da0ab4-18c4-4061-984b-9c35671f6023.png)

**Example of the Updated Icons**
![grafik](https://user-images.githubusercontent.com/119428442/205556556-be225604-916c-42f5-baf3-f1b61ae27c5a.png)

**File**
[units.zip](https://github.com/Robosturm/Commander_Wars/files/10150866/units.zip)

**Comment by UOcelot16** [comment]
Even though most of the icons have been edited, it is not clear what they are all used for. For example, there is a material icon in the folder two times by default (material.png, material1.png), also I do not know what ammoA.png does because ammo.png is also available.

**Comment by Robosturm** [comment]
Icons are intentionally larger the base size of a unit is 32 pixels and with the option to zoom.
Downscaling icons isn't an option on top the game is able to scale smaller or larger icons correctly
Also there's no need to cleanup sprites which may or may not be used later or used as a reference for an icon upgrade.
Going to anything smaller than 16px.

**Comment by UOcelot16** [comment]
What a pity. Then I keep it to myself for separate insertion.
