### ISSUE TITLE
Problem wih Grammarcorrection

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1215]
**Describe the bug**
- For the terrain "Fog" and "Meteor" there are spaces that are not obvious where they could come from.
- The structure for _BASEMOUNTAIN contains text denominations. With the request for change.
- The structure for _BASEFOREST contains text denominations. With the request for change.

**Screenshots**
![Problem wih Grammarcorrection](https://user-images.githubusercontent.com/119428442/205580283-9b29a952-7c3b-4970-b958-c599614a370b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main (2022-12-04)
 - Active Mods: Vanilla

**Comment by UOcelot16** [comment]
**Additionally:**
The following names lack an additional space to perform a correct sentence separation.

-> co_empty_bg
-> co_empty_bh
-> co_empty_bm
-> co_empty_dm
-> co_empty_ge
-> co_empty_ma
-> co_empty_os
-> co_empty_yc

For other factions this is not needed because there is no follow-up text in the script.

**Comment by Robosturm** [comment]
Since it's only a warning by linquist and you're still able to do changes and the english version is correct.
The solution is ignoring the warning since it's not relevant.
Dunno if you can tell linguist to ignore the warning, but since CoW uses some html parts in translations, there's always the potential for linguist doing a false positive

**Comment by UOcelot16** [comment]
**Since it's only a warning by linquist and you're still able to do changes and the english version is correct.**
Is there a command asking the program to remove the space? Strangely enough, another text (tried with terrain for mountains) there are not these problems. Otherwise, it should also go away if the green text is removed at this point.


**Dunno if you can tell linguist to ignore the warning, but since CoW uses some html parts in translations, there's always the potential for linguist doing a false positive**
It's not about a false error message it's about that it forces a space which it does not display / report in Qt Linguist.


**About the Text snippets within Qt Linguist**
This was something I was supposed to tell you anyway. Could you do something about it?


**About sentence separation**
If no change is considered here, could you add the missing space for the original text? Of course I can already include this in the German translation only then it is still fehrlich in English.

**Comment by Robosturm** [comment]
I think i know why you get that space. So when a text contains green text so markers like this. <div c='#00ff00'>hiding places.</div>
The following text and the previous texts must look like this:
<r>Test</r>
The reason being is that the text is interpreted as html parts and not having 
<r>Test</r> makes the html parser go wild 

**About sentence separation**
I just don't understand where a space should be missing
