### ISSUE TITLE
Talon Gun Attack without SFX

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1216]
Targets were attacked without sound effect.

**Comment by Robosturm** [comment]
Sounds are missing cause. I have no resources to get them.
That's true for several missing sounds.

**Comment by Robosturm** [comment]
I have not a complete list.
But i think at least lasers, deathray, crystals and all dc-special buildings and probably several sounds inside the battleanimations are missing.

**Comment by UOcelot16** [comment]
Noted.

Here is for the beginning the Talon Gun SFX. Since Github doesn't want mp3 directly here a zip of it.
[Talon_Gun_SFX.zip](https://github.com/Robosturm/Commander_Wars/files/10155385/Talon_Gun_SFX.zip)

**Comment by UOcelot16** [comment]
**Here are the missing cropped Nest SFX**
[AWDC_Nest_SFX.zip](https://github.com/Robosturm/Commander_Wars/files/10156236/AWDC_Nest_SFX.zip)

**For the others**
I have no Savestate of the Final Mission in AW2 but I'm on it. Now which Battle SFX should you need?

**Comment by UOcelot16** [comment]
**SFX Deathray**
[AW2_Deathray_charging_and_attacking.zip](https://github.com/Robosturm/Commander_Wars/files/10156546/AW2_Deathray_charging_and_attacking.zip)

**Comment by Robosturm** [comment]
@UOcelot16  Don't close issues or else they get lost in the void if i have still things to do for them e.g. integrate the sounds.

**Comment by UOcelot16** [comment]
I'll keep that in mind.
