### ISSUE TITLE
Proposal: Adjusted delay times between attack- and impact animation

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1217]
Is there interest in customizing this? If so, I would like to check the time delays, write it down in editor and inform you accordingly.

**Comment by Robosturm** [comment]
The game has no real delay between fire and impact.
The delay is actual Fire-Duration - actual animated time

What you can do is in the folder resources/scripts/battleanimations

Each file normally contains a function like this:
    this.getFireDurationMS = function(sprite, unit, defender, weapon)
    {
        var count = sprite.getUnitCount(5);
        return 500 + 150 * count;
    };

This means the base animation has a duration of 500ms + 150ms * unit count
Where unit count is the of shown units / in case of battleships canons which shoot. 
So increasing the 500ms would increase the delay.

However i'm rather against adding more delay cause people have said the current delay is rather long and use a higher speed for those animations anyway.
So while a larger delay may look more realistic it's mostlikely not a quality of life buff.

**Comment by UOcelot16** [comment]
Yes, that's a very good point that I didn't even consider. But thank you for letting me know the small section where I have to search for my own designs. I'll keep that information in my archive.
