### ISSUE TITLE
Missing Translationoption for Destroyed Terrain

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1219]
**Describe the bug**
Description should say all.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Checked Plains+Destroyed and Plains Plasma and Destroyed Weld all show up in linguist.

**Comment by UOcelot16** [comment]
First I thought what you mean but then I've read my Header. I've forgot to write that I mean the destroyed Terrain for gate. This cannot be found in the .ts file.

**Comment by Robosturm** [comment]
That's cause gates currently fallback to destrpyed plains and only with the next release destroyed gates are actually a thing.
Before a destroyed gate was transformed to the same terrain as a destroyed mini cananon or laser.
