### ISSUE TITLE
Missing Translationoptions in Multiplayer

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1220]
**Screenshots**
![Screenshot (574)](https://user-images.githubusercontent.com/119428442/205869827-d669aaaf-4c62-46fb-902f-f2a08fa29221.png)
![Screenshot (575)](https://user-images.githubusercontent.com/119428442/205869834-5d0d4ba5-b209-457d-9954-d388c19e2840.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
No not really. It's definetly a bug in linguist, cause i can see the entries in the translation file but they aren't visible in linguist
