### ISSUE TITLE
Proposal Perks with consistent three contents

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1222]
Since within the scripts have sometimes to have three sometimes only two changeable contents can you assign the following attributes to each ability?
- Description
- Name of Perk
- Perk Category

I'll list the perks with only two entries:
co_perk_apcboost
co_perk_conquerer
co_perk_eagleeye
co_perk_gear_head
co_perk_gold_rush
co_perk_invader
co_perk_leader
co_perk_mechanic
co_perk_sale_price_5
co_perk_sale_price_8
co_perk_scout
co_perk_sneaky
co_perk_stealthy

**Comment by Robosturm** [comment]
All named classes use the category from the base class which is General.
So they have 3 options only the 3 option is only used in co_perk.js
