### ISSUE TITLE
Issue: Icons move around in the map editor

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1223]
**Describe the bug**
The Icons of Black Fortress and Omega Base move or change in the map editor (see Screenshots). It occurs independently of the grid problem caused by the graphics card. The test was determined on another computer where the grid display is OK.

**To Reproduce**
Use the Map Editor

**Expected behavior**
Behavior like other icons.

**Screenshots**
![Map_Editor_Moving_Icon_1](https://user-images.githubusercontent.com/119428442/206133777-59bf5dff-819a-494c-9938-3f1fca4cdd61.png)
![Map_Editor_Moving_Icon_2](https://user-images.githubusercontent.com/119428442/206133794-93d9bc97-a957-4a23-9e47-5a31700f770a.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main
 - Active Mods: Vanilla

**Comment by UOcelot16** [comment]
I'm looking at the map editor interface. (Can't take a screenshot on my main pc right now)
![Unbenannt](https://user-images.githubusercontent.com/119428442/206160413-29af3252-a875-4470-8910-91cdad4c88cb.png)

**Comment by Robosturm** [comment]
I think i know what you mean sadly it's not reproduceable anymore on my pc.
It's pretty much the same issue with opengl and pixel perfect rendering,
I did already a lot of tests to get it eventually fixed on my end.
I have one task open where i want to change all initially calcualted floating numbers rounded down to pixels which may fix some of those Issues. But that's a larger task for the future.

**Comment by Robosturm** [comment]
It's an issue with the graphic cards driver when down scaling the image and swapping between frames.
The graphic card chooses different pixels in certain scenarios. :(
