### ISSUE TITLE
Proposal: Adjustment of the visual display in map menu

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1224]
**Described via Screenshot:** also missing colon
![Proposal_Arrangement_for_Text_Skirmish_Menu](https://user-images.githubusercontent.com/119428442/206135280-8877d4a3-54ad-4847-885e-39e92d7563ba.png)

**Comment by Robosturm** [comment]
The menu will get a complete overhaul. Fairy made a draft version a while back.
I close this issue since the menu gets changed in the future and the work for that improvement highly exceeds the benefit for that time
