### ISSUE TITLE
Proposal: Add qsTr script editor Entries

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1225]
**Describe the bug**
In order to call up part of the report from 12/02/22 communicated (02.12.2022 15:52, Issue Report, 16:35, Feedback) as a screenshot, there are no options to change the following terms.

**Screenshots**
![Missing_Translation_Scripteditor](https://user-images.githubusercontent.com/119428442/206136634-3799184d-d643-40dd-8f9e-a67b605a719c.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Already fixed with the earlier request for some entries in the actual modification page, i believe.
