### ISSUE TITLE
Shroud of War

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#123]
A fog of war variant, shroud of war would shroud the entire map in blackness, preventing players from seeing the terrain. Once it enters into a unit's (or building's) sight range, it is revealed like in fog of war. If it then leaves a unit's line of sight, fog of war sets in like normal.

**Comment by Koopanique** [comment]
Yes! I agree, it would be a cool (although not urgent) feature. It would give the game a "Civilization" feel.

**Comment by Robosturm** [comment]
Was already in the backlog and is the reason. Why Fog of War is a drop down menu
