### ISSUE TITLE
Amphibious factory wrongly able to resupply ships

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1233]
**Describe the bug**
Currently Amphibious factories can ressuply and repair Naval units however those units cannot move into the factory.

**Expected behavior**
Naval units should be able to move into it like if it was a port.

**Screenshots**
Supplies navals but they cant move into it:
![hideous_factory](https://user-images.githubusercontent.com/113127747/206283820-b06a1789-6fed-4153-96da-3e96993fa53b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 26_1
 - Active Mods: None

**Comment by Robosturm** [comment]
Removed ships from supply list as this is the intended behaviour
