### ISSUE TITLE
Naval units predeployed on land cannot do any action

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1234]
**Describe the bug**
When a naval unit is on a land tile unable to move, it wont be able to do any actions like wait or unload, despite being able to load units.

**To Reproduce**
1. Set a Naval unit on a ground tile via map editor.
2. See that the naval unit wont get the option to fire, wait, unload or any other action.

**Expected behavior**
Even if it cant move it should be able to fire and do its actions like producing and unloading.

**Screenshots**
No actions avaliable:
![cant_do_anything](https://user-images.githubusercontent.com/113127747/206292305-6cc243e4-1be3-401f-ac62-434dfa521634.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 26_1
 - Active Mods: None

**Additional context**
In awbw landlocked ships can do the unload and repair.

**Comment by Robosturm** [comment]
Placing units on none-moveable terrain is possible iva a mod but not in the base game.
Any behaviour for them is unexpected and undefined and will always be that way.
This isn't a bug.
