### ISSUE TITLE
Issue: Terrain names will not be updated

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1235]
**Describe the bug**
Maps created at a time x save the name of the terrain. If a later version of the game is loaded which has a different name for the terrain or is started in a different national language, the status of x is retained.

**To Reproduce**
1. Create Map with a Terrain which will be examined, make the map playable and save it.
2. Start Map in Skirmish an Screenshot the current Name of this Terrain and close the game.
3. Change the Terrain Name in .ts with something other.
4. Start the Game and start a new skirmish with this map. See the result.

**Expected behavior**
Changes that were given to the terrain in terms of the name are adapted according to the current version without them remaining in the old stock (see text file screenshot).

**Screenshots**
![Example_Temp_Translation_1](https://user-images.githubusercontent.com/119428442/206849791-d5e423ac-9fc9-4d4e-a302-47c61301dd89.png)
![Example_Temp_Translation_2](https://user-images.githubusercontent.com/119428442/206849792-8a733c29-86f1-4fab-a043-42279d6e4c4e.png)
![Example_Temp_Translation_3](https://user-images.githubusercontent.com/119428442/206849718-e87a7882-ec14-4f7f-8f04-01790b1cb4b4.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.26.1-main
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
It's both a feature and a bug, but i see that the current solution doesn't work as intended when used in combination with translation options
