### ISSUE TITLE
Proposal: Additional / optical Change Perks

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1236]
I would like to suggest perks that are currently not included in the game.

![Ebenenfaust](https://user-images.githubusercontent.com/119428442/206851157-78b394b8-a433-46b2-9ad1-c0efcce0baab.png) Plainfighter: Increases the attack from plains by 10%.
![Ebenenfaust-](https://user-images.githubusercontent.com/119428442/206851155-588e1407-58b3-43d5-8797-200649e05a27.png) Plainfighter-: Decreases the attack from plains by 10%.
![SendeturmVert-](https://user-images.githubusercontent.com/119428442/206851146-508da6fb-d451-48f9-8850-31130f22648e.png) Towerdefense-: Decreases the defense boost per tower by 5%.

Some Changes for followed Icons:
![intel_leak](https://user-images.githubusercontent.com/119428442/206851611-92f88b8f-114c-4d3e-9e69-6bdbaeed64b0.png) --> ![intel_leak_2](https://user-images.githubusercontent.com/119428442/206851612-1542ce2f-23ba-49ca-9c23-ca9740063aed.png) Don't know why the minus was orthogonal
![tax_hike](https://user-images.githubusercontent.com/119428442/206851613-3ec62cbf-3433-41f6-908d-1ac8be396e4b.png) --> ![tax_hike_2](https://user-images.githubusercontent.com/119428442/206851615-89c457bf-ec07-4b24-a268-43965654917c.png) Design like the other Coins

**Comment by Robosturm** [comment]
Added minus the Com-Tower part cause it's not really a good skill since towers normally don't give a defense boost.
