### ISSUE TITLE
Proposal: Using Color regardless of the one used

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1241]
**Is your feature request related to a problem? Please describe.**
It is currently configured in such a way that the current map composition is taken into account and the first color is thereby influenced. This creates different colors in the submenu, whether this is intended or not.

**Describe the solution you'd like**
Independent representation of the icons from the colors used.

**Screenshot**
![Screenshot (618)](https://user-images.githubusercontent.com/119428442/206877867-457e6c59-ecc6-4a48-a334-68cc9a7c4174.png)

**Comment by Robosturm** [comment]
The color is pretty much intentional.
The game shows the icons that would show up if the menu is opened in game and thus uses the color of the player.
Changing that is a lot of work and the benefit is pretty much none existent so i won't do that. 
Sry
