### ISSUE TITLE
Proposal: Key mapping

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1246]
Due to #1197 hasn't been fixed it will be reuploaded as Issue

1. Proposal - Key mapping:
Options -> Controls

Currently, "Key" is also specified for each key assignment. How about the following design?

![205438965-75e280b5-4e60-498d-993b-258f5244357c](https://user-images.githubusercontent.com/119428442/207456072-779c686c-383c-41ca-b0b2-4a4c40aa0222.png)

**Comment by Robosturm** [comment]
Enhancement get closed once they are done.
Not once you can get them ingame.
I don't know which version you try to use but it's not the latest source code state.

**Comment by UOcelot16** [comment]
It is the yesterday downloaded zip-file from
https://github.com/Robosturm/Commander_Wars
I will gonna download it again then

**Comment by Robosturm** [comment]
![screenshot+3](https://user-images.githubusercontent.com/48879701/207566007-3bb9959c-fffd-4ea8-9f02-c3fc56995258.png)

**Comment by Robosturm** [comment]
As mentioned you need to either compile the game or wait till the next release.
Enhancements get closed when done not when getting available

**Comment by UOcelot16** [comment]
Okay. Then I'll wait.
