### ISSUE TITLE
Issue: CO Offset of upper Description_2

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1247]
As today tested the Issue hasn't been solved.
CO Offset of upper Description #1207
Today taken screenshot: ![Screenshot (633)](https://user-images.githubusercontent.com/119428442/207456766-3476121c-2682-44fd-9fac-f036375e5f2a.png)

**Comment by Robosturm** [comment]
Enhancement get closed once they are done.
Not once you can get them ingame.
I don't know which version you try to use but it's not the latest source code state.

**Comment by UOcelot16** [comment]
It is the yesterday downloaded zip-file from yesterday via
https://github.com/Robosturm/Commander_Wars
I will gonna download it again then

**Comment by Robosturm** [comment]
Yeah but you didn't compile the game.

**Comment by Robosturm** [comment]
You only get changes from scripts but in many cases you need both changes in the c++ code and the js scripts.

**Comment by Robosturm** [comment]
![screenshot+2](https://user-images.githubusercontent.com/48879701/207565784-fa663316-17e3-4798-bb8d-57d43a47c8b5.png)

**Comment by UOcelot16** [comment]
> Yeah but you didn't compile the game.
So that means I can only compare this if a newer version than v0.26-1 build 5 is out?

**Comment by Robosturm** [comment]
That or you compile the game yourself

**Comment by UOcelot16** [comment]
Okay. Then I'll wait.
