### ISSUE TITLE
Proposal: Nest Factory Picture

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1248]
Currently there is no terrain icon used for the nest factory gate. How about using the same picture which is used for the black hole factory?

**Comment by UOcelot16** [comment]
**"The gate is not a good picture cause the actual tile has a high of 4 and only the first part is the gate"**
Hope that the factory gate has been meant.
![fore_factory+0](https://user-images.githubusercontent.com/119428442/207640819-eae7ba40-abc1-41f6-bb56-ca5bc9710fcd.png)
Shouldn't it be the same with the black hole factory? There are also other tiles and the factory gate.

**"also the gate takes the whole image as picture"**
Does it maybe have something to do with the fact that units can stand on the Nest gatetile and what was not possible in the earlier factories? If so then I would like to ask if the battlebackground like in Crash Landing C24 would be an better alternative?

**Comment by Robosturm** [comment]
The bh-factory is currently showing the default building background which is a town

**Comment by UOcelot16** [comment]
Yes. The Black Hole Factory itself has the default. For Factory Doors which are available is the first picture shown front which will be combinded with a background.
![1234](https://user-images.githubusercontent.com/119428442/207650539-3241e997-1ce4-4479-80dc-f27e5749553d.png)

So if this tile is splitted...
![nest_factory_1](https://user-images.githubusercontent.com/119428442/207650473-e1ea5321-84b4-472e-97c8-915633f9cc43.png)
![nest_factory_2](https://user-images.githubusercontent.com/119428442/207650480-a43c45cf-22a8-4d74-bad4-8894195628da.png)

**Comment by Robosturm** [comment]
The tile/building won't be split up, because of compatibility and simplicity reasons.
The nest is already a pretty annoying tile and further splitting it up makes things even worse.

**Comment by UOcelot16** [comment]
I've thought about the tiles of the whole nest building. Every tile which has no real relations of effect could be set as you already do / want like in #1344 mentioned since the Nest Factory x1y1 is only reliable on the gate and not the other tiles x1y2 and x1y3. So it will be also possible to show the door as it should #1394.

**Comment by Robosturm** [comment]
As said the nest production tile won't be split up.

**Comment by Robosturm** [comment]
And all tiles will show the same battle sprite since anything is not possible

**Comment by UOcelot16** [comment]
Thats not a problem if all tiles of the nest factory shows the same battle sprite because x1y2 and x1y3 it is not possible to place a unit.

**Comment by Robosturm** [comment]
They are possible to execute the action to build a unit and the unit gets spawn at the door.
So the background needs to work for all fields

**Comment by Robosturm** [comment]
Cleanup of backlog.
Closed issue since resource contributor decided to work for the project.
If this changes or someone else wants to provide the resources a new isdue can be created
