### ISSUE TITLE
Unit Taglist

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#125]
When reading about other feature requests and solutions to the problems described, I came up with an idea to make certain things easier; the ability to create 'tags' for a unit type, which would essentially just be an array of strings.

These tags could then be called upon later on and checked for various purposes, as an example, #112 could use this. Simply add "FirstStrike" to a unit type's tag list, then in ACTION_FIRE you could do something like if(tags.contains("FirstStrike)) to determine whether or not a unit would have first strike, as opposed to having to check to see if a unit is a specific unittype, which can get tedious if you have multiple units that can all do the same thing. instead of having to do a big If-statement to see if the unit is one of several units, you can just check if the unit has the required tag.

Here's how I imagine it would look:

In the unit file:
`    this.getTags = function()
    {
        return ["FirstStrike","Conceal"];
    };`

And then in ACTION_FIRE you could do

`if(unit.getTags.contains("FirstStrike")) {
[STUFF]
};
`

instead of
`
if(unit.getUnitID() === "UNITA" || unit.getUnitID() === "UNITB") {
[STUFF]
};
`

**Comment by Robosturm** [comment]
Added a string list to script variables. which should suit the puprose of asking for contains
