### ISSUE TITLE
Issue: Map Editor Longer displayed Entry 

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1266]
**Describe the bug**
In the map editor, a button specifies more text than can be found in the translation file.

**Screenshots**
![Karteneditor Mehr angezeigt als es soll Fragezeichen](https://user-images.githubusercontent.com/119428442/209806624-cdae6f15-6b10-4f2c-92a4-9f02c8a8bad1.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
The game graps the actual key selected in the option and displays it.
So the behaviour is correct

**Comment by UOcelot16** [comment]
Since B is intentional where is B in the Control Settings?

**Comment by Robosturm** [comment]
It's the same as the cancel button it's not a seperate key
