### ISSUE TITLE
Issue: Submenu -> Button Problem

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1267]
**Describe the bug**
Button problem still present in various submenus.

**Screenshots**
![Schaltflaeche im Untermenue](https://user-images.githubusercontent.com/119428442/209806867-a99636dc-2832-4358-a82d-dcf1f92c49f6.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Not reproducable on my end but i changed the code which could produce the behaviour
