### ISSUE TITLE
Issue: Submenu -> Action List

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1268]
**Describe the bug**
Action list Description instead of action specified multiple times. See image. There may be more that hasn't been shown / discovered.

**Screenshots**
![Bezeichnungen statt Aktion angegeben](https://user-images.githubusercontent.com/119428442/209807050-cea961f0-5350-4ab9-856c-430714fa3fde.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
This is intentional since every action is different in the wiki since it does something else but shown only with fire when using it in game, e.g. when firing with the nest or something.

**Comment by UOcelot16** [comment]
Ich möchte gerne meine Erläuterung zu diesen Sachverhalt in deutsch wieder geben um den Fehler in anderen Worten wieder zu geben:
Es geht darum das die Beschreibung und nicht die Aktionsbezeichnung genutzt wird. Das einzelne Aktion mehrfach die Bezeichnung "Feuer" haben ist mir schon klar. Darum habe ich auch mich in der Übersetzung dafür entschieden die Aktionen den unterschiedlichen Gebäuden anzupassen. Kurzum. Es wird der Tooltip der Aktion, nicht die Aktionsbezeichnung verwendet. Wenn dies der Fall wäre müsse folgendes ähnlich zu sehen sein. 

![a](https://user-images.githubusercontent.com/119428442/209992386-8b4e61f9-075c-43dd-8a1d-abbd61debe82.png)

Vergleiche bitte das zuvor hochgeladene Bild. Rechts ist in Qt Linguist die Beschreibung von "Fire" markiert und diese wird im linken Screenshot die Beschreibung für "Fire" als Aktion und Tooltip verwendet.
