### ISSUE TITLE
Issue: Submenu -> Action List doubled Entries

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1269]
**Describe the bug**
There are two times game surrender in the action menu. See image. Also applies to nickname given.

**Screenshots**
![Zwei mal Spiel kapitulieren](https://user-images.githubusercontent.com/119428442/209807178-44bdfc40-c7b9-4999-b82b-1ed036b1dccf.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Again intentiomal for actions using a pop question in game before actually executing the action
