### ISSUE TITLE
Proposal: Double Entry for Weather

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1270]
Display reasons sunny, windy, sandstorm, rain, fog, snow give a second definition so that the variable can be accessed once. In the other case, this is only used because of the punctuation (representation with :) in the menu. See for example the ingame settings section.

**Comment by Robosturm** [comment]
No clue what this is meant to request

**Comment by UOcelot16** [comment]
Here a Screenshot

![Screenshot (695)](https://user-images.githubusercontent.com/119428442/209986290-07e662ae-b17c-40ab-aff2-4446fe40dc50.png)
