### ISSUE TITLE
Proposal: Script Menu -> Change Terrain

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1271]
That would save switching from script to map.

**Screenshot**
![Skripteditor Terrain aendern](https://user-images.githubusercontent.com/119428442/209807489-a898fa7c-2395-4853-befc-d5dd1ce8596c.png)

**Comment by Robosturm** [comment]
The script editor and the map currently edited are not connected to each other and will never be connected.
That you have the map opened you currently edit a script for is lucky at best.
