### ISSUE TITLE
Proposal: Left Right Switching

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1273]
In case of maps with a large number of buildings, the various buildings are displayed in the lower field of the menu. The arrows to the left and right of this are currently used inverted. Wouldn't it be better to move the list of buildings to the left if you press the left button? Similarly for the right.

**Screenshot**
![Links und Rechts Schalten im Kartenmenue](https://user-images.githubusercontent.com/119428442/209807798-4407710d-3f1c-4430-8442-f018eff58ba0.png)

**Comment by Robosturm** [comment]
As mentioned this menu is in the queue for reworking and no changes will be made to it.

**Comment by UOcelot16** [comment]
I thought that the reworking would be finished with v0.27.1-main. That was the reason why I've opened #1273.
