### ISSUE TITLE
Proposal: Optical Change for MP Menu

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1274]
**Screenshot**
![Anpassung Multiplayer Spalten](https://user-images.githubusercontent.com/119428442/209807908-2115b491-fa8b-42ed-b6cb-527d869f15f9.png)

**Comment by Robosturm** [comment]
Kinda implemented behaviour is based on screen size so you still can get the current one if you play on a small screen. due to the lack of actual size to display everything
