### ISSUE TITLE
Team Elimination

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#128]
The victory condition "Elimination", works great when it comes **to 1v1 or Free For All games**, but even with that **the team matches i.e 2v2, 4v4 (or 7v7 map) can take long time to finish due to fact that ONE player of their team must collect all required kills to win.**

The good idea would be to put victory condition called "Team Elimination", where the winner is the team who will collect required number of kills. I think that could make team matches faster to end.

**Comment by Robosturm** [comment]
Already implemented for the next release. ;)
You get a checkbox for Team Victory. Same goes for Capturing a given number of buildings.
