### ISSUE TITLE
Proposal_TL: Item -> Map

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1284]
A "map" will be overwritten / deleted instead of "item".

**Screenshot**
![2](https://user-images.githubusercontent.com/119428442/209986419-4ff28d04-e320-40fd-960b-5ff69c7cc0e1.png)

**Comment by Robosturm** [comment]
This is a generic message used for maps, savegames and other items that get saved in the game

**Comment by UOcelot16** [comment]
Okay. How about "File" for Item?

**Screenshot**
![grafik](https://user-images.githubusercontent.com/119428442/211073685-d5cb425f-8608-4381-b450-4a0b2fad7639.png)

**Comment by Robosturm** [comment]
I'm fine with file
