### ISSUE TITLE
Proposal: Consistent Actionfield for Units that cannot attack

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1285]
**Screenshot**
![Screenshot (705)](https://user-images.githubusercontent.com/119428442/209986738-66f38c48-e0ee-4534-afe7-c7d9dcf19d2f.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Just as a note orange is vision range and red attack range
