### ISSUE TITLE
Map Editor tries to place tiles on the same field twice under some situations

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1286]
Within the planner, the sound for selection is played twice at short intervals from each other regardless of what was selected on the map. The probability that it occurs is not always but very often.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
PLease rever to the editor as map editor and to the planner in during playing a map as movement planner, to avoid confusion
