### ISSUE TITLE
Issue: Missing Mortar Sprite

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1287]
SFX of AWDC / AWDoR Mortar Attack is implemented. Will the sprite be needed?

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Any sprite not implemented is missing and without correct formatted source material won't be added

**Comment by UOcelot16** [comment]
If I'm ready with the sprites could you add it in game as you've done it in #1365? Would only like to know if a gif or the separatet pictures would be necessary.

**Comment by Robosturm** [comment]
For the mortar i'll only accept a full made sprite animation like e.g. this for the silo.
![silo+launch](https://user-images.githubusercontent.com/48879701/212129467-28813cf9-1881-455c-bf3e-ff275437d756.png)
I won't do work for an animation that's pretty much never seen and isn't really of any interest to me

**Comment by UOcelot16** [comment]
Thats what I've meant about an hour ago. I would like to know how do you need it as gif or separated pictures mentioned?

**Comment by Robosturm** [comment]
None of them as said one picture as posted. If you give it either as gif or separated pictures it will not be added

**Comment by UOcelot16** [comment]
I don't know what your problem ist now. You were able to do this even in #1365.

**Comment by Robosturm** [comment]
Read my comment i said i won't invest time into it.
And i do what i want this is my hobby and not a job or anything i get money paid for.
So if i say i want it in this format or i won't add it, it's what i do.
I have the luxury to be inconsistent cause i do what i enjoy and don't do stuff i don't enjoy even if it's the same task

**Comment by UOcelot16** [comment]
> I have the luxury to be inconsistent cause i do what i enjoy

Then live with the consequences.

**Comment by Robosturm** [comment]
I can live with not getting blamed for doing something i don't enjoy for a project i do for fun and 
instead do something for the project i do for fun and have fun at the same time.

Everyone doing something for the project should do it and have fun/enjoy it and if someone doesn't enjoy it,
he's free to not do that job/tasl or find someone else do to it or stop working for the project just play it and have fun or feel free to leave the project and stop contributing to it at all.

The primary objective when working or using CoW is have fun with it.
The moment you don't have fun/enjoy it anymore, it's better to remove it from your life.

I don't like putting any sprites together i did it for the silo cause it's a relativ common animation but i won't do it for a mortar animation maybe 0.0001% of the player base will see or miss.
If you can't except that feel free to do what ever you wish to do from the options i listed above.

**Comment by Robosturm** [comment]
Cleanup of backlog.
Closed issue since resource contributor decided to work for the project.
If this changes or someone else wants to provide the resources a new isdue can be created

**Comment by UOcelot16** [comment]
Cleanup of backlog.

Topic closed because Rob is not able to fulfill his attitude a human coexistence and wants to enforce his will by all means.
