### ISSUE TITLE
Issue: Map Editor -> Copy Paste

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1289]
Fields with Terrain, Units or Buildings will not be copied.

**Screenshot**
![1](https://user-images.githubusercontent.com/119428442/209987268-1e034ebe-2cef-45a3-b8e1-8733e75234fc.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build 3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
The game only copies the part currently selected for placement
