### ISSUE TITLE
Proposal_TL: Consistent shown Definition

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1293]
![DoR DC 1](https://user-images.githubusercontent.com/119428442/210134583-74589a40-dcf5-4305-abae-94291f4823d7.png)

**Comment by Robosturm** [comment]
I'm going to use the term Advance Wars 4 in those cases. Minus ship bridges since the terrain affected in game are the ship bridges and not AW-4 bridges or anything

**Comment by UOcelot16** [comment]
Then I'll use the Term "Passable Bridges" / Passierbare Brücken.
