### ISSUE TITLE
Proposal: Condition Capture Victory

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1298]
Counter starts at infinity. The actual value is given as 52 first. Start at 1 as with other values makes sense. Removed from infinity stat as that stat doesn't contribute to a revenue win. Other conditions may require the same facts.

**Comment by Robosturm** [comment]
Infinite is correct since the rule is disabled marked by the infinite value some for other rules.
The game also jumps to the first value which makes sense so a map where a player has already 10 starting props starting at 8 makes no sense

**Comment by UOcelot16** [comment]
For example where it is reasonable to have this condition.

![grafik](https://user-images.githubusercontent.com/119428442/210769799-24af8050-bdbe-4145-91e2-48a815f2b85f.png)

**Comment by Robosturm** [comment]
As said on that map the first value gets 2. It's map based and not a fix value

**Comment by UOcelot16** [comment]
Okay.
