### ISSUE TITLE
Proposal: Additional Load Button

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1312]
![Screenshot (763)](https://user-images.githubusercontent.com/119428442/210783106-61bd5447-d8f6-48b8-8c0d-383a9c755a00.png)

**Comment by Robosturm** [comment]
Loading makes no sense/ is not support once you get this far. You can only save the setup but reloading is done when you select a map. The save button mainly exists for saving random maps.

**Comment by Robosturm** [comment]
Simply by selecting it in the map selection menu like any other map.

**Comment by UOcelot16** [comment]
Okay. So it is possible to load a map with rules, but it is saved separately in the main folder so that you have it in the game twice.  ?

**Comment by Robosturm** [comment]
Basically that's how it works/ is meant to work, but mostlikely you want to do it when you play a random map.
Though you can create the same random map if you choose the same seed value and same generation options
