### ISSUE TITLE
Proposal: Double Entry for Fog of War

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1319]
Same as in #1270, additional : for Term

![grafik](https://user-images.githubusercontent.com/119428442/210809256-8ae53862-39b5-425c-bcdf-2855d34eb653.png)

**Comment by Robosturm** [comment]
Technical not possible. You add signs to texts which don't have them and they are the same texts with two appearances in the code.

**Comment by UOcelot16** [comment]
Why was it possible in #1270?

**Comment by Robosturm** [comment]
The simple answer is headlines are not meant to be followed by a : while i can agree for that for items which are changeable.
The text for the headline happens to be the same as that for the drop down entry and qt merges them into one translation option i have no influence on that and i'm not adding a : to headlines cause i don't like that layout.
And the moment you add a sign like : to a text you modify the original meaning which is technical not allowed.
