### ISSUE TITLE
Issue: Planer -> Softlock Freezed Cursor 

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1329]
If this Menu from #1326 will be closed it softlocks the Cursor Ingame. If the planer will be closed it is no longer locked.

Desktop (please complete the following information):

    OS: Win10
    Version: v0.27.1-main build 3
    Active Mods: Vanilla

**Comment by Robosturm** [comment]
#1288

**Comment by UOcelot16** [comment]
#1288 was Player Missle Targets and not the Submenu from #1326.
