### ISSUE TITLE
Proposal: Map Editor -> Change Unit Submenu

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1337]
Since the information has already been provided, how about using the label from the map editor as the header?

![grafik](https://user-images.githubusercontent.com/119428442/211040384-a39a90de-bb33-40a8-af12-bbbd270e7f86.png)

**Comment by Robosturm** [comment]
One more time the text input and the header aren't related. You can name an infantry captain but it's not related to the unit type and thus the header should never relate to it

**Comment by UOcelot16** [comment]
You can label this a fixed if it a proposal has been chanced due this instead of won't fix. Thanks.
