### ISSUE TITLE
Issue: MP Missing Buttons

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1339]
![Screenshot (815)](https://user-images.githubusercontent.com/119428442/211047164-0447e397-0703-4781-9e8b-bee028a85df9.png)

If it was intentional that the buttons are removed, perhaps graying out would be better. Otherwise removing the word "all" would be fine too.

Desktop (please complete the following information):
- OS: Win10
- Version: v0.27.1-main build 3
- Active Mods: Vanilla

**Comment by Robosturm** [comment]
The word all is intentional since the button works on all. The rest is intentional as well.
And All is meant to be related to that exact line so no changes will be made here.
Sice they make sense from my point of view.
And gray button always imply you can un gray them, which isn't possible

**Comment by UOcelot16** [comment]
Even if its currently shown as this?

**Screenshot**
![grafik](https://user-images.githubusercontent.com/119428442/211050302-b8ee896e-e573-4763-8d97-4d589ca898fd.png)

**Comment by UOcelot16** [comment]
Issue fixed.
