### ISSUE TITLE
Enemies can wait their units on teletiles

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#134]
The enemy AI can wait their units on teletiles
![stoppingonteletiles](https://user-images.githubusercontent.com/58909501/73134697-e7b31780-3ff6-11ea-8b09-d2bd6ade1bd8.png)

**Comment by Robosturm** [comment]
In theory the path should be calculated correctly so i need some details to create a test setup.

What sort of unit is that?  Looks like a modded one. So i need the abilities it can use.
Mainly attacking, capturing and loading. and the firerange and if it can move and fire at the same time.

**Comment by Robosturm** [comment]
mostlikely found the bug also added some code to prevent it in case i missed one solution.
