### ISSUE TITLE
Proposal: #C00, Entry of 29.11.22 Naval Unit Sprites

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1340]
Since it is still an open entry, it was uploaded to Github because it was once only given on Discord.

The interest is to show the newly integrated naval units in the same size as all other units.

In consultation with K'Braid, these drawings were visualized at a time when the goal was still to allow representations in 32x32.

If this still applies, work may be carried out on a 16x16 sprite accordingly.

Processing is currently in progress.

**Comment by UOcelot16** [comment]
It was also the Entry of #C03 from 01.12.2022

**Comment by Robosturm** [comment]
Removed issue since it's not an issue

**Comment by UOcelot16** [comment]
Changed Title from Issue to Proposal

**Comment by Jocrr** [comment]
There are already 16x16 sprites for the frigate and destroyer.
The frigate is just the AW2 sprite for cruisers, while the destroyer resembles the old sprite for gunboats (which I believe was made by K'Braid).
I ported and adjusted the sprites for these two some time ago, so here they are if you need them:
![destroyer+mask](https://user-images.githubusercontent.com/93048095/211220915-e78a9347-b598-4e47-ba69-2a8f351a2eb3.png)
![destroyer+walk+mask](https://user-images.githubusercontent.com/93048095/211220916-191871eb-99d8-4adb-a11d-702f239f9910.png)
![frigate+mask](https://user-images.githubusercontent.com/93048095/211220917-66c4a95f-91e9-47b4-ad50-744c0d31a2f4.png)
![frigate+walk+mask](https://user-images.githubusercontent.com/93048095/211220918-c3e42ab1-a737-4cd4-9b84-c5a364300d58.png)

**Comment by UOcelot16** [comment]
Okay then we have destroyer and frigate. Gonna work then for Torpedo, Gun and Missle Boat.

**Comment by UOcelot16** [comment]
Gonna stop it. As long as Rob remains in his infantile attitude I will not help out any further.

**Comment by Robosturm** [comment]
Cleanup of backlog.
Closed issue since resource contributor decided to work for the project.
If this changes or someone else wants to provide the resources a new isdue can be created

**Comment by UOcelot16** [comment]
Cleanup of backlog.

Topic closed because Rob is not able to fulfill his attitude a human coexistence and wants to enforce his will by all means.
