### ISSUE TITLE
Proposal: #C05, Entry of 04.12.22 Additional Sprites

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1341]
Since it is still an open entry, it was uploaded to Github because it was once only given on Discord.

The last exchange on this was that the images are not included due to more important things. However, that doesn't mean it can't be done. In order to have it here as a note, listed here again for later implementation.

![GreatBlobItself](https://user-images.githubusercontent.com/119428442/211058026-aa40bcd0-131f-4deb-9261-ac148ebca0f9.png)
![FF_over_ground](https://user-images.githubusercontent.com/119428442/211058036-3dbe3291-2840-4742-bf17-d0b7a0530e39.png)
![FF_over_water](https://user-images.githubusercontent.com/119428442/211058038-f06fb913-5e63-4d82-b03b-0c7dd577bc00.png)

**Comment by Robosturm** [comment]
As mentioned on discord flying fortress will never be added.
Second this isn't an issue

**Comment by UOcelot16** [comment]
Changed Title from Issue to Proposal.

**Comment by UOcelot16** [comment]
**As mentioned on discord flying fortress will never be added.**
You didn't write that.

> b) --> Fliegende Festung macht keinen Sinn ohne ohne Luftschlachten. Das Mega-Oozium habe ich momentan nicht vor hin zu zufügen. Technisch geht es nach dem auch Caulders-Nest im Spiel ist, aber der Aufwand für das Mega-Oozium ist aktuell zu groß. --> Gibt gerade genügend issues zu bearbeiten. Insbesondere Server-Features und das Hidden Feature einer schweren KI

But if that is no longer of interest, then I know it now.

**Comment by Robosturm** [comment]
I will never add air fights that's what i wanted to imply by that.
The game will never get the dual map mechanic of aw-ds. That's a decision i made pretty much at the beginning of the game design

**Comment by UOcelot16** [comment]
I can't read minds. I work with what you write. That said so far.

**Comment by Robosturm** [comment]
All fine. I just wanted to make sure,  you don't have wrong expectations

**Comment by UOcelot16** [comment]
Cleanup of backlog.

Topic closed because Rob is not able to fulfill his attitude a human coexistence and wants to enforce his will by all means.
