### ISSUE TITLE
Proposal: #C00, Entry of 29.11.22 Production

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1342]
Since it is still an open entry, it was uploaded to Github because it was once only given on Discord.

The last exchange was that build lists cannot be displayed if fundamentally units cannot be manufactured due to insufficient funds. Therefore, an alternative might be to play a sound if this is not possible.

[GENERAL_131 - Not possible.zip](https://github.com/Robosturm/Commander_Wars/files/10361763/GENERAL_131.-.Not.possible.zip)

**Comment by Robosturm** [comment]
You get the default menu for selecting a field.
So playing a sound makes no sense since you get a valid menu.

**Comment by Robosturm** [comment]
I still add the sound to the database.

**Comment by UOcelot16** [comment]
If you want to select a building which is able to produce units and you don't have sufficient funds you'll get a sound that is not possible so in which case would it not make sense?

**Comment by Robosturm** [comment]
If you try to click on a building and you can't build anything. 
You get the same menu as if you clicked on an empty field, so no sound is needed/ is useful.
Since the core game doesn't know care that you clicked a production building. It checks can you do something on/with this field.
If yes do that else show the main menu for info next player etc.

**Comment by Robosturm** [comment]
This behaviour won't be changed and is intentional if you won't do know what you can build here, you can always press the i-information key to get that information. So showing a menu with everything disabled makes no sense.

**Comment by UOcelot16** [comment]
**So showing a menu with everything disabled makes no sense.**
This is why I've thought about a solution which doesn't need an additional menu just a sound.
