### ISSUE TITLE
Proposal: #1196 Log 04 Oil Rig Addition

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1343]
Since the incapability for Oil Rigs on Sea is intentional it would be good to add this relevant information in the Description.

"... Can only be captured on land."

In the german translation this information is already inplemented.

**Comment by Robosturm** [comment]
This is invalid as well oil rigs can be captured on sea. There's a sea unit able to capture things currently it's the cheapest naval unit.
So this information would be wrong

**Comment by UOcelot16** [comment]
What Naval Unit is capable of capturing Oil Rigs?

**Comment by Robosturm** [comment]
Gun boat can capture tiles it can move on.

**Comment by UOcelot16** [comment]
"At sea an oil rig can be captured by a gunboat."

**Comment by Robosturm** [comment]
This is something that's impicit since all units that can capture can capture buildings they can move on.
So i don't see a real benefit of adding it.
The oil rig is also primarly a sea and not a land building.

**Comment by UOcelot16** [comment]
**This is something that's impicit since all units that can capture can capture buildings they can move on.
So i don't see a real benefit of adding it.**
Since it was not something which was able in the earlier games it is in my opinion something which is an information  for players which already know this unit from the original game.

**The oil rig is also primarly a sea and not a land building.**
How about to delete it on land if it shouldn't be there?

**Comment by Robosturm** [comment]
The unit doesn't exist in any other game same for the building.
And this is more something that would be added to a tutorial section which the game currently only has 2 very basic missions.

And no the building is used on land on maps and it was a feature intentionally added later on and the behaviour is similar to bridges so nothing out of the box either.

**Comment by UOcelot16** [comment]
**The unit doesn't exist in any other game same for the building.**
https://advancewars.fandom.com/wiki/Gunboat

**Comment by Robosturm** [comment]
They're not the same unit. They share nothing minus the name, which i didn't notice that K'Braid suggested an existing name

**Comment by UOcelot16** [comment]
Then its reasonable to use a other name. How about
Fast attack Craft (FAC) https://en.wikipedia.org/wiki/Fast_attack_craft
 or Fast capture Craft (FCC)
or a Name of a ship that already exist.
