### ISSUE TITLE
Proposal: Additional Tilesets for Nest

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1344]
Currently there are missing Tiles of the Nest. I'm gonna search for it.

**Screenshot**
![grafik](https://user-images.githubusercontent.com/119428442/211065953-9d203c5e-af33-4751-9c24-96a177ff933f.png)

**Comment by UOcelot16** [comment]
![Nest Wall](https://user-images.githubusercontent.com/119428442/211066817-530db657-3f3c-4ca5-9f56-ea66ecdb7175.png)

**Comment by Robosturm** [comment]
Since this can be achieved by re-styling a pipeline or wall and renaming it. I don't think i want to add it since it has no real efffect. and the size of 1x2 is not really a nice once.

**Comment by UOcelot16** [comment]
**I don't think i want to add it since it has no real efffect.**
How about for later additions if the Campaigns will be remade?

Here a split of them:
![1](https://user-images.githubusercontent.com/119428442/211075870-1ef03916-00c0-4bdc-ba11-561406bbd538.png)
![2](https://user-images.githubusercontent.com/119428442/211075871-d8b98086-343f-4497-b8ed-97cb9a3504f3.png)

**Comment by Robosturm** [comment]
If it needs to be added for the campaign it would be a re-style of a a pipe or wall and getting a rename to nest or something.
This can be done in the map editor by selecting an image there, but i have mentioned i have no real intention to remake the final mission cause i think it's one of the most horrible designed missions in the aw universe

**Comment by Robosturm** [comment]
But if someone wants to remake the map he use those assets.

**Comment by UOcelot16** [comment]
**If it needs to be added for the campaign it would be a re-style of a a pipe or wall and getting a rename to nest or something. ... Note an example for this is the map crash landing of the aw-dc campaign**
Okay. Then it's only necessary to have them in the folder for implementing them.

**Comment by Robosturm** [comment]
Similar to those of crash landing yes and no building is needed.

**Comment by UOcelot16** [comment]
Then this thread is completed.
