### ISSUE TITLE
Proposal: Disabled Tooltips for Main Menu

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1347]

**Comment by Robosturm** [comment]
Tooltips will never get disabled..
They're a fallback net in case something ca't be displayed fully

**Comment by UOcelot16** [comment]
**Tooltips will never get disabled..**
for Reference here examples:
-> Video Submenu
-> Audio Submenu
-> Mechanic Submenu
-> Settings Submenu
-> Network Submenu
-> CO Settings Submenu (single / all)
...

example where is is not disabled:
-> Random Map Submenu
-> Rules Menu
...

**Comment by UOcelot16** [comment]
![grafik](https://user-images.githubusercontent.com/119428442/211162814-8de79eda-2b53-4a2c-aff7-04ef7f7d5d64.png)
