### ISSUE TITLE
Proposal: Map Editor Placement of Units

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1348]
As in #1325 there has been given additional SFX for placing buildings / terrain for the Map Editor.

How about adding Sounds for the Units aswell? The sound used here is the same as when a unit is / has been moved.

**Comment by Robosturm** [comment]
The answer is yes/no.
I won't use the walking sound cause some of them are several seconds long (naval/air).
I can accept one generic sound for all

**Comment by UOcelot16** [comment]
C++ has an option to cancel sounds while they are being played. But since it is labeled as done maybe you've found it already.
