### ISSUE TITLE
Modding in new weathers will be missing from saved maps

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#135]
When introducing a new weather to the game, all saved maps cannot utilize the new weather effect, only newly saved maps can. It'll show up as snow instead.
![MissingNewWeather](https://user-images.githubusercontent.com/58909501/73136967-d119ba00-4010-11ea-8e60-4fac41ab018c.png)

**Comment by Robosturm** [comment]
I tested it with a very old map and it works fine.
So my guess is your script has a bug somewhere it. Either the name you return is wrong or the weather you create is wrong could you attach your weather script for veryfication.
Thx.

**Comment by Everglass** [comment]
Oh I see, this only applies to maps that have saved settings to them. Here's the weather script I'm using.
[weather_ash.zip](https://github.com/Robosturm/Commander_Wars/files/4119181/weather_ash.zip)
