### ISSUE TITLE
Proposal: Centering Generating Map Loading Screen

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1351]
![grafik](https://user-images.githubusercontent.com/119428442/211162971-ca461f02-de4d-41e6-a504-9cf1d137aa15.png)

In addition, there is the question whether the English terms mentioned can be translated or whether they are terms which are to be regarded as loading at startup? Is it possible to change this with icons?

**Comment by Robosturm** [comment]
#1350

**Comment by UOcelot16** [comment]
So this is the same script then?
