### ISSUE TITLE
Proposal: Better Icon for Perk Leader

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1353]
![Leader Icon](https://user-images.githubusercontent.com/119428442/211165743-725ae97f-3b85-4935-920a-fdc85dda7047.png)
![Leader Perk](https://user-images.githubusercontent.com/119428442/211165747-6402fad5-c5f6-49d8-8428-85d90f42f8b7.png)

**Comment by Robosturm** [comment]
Looks worse in my opinion as the current one.
So i want change it.

**Comment by UOcelot16** [comment]
Wat?

**Comment by Robosturm** [comment]
So my problems are the red-color and the middle white bar. It doesn't match the original co-icon from aw-dor and with the brighter red color and the smaller white bar it looks not natural/ it stands out from the rest of the icons even more than the current one.

**Comment by UOcelot16** [comment]
The last answer is more helpful instead of writing "I won't change this". Due I'm not sure that you write this only because I've also mentioned it in Discord but anyway now I know.

**Comment by UOcelot16** [comment]
You can do this yourself then.

**Comment by UOcelot16** [comment]
Cleanup of backlog.

Topic closed because Rob is not able to fulfill his attitude a human coexistence and wants to enforce his will by all means.
