### ISSUE TITLE
Issue: Script Editor -> Check CO begins with NULL Condition

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1355]
![Check CO begins with Null condition](https://user-images.githubusercontent.com/119428442/211195632-879cd2fd-3083-4b0a-9c43-5babc60ac138.png)

**Comment by Robosturm** [comment]
0 is correct you're programming here atm and we start counting at 0.

**Comment by UOcelot16** [comment]
Yes while it is usual due to programming that it starts at 0 a 0 Player does not exist. In many other caases you were able to adjust this so... ?
