### ISSUE TITLE
Proposal: Script Editor -> Build List Menu Targeting

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1360]
![Other Build List Menu targeting](https://user-images.githubusercontent.com/119428442/211195871-0ee2ec5e-2fab-4c64-aa20-826147041fb5.png)

Reasons for this Proposal:
-> Menu is already available
-> Loadable Build List
-> If more than one unit should be changed it is not necessary to create multiple Events for that

**Comment by Robosturm** [comment]
Not possible / overhead highly exceeds benefits.
The script editor is and will be a basic tool for creating scripts but you still need to understand scripting programming.

**Comment by UOcelot16** [comment]
Okay.
