### ISSUE TITLE
Proposal: MP Optical Change Part 2

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1361]
Fully Screen usage / Clearing Corner with same Colour as shown Window / adjusted button in same size as Direct Connection

![Screenshot (835)](https://user-images.githubusercontent.com/119428442/211196032-a9229c50-4c62-4a42-95f1-ec03f27387cf.png)

**Comment by Robosturm** [comment]
Corner won't be filled.

**Comment by UOcelot16** [comment]
Okay.
