### ISSUE TITLE
Issue: Missing Launch / Fall from Rocket

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1365]
Like in #1287 there is also an Animation that can be added.

I'm currently working on it to provide this.
https://github.com/UOcelot16/Commander-Wars-German-TL-and-additional-Content/blob/main/ReversedLaunchingAnimation.gif

**Comment by UOcelot16** [comment]
I'm done with the animation but I cannot extract it as separate Pictures. Gimp is incapable of exporting layers and currently I don't know how to solve this problem.

![RocketLaunchingAnimation](https://user-images.githubusercontent.com/119428442/211219160-0c182346-7441-4182-9b24-b9178b5b2451.gif)
![RocketDropExplosionAnimation](https://user-images.githubusercontent.com/119428442/211219162-84efc862-945b-45a2-8524-259fa11c4c1a.gif)

**Comment by UOcelot16** [comment]
Done
[RocketLaunchingAnimation.zip](https://github.com/Robosturm/Commander_Wars/files/10369564/RocketLaunchingAnimation.zip)
[RocketDropExplosionAnimation.zip](https://github.com/Robosturm/Commander_Wars/files/10369565/RocketDropExplosionAnimation.zip)

**Comment by Robosturm** [comment]
Would have been cool to get them provided in the correct format and not as separated images

**Comment by UOcelot16** [comment]
Thought that you need them as separated images. What do you need exatly with correct format? As full animation has been send this already 18 hours ago.

**Comment by Robosturm** [comment]
Example animation
![laserray+center](https://user-images.githubusercontent.com/48879701/211346534-ba88d459-0169-4926-8031-d3dd4709f387.png)

**Comment by UOcelot16** [comment]
Is this limited for a row? If so how many frames can I use?

**Comment by Robosturm** [comment]
One row as many frames as needed though the display time for one frame is adjustable.

**Comment by UOcelot16** [comment]
If there would be a program with an option to merge many pngs into one that would make it so much easier to realise this...
