### ISSUE TITLE
Proposal: Only Neutral Volcanoes

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1367]
Volcanoes cannot be used if they are assigned to a player (marked with color on the minimap). Additionally, if a unit is locked on by that player, it also takes damage. Hence the suggestion to block anyone other than neutral in Map Editor.

**Comment by Robosturm** [comment]
Volcanos fire at the start of the turn of the player they're placed for it's feature which won't be removed

**Comment by UOcelot16** [comment]
So it is necessary to use a fraction setting for the volcano t be specifically used in the round? So if it has been set to neutral and the volcano is set to player 1 it should the same action? For what purpose? I'm quite sure I haven't seen the Volcano errupts due to specific moments in a turn in AW2 and AWDS.

**Comment by Robosturm** [comment]
And CoW isn't advance wars so additional options are here and will stay here

**Comment by UOcelot16** [comment]
Calm down
