### ISSUE TITLE
AI more conscious of Victory Conditions

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#137]
It would be nice if the AI was more reactive to special victory condition, such as needing to get a unit to a location to win or needing to kill a specific unit or co to win.

**Comment by Robosturm** [comment]
I understand your wish. But sadly the complexity is way to high. 
Starting from how to find out scripted victory conditions to get out what and how to achieve them.
Those things are kinda easy for a human but impossible for an AI.
