### ISSUE TITLE
Issue: Teleportation Tile

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1373]
**Describe the bug**
The Teleport Tile can be used in the map editor. Placing units on this field is basically not possible and therefore assume that it is wanted.
![Screenshot (882)](https://user-images.githubusercontent.com/119428442/211241720-b507e753-7dcf-4bcd-b3b8-4f3e79156eb4.png)

But if you then try it out during the game, it works for a lot of units to wait on this tile (following picture shows for what units it is possible). In addition, there is also the question of whether the sea units can move through areas even if there is no sea there or if it is also wanted.
![Screenshot (887)](https://user-images.githubusercontent.com/119428442/211241777-9e05e014-684f-4c83-a88f-bb14534f716c.png)

It would be good to have more information on this in the internal wiki.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.27.1-main build3
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Note only reproducable for ooziums

**Comment by UOcelot16** [comment]
> Note only reproducable for ooziums
No joke. This was possible with the Version I've mentioned. Even the marine Units where able to do this.
