### ISSUE TITLE
Proposal: Action Icons Part 1

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1374]
![Temp_Hafen_FlzgHafen_Action](https://user-images.githubusercontent.com/119428442/211242136-4ec05d2a-c84a-4350-bd0b-b58a544cc896.png)
This suggestion has been made because many actions have the same image. In my opinion, the following would make sense for a better distinction. Since there are two actions with colors of a certain faction, the question would be whether you can do it in this case as well. Otherwise here a neutral variant.
![build_temp_airport](https://user-images.githubusercontent.com/119428442/211242141-e1faba5a-11ef-4091-a175-6f660d77a513.png)
![build_temp_port](https://user-images.githubusercontent.com/119428442/211242142-8ec68e66-e893-4f1c-9ec2-d7dc5e9d50ab.png)

Further proposals on this will come if it is not rejected to continue.

**Comment by Robosturm** [comment]
Icon's don't fit the 16x16 32x32 or multiplier of 2 sprite size.
I replaced the airport with the ingame building variant by using the ingame sprite but harbours are to large
