### ISSUE TITLE
Proposal: Additional Perks

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1377]
Since AWDS uses these Perks maybe they could be implemented?

Rank 1 | Rank 2 | Rank 3 | Rank 4 | Rank 5 | Rank 6 | Rank 7 | Rank 8 | Rank 9 | Rank 10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
X | X | O | X | X | O | X | X | O | X |
X | X | X | X | O | X | X | X | X | X |
X | X | X | X | O | X | X | X |  | X |
X |  | X | X | X | X |  | X |  | O |
O |  | X | X |  | X |  |  |  | X |
X |  |  | X |  |  |  |  |  |  |

O: Missing; X: Implemented

- Mistwalker, Hides units during Super CO, !
- Synergy, Tag CO Attack, +8%
- Bodyguard, Tag CO's defense, +10%
- Missle Guard, Damage from silos, -1
- Cannon Guard, Damage from cannons, -2
- Combat Pay, Damage foes to earn cash, +2%
- Teamwork, Tag CO's Attack, +5%

Gonna search for Icons.

**Comment by Robosturm** [comment]
None of them will be added cause they're not really doable in cow/ overhead exits the benefit. That's why they aren't in the game

**Comment by UOcelot16** [comment]
Ah okay.
