### ISSUE TITLE
Proposal: Intel Truck Size Correction

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1378]
![Screenshot (895)](https://user-images.githubusercontent.com/119428442/211311689-93ca8ba0-ff59-4d8a-a26f-9c64ef3e05e2.png)

![intel_truck+mask](https://user-images.githubusercontent.com/119428442/211311636-c620b855-a12a-405e-8381-54ee8480a940.png)

![intel_truck+walk+mask](https://user-images.githubusercontent.com/119428442/211311642-87720c49-aa02-445c-b774-fd27548468b9.png)

**Comment by UOcelot16** [comment]
Then this will be something for the Mod.

**Comment by UOcelot16** [comment]
I've tried it for many other tiles like HQ, Crystal, Rocket Silo, Oil Rig, Com Tower, Radar Station and, of course, moving the unit. It is still without difficulties.

So again my proposal stands for implementing it. Maybe it has something to do with the >16,>16 change?

**Comment by Robosturm** [comment]
Units are simply not allowed to be drawn on top of other units to not hide other units, while as said it seems to work technically that's a fun fact but nothing i''l add.
Unit sprites need to have a size of 16x16, 32x32 48x48 or anything else that is a multiplicate of 2

**Comment by UOcelot16** [comment]
> 32x32 48x48

These are sizes what I try to avoid for an Unit Implementation because same size as the others. Is there a chance if the Design of the Intel Truck will be changed? The Antenna is the main reason for its larger size.

**Comment by Robosturm** [comment]
No. This is a design decision and not a technical one
