### ISSUE TITLE
Proposal: Additional Buttons in playerSelection 2

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1379]
Still double All #1317

**Screenshots**
![grafik](https://user-images.githubusercontent.com/119428442/211542651-d71a3f4c-d88e-4993-826f-c50043237328.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v0.28.2 (downloaded as v0.28.2 will be displayed ingame as v0.28.1-main)
 - Active Mods: Vanilla

**Comment by Robosturm** [comment]
Intentional

**Comment by UOcelot16** [comment]
Good. Then I'll change the Button Definition to this

**Screenshot**
![grafik](https://user-images.githubusercontent.com/119428442/211588603-3e07cb5e-39e8-4a68-a6e9-6a3cdbdfa6c0.png)
