### ISSUE TITLE
AI score modifiy for Map Editor 

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#138]
Perhaps include an Priority Modifier for the Script Editor to incentivize the AI to move a unit onto a specific location or attack a certain target then?

**Comment by Robosturm** [comment]
These are the modifications you can do to the AI and not much more will happen.
[https://github.com/Robosturm/Commander_Wars/wiki/AI-Modification-for-a-Single-Maps](https://github.com/Robosturm/Commander_Wars/wiki/AI-Modification-for-a-Single-Maps)
Espacially nothing to modify a single unit further than given the AI the control of Offensive, Hold or Defense. You can modify the AI in a way to more likely move to a certain place or path by increasing the virtual movecosts over all other terrains. But the AI won't and doesn't have anything to plan more than the current turn ahead which is pretty time consuming and complex already. TBS AI is really the most difficult AI to program compared to Shooters or RTS AI.
