### ISSUE TITLE
 Issue: Missing blocked button 2

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1380]
As in  #1316 in v0.27.1-min build 3 stated so is it still in v0.28.2

**Screenshot**
![grafik](https://user-images.githubusercontent.com/119428442/211543845-1e04b9fb-82bb-4a7c-bd43-1f0ee0a08741.png)

Desktop (please complete the following information):
- OS: Win10
- Version: v0.28.2 (downloaded as v0.28.2 will be displayed ingame as v0.28.1-main)
- Active Mods: Vanilla

**Comment by Robosturm** [comment]
You probably have a weird resource folder state.
Downloaded the folder and tested it works correctly.

**Comment by UOcelot16** [comment]
Then look up a third time.

https://user-images.githubusercontent.com/119428442/211596224-2770d3c5-a17f-4cbb-93d7-caba4efd833d.mp4
