### ISSUE TITLE
Issue: Map Editor -> Hotkeys does not work for... 2

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1382]
For ESC hasn't been solved #1345

Desktop (please complete the following information):
- OS: Win10
- Version: v0.28.2 (downloaded as v0.28.2 will be displayed ingame as v0.28.1-main)
- Active Mods: Vanilla

**Comment by Robosturm** [comment]
Key is only placed wrong in the ui. Key works as intended.
