### ISSUE TITLE
Issue: Map Editor -> New Map not possible

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1384]
If a new map should be created, the program jumps to the Map settings menu.

Desktop (please complete the following information):
- OS: Win10
- Version: v0.28.2 (downloaded as v0.28.2 will be displayed ingame as v0.28.1-main)
- Active Mods: Vanilla

**Comment by Robosturm** [comment]
Works as intended

**Comment by UOcelot16** [comment]
https://user-images.githubusercontent.com/119428442/211591583-ab18f0d4-e3fa-41ec-91ad-1e7c697758fd.mp4

**Comment by Robosturm** [comment]
Yes and that's the correct behaviour the menu is the same just what happens when you press okay is something else.
So invalid is correct

**Comment by UOcelot16** [comment]
Ah okay.
