### ISSUE TITLE
Proposal: CW Wiki -> Building Changing Nest 

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1394]
Atm the factory door is not displayed. I now that it could be a problem due of its 1x3 dimensions. How about using the full size of it what I've already suggested?

![grafik](https://user-images.githubusercontent.com/119428442/211647126-a73019f9-6c4f-4ac4-bf15-ddbcfaf480e8.png)

**Comment by Robosturm** [comment]
It shows the building scaled to a single tile which is correct just doesn't look the best. --> won't be changed

**Comment by UOcelot16** [comment]
"won't be changed" labeled as invalid.
