### ISSUE TITLE
Issue: Submenu Mod -> Scrollbar has been cut

### ISSUE THREAD

**Issue by ghost** [Robosturm/Commander_Wars#1395]
![grafik](https://user-images.githubusercontent.com/119428442/211652380-abcd1952-92d8-45f4-86bf-fda7b8e48f63.png)

Desktop (please complete the following information):
- OS: Win10
- Version: v0.28.2 (downloaded as v0.28.2 will be displayed ingame as v0.28.1-main)
- Active Mods: Vanilla

**Comment by UOcelot16** [comment]
Cleanup of backlog.

Topic closed because Rob is not able to fulfill his attitude a human coexistence and wants to enforce his will by all means.

**Comment by UOcelot16** [comment]
GFY

**Comment by Robosturm** [comment]
Last warning stop torpeding the issue management or i have to ban you from CoW which would be the first time i have to do that.

**Comment by UOcelot16** [comment]
I will not tolerate your dictator manner and you can push such a ridiculous manung anywhere else. Just behave and leave it at that.
