### ISSUE TITLE
Issue: Map can't be played

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1397]
Since I was doing a map to play with a good friend I've found out that there was a problem with playing it. It's not possible to do anything. So I've uploaded my map for testing purposes.

[SPANN ISLAND double team.zip](https://github.com/Robosturm/Commander_Wars/files/10387493/SPANN.ISLAND.double.team.zip)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: v028.1 (even if its in github 0.28.2)
 - Active Mods: Vanilla

For the time being this will be the last for this day.

**Comment by Robosturm** [comment]
That's cause the bann list for actions and minimum co's are empty.
So you can't do any actions but that's your fault.
