### ISSUE TITLE
Proposal: Fixed Statistics Icon

### ISSUE THREAD

**Issue by UOcelot16** [Robosturm/Commander_Wars#1402]
**Currently Ingame** Pixelated jpeg Icon
![grafik](https://user-images.githubusercontent.com/119428442/211870458-15a2d826-3879-4f23-a682-bc48860e4b74.png)

Working on an alternative.

**Comment by UOcelot16** [comment]
Also decided to go 16x16
![statistics](https://user-images.githubusercontent.com/119428442/211874134-f43655e9-549d-431e-82e2-a6f3ae962ff1.png)

**Comment by Robosturm** [comment]
Note removed the white pixel area
