### ISSUE TITLE
game replays broken

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1408]
When loading a replay the map starts but there's no sound and when you go to exit the game crashes

[console.log](https://github.com/Robosturm/Commander_Wars/files/10433630/console.log)

**Comment by Robosturm** [comment]
Only happens to replays created in the session you enabled recording.

**Comment by TeslaTrooper09** [comment]
I'm not sure, I've tested it a bunch of times recording has been enabled since before I had the issue and I still cant get a recording to replay... still crashes on exit.

[console.log](https://github.com/Robosturm/Commander_Wars/files/10439899/console.log)

**Comment by Robosturm** [comment]
I was mainly refering to the replay not playing.
Exiting is another bug. :(
