### ISSUE TITLE
biome tile recolour via colour table

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1409]
adding new terrain tiles by changing the base colour of existing tiles via coding rather than through adding more sprites to save on file size

water tile table as an example
![image](https://user-images.githubusercontent.com/53922323/212972990-8be0ad73-7413-4f65-8b3c-a7bb1269469c.png)

**Comment by Robosturm** [comment]
So how it works.
The palette should have a size of 32x32 pixels.
The color choosen from the palette is x = red * 8 and y = green * 8.
Like for the player colors each color should have a size of 3x3 in the palette and the x-y coordinates should be the middle of that 3x3 pixel.
So biomes with the same sprite and only different colors could be realized with this mechanic.

**Comment by Robosturm** [comment]
Small correction red in the source image equals red=x*8 from the palette
and green = y*8

**Comment by Robosturm** [comment]
So same process as for player colors with a smaller image 32×32 and a factor of 8 for the rg to xy conversion
