### ISSUE TITLE
AI air units ignore Aircraftcarries when needing to refuel

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#141]
At the moment, AI aircraft will usually only start flying back to an airport when reaching critical fuel and they'll ignore this if there is a target to attack. But when they do try to pull the unit back to an airport, they ignore using Aircraftcarriers as an option, rather they'll try for an airport that's way out of reach.
![Failuretorefuel1](https://user-images.githubusercontent.com/58909501/73607937-e09d8380-4579-11ea-82e8-0616b41ccb42.png)
![Failuretorefuel2](https://user-images.githubusercontent.com/58909501/73607938-e4c9a100-4579-11ea-8ab9-839104b5f396.png)
![Failuretorefuel3](https://user-images.githubusercontent.com/58909501/73607942-e7c49180-4579-11ea-8491-f142ef6a36d0.png)
![Failuretorefuel4](https://user-images.githubusercontent.com/58909501/73607943-ea26eb80-4579-11ea-92bd-d9f46126a37b.png)

**Comment by Robosturm** [comment]
Cause it's not implemented and as far as i remember AW AI never did that as well.
But i think i have a way to implement it we'll see
