### ISSUE TITLE
dropdown menu in mods screen behind mods list

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1418]
![image](https://user-images.githubusercontent.com/53922323/215345143-8193b2c7-bbec-4bb4-b589-525c7b2c2ccf.png)

**Comment by Robosturm** [comment]
#1395

**Comment by KBraid** [comment]
oh whoops. i had looked through the list of issues to make sure i didn't post a duplicate but somehow glossed right over that one
