### ISSUE TITLE
A list of loadable units for a Transport unit in it's wiki page

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#142]
Similar to how building show you what units are buildable and resupplied there, a list of units that can be loaded into a unit would be a nice feature. Mostly helpful for modded units that can only carry a select weight classification, like Fairy's Transport Copters and my Hovertransport modded unit.

**Comment by Robosturm** [comment]
I think i'm also going to add a reverse list so you can see the units that can transport the current one. 👍
