### ISSUE TITLE
Player Statistics Lost units show wrong army color

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1421]
**Describe the bug**
In the Player Statistics screen the Lost units show other armies colors instead of the color from the player

**Expected behavior**
Lost units should have the color from the player.

**Screenshots**
Lost units show player 2 and 3 colors:
![wrong_army](https://user-images.githubusercontent.com/113127747/215458467-fe1428cb-f923-4196-96b0-53265e18f07d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 28_2
 - Active Mods: None

**Additional context**
I saw a post thats reported this same thing that said that there was another post about this.

**Comment by Robosturm** [comment]
The different color represents to which player you lost the units.
Only the summary shows the own player color
