### ISSUE TITLE
Custom map makes game freeze

### ISSUE THREAD

**Issue by MrDuck557** [Robosturm/Commander_Wars#1423]
**Describe the bug**
When trying to load [this map](https://github.com/Robosturm/Commander_Wars/files/10574416/TestingMap.zip) in the map editor, the game freezes and starts leaking memory. The game also freezes when trying to make a new game on said map.
[console.log](https://github.com/Robosturm/Commander_Wars/files/10574418/console.log) if it helps

**To Reproduce**
1. Put TestingMap into maps folder
2. Open game
3. Try to load TestingMap (either in map editor or new game)
4. See Commander Wars freeze
5. Open task manager and end task

**Expected behavior**
the map being able to load

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.27.1-dev (as seen in bottom right corner) (edit: Tested on 0.28 main, still froze)
 - Active Mods: None

**Comment by Robosturm** [comment]
Using dev builds in general is not recommended at all.
Using them is at your own risk and compatibility of maps or loading saving in them isn't guranteed to work.
You used a development version which probably had a bug in the map saver code.
So your map is lost.
Only use official versions to prevent issues like that.
