### ISSUE TITLE
Amy's CO power discount not working in android

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1426]
**Describe the bug**
Amy's co power discount to hovercraft doesnt work in android.

**To Reproduce**
1. Play in android.
2. Use Amy's power.
3. See that the discount doesnt work.

**Screenshots**
No discount with the power on.
![modless_ss](https://user-images.githubusercontent.com/113127747/217414696-de1acf3b-1950-4c65-bcd0-c76fe8e51daf.jpg)

**Desktop (please complete the following information):**
 - OS: Android
 - Version: 29
 - Active Mods: None

**Comment by Robosturm** [comment]
Tested with release works correct on my device.
And there's no reason why the game should work different in vanilla version on android or pc
