### ISSUE TITLE
Firing on one of Nana's Indirect units while under the effects of her CO Zone will cause the damage splash effect to occur around the attacking unit

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#143]
While attacking an indirect unit that's under the effects of Nana's CO zone, these units will cause her damage splash effect to occur around your attacking unit. And direct units that attack this unit will cause the indirect unit to survive with one health due to the splash damage effects.
![Nanasbroken](https://user-images.githubusercontent.com/58909501/74000963-25813b80-4927-11ea-8f55-7dbce6e438e2.png)

**Comment by Robosturm** [comment]
Fixed:
The fix also fixes a bug for the following CO's
Adam, Conrad, Graves, Mary, Minamoto, Nana, Robo-Andy, Sabaki, Sanjuro, Sasha, Smitan, Sophie
