### ISSUE TITLE
AI sub-process option causes the AI to be idle on multiplayer, match won't start on single player

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1430]
**Describe the bug**
When the AI sub-process option is set on the video menu, and a multiplayer match is created, the AI player will remain idle, its turn won't take place. The menus and options will work as normally, but the game will otherwise stay in that state.

When the same is done on single player, the character select window loads, but when pressing next, the character select window reloads instead of starting the match.

**To Reproduce**
1. Go to 'multiplayer' or 'single player' while the AI sub-process option is checked
2. Create a new match and add at least an AI player
3. Click ready or next
4. Either error should appear

**Expected behavior**
The AI should move the units in the multiplayer session and allow the match to start on the single player one.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 29
 - Active Mods: None

**Comment by Robosturm** [comment]
#1429
