### ISSUE TITLE
Still getting AI desync and it doing nothing in the Multiplayer Server

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1435]
**Describe the bug**
When playing in the multiplayer server vs the normal ai, the desync message shows up after its turn is done, and depending on the map it wont even act.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 29.1
 - Active Mods: None

**Comment by Robosturm** [comment]
Note the stopping is a problem of the sub ai process part
