### ISSUE TITLE
the 16x16 unit mod isn't active

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1438]
i added the sprites that had been replaced back into the game via integrated mod so if people didn't like the 32x32 units they could switch back, but the mod is not on the mod lists

**Comment by Robosturm** [comment]
Similar to the DC-Unit mods.
I don't want this to be part of the vanilla game. It's fine to be a mod on the discord page.
But i want to have reasonable amount of vanilla mods which need to be maintained with the base game.
I hope that's understandable for you. :)
