### ISSUE TITLE
Next Active unit option for game menu

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#144]
Just a little feature to allow you to select the next active unit for when you're needing to make sure you've moved all your units for that turn. Either a menu selection or perhaps even a keybinding you can use to cycle through your active units.

**Comment by Robosturm** [comment]
Well what about using the keys q and e? They toggle through all units/buildings which still can perform something. Works for everything e.g. also unloading fields or fire fields.
Pressing q or e will select the next possible selectable field or previous one.

Named Key Next and Previous in the option menu

**Comment by Everglass** [comment]
Oh how silly of me, I thought I remember such a feature already existing but when I check the keybinding, it didn't occur to me that that's exactly what next and previous did :P

**Comment by Robosturm** [comment]
No problem
