### ISSUE TITLE
Random beach related crash? I got in the Multiplayer tab.

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1442]
**Describe the bug**
I dont remember what I was doing but this showed up and my game closed.

**Expected behavior**
No random crashes in multiplayer pls.

**Screenshots**
Beaches!
![beach](https://user-images.githubusercontent.com/113127747/220697245-057866de-a478-4781-ad4f-d47183eb323c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 29_1
 - Active Mods: None

**Comment by Robosturm** [comment]
Without context i won't invest any time into it.
If you have more information open a new issue
