### ISSUE TITLE
Vanilla Mods not working in the Multiplayer Server

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1443]
**Describe the bug**
Whenever a match wants to be created in the multiplayer server using vanilla mods the "Host has different mods" message shows up.

**Expected behavior**
In the last version, 29.0, the server worked fine with the vanilla mods.

**Screenshots**
The error in particular:
![vanilla_mods](https://user-images.githubusercontent.com/113127747/220986653-857be875-50ae-4d9b-904b-1477a09018b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 29.1
 - Active Mods: Advance Wars 2 Damage Formula, Advance Wars Dual Strike Unit Mod

**Additional context**
Those 2 mods arent the issue, I tried with most vanilla mods and the same host has different mods showed up.

**Comment by Robosturm** [comment]
Mostlikely it's an issue with LoneWolf hosting the server.
He relaunched the server a couple of minutes again and playing a game should work properly again.
