### ISSUE TITLE
Auto-resize/auto-center option for matches

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1446]
**Is your feature request related to a problem? Please describe.**
There are maps that do not cover the entire screen and there is usually a lot of unused space between the map and the GUI elements.

This space would be best used by the entire map if an auto-resize option to screen or auto-center option was added to the game. 

**Describe the solution you'd like**
A shortcut, or a menu option which allows one to make a map fill most of the screen. 
**Additional context**
This was requested on stream here: 
https://www.youtube.com/live/cxOhlOVLRRI

**Comment by Robosturm** [comment]
With the current support scalings and the fact that's not always what players want. I don't think this is a good feature
