### ISSUE TITLE
Doing local interactions via the empty field options in a multiplayer match causes a desync

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1447]
**Describe the bug**
Whenever an animation speed is changed the desync message shows up.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 29.1
 - Active Mods: None

**Comment by lonewolf19991** [comment]
Changing the sound also has an impact. It desyncs and one needs to rejoin the match.

**Comment by Robosturm** [comment]
Any local action results in a desync atm....
So anything happening only on your side will trigger a desync....
