### ISSUE TITLE
Turn indicator in My Games tab

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1451]
A small icon telling you that its your turn to move would be great.
![image](https://user-images.githubusercontent.com/113127747/221383049-120bd8ba-3a9e-4baf-bbc9-a9f3905032d9.png)

**Comment by Robosturm** [comment]
Games which continue once you joined have a green text. Note: If it's an ai turn it's also green cause ai turn's are calculated on the client and not the server
