### ISSUE TITLE
Tile visual disparancies in current Map Editor/Rendering

### ISSUE THREAD

**Issue by HammerGuy** [Robosturm/Commander_Wars#1454]
When placing terrain like Mountains/Forests/Wastes if the underlying tile is a plains or plains equivalent it'll not override it with the biome equivalent. Compare when placing such terrain with another from any of the groups.

Example:
Placing a Mountain on a Snow tile or Snow Mountain on a Plains tile
vs
Replacing a Mountain with a Snow Mountain or visa versa.

Buildings also have its fair share of "undertile shenanigans."

Example:
Placing a city on the "biome-plains" they'll be placed fine.
However, placing a city on any of the biome equivalents will not just bring it to the base "biome-plains", defaulting to the grassy green plains.
You can also place buildings on roads but it'd be the lone tile version, and no roads adjacent picks up on it, pretending it doesn't exist. Edit: Correction, the tile underneath still sees roads next to it, just not the roads on the outside looking in?

**Comment by Robosturm** [comment]
This is intentional behaviour and won't be changed.
You can place any biome tile onto another biome, to get a visual change but the tile on top defines the biome used for effects.

**Comment by HammerGuy** [comment]
Thank you, just wanted clarification if the behavior is intended across the board.
