### ISSUE TITLE
Transportplanes are unable to unload loaded Hovercraft units

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#146]
I believe this has something to do with how hover movement works now. They don't seem to want to be unloaded on to any terrain. I was also having an issue with my Hovertransport unit when it was using the hover movement as it was unable to unload any unit it was carrying.

**Comment by Robosturm** [comment]
Yeah the unload action calls the getMovementcost function wrong after i changed Hovercraft Movement
