### ISSUE TITLE
Unit with getCOUnits and a custom Movement Table causes savefile corruption in Multiplayer, despite working correctly in Single Player

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1461]
**Describe the bug**
A mod which uses getCOUnits() and loads a Movement Table, loads and perform correctly on single player. However it causes a desync in multiplayer, and causes the msav file to become corrupted. I believe it has to do with some problem with how the getCOUnits() function interacts with  unit.setMovementType() 

**To Reproduce**
1. Load the attached mod [testco.zip](https://github.com/Robosturm/Commander_Wars/files/10886941/testco.zip)
2. Go to multiplayer and create  match
3. Activate super power 
4. See the error as shown in the screenshot, turn cannot be passed to the next player

**Expected behavior**
The custom movement table along with getCOUnits should not cause desync's nor should there be msav file corruptions. 

**Screenshots**
![Screenshot from 2023-02-26 10-58-12](https://user-images.githubusercontent.com/96459683/222854942-b5c4eeb9-c16a-46dd-999c-05cf2ed0a77a.png)

**Desktop (please complete the following information):**
 - OS: Linux/Windows/Android
 - Version 29.3
 - Active Mods: Attached mods intended for testing the interaction between the functions.

**Comment by Robosturm** [comment]
Just looked at the code doing something like this:
var aiTypes = [GameEnums.AiTypes_VeryEasy, GameEnums.AiTypes_Normal,  GameEnums.AiTypes_NormalOffensive,   GameEnums.AiTypes_NormalDefensive];
         if (aiTypes.indexOf(co.getOwner().getControlType()) > -1)
        {
        
Is guranteed to not work in a multiplayer environment.
This has a 99,99999999999999999999% change leads to different results on server and client sides and is forbidden.

Checking for ai types and doing weird shit in a multiplayer environment of cow is not allowed/supported
