### ISSUE TITLE
opening a pre-deploayed map in the map editor has all the units loaded in with zero ammo and fuel

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1473]
in editor screenshot
![image](https://user-images.githubusercontent.com/53922323/223526237-d6c17909-0a6f-49a3-ad1c-5d892d615e2a.png)

in game screenshot
![image](https://user-images.githubusercontent.com/53922323/223526277-412b9920-ce80-4db8-888a-8c553c113ea6.png)

**Comment by Robosturm** [comment]
Note only maps to some maps not all, depending on how they got saved
