### ISSUE TITLE
test build: palette set inconsistancies

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1477]
desert palette sets desert terrain to AW4 palette
![image](https://user-images.githubusercontent.com/53922323/223538142-ba24c9bc-ad44-42af-acaa-06908763878a.png)

**Comment by KBraid** [comment]
setting the palette to any snow sets the snow terrain to the mw4 palette
![image](https://user-images.githubusercontent.com/53922323/223538999-3590741d-0f3f-41f2-a359-1b1a92d6da4c.png)

**Comment by KBraid** [comment]
setting the aw4 waste palette sets waste terrain to the default waste palette, while all other waste set it to the aw4 palette
![image](https://user-images.githubusercontent.com/53922323/223539289-0ab0a3bc-9b85-4620-b97d-0c0bd77cc283.png)

**Comment by Robosturm** [comment]
This is intentional cause the snow biome has a different effect than the plains with the snow palette.
For that reason i selected a different palette for the biomes in case the same palette was selected for the plains

**Comment by KBraid** [comment]
ah okay, yeah that makes sense
