### ISSUE TITLE
Yukio's CO Zone applying a negative attack value on enemy units

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#148]
Encountered this strange bug when I was play testing my Lens unit. While within range of the enemy Yukio's CO zone, this unit was receiving a damage penalty and was also unable to attack some units that was clearly within range. So did a little bit of testing with mods turned off and it seems that Yukio is having a weird interaction with his zone.
![Yukionormal](https://user-images.githubusercontent.com/58909501/74696543-1a46cf00-51b5-11ea-8755-68d03939312c.png)
Here you can see every thing normal, the infantry unit receiving the damage and true damage bonus from his Yukio CO within range.
![Yukiostrange](https://user-images.githubusercontent.com/58909501/74696636-672aa580-51b5-11ea-9e43-baa380968310.png)
However, for the infantry withing the enemy's Yukio CO zone, the infantry is receiving a damage penalty and can no longer even attack the light tank or mage tank because it appears that the damage is too low.

**Comment by Robosturm** [comment]
The damage reduction is normal. The fact that you can't attack the unit is a bug, but it you would deal 0 damage even with luck in most siutations.

Fixed it for the next release
