### ISSUE TITLE
Test build: requesting a "none" option for map palette in game settings

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1492]
the map palette set in editor overridden by game settings.
as far as i can tell, there is currently no way to play a map with any sort of custom layout assigned in the map editor. 

![image](https://user-images.githubusercontent.com/53922323/224514540-aebdf256-33f1-4ce0-aed9-2794b37caa95.png)

![image](https://user-images.githubusercontent.com/53922323/224514604-47cf652c-67ad-4303-8129-c5070e2f07a3.png)

**Comment by Robosturm** [comment]
This is more a bug in the sense that default shouln't change the palette.
