### ISSUE TITLE
Loading 29.x save games makes the color pallet weird 

### ISSUE THREAD

**Issue by Coolmc2222** [Robosturm/Commander_Wars#1496]
(Bug)
when i open a save file made before the new release the color pallet is an ugly red and green

(Reproduce)
1.Make a game in the previous version
2. save the game
3. update to latest version
4. load save

im on version 0.30.1-main

**Comment by KBraid** [comment]
for spreading behind the scenes trivia, what you were seeing was the sprites as they are in the game's files mapped to xy coordinates using rg values the game applies a texture map with colours located at those coordinates
