### ISSUE TITLE
CO descriptions that lack exact numbers for stats in Wiki Description 

### ISSUE THREAD

**Issue by Coolmc2222** [Robosturm/Commander_Wars#1498]
some COs have there stats in plain numbers while other are just "firepower increases" but not specific numbers
like with Sami its hard to tell what the difference between the global firepower and CO Zone firepower for infantry
 without having to go into the damage calculator, this is more a quality of life improvement

**Comment by Robosturm** [comment]
I'm going to be honest here.
This is very unlikely to happen, cause it's tedious boring thing to do which I wasn't in the mood to do for over 2 years and i don't expect that to change. 
So the task is on the stack forever

**Comment by Robosturm** [comment]
Initial work has been done
