### ISSUE TITLE
Sequence of unit commands

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#15]
**Is your feature request related to a problem? Please describe.**
Commanding a unit should feel like how it was in the games, at least visually. (For reference I'm playing through AW2 at the moment).

**Describe the solution you'd like**
When commanding a unit, the sequence would be: Selecting the unit :arrow_right: deciding where it goes :arrow_right: the unit moves (at least visually) :arrow_right: extra commands (wait, attack, capture, etc) :arrow_right: the unit is done. If the player presses B after the unit has moved (but before choosing any extra commands), the unit goes back to its original position like in the original games. At the very least this would enhance visual feedback when planning.

**Comment by Robosturm** [comment]
If you would have played Advance Wars Darc Conflict lately you would realize that the Commander Wars Input is exactly like in the game.
I know that AW 1- to AW DS used your solution.

* I'm currently not keen an changing this behaviour cause it's a pain in the ass to do it the way you described it. Especially the way engine is designed right now.
* It's not fitting into the generic solution i choose to make pretty much any action possible.

I hope you can life with that. ;)

**Comment by Robosturm** [comment]
By the way i'll added you to the credits for your sweet game testing. ;)

**Comment by GuardianTempest** [comment]
Thank you for the credits.

I've seen some gameplay footage of Days of Ruin, and I will admit that I have been too hasty.
