### ISSUE TITLE
tiles no longer taking the proporty of the plains tile placed upon, defaulting to the category they're under

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1500]
![image](https://user-images.githubusercontent.com/53922323/225454385-5a81c2a4-b4a9-4be8-aab2-a4648d809e43.png)

**Comment by Robosturm** [comment]
This is incorrect.
They don't take the palette of the terrain they're placed on.
The rest works as intended.
So this is an improvement not a bug.

**Comment by KBraid** [comment]
you may have misunderstood what i meant, i didn't mean take on the palette i meant take on the biome, before the palette systems. before i mentioned with you how the palette system would make duplicate terrain across biomes obsolete, but if this is how it will be that statement is actually inverted they are necessary

**Comment by KBraid** [comment]
i understand what i going on with the image above now.
![image](https://user-images.githubusercontent.com/53922323/225785976-0f68e770-2cc8-47c5-b38a-86edb0b230f0.png)
it works correctly for the default palette but doesn't work for any other palette
