### ISSUE TITLE
Battlecruiser price not changing with the AWDS Units Mod

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1501]
**Describe the bug**
When playing with the AWDS Units Mod the Battlecruiser price remains at 14000.

**Expected behavior**
Considering the Cruiser price with the mod is 18000 the Battlecruisers price should be higher.

**Screenshots**
Cheap cheap:
![image](https://user-images.githubusercontent.com/113127747/225725821-2a0c8c83-3fc3-49d0-b188-37256797e38a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 30.1
 - Active Mods: Advance Wars Dual Strike Unit Mod

**Comment by Robosturm** [comment]
Units not present in the game won't be adapted.

**Comment by Firewito** [comment]
So why does the Destroyer get a price change?
