### ISSUE TITLE
Playing with an android user causes a desync in the first move of the match

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1504]
Every time I play with this android guy whenever I build the first unit of the game the desync message shows up.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 30.1 (Happens in older version too)
 - Active Mods: Advance Wars 2 CO Mod, Advance Wars 2 Damage Formula, AW-Styled Icons, Advance Wars Dual Strike Unit Mod

**Additional context**
I havent had this happen when playing with other pc users.
There are more game ruining bugs I've had with this android user.

**Comment by Robosturm** [comment]
Device specific issues will never be investigated cause the same code is run on all devices and if something goes wrong due to that specific os. It's like that
