### ISSUE TITLE
AW2 Campaign Red Star Lab Mission: Test of Time (2) Victory Condition

### ISSUE THREAD

**Issue by QuickenedPrism** [Robosturm/Commander_Wars#1505]
**Describe the bug**
The mission does not end when all enemy units are destroyed.

**To Reproduce**
1. Defeat each enemy unit on the map:
(Rocket, 2x Artillery, Lander, APC, Recon, Anti-Air, 2x Infantry)

**Expected behavior**
When each enemy unit is defeated in this mission, the player wins.

**Screenshots**
![image](https://user-images.githubusercontent.com/98768101/225779003-84c4b6a8-0a19-4332-8f05-302cbe54f8ae.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Beta_30_1
 - Active Mods: None

**Additional context**

**Comment by Robosturm** [comment]
Affects all lab missions
