### ISSUE TITLE
Multiplayer in match indicator for player being online/offline

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1508]
Many times me or the guy I'm playing against get disconnected for half a second, yet the game doesnt send the disconnect message, leading to long times of us thinking why isnt the other player playing the turn.

I would like a green dot or something meaning that the other player is on and actually in the present game or better disconnect detector.

**Comment by Robosturm** [comment]
Please provide some mock ups where you think this should pop up.
For now this isn't enough information to get any work.
