### ISSUE TITLE
gunboat frigate attack animations swapped?

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1509]
i noticed the gunboat's 3'inch gun fires like a tank while the frigate's 6'inch gun fires like the cruiser's AA

**Comment by Robosturm** [comment]
Well the frigate as a cruiser weapon while the gunboat looks to me more like a tank mg, so i choose those animations

**Comment by KBraid** [comment]
i had taken the cruiser's gun barrel and put it on a shrunken down battleship mg turret for the gunboat and took the light tank barrel and put it on the cruiser's turret for the flrigate

**Comment by Robosturm** [comment]
Since in the original game the cruiser use mg animations for firing in my opinion the animations are fitting.
Since the frigate weapon looks similar to the cruiser weapon..... and the gunboat is looking like something "new"
