### ISSUE TITLE
map editor: modded tiles replace the palette of the underlaying terrain with the default palette, regardless of selected palette

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1515]
examples: AW4 creeper sprite replacement on the left, silver horizon's forcefield on the right
![image](https://user-images.githubusercontent.com/53922323/226183063-97c564d2-4fc4-4326-bba5-964fea68e702.png)

**Comment by Robosturm** [comment]
That's a problem of the mod and not the base game.
I recommend taking a look at the function:
loadBaseTerrain and init of the river.js file.
Those handle the loading of default palettes and the placement of terrains onto existing terrains.

**Comment by KBraid** [comment]
i see, thank you
