### ISSUE TITLE
Edited River and Beach error

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1519]
Rivers and beaches which were edited via the Terrain Edit option from v29 have their images reverted back to a default one in v30.

v29:
![v29](https://user-images.githubusercontent.com/93048095/226959873-463f905d-fd26-4e0d-b070-d636450700de.png)

v30:
![v30](https://user-images.githubusercontent.com/93048095/226959915-080d0e21-bca7-4430-b96d-bca8144119b4.png)

**Comment by Jocrr** [comment]
Just found out that the same error also applies to edited lake tiles.

**Comment by Robosturm** [comment]
Some of the sprites have been renamed, therefor the game doesn't find the sprite and uses the default one. Thus isn't a fixable problem
