### ISSUE TITLE
Forest tiles don't change with "AW2 Image Mod" enabled and Wasteland visual bug(?)

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#152]
The title pretty says it all. When you enable the "AW2 Image Mod", every other Terrain changes to their usual AW2 sprites _except_ for the Forest tiles. And the Wasteland tile looks out of place when on top of the plain tiles. (I'm not entirely sure if that's intentional though.)
![Sceenshot](https://user-images.githubusercontent.com/53684963/75635317-b243b000-5bda-11ea-8b42-1579c2a84989.png)
(Ignore the map, it's a massive WIP and the bug still appears on other maps as well.)

I am playing on the 10th release btw.

**Comment by Robosturm** [comment]
The forest is a bug in the mod.
As for Wasteland tiles they weren't avaible in AW2 and are replaced with the sprites of AW DC.
If you create them in AW2-Style i happily add them though
