### ISSUE TITLE
Request: Make game records be activated by default

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1523]
**Is your feature request related to a problem? Please describe.**
Currently one needs to activate the records to see replays of matches. This would be ideal to have activated by default so that new users don't have to find the menus to activate them, or forget the option is not activated, making a match info be lost.

**Describe the solution you'd like**
Ideally, the ini file could have it set to enabled, when the game is launched the first time. 

**Additional context**
This is requested to simplify steps needed for the new players of the game, particularly tournament participants.

**Comment by Robosturm** [comment]
I can see why you want this, but the fact that the records are not always compatible and require a lot space compared to the rest of the game, the default will remain disabled. This is an intentional decision
