### ISSUE TITLE
Android players cannot join a server match with non vanilla mods

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1524]
**Describe the bug**
Whenever an Android user wants to join a server match with non vanilla mods the "Host has different mods" message shows despite the mods being the same.

**Screenshots**
Same mods:
![image](https://user-images.githubusercontent.com/113127747/227219579-4477ce21-3051-439a-a9eb-1eba76bfbc17.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Version: 30.2
 - Active Mods: Those in the pic.

**Additional context**
Vanilla mods work with no problem.
I rememeber this happening in the past or similar.

**Comment by Robosturm** [comment]
100% you have different mod versions on your android device.

**Comment by Firewito** [comment]
I literally copied the pc mods folder to android.
