### ISSUE TITLE
Cannot do any action in a multiplayer match when the Waiting for player to join screen shows up

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1525]
**Describe the bug**
Sometimes when that screen shows up, the current player wont be able to do any action until leaving and rejoining.

**Screenshots**
The screen:
![image](https://user-images.githubusercontent.com/113127747/227258549-2e386f98-1c99-407b-b666-e1451480c7d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 30.2
 - Active Mods: Contest mod

**Comment by Robosturm** [comment]
Added some improvements but without better information.
Aka console.log's with debug level on and a better description what steps happened on the other side or the log from them. Issues like that won't really be fixed or worked on
