### ISSUE TITLE
Cannot reconnect to a server match if the other player is still in

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1526]
**Describe the bug**
Sometimes when losing connection or desync or something, leaving and trying to rejoin shows the Connecting screen forever, and it wont reconnect until the other player leaves and the server detects Players 0/2

**Screenshots**
Only able to reconnect if nobody is in:
![image](https://user-images.githubusercontent.com/113127747/227259893-196f9eb9-82f1-4f5a-b8e1-776173be115e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 30.2
 - Active Mods: Contest (I've had this happen with vanilla mods too)

**Comment by Robosturm** [comment]
Only reason i sse this to happen is that #1525 happened as well.

And that only can happen if you have a very shitty internet connection which disconnects from the internet while you try to connect to the game, but again without any logs those issues don't help at all and won't be investigated.
