### ISSUE TITLE
Rain breaks the new Fog of Shroud/Shroud of War mechanic

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#153]
There are a lot of visual glitches during the rain when you have the new "Fog of Shroud" feature enabled. A terrain's sprite doesn't load when it's revealed in the rain, and if you save the game while it's raining, the whole map is revealed when you reload (albeit still obscured by the rain), and it stays that way until the rain stops.

**Comment by Robosturm** [comment]
Oh darn. Rain changes the rule set without checking if the current rule is harder or softer.
Fixed a simple if condition. xD
Thx for the report.
