### ISSUE TITLE
beach using open sea tiles for corner land connections when there are corner land beach tiles

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1533]
![image](https://user-images.githubusercontent.com/53922323/228699295-677bdc0d-650d-40d0-87fd-6c81b5d7e756.png)
rather, the game is using the corner land beach tiles, but still treats it like an open sea beach tile

**Comment by KBraid** [comment]
the corner beach tiles also do not appear in the terrain editor menu

**Comment by Robosturm** [comment]
The game is actually using the correct sprite. It just selects a wrong overlay.
