### ISSUE TITLE
(Bug) when customizing Nell in "Edit COs" i can't change the colors of her advance wars 2 render

### ISSUE THREAD

**Issue by Coolmc2222** [Robosturm/Commander_Wars#1534]
Bug
when i tried to change the colors of the AW2 look of Nell it didn't work

Reproduce
1.Go to Personal, CO Style
2. Click Nell and go to edit colors
3. Select her AW2 render and select a different style
then you will see it

**Comment by Robosturm** [comment]
@KBraid  probably the first row of the color table doesn't match the image colors.
Do you want to fix it else the issue won't be resolved and i keep it open
