### ISSUE TITLE
(QOL) Selecting Campaign Maps in Standard Singleplayer

### ISSUE THREAD

**Issue by Coolmc2222** [Robosturm/Commander_Wars#1537]
This is a Quality of Life Feature but can the Campaign maps be made available in the "New Game" tab(AW1, AW2 and DoR), like how the DS maps are now. since id like to switch around COs and colors and do silly stuff like that(and currently i can do it if i launch multiplayer but that feels like something can be updated to be done quicker maybe)

**Comment by Robosturm** [comment]
Campaign maps will never be made freely accessable cause it's defeating the purpose of a campaign.
The aw ds campaign is currently an exception cause it's not finished.
