### ISSUE TITLE
Setting a unit's HP to 0.001 deletes the unit

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1539]
Anything in the game that sets a unit's health to 0.001, such as splash damage CO powers and missile silos, will cause the unit to "disappear" (it dies without an explosion).

I suspect this might be caused by a recent change related to float values. I tested Sturm's meteor without any mods enabled, and if it hits a 1 HP unit, that unit dies when it shouldn't.

It seems like setting the HP to 0.1 instead of 0.001 fixes it?

**Comment by Robosturm** [comment]
Note: The rounding remains as it's the only change will be that the hp gets set to a trackable value.
Also fixed a potential situation in which a unit could be deleted with the old code
