### ISSUE TITLE
Minamoto should get firepower from Mines

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1544]
Considering Mines are Mountains that can be captured for income, they should give him increased firepower.

Both are mountains:
![image](https://user-images.githubusercontent.com/113127747/232307185-0bcd09b5-193a-4975-8ee1-01a9a92574a2.png)

**Comment by Robosturm** [comment]
Mines are not mountains that can be captured. It's only the visual that looks like a mountain at the moment.
