### ISSUE TITLE
Cannot attack some units that have first strike

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1547]
**Describe the bug**
Sometimes against COs who have first strike some units wont be able to attack some enemy units. I think its when the enemy units would kill the attacking unit with the first strike.

**Screenshots**
Video:
https://user-images.githubusercontent.com/113127747/232779749-beece1fa-eef2-48ec-a69c-cbe57a6c56aa.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Version: 30.2
 - Active Mods: None

**Additional context**
In the same turn I tried to attack Joey's units and the strike first animation broke, visually Sonja's units striked first but dealt little to no dmg while Joey's counter attacks dealt the first strike damage. (This same bug happened when playing vs a co of the cows co contest that has first strike.)

**Comment by Robosturm** [comment]
Not the battle animation is only a visual bug and not being able to attack a unit which would kill you without dealing damage to it's a minor inconenience
