### ISSUE TITLE
Feature Request: Loaded msav files automatically setting players without a lobby waiting time

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1548]
**Is your feature request related to a problem? Please describe.**
Currently, when an msav file of a game is hosted, the game goes to the lobby, where players must setup which player number they were and then hit ready. This is not always loaded as the original match and makes it difficult for new players to setup.

**Describe the solution you'd like**
Data about the player names and player numbers could be saved in the msav file, then when the msav file is hosted again, the players would automatically be set with their correct player number. This could make it easier for newer players.

**Comment by Robosturm** [comment]
1. The msav file is more Hearts of Iron like
2. usernames are not unque for msav files
3. Using the hosted server does handle this, so using an msav file is using a variant not meant to be used for things like that cause the msav files gets desynced with the server data.
