### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ringtaill99** [Robosturm/Commander_Wars#1550]
**Describe the bug**
on the map take and hold there are 3 players instead of 2 why is that ? captured hq on day 10 map did not end [

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/131489685/233736599-c9eb5618-324a-4061-8058-9238d088d15b.png)

**Comment by Robosturm** [comment]
Cause you need to route os as well, which should have an army to the west

**Comment by ringtaill99** [comment]
but it's only a mega tank the mission is impossible to beat in 11 days so on day 11 os starteds moving

**Comment by Robosturm** [comment]
That's cause the mission isn't finished yet.
In practice ones you captured the ma an orange army will be spawned which you need to defeat.

**Comment by ringtaill99** [comment]
how do you beat the olie mission
