### ISSUE TITLE
AI's turn won't change in a multiplayer game, except for the host

### ISSUE THREAD

**Issue by aitermoo** [Robosturm/Commander_Wars#1552]
**Describe the bug**
AI's turn won't change in a multiplayer game, except for the host

**To Reproduce**

1.Direct host a game in Local with some ai
2.Wait a player join than start the game
3.Wait until ai's turn
4.Ai's turn won't change except for the host , another player stuck forever

**Desktop (please complete the following information):**
OS: Windows 10.
Version: 30.2
Active Mods: None

**Additional context**
By using Normal AI in Local Direct host

**Comment by Robosturm** [comment]
#1542
