### ISSUE TITLE
Fortified HQs - funtionaly unhacky and visually pleasing caprush guard building

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1553]
basically a destructible building that when destroyed transforms its tile into the owner's HQ.
though there are some details to consider.
blocks enemy movement or all movement? and if only enemy, does it allow for resupply? should it be allowed to attack, and if so what kind of attack and what range?

**Comment by Robosturm** [comment]
I would not give it any offence optionand rather have it work like a gate/weld. 
As for movement if it goes the gate routeit should resupply since destroying it transforms it into a normal hq
