### ISSUE TITLE
Capturable Depots that only supply allies

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1554]
Currently Depots cannot be captured and supply any ground unit on top of it (Weirdly they can be given an owner in the Map Editor.). It would be good if Depots could be captured so they would only supply allied units instead all units.

**Comment by Robosturm** [comment]
THe idea of depots is beeing always able to supply any unit.

**Comment by Robosturm** [comment]
This is something for mod it yourself if you don't like it section
