### ISSUE TITLE
Add Alternate Themes option for the Edit COs screen

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1567]
Just like you can change the Co Style it'd be great if a similar option was added for themes, so alternate Co themes like the reboot camp could be added to the game and chosen to play or not with those cos, or just as an option for mods idk.

**Comment by KBraid** [comment]
audio files are significantly large, this would better be serviced via mods

**Comment by Robosturm** [comment]
As mentioned this is modding territory

**Comment by Firewito** [comment]
I dont mean to add all themes but to add a menu to the Edit Cos screen so modded cos can have multiple themes to be chosen.
