### ISSUE TITLE
Crash when trying to join a Server match with the cows movement mod

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1568]
When I tried to join the lobby with those mods my game crashed in the "Connecting..." screen.
After that I could join with no problem.

The message the crash window left:
[message (2).txt](https://github.com/Robosturm/Commander_Wars/files/11355880/message.2.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 30.2
 - Active Mods: AW-Styled Icons, Cooperation mod and Commander Wars movement mod.

**Comment by Robosturm** [comment]
Only thing i can find is that the movement mod has a bug but i can't create a crash in the current source code state --> might have been fixed during development by accident
