### ISSUE TITLE
Camaign getting overwritten

### ISSUE THREAD

**Issue by Jovermask** [Robosturm/Commander_Wars#1569]
Everytime I save two or three times a campagin, it ends up getting overwritten by an other one(mostly the tutorial campaign and in second the advance wars 1 campaign), loading the campaign in the editor, deleting it and resave it then doesn't change anything, changing the informations of the campaign does not change anything too.
 - Version: Beta_30_2
 - Active Mods: advance wars dual strike mods

**Comment by Robosturm** [comment]
Don't save the campaign with the name of autosaves. Those get overwrittem.
You can't overwrite vanilla files and the vanilla campaign files are not loadable by the editor in a useful way. 
Saving and loading a custom campaign.jsm works as intended.
