### ISSUE TITLE
Boat movement type

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1574]
Same as #1521, there's just no use for it anymore.

Btw, if this gets rejected again, can an explanation be provided for why the boat movement should stay? Thanks

**Comment by Firewito** [comment]
The Boat move type is used in the aw2/ds units mod, but in cows I agree that it should be changed.

**Comment by Robosturm** [comment]
Cause  it's used and not always the same and cause of compatibility reasons
