### ISSUE TITLE
Game crashes when trying to play on a custom map with Fog of Shroud enabled by default

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#158]
I was making a randomly-generated map that has Fog of Shroud already enabled in the rules, but trying to play on it crashes the game. Can't even start an actual game on it because the game crashes as soon as I hover over it in the maps list. I made sure to disable all mods, and the game still crashes.

Here's the crash log file if needed: [20200304-125752 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4288967/20200304-125752.Commander.Wars.Crash.log)

By the way, another related question... shouldn't it be called "Shroud of War" and not "Fog of Shroud"?

**Comment by Robosturm** [comment]
Fixed and renamed it.
The minimap shows now a black map as preview. :)
