### ISSUE TITLE
Neotanks should deal a bit more dmg to heavier tanks

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1583]
Currently the Heavy Tank deals 45% dmg to other Heavy Tanks and 30% to Megatanks, but the Neotank only deals 40% dmg to other Heavy Tanks and 30% to Megatanks.
Considering the Neotank is more expensive and supposed to have more firepower than the Heavy tank (but less defense) it should deal atleast 45% dmg, if not 50% to Heavy Tank,  and maybe even 35% to Megatanks (Would be good maybe?).

**Comment by KBraid** [comment]
Neotanks have been rebalanced to play more of a Medium Tank role, though not quite even between light and Heavy tanks. Having similar armour value, moving slightly faster, and being slightly weaker.

**Comment by Robosturm** [comment]
You pay for the movement not the firepower
