### ISSUE TITLE
ai nonfunctional

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#1590]
ai refuses to do anything on their turn
[console-04-05-2023-13-54-16.log](https://github.com/Robosturm/Commander_Wars/files/11400693/console-04-05-2023-13-54-16.log)

**Comment by KBraid** [comment]
Info: 04.05.2023 13:54:28: Started with: D:\Games\Comander Wars\beta 25\Commander_Wars.exe --noUi --noAudio --mods mods/BattletanxCO,mods/Iron_Curtain_Mod,mods/KTEKNIS_Projects,mods/SFW CO's,mods/SFW and WG palette unlock,mods/Wargroove cos,mods/aw_styled_icons,mods/awall_co,mods/awdc_creeper,mods/cowextraunits,mods/cyrus,mods/interior,mods/kbraidcos,mods/powerbar,mods/silver_horizon,mods/train --spawnAiProcess 0 --aiSlave File:  Line: 0 Function: 
Info: 04.05.2023 13:54:28: Enter "help()" for console info. File:  Line: 0 Function: 
Info: 04.05.2023 13:54:28: Starting Game... File:  Line: 0 Function: 
Info: 04.05.2023 13:54:28: Prepare to Fight... File:  Line: 0 Function: 
Info: 04.05.2023 13:54:28: Read this message while waiting... File:  Line: 0 Function: 
Info: 04.05.2023 13:54:28:  File:  Line: 0 Function: 
Info: 04.05.2023 13:54:28: I don't have a solution, but I admire the problem! File:  Line: 0 Function: 
Info: 04.05.2023 13:54:28:  File:  Line: 0 Function: 
Critical: 04.05.2023 13:54:29: File: mods/interior//scripts/movementtables/move_patch.js didn't add an object named MOVE_PATCH to the game File:  Line: 0 Function: 
Critical: 04.05.2023 14:00:17: An interaction changed the map state outside performing actions. File:  Line: 0 Function: 
Critical: 04.05.2023 14:01:12: An interaction changed the map state outside performing actions. File:  Line: 0 Function: 
Critical: 04.05.2023 14:02:07: An interaction changed the map state outside performing actions. File:  Line: 0 Function: 
Critical: 04.05.2023 14:02:50: An interaction changed the map state outside performing actions. File:  Line: 0 Function: 
Critical: 04.05.2023 14:02:50: An interaction changed the map state outside performing actions. File:  Line: 0 Function: 
Critical: 04.05.2023 14:03:08: An interaction changed the map state outside performing actions. File:  Line: 0 Function:

**Comment by KBraid** [comment]
fresh install of the game fixed the issue, probably the result of leftover files causing conflicts

**Comment by KBraid** [comment]
nevermind it is still broken

Commander Wars vVersion: 0.31.1-main Builddate: May  3 2023 18:57:57
04 May 2023 @ 14:33:20

EXCEPTION_ACCESS_VIOLATION

INFO: 04.05.2023 14:26:24: Started with: D:\Games\Comander Wars\Commander_Wars_Release\Commander_Wars.exe --noUi --noAudio --mods mods/BattletanxCO,mods/Iron_Curtain_Mod,mods/KTEKNIS_Projects,mods/SFW CO's,mods/SFW and WG palette unlock,mods/Wargroove cos,mods/aw_styled_icons,mods/awall_co,mods/awdc_creeper,mods/cowextraunits,mods/cyrus,mods/interior,mods/kbraidcos,mods/powerbar,mods/silver_horizon,mods/train --spawnAiProcess 0 --aiSlave
INFO: 04.05.2023 14:26:24: Enter "help()" for console info.
INFO: 04.05.2023 14:26:24: Starting Game...
INFO: 04.05.2023 14:26:24: Prepare to Fight...
INFO: 04.05.2023 14:26:24: Read this message while waiting...
INFO: 04.05.2023 14:26:24: 
INFO: 04.05.2023 14:26:24: Mommy, there's a monster in front of my screen!
INFO: 04.05.2023 14:26:24: 
CRITICAL: 04.05.2023 14:26:24: File: mods/interior//scripts/movementtables/move_patch.js didn't add an object named MOVE_PATCH to the game
CRITICAL: 04.05.2023 14:26:41: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:41: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:41: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:41: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:41: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:41: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:41: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:42: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:43: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:43: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:43: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:43: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:43: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:43: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:43: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:44: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:26:44: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:33:20: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:33:20: An interaction changed the map state outside performing actions.
CRITICAL: 04.05.2023 14:33:20: An interaction changed the map state outside performing actions.

**Comment by Robosturm** [comment]
Any issue happening in a none vanilla envir9nment won't be investigated.
The issue is 99,99% created by a bug 8n one of the mods
