### ISSUE TITLE
sound 

### ISSUE THREAD

**Issue by ringtaill99** [Robosturm/Commander_Wars#1592]
**Describe the bug**
a bug happens when a sound effects plays nonstop until you quit the game 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Active Mods (Note: none vanilla mod problems want be investigated)

**Additional context**

**Comment by Robosturm** [comment]
Not reproducable in the latest version or the describtion lacks details
