### ISSUE TITLE
Music automatically ends after 90 seconds

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#160]
I've music from one of the custom COs which last about 3 minutes. The problem is that music suddenly ends when 90 seconds have elapsed and it's replayed from the beginning. That is quite bug or some limit in music engine.

**Comment by Robosturm** [comment]
How do you start playing the CO music?
Since the last two arguments are the start looping point and the end looping point in milliseconds. So if the last number equals 90 seconds it would explain it.

**Comment by Danmark25** [comment]
Well the numbers (first and second are as follows 631, 59458)

**Comment by Robosturm** [comment]
That means the game will loop the music from 0,5s to 60s. So this is no bug. You need to change at least the last number to the looping point of your choice. Propably 180000

**Comment by Danmark25** [comment]
so ~60000 means 60 seconds?

That means second ~ 1000?

So if music have 4 minutes and 37 seconds.. the correct number will be 243700?

**Comment by Robosturm** [comment]
Yeah correct the number means time in milliseconds. The reason is to select a looping point. So you listen to a continuous music
