### ISSUE TITLE
Edited Rivers looking invisible

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1604]
**Describe the bug**
Edited those rivers in the map editor and there were visible there, ingame no.

**Screenshots**
Cant see them:
![image](https://github.com/Robosturm/Commander_Wars/assets/113127747/dfbd4c10-49d5-42e1-adf2-eca681433a45)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 31.2
 - Active Mods: None

**Comment by Robosturm** [comment]
More info needed to solve the issue works correctly on my end

**Comment by Robosturm** [comment]
Closed the issue cause no further information was provided, since it works correctly on my end.
