### ISSUE TITLE
AI doesn't use recon before sending expensive units into the fog.

### ISSUE THREAD

**Issue by aitermoo** [Robosturm/Commander_Wars#1608]
**Is your feature request related to a problem? Please describe.**
This makes it easy for them to lose expensive units.

**Describe the solution you'd like**
AI should do more reconnaissance work before launching an attack.

**Describe alternatives you've considered**
just let AI build some Recons if Flare is ban on map

**Comment by Robosturm** [comment]
The ai builds flares and recons at random and currently i'm not improving or adding new conditions for e.g. recons to enfore production of a vision unit.

On top reconnaissance is one of the topics that is impossible to realize with the man power currently working on the game which is just me.
