### ISSUE TITLE
Getting a crash with Nana on Fairy's Japan map with Shroud of War

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#161]
Can't tell what specifically is causing this crash due to not being able to see what's happening, but should also note that her CO power was modified to kill units rather then leaving them at one hp and not sure if that's has anything to do with the crash.
[20200307-001215 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4301495/20200307-001215.Commander.Wars.Crash.log)

**Comment by Robosturm** [comment]
I don't have the changes you made in the the script, but I can say the bug happens due to you killing units in the script. Most likely you kill the attacking or defending unit in the action, which is required/killed by the normal attack script and then everything explodes. I can tell you more if I see the actual script changes

**Comment by Everglass** [comment]
Here's the edit in question:

CO_NANA.postBattleActions = function(co, attacker, atkDamage, defender, gotAttacked)

    {
        if (!gotAttacked)
        {
            var owner = co.getOwner();
            var powerMode = co.getPowerMode();
            var damage = 0;
            var explosionRange = 1;
            var friendlyFire = true;
            var i = 0;
            var defX = defender.getX();
            var defY = defender.getY();
            var unit = null;
            var point = Qt.point(0, 0);
            var hp = 0;
            switch (powerMode)
            {
                case GameEnums.PowerMode_Tagpower:
                case GameEnums.PowerMode_Superpower:
                    damage = 2;
                    explosionRange = 2;
                    friendlyFire = false;
                    break;
                case GameEnums.PowerMode_Power:
                    friendlyFire = false;
                    damage = 1;
                    if (attacker.getBaseMaxRange() === 1 && damage > 0)
                    {
                        damage = 2;
                        var width = map.getMapWidth();
                        var heigth = map.getMapHeight();
                        var maxRange = width;
                        if (heigth > width)
                        {
                            maxRange = heigth;
                        }
                        var found = false;
                        // deal direct chain damage to nearest enemy
                        for (var curRange = 1; curRange < maxRange; curRange++)
                        {
                            var directCircle = globals.getCircle(curRange, curRange);
                            for (i = 0; i < directCircle.size(); i++)
                            {
                                point = directCircle.at(i);
                                if (map.onMap(defX + point.x, defY + point.y))
                                {
                                    unit = map.getTerrain(defX + point.x, defY + point.y).getUnit();
                                    if (unit !== null &&
                                        owner.isEnemyUnit(unit))
                                    {
                                        hp = unit.getHpRounded();
                                        if (hp <= damage)
                                        {
                                            unit.killUnit();
                                        }
                                        else
                                        {
                                            unit.setHp(hp - damage);
                                        }
                                        found = true;
                                        break;
                                    }
                                }
                            }
                            directCircle.remove()
                            if (found === true)
                            {
                                break;
                            }
                        }
                    }
                    break;
                default:
                    if (co.inCORange(Qt.point(attacker.getX(), attacker.getY()), attacker))
                    {
                        damage = 1;
                    }
                    break;
            }

            // deal indirect unit splash damage
            if (attacker.getBaseMaxRange() > 1 && damage > 0)
            {
                var circle = globals.getCircle(1, explosionRange);
                for (i = 0; i < circle.size(); i++)
                {
                    point = circle.at(i);
                    if (map.onMap(defX + point.x, defY + point.y))
                    {
                        unit = map.getTerrain(defX + point.x, defY + point.y).getUnit();
                        if (unit !== null)
                        {
                            if (owner !== unit.getOwner() || friendlyFire === true)
                            {
                                hp = unit.getHpRounded();
                                if (hp <= damage)
                                {
                                    unit.killUnit();
                                }
                                else
                                {
                                    unit.setHp(hp - damage);
                                }
                            }
                        }
                    }
                }
                circle.remove()
            }
        }
    };

**Comment by Robosturm** [comment]
Yes the problem is that you may kill the attacker or defending unit.
You need to check if the unit you want to kill isn't the attacker or defender else the game will crash.

**Comment by Everglass** [comment]
I see, I'll see what I can do to fix it.

**Comment by Everglass** [comment]
Ok, set it to where it doesn't kill friendly units, that should have resolved the issue.

Thanks for the help :)
