### ISSUE TITLE
Unable to Attack Structures on Android

### ISSUE THREAD

**Issue by MaxAstro** [Robosturm/Commander_Wars#1613]
Version: 0.31.2-main Android

Units cannot attack structures (Black Cannons, etc; any map tile with health). After moving the unit into position the "Fire" option appears, but selecting it does not give the ability to target the structure. Instead the fire cursor appears over the attacking unit. Tapping on various tiles results in the cursor moving to that tile, but no attack can actually be launched.

Testing: I first noticed this on the map Andy's Time. I also tried attacking the mini cannons in Take and Hold, and finally I went to the map editor and created a custom map with a Black Laser. In all case, both direct and indirect units were unable to fire on the structures.

**Comment by Robosturm** [comment]
#1603
