### ISSUE TITLE
Volcano Rework

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1616]
Could the volcano be changed so you can put which tiles get hit on even and odd days instead of it being random? That is, for it to function just like in the Reboot camp?

Here's a screenshot I found of the AWRC volcano

![RDT_20230524_2036546384031428646711293](https://github.com/Robosturm/Commander_Wars/assets/93048095/863df9ab-60e3-4f7e-8cd3-341f2b0055ea)

**Comment by Robosturm** [comment]
That's already possible and with more options compared to reboot camp. Using scripts e.g. in rain of fire.
Though i admit it's currently not intuitiv useable cause you need to manually script it.
But the solution doing it via scripts won't be changed.
I can only see the point of adding options to the script editor for thar
