### ISSUE TITLE
Edited Overlay bug

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1618]
When you use the Mass Edit Terrain tool to change the palette of the entire map, tiles whose overlays were manually selected don't change.

**Comment by Jocrr** [comment]
Just found out that if you edit a overlay of a lake for example, with a palette other than the default one (for example Rain AW2), the new overlay still has the default overlay instead of the new one

**Comment by Robosturm** [comment]
Works exactly as it should for me.
Please make a step by step guide with screenshots.
On what you think is a bug atm it looks correct to me

**Comment by Jocrr** [comment]
1.Place a lake tile with Waste palette selected
2.Change the lake tile overlay with Edit Terrian tool

The lake tile should revert back to the Clear palette then
