### ISSUE TITLE
A way to add custom text to the Victory Conditions screen for Custom Maps

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#162]
Perhaps some way to include objectives to the Victory Conditions screen. Just flavor text to give the player some heading on hidden mechanics to a Custom Map. Maybe even an event to where the Victory Conditions update during match.

**Comment by Robosturm** [comment]
You can do that already. Just add a function called getVictoryInfo to the generated script. An example can be found in the aw2 campaign scripts e. G. Andy's Time.

Going to add an actual support to the Ingame editor for the next release
