### ISSUE TITLE
 Incorrect Instruction Document

### ISSUE THREAD

**Issue by aitermoo** [Robosturm/Commander_Wars#1621]
**Describe the bug**
some co had incorrect information in their game wikis.

**Screenshots**
![1](https://github.com/Robosturm/Commander_Wars/assets/24765923/5da61d6e-4eac-4d3f-a104-294968c51666)
![2](https://github.com/Robosturm/Commander_Wars/assets/24765923/fb70703b-fe5a-4d77-8633-2c1a0ee2f21e)
![3](https://github.com/Robosturm/Commander_Wars/assets/24765923/16e7cfb7-b250-4d78-b34d-d5656daafb0a)
![4](https://github.com/Robosturm/Commander_Wars/assets/24765923/47c4d1b1-f241-4480-a2a7-33454aa04da9)
![5](https://github.com/Robosturm/Commander_Wars/assets/24765923/350d06b7-1c57-401d-be4b-6f5887ebd32c)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 32.1
 - Active Mods N/A

**Comment by Robosturm** [comment]
The zero values are correct. Those are the values used in other vanilla mods and are 0 for the vanilla game
