### ISSUE TITLE
Move Animation

### ISSUE THREAD

**Issue by ATNoName** [Robosturm/Commander_Wars#1627]
The unit moving animation still plays despite over world animation being turned off

1. Turn overworld animations off
2. Turn movement animations on
3. In any game move a unit
4. Unit does the move animation instead of teleporting to the spot

Information:
 - OS: Windows
 - Version: Latest version

Additional context: Very minor bug that I didn't know if it is even intentional. Another funny note is how weird it tends to be when the unit moves to fight especially when it move to kill a unit.

**Comment by Robosturm** [comment]
This is the intentional behavior it was requested to have a separat disable button for that.
All animations with separat toggle aren't affected by the overworld selection
