### ISSUE TITLE
Request/question: Is it possible to display dialogue on the campaign world map screen?

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1644]
If it isn't already possible, I have a feeling there's probably a technical reason why that's the case. But regardless... is it possible to display dialogue on the world map screen? (As in the campaign mission selection screen with the flags.)

Might be useful for custom campaigns and the game's own recreations of the AW campaigns, since that's how those games display pre-mission dialogue.

**Comment by Robosturm** [comment]
Dialogues are an animation which useally runs inside a running game, which tracks the animations and prevent input while they are running.
The campaign menu lacks that information / several ui elements are not designed to get blocked while animations are running.
While it's a reasonable request. The technical overhead feels to large for me atm.

**Comment by Robosturm** [comment]
Note: You may stumble across weird interactions. I didn't think of in that case you need to create a bug report for it. ;)
Basic version worked for me.

**Comment by XnKradst** [comment]
I see, thanks for implementing it! I'll test it when the next version is out and I'll let you know if there are any bugs.
