### ISSUE TITLE
Unit Movement Issues

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1646]
Air Units do not have 'FORTHQ' listed in their movementtable (but they do have it in the getMovementPoints code section)
Foot Units do not have 'WASTE_DESTROYEDWELD', Mech Units do
Boat Units can move onto ZGATE tiles (which Small Boat and Ship Units cannot) without having any code to check if you actually own the Gate

**Comment by Robosturm** [comment]
Note: Air units have the entry according to my code

**Comment by FranticFairy** [comment]
Probably because it was added _after_ the latest public release? move_air got the FORTHQ line on Jun27, Last public release was May31
