### ISSUE TITLE
v32 Server returns players to lobby upon hitting ready

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1647]
**Describe the bug**
When hitting ready on a game on a multiplayer game, the game returns both players to the lobby. No error shown in the console.

**To Reproduce**
Login to the game server and host a multiplayer game, make both players hit ready. See players being returned to the multiplayer lobby. 

**Expected behavior**
The server loading a match with the map and players
**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Version 32
 - Active Mods: None

**Comment by Robosturm** [comment]
Pretty sure it's related to your compilation or versions i tested it on my end and it works fine with the current source code / i didn't change the handling for it since the release.
You probably see the issue in the logs of the server or client if the debug output is enabled

**Comment by lonewolf19991** [comment]
I used the source code directly from the download, it's the binary generated by github.
