### ISSUE TITLE
v32 has sound issues on Linux

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1649]
**Describe the bug**
The v32 of the game fails to compile with the following output:
`coreengine/audiomanager.cpp: In constructor ‘AudioManager::AudioManager(bool)’:
coreengine/audiomanager.cpp:23:24: error: use of deleted function ‘AudioManager::SoundEffect::SoundEffect(AudioManager::SoundEffect&&)’
   23 |       m_noAudio(noAudio)
      |                        ^
/coreengine/audiomanager.cpp:1:
coreengine/audiomanager.h:284:12: note: ‘AudioManager::SoundEffect::SoundEffect(AudioManager::SoundEffect&&)’ is implicitly deleted because the default definition would be ill-formed:
  284 |     struct SoundEffect
      |            ^~~~~~~~~~~
coreengine/audiomanager.h:284:12: error: use of deleted function ‘QScopedPointer<T, Cleanup>::QScopedPointer(QScopedPointer<T, Cleanup>&&) [with T = QSoundEffect; Cleanup = QScopedPointerDeleter<QSoundEffect>]’
In file included from Qt/6.5.2/gcc_64/include/QtCore/qglobal.h:38,
                 from Qt/6.5.2/gcc_64/include/QtCore/qnamespace.h:12,
                 from Qt/6.5.2/gcc_64/include/QtCore/qobjectdefs.h:12,
                 from Qt/6.5.2/gcc_64/include/QtCore/qobject.h:10,
                 from Qt/6.5.2/gcc_64/include/QtCore/QObject:1,
                 from coreengine/audiomanager.h:4,
                 from coreengine/audiomanager.cpp:1:
Qt/6.5.2/gcc_64/include/QtCore/qscopedpointer.h:186:5: note: declared here
  186 |     Q_DISABLE_COPY_MOVE(QScopedPointer)
      |     ^~~~~~~~~~~~~~~~~~~
In file included from coreengine/audiomanager.cpp:1:
coreengine/audiomanager.h:284:12: error: use of deleted function ‘QTimer::QTimer(const QTimer&)’
  284 |     struct SoundEffect
      |            ^~~~~~~~~~~
In file included from Qt/6.5.2/gcc_64/include/QtCore/qglobal.h:38,
                 from Qt/6.5.2/gcc_64/include/QtCore/qnamespace.h:12,
                 from Qt/6.5.2/gcc_64/include/QtCore/qobjectdefs.h:12,
                 from Qt/6.5.2/gcc_64/include/QtCore/qobject.h:10,
                 from Qt/6.5.2/gcc_64/include/QtCore/QObject:1,
                 from coreengine/audiomanager.h:4,
                 from coreengine/audiomanager.cpp:1:
Qt/6.5.2/gcc_64/include/QtCore/qtimer.h:180:5: note: declared here
  180 |     Q_DISABLE_COPY(QTimer)
`

It implies that resources are trying to be accessed by the game, while such have been removed from memory, if there's any way to debug this further let me know, this did not occur in v30 of the game.

Notice: If I set the Audio Support flag to off, the game compiles and plays normally. 

**Qt version used:** 6.5.2
**cmake version:** 3.24.2
**Game version:** 32
**OS:** Linux
Let me know if there's anything I could be missing

**Comment by Robosturm** [comment]
My guess is that you miss Qt-Multimedia or gstreamer libs or it's an issue with your qt-version.

The game gets compiled on Android, Ubuntu, MacOs and Windows. So any compilation errors are always on your end and not mine.

I recommend checking out the yml-files used to build the game on the gitlab-ci
