### ISSUE TITLE
Request: Reducing the size of the data transfered for Multiplayer connections

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1650]
**Is your feature request related to a problem? Please describe.**
Currently the game performs properly when two clients connect, while being physically close. However, when the clients are physically distant from each other, the hops needed to go from the player a  to the server and then to player b, increase, for which reason, if the internet on either side is not as good, the players experience disconnections, or desyncs. This would occur less often if the size of the data in MB was reduced.  

**Describe the solution you'd like**
A reduction of the size of the data transferred, by either further compressing the data that is currently being sent, or by making the client do more of the code execution locally. 

**P.S. The ideal size for the maximum size of websites in MB is 2Mb, perhaps a data size close to that one might be ideal to improve upon on the response of the network code**

**Comment by Robosturm** [comment]
The only time a packet is send with a size over 100 Bytes is when the map gets transferred and that one is not a problem.
On top everthing is send using tcp so any error here would only result in a longer sending time but nothing more.
