### ISSUE TITLE
AI crashes game when playing a savegame 

### ISSUE THREAD

**Issue by Brilliand** [Robosturm/Commander_Wars#1656]
**Describe the bug**
I'm getting a game crash.  No idea what's going on, but it happens consistently on this save (with or without mods).

**To Reproduce**
1. Load the attached save
2. End your turn
3. Watch the game crash sometime during Blue Moon's turn

**Expected behavior**
The AIs take their turns in the fog, and my turn comes back around

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.33.0-main
 - Active Mods: There were some, but I turned them off and the crash keeps happening.

**Additional context**
Here's the save I'm getting the crash on:
[Random Map_autosave_3.zip](https://github.com/Robosturm/Commander_Wars/files/12330000/Random.Map_autosave_3.zip)

Here's the crash log:
[20230813-121346 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/12330013/20230813-121346.Commander.Wars.Crash.log)

**Comment by Brilliand** [comment]
Got it to happen on a save that never had any mods involved at any point.
[Random Map_autosave_2.zip](https://github.com/Robosturm/Commander_Wars/files/12330208/Random.Map_autosave_2.zip)

**Comment by Ischnaroth** [comment]
Hello,

it looks like this bug occurs with every saved game.

1. Start a new match with at least one AI
2. Play 2-3 turns
3. Save the game
4. Close the program
5. Start the program
6. Load the saved game
7. End your turn
8. Watch the program crash when the AI ​​wants to end its turn
