### ISSUE TITLE
Game freezes by AI on larger maps

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#166]
I'm playing a custom maps with 40x30 size with 3 AIs.

The problem is that after some turns, AI needs 1-2 minutes to make recruit and last movement phase (during that phase it impossible to move map)

On smaller maps this issue don't exist

**Comment by Danmark25** [comment]
And I see that AI have a problems with recruiting other type of forces, over 90% is Infantry or Mechs, and Tanks or Hovercrafts are built very rarely (There was no build limits set)

**Comment by Everglass** [comment]
I also ran into this issue while playing on Fairy's Wraparound Global Map. It only occurred for one of the AI opponents. The game doesn't actually freeze, it just locks up for a very long time until the AI eventually builds a unit. Then lags for a very long time again for every unit the AI builds. It returns to normal after the AI player finishes their building phase, but the cycle begins all over again when it reaches that player's turn and they start building units.

**Comment by Robosturm** [comment]
As for building units. The AI builds units based on the Income / Factory Ratio. If that is getting to around 1000 Funds the AI builds a lot of infantry units.
But on my test maps the Units the AI builds is the way it should be infantries to build meatwalls and the rest tanks, copters etc. 

As for game freezing i'll check if i can optimize the ai speed

**Comment by Robosturm** [comment]
Okay you can now move the map a lot more smoothly during AI-Turns. 
On top AI is a lot faster with building units and produce units more narrow to fronts and what is needed there.
