### ISSUE TITLE
Please add a scroll bar to the map search bar in the menu.

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1660]
**Is your feature request related to a problem? Please describe.**
There are lots of maps in the game, so it takes a long time to scroll through them in the menu list. Searching maps by filter can be slow and useless if you don't know what you are looking for.

**Describe the solution you'd like**
I would like there to be a scroll bar so I can find maps faster.

**Describe alternatives you've considered**
I would like for the official Intelligent Systems maps to be separated into their own sub-folder that separates them from custom ones.

For example...
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/963ff216-de71-49a4-a7cd-8670e870e6e8)

And in here, you would find "Intelligent Systems", where the IS maps would be found.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/a94aa320-67a5-47ae-8dd8-621c722aa02e)

**Additional context**
Here is a screenshot of the map selection list.
![Screenshot 2023-08-01 184945](https://github.com/Robosturm/Commander_Wars/assets/142738275/9e28c116-6ac6-4ee9-a5ad-a1c979ca84e1)

Here is a screenshot of the map list when you are in the map editor.
![Screenshot 2023-08-01 185211](https://github.com/Robosturm/Commander_Wars/assets/142738275/0b5d0f26-3aab-4730-9645-a01ae5ed364a)

I would like this to be added.
![Screenshot 2023-08-01 185004](https://github.com/Robosturm/Commander_Wars/assets/142738275/3d22b8e9-9322-4f82-ae08-3d6d952b52bf)

**Comment by Robosturm** [comment]
Probably won't happen for a long time due to the way the ui element is currently implemted. Adding a scrollbar requires a lot of refactoring and the whole map selection ui needs a rework answay.

**Comment by FruityGumGuiltyFruit** [comment]
Alright, thank you.
