### ISSUE TITLE
Skipping a unit's animation causes its move sound to loop indefinitely.

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1663]
**Describe the bug**
Bug where foot soldiers sometimes tap dance, and drivers sometimes leave their engines idle.
Skipping the movement/capture/battle animation of a unit can cause the unit's move sound to play on repeat until another unit is commanded. Incredibly distracting, and can happen multiple times per battle, or not at all for several battles.

**To Reproduce**
1. To reproduce, play battle mode and skip unit animations with m2 when they start to play.
2. Get lucky and hear error

**Expected behavior**
Movement sound should only play when the unit moves, and stop when it stops.

**Screenshots**
My recording software was a bit quiet, so if you can't hear it either turn up your volume or check to make sure Github doesn't have the video muted.

Example of bug when moving
https://github.com/Robosturm/Commander_Wars/assets/142738275/09c819b8-dc95-4d84-ba4e-404991214386

Example of bug when capturing
https://github.com/Robosturm/Commander_Wars/assets/142738275/c0324994-cb40-45dc-a157-a34bbbd75f61

Example of bug when battling
https://github.com/Robosturm/Commander_Wars/assets/142738275/a5bd557e-7519-4888-b93e-92fb85bf2729

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Version [22H2]
 - Active Mods (Note: none vanilla mod problems want be investigated)

**Additional context**
Here's my animation settings. I believe it happens regardless of settings.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/c1a48c93-2c11-4e04-ae25-84294cfe4c12)

**Comment by Robosturm** [comment]
It's a bug I already heard of but never was able to reproduce on my settings.
And I've read the code multiple times.
Are those records from v33?
Could you set the log levels in the Commander_Wars.ini to
LogLevel=1
LogModules=34
and reproduce the issue and send me the logs of a situation immediatly after it happened ?

**Comment by FruityGumGuiltyFruit** [comment]
Yes, I am playing on v33.  I can confirm I've experienced it as far back as Beta_29_3_Build1, maybe earlier.
I checked the .ini. LogLevel and LogModules are already set to 1 and 34 respectively.
What file would I need to send? console.log?

**Comment by Robosturm** [comment]
Yeah the console.log
