### ISSUE TITLE
Placing tiles over trees makes the grass greener

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1667]
**Describe the bug**
Read title.

**To Reproduce**
1. Go to map editor.
2. Place some trees.
3. Place trees or other objects on top of the trees.

**Expected behavior**
No change to the plains tile underneath.

**Screenshots**
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/8a8c0179-e423-4e0e-8d1d-f7c2c0523a42)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Version [22H2]
 - Active Mods (Note: none vanilla mod problems want be investigated)

**Additional context**

**Comment by Robosturm** [comment]
The game reselects a new sprite at rand9m for adjusting tiles which sometimes is the greener version

**Comment by FruityGumGuiltyFruit** [comment]
I did further testing, and would like you to reevaluate this issue. This shade of green doesn't appear in the default plains palette.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/e67075f5-7c4c-4b0d-b4f5-0a74e4f9f5dc)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/470b42bd-1318-4996-95bb-a356402e9f17)

Placing certain tiles over forests (I've confirmed mountain, ruins, forests of the same type, and other forest types. Instead of changing the tile underneath to Default, it changes it to Clear AW DS.

https://github.com/Robosturm/Commander_Wars/assets/142738275/e1cd2c00-eec3-4f93-98d6-4e340eee0210
