### ISSUE TITLE
Can't progress in campaigns anymore

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1669]
In version 33.1, beating a campaign mission doesn't actually complete it. At first I thought it's just a mod issue, but I've tested it with the vanilla campaigns and the same issues occur.

For campaigns that use a simple map list like the AW campaign recreations, the list doesn't even update. For example, after beating "It's War" in the AW1 campaign, it remains the only map available.
For campaigns that use the world map like the Commander Wars one, the flag isn't marked as complete. It just stays the same as if nothing happened, no fireworks animation, and the player can re-select and replay the mission when normally that shouldn't be possible.

**Comment by FruityGumGuiltyFruit** [comment]
I noticed this too, after beat AW4 campaign's first mission, Days Of Ruin.

**Comment by FruityGumGuiltyFruit** [comment]
Also, is there any particular reason why the Dual Strike maps are playable unlike the other campaigns?
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/4571f611-05ab-45db-8c7d-8db82de6fec4)

**Comment by Robosturm** [comment]
AW-DS campaign isn't finished and never will be (mostlikely cause several things aren't supported by CoW).
So the created maps are just visible but don't have a campaign surrounding it
