### ISSUE TITLE
A unit destroyed animation to play when a terrain change event causes a unit to be on terrain they cannot occupy

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#167]
It would be nice to have units appear to be destroyed when ever terrain is changed underneath them that they're unable to exist upon. At the moment, the unit's image kind of lingers there even though they no longer exist.

**Comment by Robosturm** [comment]
Reason is the same as bug #168. 
Fixed the visual glitch however the explosion want be added. You have to add an animation for that in your script.
