### ISSUE TITLE
New Command for Map Editor

### ISSUE THREAD

**Issue by QuestionMark210** [Robosturm/Commander_Wars#1671]
I'd like to see a Command that shows unit's movement and attack range. Just like in a normal game. This will make custom scenario creation much easier in my opinion. Also, I'd like to see it aplied to buildings like Black Cannons, Lasers and e.t.c.

**Comment by Robosturm** [comment]
Examples how it looks ingame.
![screenshot+3](https://github.com/Robosturm/Commander_Wars/assets/48879701/86cc6571-1470-4ed0-a069-be85309febbf)
![screenshot+2](https://github.com/Robosturm/Commander_Wars/assets/48879701/054ed728-d439-4af4-8ee6-1f4175c36bef)

It's not a new command just right clicking on a unit or building will toggle through firerange / vision range of a unit like during a match. So you can place stuff while the range of a building or unit is shown
