### ISSUE TITLE
Ability to choose which side of map is flipped or rotated in Map Editor

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1678]
**Is your feature request related to a problem? Please describe.**
When building symmetrical maps, my brain likes to try and build on the right side of the map editor, and when it is time to rotate the map I get annoyed that it copies the left or top side.

**Describe the solution you'd like**
Add the ability to select the bottom or right side of the map to rotate.

**Describe alternatives you've considered**
Here is how you can do it ingame, which takes time:
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/1e1d606b-5e09-40e5-bb93-4a6be83448f5)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/4374f2ef-773e-42c4-8c2c-e1f40aec4572)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/df17e961-8e48-4e42-9fc8-645521919c7c)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/5359b883-031c-4583-b994-be52d8342260)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/d0f22ade-2562-43e3-87d2-d21ccdc270ad)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/158adf9f-624a-424b-8f72-5915539b63bc)

**Comment by Robosturm** [comment]
Flip and rotate are available and changing stuff on the top or left side via code is in generel to much of a headache and adding an option with a similar increases confusion and isn't really helpful.
