### ISSUE TITLE
Ability to See Global Danger Zone, and Ability to Mark a Unit

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1680]
**Is your feature request related to a problem? Please describe.**
I get annoyed when I check several enemy units' range and try to move my unit just outside the range, but accidentally move it a space too close or miscount and lose the unit. It would also be helpful if you could "mark" an enemy unit so that its movement and range areas are always visible.

**Describe the solution you'd like**
Allow pressing a button to turn on/off viewing the danger zones of all enemy units at once, and pressing a button while the cursor is over an enemy marks it.

**Describe alternatives you've considered**
Allow the player to select and use their own units after selecting an enemy unit. It is already possible to move the cursor after selecting an enemy, but can't select your own unit.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/e71f9d0d-2705-41af-b872-5d8280c2c851)

**Additional context**
Note how the marked unit has an icon that lets the player know they have marked it. This is from one of the newer Fire Emblem games, and I find it incredibly useful when playing.
![show](https://github.com/Robosturm/Commander_Wars/assets/142738275/87cacc9c-17b0-4ee1-ac22-a39321cb42a6)

**Comment by Robosturm** [comment]
There won't be marking for now.
But the game already has two keys while you have a unit selected you can press 1 to see indirect units range near that unit and 2 for seeing all units firerange close to that unit.
There won't be such a thing like a global range due to the unit and map size difference compared to an fe game
