### ISSUE TITLE
Map Editor: Placing Bridges to Replace Bridges

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1681]
**Is your feature request related to a problem? Please describe.**
It is not possible to replace ship bridges / bridges with another type of bridge, so you have to place water then put down another bridge. I understand the bridges work differently than other tiles, so I don't know how difficult this would be to implement.

**Describe the solution you'd like**
Allow the player to use the place or fill tool to place bridges of one kind over another kind. The addition of this feature isn't too important to me, but it would be nice to have.

**Additional context**
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/f36416d6-a38d-4146-8f03-fd86d270319f)

**Comment by FruityGumGuiltyFruit** [comment]
Update and Bug:
It appears that ship bridges can already be placed over ship bridges, but doing so resets the river. Some of them also appear to possibly be desert rivers. 

![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/41db00f7-f7df-4757-931c-53ae0420cd3a)

**Comment by Robosturm** [comment]
Since the base game is treated as a mod as well. 
Aka the game has no real knowledge of bridges or forest etc. THis isn't really doable / won't be changed since it goes against a major design decision
