### ISSUE TITLE
Loading a save can mess up script

### ISSUE THREAD

**Issue by BCG-Jackson** [Robosturm/Commander_Wars#1685]
**Describe the bug**
There is a bug on the map Take and Hold from the Commander Wars campaign. On turn 11 after enemy reinforcements show up, if you then load the latest auto save, they don't show up on time again. This happened while i was trying to save scum because my units were way out of position but as I prepared for them after loading the save they never arrived. But destroying the megatank on the left ended the mission.

**To Reproduce**
1. Go to Take and Hold from the Commander Wars campaign
2. Wait for enemy reinforcements to arrive after turn 11
4. Load an auto save
5. They don't show up

**Expected behavior**
Scripted events happen on time after loading a save.

**Desktop**
 - OS: Windows
 - Version 10
 - Game Version 0.33.1

**Additional context**

**Comment by BCG-Jackson** [comment]
As a side note I LOVE this project. I just played through the campaigns of the new advance wars for switch and its a joke for $60, meanwhile this project offers unlimited content, so many more units, buildings, campaigns, and map editor functions. Its a dream come true from my DS days. I'm working on a new campaign. Its so fun to use the map editor. I wish I could contribute to the source code but its a lot

**Comment by Robosturm** [comment]
All fine. I know it's a lot of code. Though depending on what you want to work on you don't need to know all the code.
