### ISSUE TITLE
Mini Co facing

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1688]
I think all of the new mini co's face the opposite direction of attacking units.

![image](https://github.com/Robosturm/Commander_Wars/assets/75344715/8cf52d52-9efb-4637-bb9b-055482292e35)

![image](https://github.com/Robosturm/Commander_Wars/assets/75344715/2f7abf9c-3c8d-443e-850f-f1fcb30e8a3f)

![image](https://github.com/Robosturm/Commander_Wars/assets/75344715/d9da9dfd-ca46-4288-bd6e-446ca9cc37f5)

**Comment by FruityGumGuiltyFruit** [comment]
I can confirm. 
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/9fcff798-c5f2-4a2f-acf3-6da9df37f157)

**Comment by FruityGumGuiltyFruit** [comment]
I fixed the issue by flipping the images to match the proper direction. I only did the ones that are located in version 33.
[Fixed Minis.zip](https://github.com/Robosturm/Commander_Wars/files/12602258/Fixed.Minis.zip)
