### ISSUE TITLE
mini co images pt 2

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1689]
see attached for the remaining mini co's,

[cow minis part 1 and 2.zip](https://github.com/Robosturm/Commander_Wars/files/12601374/cow.minis.part.1.and.2.zip)

**Comment by FruityGumGuiltyFruit** [comment]
I fixed these as well. [Fixed Minis 2.zip](https://github.com/Robosturm/Commander_Wars/files/12602297/Fixed.Minis.2.zip)
