### ISSUE TITLE
An "Any" player trigger for player specific conditions

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#169]
At the moment, if you want an event to occur if a player triggers an area with a unit, you can only specify one player. If you group the event to include more players, then each one of those players must have a unit in the trigger zone to trigger the event. And if you create a separate condition for each of the players, then you end up allowing the event to occurring multiple times. Perhaps a Any player option to choose when selecting the players or a method to include multiple players in one condition.

**Comment by Robosturm** [comment]
Extended the player reached option to select multiple players
