### ISSUE TITLE
Request: Display both players data on the screen

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1693]
**Is your feature request related to a problem? Please describe.**
Currently, the interface shows the information of the player, when it's that player's turn. However, one needs to for turn to be passed, to the opponent, to see information such as the army value, the number of units and the number of capture properties

**Describe the solution you'd like**
Displaying more information, primarily the army value, unit numbers and owned properties, below the CO interface, perhaps by taking inspiration from AWBW's. This would make it friendlier for streams, be it on discord or youtube.

![Screenshot from 2023-09-15 23-10-00](https://github.com/Robosturm/Commander_Wars/assets/96459683/f5a9be72-c35d-45de-84cd-3b1f39cb8150)

**Comment by Robosturm** [comment]
Note: The feature only works with larger screens if you have a small screen resolution the feature won't be active.
The amount of players depends on the screen resolution.
