### ISSUE TITLE
Reloading a multiplayer msav file, blocks the second player from loading the lobby screen

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1696]
**Describe the bug**
In version 33.2-debug, when a multiplayer game is loaded through an msav file, the second player is not allowed to rejoin, instead, they get an error message, stating the user is already in the game as shown in the screenshot.

![image (1)](https://github.com/Robosturm/Commander_Wars/assets/96459683/a537478a-1368-43de-98e8-2ba235d81f73)

If the second player, changes his username however, the lobby window loads as normal. 

**To Reproduce**
1. Load an msav on the multiplayer 
2. Make the second player join
3. See error

**Expected behavior**
The game should let the player enter the lobby, to continue the match with the msav file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.33.2-debug
 - Active Mods (Note: none vanilla mod problems want be investigated)
 - Game Version 0.33.2-debug

**Comment by Robosturm** [comment]
#1677
