### ISSUE TITLE
Game randomly crashes during multiplayer matches (0.33.2-debug version)

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1697]
I was playing multiplayer matches today with Namelessone, using the debug build (0.33.2-debug), and our games would keep crashing randomly. It happened to both of us, typically when we were moving a unit, or attacking. One player would crash, and the other would stay in the game (receiving a message about the other player disconnecting).

Sadly, there's no error message or console log as the game just abruptly closes itself, so you'll have to try to reproduce it...
We made sure it wasn't a mod issue either. Tested a basic PvP match on Caustic Finale _without_ any mods enabled, our COs were Max and Andy.

**Comment by Robosturm** [comment]
Please provide a savegame or log from when it happened ideally with enabled debug output else the issue is way to dunios to investigate.
The current information isn't enough to investigate into the issue.

**Comment by XnKradst** [comment]
As I said, there's no log, but luckily we do have a save due to autosave. I checked if there was a record but couldn't find one either.

Here you go:
[Caustic Finale_autosave_3.zip](https://github.com/Robosturm/Commander_Wars/files/12720702/Caustic.Finale_autosave_3.zip)
(It's a zip file because Github doesn't let me upload an msav directly.)

Also, upon further investigation, it seems to happen randomly, and not _only_ in multiplayer. I left an offline 1v1 match between two AI players running in the background, and I noticed the window eventually closed itself, so I would assume the game crashed at some point during the match.
You can probably try that too and see what happens.

**Comment by XnKradst** [comment]
Forgot to mention yesterday, I did one more AI vs AI offline test, and remembered to enable the record game feature this time.
Unfortunately, it seems like even the recording is bugged (possibly due to the crash), but you can take a look if it helps.
[Bean Island-25-09-2023-20-55-33.zip](https://github.com/Robosturm/Commander_Wars/files/12733344/Bean.Island-25-09-2023-20-55-33.zip)
There's no autosave for this as autosaves only happen during a human player's turn.

One thing I'd like to note is that the crash usually happens when the window is in focus. This match managed to last for several turns, but once I open the window, it crashed.
(Although I've seen it crash in the background too.)

**Comment by Robosturm** [comment]
So i found two bugs which lead to crash but only when starting a game. 
However i added a lot of debug tracing and changed one thing which is fine from my code side but might be a bug in qt.
However i can't reproduce it the crashes i found so far happen only at the start of match and not during one.
@XnKradst Could you mute all music and sounds in the options and do the test again? My guess is that the release version of qt crashes when creating and destroying sounds and ultimately crash the game. Muting the game stops that from happening and might be the reason for the crash

**Comment by Robosturm** [comment]
Nevermind i found an array out of bounds bug....

**Comment by XnKradst** [comment]
I see, so it has been fixed?
Anyway, if it helps, I still tested what you suggested, and it seems the game doesn't crash as much when all sounds are muted. A long AI vs AI match finished without crashing, and I kept the window focused the whole time.
(However, one time when I tried saving in the middle of the AI vs AI match, it still crashed.)

**Comment by Robosturm** [comment]
There's definetly a bug that crashes the game due to sound effects, which i fixed.
Though i couldn't reproduce any crashes when saving the game.
Could you give me your animation settings? Cause I normally have everything set to high speed during my automated tests.

**Comment by XnKradst** [comment]
Sorry, late response. I just tested the build you shared with the same match settings (AI vs AI), but with sounds enabled. Yeah, so far it hasn't crashed. Also tried saving and it didn't crash either.
My usual animation speed is around 20 for everything, and 30 for walk animations.

Seems like the bug has indeed been fixed.
