### ISSUE TITLE
Increased AI Processing Ideas (at the cost of increased CPU/GPU usage)

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#1699]
I've been getting back to this game and doing some more tests. One issue that I found compelling dealt with the AI Player count and Map sizes both really did not like the AI's processing time. Based on the result, increasing the Player count for larger maps multiplies the AI's need for processing for **each individual AI turn**. The same applies vice versa. Even if most of the space isn't used, such as maps with large oceans with no ports/ships/aircraft, the AI will still waste time processing the empty space.

I cannot say for certain how to decrease this speed for this case, as such changes would result in the AI system being overhauled, which I understand is something that could take a long time for little benefit. So instead of this, why not increase the AI's own processing usage?

-- Possible Ideas --

1. Increased AI Scope: Seeing how to map size does contribute, I can only assume that the AI is checking/is being informed by the engine 1 tile at a time. Instead, it can be screened all at once followed with whatever it needs to enact.
2. Multi-Task: Instead of having the AI do one task at a time, such as for building, planning attacks, etc, it should instead try to do all of this at once with individual parts, like building and commands being separate.
3. Pre-Map Instructions: Before the map even starts, or when updates are made through commands, instructions on the map could be provided to the AI on a series of actions.

**Comment by Robosturm** [comment]
I don't want to be offensive bur None of your points show on how

**Comment by HappyPotatoFunTime** [comment]
Makes sense, and no offense added. Was hoping for a solution to laggy larger maps with higher player counts by using a lot of unused processing power that beefier PCs can use.

**Comment by Robosturm** [comment]
Just so you can understand what complexity a TBS game offers the following text is from a Neural Network Paper using an AW like game as base.
Taking three Infantries versus three Infantries (situation in Figure 2) without considering unit interaction as an example, each player has roughly (3!) × 25 × 25 × 25 = 93, 750 moves per turn.
