### ISSUE TITLE
Animation of idle units could be slower

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#17]
**Is your feature request related to a problem? Please describe.**
When ingame, idle units are animated (which I find awesome considering the number of different sprites for each units, both custom and from the original games).
But, animation for the idle units is very fast.
In the original Advance Wars games, the idle animations were far slower, and yet it still made the games felt alive without being cluttered by fidgeting soldiers :)

**Describe the solution you'd like**
Animations for idle units could be 2 times slower.

This is just something that tapped my eyes right off the bat when I first played Commander Wars a few days ago. I figured I'd mention it here!

**Comment by Robosturm** [comment]
Slowed it down by 50% for units and by 100% for buildings.
