### ISSUE TITLE
Suggestion: Confirmation screen when exiting the map editor

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#170]
You know that feel when you exit the map editor only to realize you've completely forgotten to save the map? Yeah, losing all your work can be extremely frustrating. This has happened to me once, and to some of my friends. It's also possible to hit the Esc key accidentally.
I think adding a confirmation screen similar to the screens that appear when you surrender or exit a game will help a lot. Or maybe an autosave feature?

**Comment by Robosturm** [comment]
removed esc key -> was a relic from the initial test versions
added message box
added autosave interval of 1 min to the editor. File will be saved under autosave.map
