### ISSUE TITLE
getDeffensiveReduction affects the player's units instead of the Opponent's

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1700]
**Describe the bug**
Currently, the getDeffensiveReduction function affects the player's units, instead of the Opponent's as the Offensive counterpart does. 

**To Reproduce**

1.  Create a CO and add the getDeffensiveReduction function to it, set it to return a hight value such as 1000. 
2. Try attacking with a unit, while it's present. 
3. See how it affects the attacking unit, rather than the opponent's

**Expected behavior**
The function should be affecting the opponent's units, not the user's

**Screenshots**
Screenshot of the function, returning 100
![Screenshot from 2023-10-08 01-17-22](https://github.com/Robosturm/Commander_Wars/assets/96459683/3dffc51f-e87e-44c9-886d-9bf1f5efc875)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Debian Bullseye
 - Active Mods (Note: none vanilla mod problems want be investigated)
 - Game Version 33, build 2

**Comment by Robosturm** [comment]
It works exactly as it should for CO's like Cairn or Mary which reduce the defense of an enemy when attacking the,m with that player.
Either your pre checks are wrong or going with extreme values leads to underflow issues in the defense calculation.
