### ISSUE TITLE
Provide the unit to weather getVisionrangeModifier

### ISSUE THREAD

**Issue by Brilliand** [Robosturm/Commander_Wars#1709]
I see the function getVisionrangeModifier() for weather types doesn't receive the unit as a parameter, despite modifying the vision range of individual units.  Could that parameter be added?  (I'm trying to make a modded weather type that only reduces the vision of ground units.)

**Comment by Robosturm** [comment]
Also added it to the firerange functions.
Note: the argument order differs from the other ones to be upwards compatible.
