### ISSUE TITLE
Got randomized a CO that was availbe to the game when play someone else's custom map

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#171]
So how I was able to randomize a CO that was active in the game. It just showed up blank during the game, but then crashed at the victory screen. They didn't have any preset COs for the map however, so I'm assuming some how saving the map while they had the COs some how created this issue.
[20200311-032523 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4317306/20200311-032523.Commander.Wars.Crash.log)

**Comment by Robosturm** [comment]
As Quick-Fix you need to check the CO-Bannlist to avoid selection of deleted CO's.
