### ISSUE TITLE
Building style

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1714]
How about we have like a option to choose which building style we get?
Like we could have: default (cow), aw1, aw2, dor and sfw
So uh making the DOR building image mod an option instead of a mod

Basically changing whether a city looks like its from aw1 or other games

**Comment by Robosturm** [comment]
This will never be an option since having it as mod makes 
a) handling it way easier
b) having it as an option doesn't add a real benefit compared to a mod.
Sprite variants will always be a mod and never make it into an option due to the overhead involved in doing so.
