### ISSUE TITLE
Feature request: Self contained replay data

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1715]
**Is your feature request related to a problem? Please describe.**
Currently, a replay depends on the loaded game data, for instance, if a mod is not loaded, the replay won't display properly, stating the game does not have the mods installed.

However, to increase the simplicity, it'd be best to have an option, or even be by default that modded content or configuration specific changes, be loaded into the replay's data, so this replay can be shared to others who do not have the same mods installed, or to increase the user friendliness of the game.

**Describe the solution you'd like**
An option that lets you dump mod data into the replay that is being generated, or this being a default, such that this data can be independent of any game configuration changes.

**Additional context**
Simplifying the sharing of replays could improve how much content of the game is generated. Replays in particular are used often by people who want to showcase COs, and matches between players, so this feature should have a good impact on how many people want to play the game.

**Comment by Robosturm** [comment]
This won't ever happen.
Reasoning:
a) Putting all resources into the mod lets the replay explode in certain situations
b) Handling resources from a replay would lead to hell when it comes to managing them. The beauty of the current system is that it needs no further code or handling compared to a normal game and I don't want that to change
c) While I understand why you wish it. I don't see the big benefit compared to the massive overhead that is required to achieve it.
d) Replays are not designed to be self contained aka they are not a video and I don't want that to change

**Comment by Robosturm** [comment]
On a sidenote the replay does contain the js-code of the game but not the resources aka images, music etc. and those are the real pain and are the reason why you need to enable the given mods of a replay
