### ISSUE TITLE
Famicom Wars palette

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1716]
Why not? A palette of the colours from NES Famicom wars
![Famicom_Wars_map_16](https://github.com/Robosturm/Commander_Wars/assets/93048095/cdb2f01a-9afa-4512-8f19-9cb46e580179)

**Comment by Robosturm** [comment]
I'm not a fan of those retro palettes and I'm not creating any palettes. However a good one gets provided. I can add it

**Comment by FruityGumGuiltyFruit** [comment]
I could try to make that, but I would have to familiarize myself with how palettes work before I am able to do that.
