### ISSUE TITLE
Sophie's Superpower causes her indirect attacks to be counter-attacked by direct units

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#172]
The animations don't play, but after the indirect attack on a direct unit, the unit will show to have taken damage as if they had attacked the unit from direct range.

**Comment by Robosturm** [comment]
Pffff.
Again this bug affects a couple of CO's:
Adam, Conrad, Graves, Mary, Minamotot, Nana, Roboandy, Sabaki, Sanjuro, Sasha, Smitan and Sophie
