### ISSUE TITLE
Forest palette bug

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1722]
When placing down the DS forest tile on a plains tile it will change the plains palette from Default to presumably Clear AWDS.

**Comment by FruityGumGuiltyFruit** [comment]
This is intentional behaviour. When placing a forest onto itself, the terrain gains the pallet of the game that forest tile is from.

**Comment by Jocrr** [comment]
Might as well change it then. It's rather annoying

**Comment by FruityGumGuiltyFruit** [comment]
> Might as well change it then. It's rather annoying

If you find it bothersome, you can use the "Mass edit terrain" tool, found in "Commands" to fix the forest tile palettes when you are finished making your map. It should fix it, though the game will be confused and claim the default palette terrain to be AWDS clear, even if it is not.
