### ISSUE TITLE
[Bug] ZoomModifier exception

### ISSUE THREAD

**Issue by DraLUSAD** [Robosturm/Commander_Wars#1723]
**Describe the bug**
Prolonged game play leads to cursor sound effects to break, making awful noises, and eventually, leading to a crash

![Screenshot 2023-12-24 144941](https://github.com/Robosturm/Commander_Wars/assets/57923958/f58887cf-e789-44b3-9664-314157e81722)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Active Mods (None)
 - Game Version [0.34.0-debug?]

**Additional context**
Previous version before update was working fine, this recent patch is killing me.

**Comment by Robosturm** [comment]
How is the crash description with the sound? Since you're metioning zoom modifier which is unrelated to sounds

**Comment by DraLUSAD** [comment]
Ahh, I've worded it wrong, seems like the issues I'm having are in two parts, the major one is the crash I keep getting with the ini file, not sure why I'm getting this problem, I've not even tampered with it, I even downloaded a fresh copy and just ran it as it is, but still kept getting this Exception error, using a game pad (albeit poorly optimised) seems to work fine, but with mouse controls it eventually crashes, not sure if it would just be me though

**Comment by Robosturm** [comment]
The ini file part isn't causing the crash or anything. It just resets the zoom level to 2 if the value is 2 because a check is wrong but that's not causing any further issues.

Do you know what you did before the crash happens?
