### ISSUE TITLE
Keep Getting Bugs Like This

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1729]
Commander Wars v0.34.2-main Builddate: Dec 27 2023 22:45:24
29 Dec 2023 @ 17:00:54

EXCEPTION_ACCESS_VIOLATION

[0] 0x0000000000000000 ?? ??:0
[1] 0x00007ff7a4f05171 ?? ??:0
[2] 0x00007ff7a4f05171 ?? ??:0
[3] 0x00007ff7a4f05171 ?? ??:0
[4] 0x00007ff7a4efb8da ?? ??:0
[5] 0x00007ff7a4f013bc ?? ??:0
[6] 0x00007ffd9a86bd90 ?? ??:0
[7] 0x00007ffd98a451d6 ?? ??:0
[8] 0x00007ffd99bea5e8 ?? ??:0
[9] 0x00007ffd9a8250e4 ?? ??:0
[10] 0x00007ffd9a86de7b ?? ??:0
[11] 0x00007ffd99d75648 ?? ??:0
[12] 0x00007ffd9ab4a3e5 ?? ??:0
[13] 0x00007ffd99bf4d64 ?? ??:0
[14] 0x00007ffd99bf31a9 ?? ??:0
[15] 0x00007ff7a4f29812 ?? ??:0
[16] 0x00007ff7a5791c92 ?? ??:0
[17] 0x00007ff7a4ea1395 ?? ??:0
[18] 0x00007ff7a4ea14c6 ?? ??:0
[19] 0x00007ffe141d257d ?? ??:0
[20] 0x00007ffe1550aa58 ?? ??:0

INFO: 29.12.2023 17:00:29: Started with: C:\Users\camer\Downloads\Commander_Wars_Win10_x64 (3)\Commander_Wars_Release\Commander_Wars.exe
INFO: 29.12.2023 17:00:29: Enter "help()" for console info.
INFO: 29.12.2023 17:00:29: Starting Game...
INFO: 29.12.2023 17:00:29: Prepare to Fight...
INFO: 29.12.2023 17:00:29: Read this message while waiting...
INFO: 29.12.2023 17:00:29: 
INFO: 29.12.2023 17:00:29: There are two major products that come out of Berkeley: LSD and UNIX. We don't believe this to be a coincidence.
INFO: 29.12.2023 17:00:29:

**Comment by Rephath** [comment]
I was getting it using a mod, so I deactivated the mod. Having problems in vanilla still.

**Comment by Robosturm** [comment]
Without further information on what you do e.g. menu you use etc. or the game e.g. the ai did.
I can't fix it.

**Comment by junky4040** [comment]
I've been getting the same error message and crashing since v0.34 though recent updates have made it less common. I cant tell what exactly triggers it. So far it seems kind of random. It only occurs when I give a unit a move or attack order on my turn. It may be related to the movement animations for units, but I find that it takes awhile to trigger the crash; about 10-20 minutes (or a few long turns) after I load a map. I'll add more details if I notice something else. I am on Windows 10 and am using all the default settings for the latest version if that helps.

**Comment by Rephath** [comment]
I could repeat all of that word for word in my experience.  Random, my turn, 10-20 minutes into game, Windows, default settings. Changing up unit animations doesn't seem to do anything to the problem.

**Comment by junky4040** [comment]
I think I got it. I timed it out and it looks like the game crashes when the autosave is triggered. Happened exactly 10 min after i loaded up the map, and my autosave timer was also set to ten minutes. I don't know if the crash is an issue with the autosave function itself or if its because I'm doing stuff while the game is trying to autosave. Gonna try a match without autosave and/or try remaining idle while the save finishes and see if anything changes.

**Comment by Rephath** [comment]
Woot! Test away!

**Comment by junky4040** [comment]
Ok it is 100% a problem with the autosaves. If I change the save frequency, the crashes always match the new timing. The crashes also seem to occur only while I'm playing/moving around when the save triggers. If I go afk and just let the game sit, it goes on without issue.

**Comment by Rephath** [comment]
It also triggers after manual saves.

**Comment by Jocrr** [comment]
[Commander_Wars.zip](https://github.com/Robosturm/Commander_Wars/files/13801786/Commander_Wars.zip)
Here's my ini file, i have the same problems
My os is win10 and i'm using the latest CoW version

**Comment by Robosturm** [comment]
@Jocrr  @Rephath @junky4040 Can one of you use the build here https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_34_2_Build2
And post the crash report here if the crash happens?
It should include the call stack aka what the game did right before it crashed....
Since I wasn't able to reproduce it and the things I changed are more I jope it fixes it changes.....
Thx.

**Comment by Latiafa** [comment]
still crashing on 34.3...

here's che crashlog:

Commander Wars v0.34.3-main Builddate: Dec 31 2023 22:02:33
01 Jan 2024 @ 17:35:56

EXCEPTION_ACCESS_VIOLATION

Failed error: 126
Frame : 0 PC address: 0x0000000000000000 Stack address: 0x000000f0a2dfb608 Frame address:  0x000000f0a2dfb600 Symbol name: Unknown
Frame : 1 PC address: 0x00007ff6af4b5261 Stack address: 0x000000f0a2dfb610 Frame address:  0x000000f0a2dfb6d0 Symbol name: handleEventImpl
Frame : 2 PC address: 0x00007ff6af4b5261 Stack address: 0x000000f0a2dfb6e0 Frame address:  0x000000f0a2dfb7a0 Symbol name: handleEventImpl
Frame : 3 PC address: 0x00007ff6af4b5261 Stack address: 0x000000f0a2dfb7b0 Frame address:  0x000000f0a2dfb870 Symbol name: handleEventImpl
Frame : 4 PC address: 0x00007ff6af4ab9ca Stack address: 0x000000f0a2dfb880 Frame address:  0x000000f0a2dfb920 Symbol name: sendPointerMotionEvent
Frame : 5 PC address: 0x00007ff6af4b14ac Stack address: 0x000000f0a2dfb930 Frame address:  0x000000f0a2dfb9a0 Symbol name: mouseMoveEvent
Frame : 6 PC address: 0x00007ff9df41bd90 Stack address: 0x000000f0a2dfb9b0 Frame address:  0x000000f0a2dfba90 Symbol name: ZN7QWindow5eventEP6QEvent
Frame : 7 PC address: 0x00007ff9de1951d6 Stack address: 0x000000f0a2dfbaa0 Frame address:  0x000000f0a2dfbae0 Symbol name: ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
Frame : 8 PC address: 0x00007ff9ded7a5e8 Stack address: 0x000000f0a2dfbaf0 Frame address:  0x000000f0a2dfbb70 Symbol name: ZN16QCoreApplication20sendSpontaneousEventEP7QObjectP6QEvent
Frame : 9 PC address: 0x00007ff9df3d50e4 Stack address: 0x000000f0a2dfbb80 Frame address:  0x000000f0a2dfbe60 Symbol name: ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE
Frame : 10 PC address: 0x00007ff9df41de7b Stack address: 0x000000f0a2dfbe70 Frame address:  0x000000f0a2dfbed0 Symbol name: ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 11 PC address: 0x00007ff9def05648 Stack address: 0x000000f0a2dfbee0 Frame address:  0x000000f0a2dff040 Symbol name: ZN21QEventDispatcherWin3213processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 12 PC address: 0x00007ff9df6fa3e5 Stack address: 0x000000f0a2dff050 Frame address:  0x000000f0a2dff080 Symbol name: ZN26QWindowsGuiEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 13 PC address: 0x00007ff9ded84d64 Stack address: 0x000000f0a2dff090 Frame address:  0x000000f0a2dff120 Symbol name: ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
Frame : 14 PC address: 0x00007ff9ded831a9 Stack address: 0x000000f0a2dff130 Frame address:  0x000000f0a2dff180 Symbol name: ZN16QCoreApplication4execEv
Frame : 15 PC address: 0x00007ff6af4d9902 Stack address: 0x000000f0a2dff190 Frame address:  0x000000f0a2dff6d0 Symbol name: qMain
Frame : 16 PC address: 0x00007ff6afd444d2 Stack address: 0x000000f0a2dff6e0 Frame address:  0x000000f0a2dff760 Symbol name: qtEntryPoint
Frame : 17 PC address: 0x00007ff6af451395 Stack address: 0x000000f0a2dff770 Frame address:  0x000000f0a2dff830 Symbol name: public_all
Frame : 18 PC address: 0x00007ff6af4514c6 Stack address: 0x000000f0a2dff840 Frame address:  0x000000f0a2dff860 Symbol name: public_all
Frame : 19 PC address: 0x00007ffa5f777344 Stack address: 0x000000f0a2dff870 Frame address:  0x000000f0a2dff890 Symbol name: BaseThreadInitThunk
Frame : 20 PC address: 0x00007ffa5ffa26b1 Stack address: 0x000000f0a2dff8a0 Frame address:  0x000000f0a2dff910 Symbol name: RtlUserThreadStart

CRITICAL: 01.01.2024 17:32:41: Unable to locate sound: button.wav
INFO: 01.01.2024 17:32:48: Started with: C:\Users\Laty\Downloads\Commander_Wars_Win10_x64\Commander_Wars_Release\Commander_Wars.exe
INFO: 01.01.2024 17:32:48: Enter "help()" for console info.
INFO: 01.01.2024 17:32:48: Starting Game...
INFO: 01.01.2024 17:32:48: Prepare to Fight...
INFO: 01.01.2024 17:32:48: Read this message while waiting...
INFO: 01.01.2024 17:32:48: 
INFO: 01.01.2024 17:32:48: It should be fair. God go away with your human feelings. It's of course unfair.
INFO: 01.01.2024 17:32:48:

**Comment by junky4040** [comment]
Still crashing as well on the linked build, though not on every autosave now. Got a good 10 minutes in before a crash with my save timer set to one minute. Here's the crash report:

**Comment by junky4040** [comment]
Failed error: 126
Frame : 0 PC address: 0x0000000000000000 Stack address: 0x000000accf3fb7f8 Frame address:  0x000000accf3fb7f0 Symbol name: Unknown
Frame : 1 PC address: 0x00007ff72f3e5261 Stack address: 0x000000accf3fb800 Frame address:  0x000000accf3fb8c0 Symbol name: handleEventImpl
Frame : 2 PC address: 0x00007ff72f3e5261 Stack address: 0x000000accf3fb8d0 Frame address:  0x000000accf3fb990 Symbol name: handleEventImpl
Frame : 3 PC address: 0x00007ff72f3e5261 Stack address: 0x000000accf3fb9a0 Frame address:  0x000000accf3fba60 Symbol name: handleEventImpl
Frame : 4 PC address: 0x00007ff72f3db9ca Stack address: 0x000000accf3fba70 Frame address:  0x000000accf3fbb10 Symbol name: sendPointerMotionEvent
Frame : 5 PC address: 0x00007ff72f3e14ac Stack address: 0x000000accf3fbb20 Frame address:  0x000000accf3fbb90 Symbol name: mouseMoveEvent
Frame : 6 PC address: 0x00007ffc8e81bd90 Stack address: 0x000000accf3fbba0 Frame address:  0x000000accf3fbc80 Symbol name: ZN7QWindow5eventEP6QEvent
Frame : 7 PC address: 0x00007ffc8e0f51d6 Stack address: 0x000000accf3fbc90 Frame address:  0x000000accf3fbcd0 Symbol name: ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
Frame : 8 PC address: 0x00007ffc8f14a5e8 Stack address: 0x000000accf3fbce0 Frame address:  0x000000accf3fbd60 Symbol name: ZN16QCoreApplication20sendSpontaneousEventEP7QObjectP6QEvent
Frame : 9 PC address: 0x00007ffc8e7d50e4 Stack address: 0x000000accf3fbd70 Frame address:  0x000000accf3fc050 Symbol name: ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE
Frame : 10 PC address: 0x00007ffc8e81de7b Stack address: 0x000000accf3fc060 Frame address:  0x000000accf3fc0c0 Symbol name: ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 11 PC address: 0x00007ffc8f2d5648 Stack address: 0x000000accf3fc0d0 Frame address:  0x000000accf3ff230 Symbol name: ZN21QEventDispatcherWin3213processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 12 PC address: 0x00007ffc8eafa3e5 Stack address: 0x000000accf3ff240 Frame address:  0x000000accf3ff270 Symbol name: ZN26QWindowsGuiEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 13 PC address: 0x00007ffc8f154d64 Stack address: 0x000000accf3ff280 Frame address:  0x000000accf3ff310 Symbol name: ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
Frame : 14 PC address: 0x00007ffc8f1531a9 Stack address: 0x000000accf3ff320 Frame address:  0x000000accf3ff370 Symbol name: ZN16QCoreApplication4execEv
Frame : 15 PC address: 0x00007ff72f409902 Stack address: 0x000000accf3ff380 Frame address:  0x000000accf3ff8c0 Symbol name: qMain
Frame : 16 PC address: 0x00007ff72fc744d2 Stack address: 0x000000accf3ff8d0 Frame address:  0x000000accf3ff950 Symbol name: qtEntryPoint
Frame : 17 PC address: 0x00007ff72f381395 Stack address: 0x000000accf3ff960 Frame address:  0x000000accf3ffa20 Symbol name: public_all
Frame : 18 PC address: 0x00007ff72f3814c6 Stack address: 0x000000accf3ffa30 Frame address:  0x000000accf3ffa50 Symbol name: public_all
Frame : 19 PC address: 0x00007ffccd087344 Stack address: 0x000000accf3ffa60 Frame address:  0x000000accf3ffa80 Symbol name: BaseThreadInitThunk
Frame : 20 PC address: 0x00007ffccdd426b1 Stack address: 0x000000accf3ffa90 Frame address:  0x000000accf3ffb00 Symbol name: RtlUserThreadStart

INFO: 01.01.2024 13:23:28: Downloading new version failed.
INFO: 01.01.2024 13:23:28: Downloading new version failed.
INFO: 01.01.2024 13:23:35: Started with: C:\Users\E B\Desktop\Commander_Wars_Win10_x64\Commander_Wars_Win10_x64\Commander_Wars_Release\Commander_Wars_1.exe
INFO: 01.01.2024 13:23:35: Enter "help()" for console info.
INFO: 01.01.2024 13:23:35: Starting Game...
INFO: 01.01.2024 13:23:35: Prepare to Fight...
INFO: 01.01.2024 13:23:35: Read this message while waiting...
INFO: 01.01.2024 13:23:35: 
INFO: 01.01.2024 13:23:35: Error 404 no game found. Do your homework instead.
INFO: 01.01.2024 13:23:35:

**Comment by junky4040** [comment]
There are some differences and other things to note as well. The crashes are happening on my turn when I make attacks, usually with infantry. Haven't noticed it on other units but I'm also playing Sami so it could be a coincidence. The last couple of crashes happened 10 minutes after starting the map, regardless of the autosave timer so that part may be fixed. I'm still on default settings with a fresh install (minus a few changes to the autosave timer for testing between games).

**Comment by Robosturm** [comment]
@junky4040 @Latiafa Since you two can still crash the game.
I fixed/changed some lines which I believe could cause the crash based on the crash report.
Can you try the build https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_34_3_Build2_TestBuild and see if it still happens.
And report back with either a it works or the crash report again,
Thx

**Comment by junky4040** [comment]
Still crashes, but it happens more frequently with this build. Only a few minutes in on the last few attempts to play. Also, it's crashing straight to desktop, without the crash report appearing at all so I can't post it here. If it helps, each of the last 3 crashes occurred while I was moving the cursor. Sitting idle didn't seem to trigger it and I've had crashes both while giving orders and just looking around the map.

**Comment by Latiafa** [comment]
still crashing, and the campaign map was glitchy too. as usual i've recorded it, will send you the clip in pm on discord.

crash log:

Commander Wars v0.34.3-main Builddate: Jan  1 2024 22:00:58
02 Jan 2024 @ 16:46:52

EXCEPTION_ACCESS_VIOLATION

Failed error: 126
Frame : 0 PC address: 0x0000000000000000 Stack address: 0x0000001b6d5fb548 Frame address:  0x0000001b6d5fb540 Symbol name: Unknown
Frame : 1 PC address: 0x00007ff66c848072 Stack address: 0x0000001b6d5fb550 Frame address:  0x0000001b6d5fb610 Symbol name: handleEventImpl
Frame : 2 PC address: 0x00007ff66c848072 Stack address: 0x0000001b6d5fb620 Frame address:  0x0000001b6d5fb6e0 Symbol name: handleEventImpl
Frame : 3 PC address: 0x00007ff66c848072 Stack address: 0x0000001b6d5fb6f0 Frame address:  0x0000001b6d5fb7b0 Symbol name: handleEventImpl
Frame : 4 PC address: 0x00007ff66c83b9da Stack address: 0x0000001b6d5fb7c0 Frame address:  0x0000001b6d5fb860 Symbol name: sendPointerMotionEvent
Frame : 5 PC address: 0x00007ff66c8414bc Stack address: 0x0000001b6d5fb870 Frame address:  0x0000001b6d5fb8e0 Symbol name: mouseMoveEvent
Frame : 6 PC address: 0x00007ff9de37bd90 Stack address: 0x0000001b6d5fb8f0 Frame address:  0x0000001b6d5fb9d0 Symbol name: ZN7QWindow5eventEP6QEvent
Frame : 7 PC address: 0x00007ff9dd3751d6 Stack address: 0x0000001b6d5fb9e0 Frame address:  0x0000001b6d5fba20 Symbol name: ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
Frame : 8 PC address: 0x00007ff9e78ca5e8 Stack address: 0x0000001b6d5fba30 Frame address:  0x0000001b6d5fbab0 Symbol name: ZN16QCoreApplication20sendSpontaneousEventEP7QObjectP6QEvent
Frame : 9 PC address: 0x00007ff9de3350e4 Stack address: 0x0000001b6d5fbac0 Frame address:  0x0000001b6d5fbda0 Symbol name: ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE
Frame : 10 PC address: 0x00007ff9de37de7b Stack address: 0x0000001b6d5fbdb0 Frame address:  0x0000001b6d5fbe10 Symbol name: ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 11 PC address: 0x00007ff9e7a55648 Stack address: 0x0000001b6d5fbe20 Frame address:  0x0000001b6d5fef80 Symbol name: ZN21QEventDispatcherWin3213processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 12 PC address: 0x00007ff9de65a3e5 Stack address: 0x0000001b6d5fef90 Frame address:  0x0000001b6d5fefc0 Symbol name: ZN26QWindowsGuiEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
Frame : 13 PC address: 0x00007ff9e78d4d64 Stack address: 0x0000001b6d5fefd0 Frame address:  0x0000001b6d5ff060 Symbol name: ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
Frame : 14 PC address: 0x00007ff9e78d31a9 Stack address: 0x0000001b6d5ff070 Frame address:  0x0000001b6d5ff0c0 Symbol name: ZN16QCoreApplication4execEv
Frame : 15 PC address: 0x00007ff66c8697b2 Stack address: 0x0000001b6d5ff0d0 Frame address:  0x0000001b6d5ff610 Symbol name: qMain
Frame : 16 PC address: 0x00007ff66d0d5152 Stack address: 0x0000001b6d5ff620 Frame address:  0x0000001b6d5ff6a0 Symbol name: qtEntryPoint
Frame : 17 PC address: 0x00007ff66c7e1395 Stack address: 0x0000001b6d5ff6b0 Frame address:  0x0000001b6d5ff770 Symbol name: public_all
Frame : 18 PC address: 0x00007ff66c7e14c6 Stack address: 0x0000001b6d5ff780 Frame address:  0x0000001b6d5ff7a0 Symbol name: public_all
Frame : 19 PC address: 0x00007ffa5f777344 Stack address: 0x0000001b6d5ff7b0 Frame address:  0x0000001b6d5ff7d0 Symbol name: BaseThreadInitThunk
Frame : 20 PC address: 0x00007ffa5ffa26b1 Stack address: 0x0000001b6d5ff7e0 Frame address:  0x0000001b6d5ff850 Symbol name: RtlUserThreadStart

CRITICAL: 02.01.2024 16:46:33: Unable to locate sound: button.wav
INFO: 02.01.2024 16:46:40: Started with: C:\Users\Laty\Downloads\Commander_Wars_Win10_x64\Commander_Wars_Release\Commander_Wars.exe
INFO: 02.01.2024 16:46:40: Enter "help()" for console info.
INFO: 02.01.2024 16:46:40: Starting Game...
INFO: 02.01.2024 16:46:40: Prepare to Fight...
INFO: 02.01.2024 16:46:40: Read this message while waiting...
INFO: 02.01.2024 16:46:40: 
INFO: 02.01.2024 16:46:40: Eek! A mouse! Plug it out! Eek! It's full of bytes!
INFO: 02.01.2024 16:46:40:

**Comment by Robosturm** [comment]
@Latiafa  @junky4040  Okay one more try.
https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_34_3_Build3_TestBuild
Note: The campaign thing is just a result of the game already being in the process of crashing. :(
I moved the mouse handling to a different thread (Might feel lacky for the moment), now the crash report should either not happen or contain more context.
I lean towards the first.
Once again thx for testing. It's a bit frustrating to not be able to reproduce it on my pc. :(

**Comment by Latiafa** [comment]
just ran an hour and half match in deep forest, no crash at all

**Comment by Robosturm** [comment]
@Latiafa PLease be a bit more specific in which campaign and at what point did it happen?

**Comment by Latiafa** [comment]
advance wars 1 campaign, mission 2, at the start, the map was fully glitched. i can PM you a screenshot on discord if you want

**Comment by junky4040** [comment]
Okay! I too got through an entire match without any crashes on the new build. Seems that bug is squashed! As for the campaign map glitch, I think that may be a separate problem entirely. I had issues with that as well back in v0.34's initial release but didn't make a bug report because I am new to the community and didn't know how. Anyway, advance wars 2 campaign mission 1 also starts glitched for me. Tiles just don't show up properly and units are translucent if you can even manage to find them.

**Comment by Latiafa** [comment]
junky, try to double click on the map, instead of using the next button

**Comment by junky4040** [comment]
Huh, that works! Weird though. Thanks for the heads up.
