### ISSUE TITLE
Trap Function: Trapping Unit

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#173]
Currently, the trap function does not contain anything referring to the trapping unit (the stealthed unit that the moving unit walked into). It would be nice to see the information of the trapping unit added to the Trap function so things can be done involving it, such as:

- Land/Seamine triggering on trap
- Trapping unit automatically attacking the trapped unit
- Trapped unit automatically attacking the trapping unit

**Comment by Everglass** [comment]
Oh! Attacks on traps, that would be a neat inclusion!

**Comment by Robosturm** [comment]
Already possible!
ACTION_TRAP.postAnimationTrapSignX = action.readDataInt32();
ACTION_TRAP.postAnimationTrapSignY = action.readDataInt32();

The X and Y coordinates read from the action are the coordinates of field the stealthed unit
