### ISSUE TITLE
Overlay Palette Bug

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1734]
Manually selected overlays for tiles don't change their palette when changing the palette before starting a new game

For example, using the Edit terrain tool and changing the overlay of a sea tile looks fine
However, when starting a new game and changing the palette from Default to, for example, SFW, the edited overlay still stays in the Default palette

**Comment by Robosturm** [comment]
Note this won't work reto active.
So maps need to be redone with a new release to change it.
Cause the palette is written into the map data which prevents rule palettes to overwrite the palette
