### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1738]
Happened all of a sudden, but some unit movement sounds sounded weird

[20240106-225137 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/13851464/20240106-225137.Commander.Wars.Crash.log)

**Comment by Jocrr** [comment]
Hm, actually, I think it might have something to do with #1737 , that is the battle animation and movement animation played at the same time
It happened also during an AI vs AI turn
Also I had battle animation set to only show my own, so it might have something to do with that

**Comment by Jocrr** [comment]
This may be unrelated to the crash, but I disabled all battle animations and yet I can still hear them.
I can hear like a second of the battle animation, but nothing happens onscreen.

**Comment by Robosturm** [comment]
I hope it got fixed. I wasn't really able to reproduce it....
