### ISSUE TITLE
Script still bugged

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#1743]
#1736 still persists
Here's the stuff I used + log

[console.log](https://github.com/Robosturm/Commander_Wars/files/13855239/console.log)
[test.zip](https://github.com/Robosturm/Commander_Wars/files/13855240/test.zip)

The map "temp" uses the script "h"
The infantry is supposed to cap the lab and then it the infantry should turn into a neotank, but it doesnt

**Comment by Robosturm** [comment]
I have no clue what you want to achieve with this script but whatever it's. I would say you need to handwrite it.
