### ISSUE TITLE
Closed AI is shown as Normal Def. AI instead in the ui

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1745]
I made a map. For some reason, as soon as I start the map, I automatically win. I don't get a chance to play. It has the default victory conditions and it should have the default victory conditions. 
[Clover Fortress.zip](https://github.com/Robosturm/Commander_Wars/files/13862949/Clover.Fortress.zip)

**Comment by Robosturm** [comment]
As mentioned the AI is actually closed which means you have no enemies and as such win immediatly.

**Comment by Rephath** [comment]
Thanks. I tried everything and nothing was working, but that did it.
