### ISSUE TITLE
Play 'unable' sound effect in map editor way less often.

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#1749]
This is a quality of life thing, in my opinion.

When in the map editor, if you try to replace a tile with an already existing tile, it plays the error sound. Okay, fine, I can understand that (though I wish we could turn this off, too). However, if you keep your mouse held down and drag, it keeps playing that sound effect for every tile you get to, and THAT is really annoying.

Ideally, if the error sound has already played, maybe don't play it again until the mouse has been released? This way I can click-and-drag over terrain to change what it is without getting errors for tracing over existing, idetnical terrain.

**Comment by Robosturm** [comment]
Note: None of your suggestions is implementet.
Instead the sound can only be played 5 times at the same time instead of 60 which removes the annoying part
