### ISSUE TITLE
Feature request: GetUnitDamageID() function that can update data from a matching string

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1754]
**Is your feature request related to a problem? Please describe.**
Currently, one can create a custom unit and pass the GetUnitDamageID() to make it match what already exists in the game. However in order to set defense values of a new unit that change even slightly from that, one needs to create a custom CSV table. If a function that could take the parameter of the sting like that function does and then add, substract, multiply or otherwise from such table, it'd be faster to create custom units that are like an existing one, but just increase slightly the defense, making the process much easier.  

**Describe the solution you'd like**
A function that can take the string of an existing unit and manipulate the data, through parameters, or otherwise. 

**Describe alternatives you've considered**
A way to define the defense values, through an array, like when setting the damage output of a custom weapon.

**Comment by Robosturm** [comment]
You can always implement a weapon which returns a value from a differnt weapon and multiply it with that value,
