### ISSUE TITLE
AI Does Not Build Anti-Air

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1757]
**Describe the bug**
I tested the AI on several maps, and it never builds any Anti-Air.

**Screenshots**
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/64f66db4-e1d2-4c3c-94b6-3787f3e7e61a)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Version [22H2]
 - Active Mods (Note: none vanilla mod problems want be investigated)
 - Game Version [e.g. Beta 35]

**Comment by Jocrr** [comment]
Can confirm
