### ISSUE TITLE
Script is messed up

### ISSUE THREAD

**Issue by Rephath** [Robosturm/Commander_Wars#1758]
I made a script and then made some changes and saved them, but when I saved the new changes and then reload the map, it goes with an older version of the script that has the issues. There's a lot of things wrong, but the easy one to tell is in the older version, Will's dialog has the typo "FlotillaAce" when there should be a space between "Flotilla" and "Ace". I fixed that, but while the script editor recognizes the saved changes, the mission runs the older version for some reason. 
[Beady Bayou.zip](https://github.com/Robosturm/Commander_Wars/files/14335075/Beady.Bayou.zip)

I don't know what to do to fix this. But I want the current victory script to run when the player accumulates 250,000 funds, but I don't know how to code that. 

I'd also like an alternate script to run if the player defeats the enemy through conventional means, but again, I can't figure out how to manage that:
Isabella: What just happened?
Will: We beat them.
Isabella: I thought our goal was just to raid for resources. 
Will: Well, I figured if we take over the entire region, we can get all the oil we need. Seemed easier. 
Isabella: I... I guess. That works too.

**Comment by Robosturm** [comment]
1) You probably have two versions of your script and the map links against the wrong one.
2 and 3) I'll add a funds gathered condition and for the 3 you would need a script variable checking wether the funds victory condition was triggered or not.
4) Please make seperate issues for different problems.
Also it's pretty unlikely that the saved scripts don't work but rather that you messed up the linking between maps and scripts.
