### ISSUE TITLE
Auto Tank Cannot Attack Again After Damaging Structure

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1762]
**Describe the bug**
Read title.

**To Reproduce**
1. Play on map with structure.
2. Use CO with auto tank.
3. Attack structure with auto tank.

**Expected behavior**
Auto tank should be able to use its second attack or wait.

**Screenshots**
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/6b27f7d6-fd52-4bcc-a12d-507af19f822e)

**Desktop (please complete the following information):**
OS: [Windows 10 Home]
Version [e.g. 22H2]
Active Mods (Note: none vanilla mod problems want be investigated)
Game Version [e.g. Beta 35]

**Comment by MrDuck557** [comment]
ah heck I'll look into it

**Comment by MrDuck557** [comment]
ACTION_FIRE does not call postBattleActions if a building is attacked
I can try to use postAction instead

**Comment by MrDuck557** [comment]
alright, confirmed
I was about to make a fix, but looks like robosturm was one step ahead of me
