### ISSUE TITLE
Built-in mod to remove AW4 CO D2Ds

### ISSUE THREAD

**Issue by MrDuck557** [Robosturm/Commander_Wars#1763]
**Is your feature request related to a problem? Please describe.**
I've seen the recent changes to CO D2Ds, and I agree with most of them.
But, some AW4 COs (Tabithia, Tasha, Waylon, and Will) got a D2D
I personally thought that the main gimmick of those COs (compared to other, similar COs) was that they had a stronger than average COZ, but no D2D to compensate
They got a D2D, so that's broken
(Beast is an exception due to not actually having an effect in AW4, I'm good with him having a D2D)

**Describe the solution you'd like**
A built-in mod (like the AW1, AW2, AWDS, AWDC mods) to remove the D2Ds (don't include beast). Not hard, just set the D2D values to 0

**Describe alternatives you've considered**
I suppose you could give the rest of the AW4 COs D2Ds to keep parity, but that destroys their identity compared to, say, jess and eagle even harder

**Additional context**
this commit https://github.com/Robosturm/Commander_Wars/commit/d931610e4609935214356b940c20f7323b8db51c

**Comment by Robosturm** [comment]
I won't add any new co mod to the base game in any near or mostlikely later future.

If you don't like the d2d's for those CO's you can easily make a mod that removes those buffs.
