### ISSUE TITLE
Forsythe Buffs

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1764]
**Is your feature request related to a problem? Please describe.**
Forsythe seems somewhat weak after CoW's increase in power.

**Describe the solution you'd like**
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/588840e9-8b52-4081-b613-ad586e8e5b67)
I would like to see all of these increase by 10, but d2d could be 10 or 5.

**Comment by Robosturm** [comment]
You can always easily mod that in yourself but I won't add it to the vanilla game.

**Comment by FruityGumGuiltyFruit** [comment]
OK, thank you.
