### ISSUE TITLE
getFirerangeModifier Affects the Range of Direct-Attack Units, But getMinFirerangeModifier Does Not

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1766]
**Is your feature request related to a problem? Please describe.**
I noticed that getFirerangeModifier can increase or decrease the max range of all units, but getMinFirerangeModifier only increases the minimum range of indirect-attack units.

**Describe the solution you'd like**
Direct-attack attack units should also be effected by getMinFirerangeModifier.

**Additional context**
Here is a CO with the code below.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/e02a58cc-b6e3-4f73-9987-23b251d43b5c)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/7899bce1-4dc8-45aa-b472-97c689dcb558)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/2bccfd35-414d-42c9-88fb-77af40fc9cd6)

    this.getFirerangeModifier = function(co, unit, posX, posY, map)
    {
        if (CO.isActive(co))
        {
            if (co.getPowerMode() === GameEnums.PowerMode_Superpower ||
                    co.getPowerMode() === GameEnums.PowerMode_Tagpower)
            {
                return 3;
            }
            else if (co.getPowerMode() === GameEnums.PowerMode_Power)
            {
                return 2;
            }
            else if (map === null ||
                     (map !== null && map.getGameRules().getCoGlobalD2D()))
            {
                return 1;
            }
        }
        return 0;
    };

    this.getMinFirerangeModifier = function(co, unit, posX, posY, map)
    {
        if (CO.isActive(co))
        {
            if (co.getPowerMode() === GameEnums.PowerMode_Superpower ||
                    co.getPowerMode() === GameEnums.PowerMode_Tagpower)
            {
                return 3;
            }
            else if (co.getPowerMode() === GameEnums.PowerMode_Power)
            {
                return 2;
            }
            else if (map === null ||
                     (map !== null && map.getGameRules().getCoGlobalD2D()))
            {
                return 1;
            }
        }
        return 0;
    };

**Comment by Robosturm** [comment]
You're screenshots don't show that it doesn't work and accprding to the code.
It's not prevented either.
My guess is direct units can always move and fire.
And you're code just gives the infantry move and fire with a 2 range attack which is proably shown by the attack range
