### ISSUE TITLE
Feature request: CO getEnemyMovementpointModifier()

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1769]
Here's a small request. So I noticed getEnemyMovementpointModifier doesn't actually exist as a function for COs, which is a bit surprising since enemy functions for pretty much every other stat have been added a while ago. I understand too many of these functions might affect performance, but this one feels like it should exist.

(I know getMovementcostModifier affects every player, but that affects movement costs, not points. It can be used to simulate -1 movement to enemy players, but COs like Sturm would be immune to it.)

**Comment by FruityGumGuiltyFruit** [comment]
I also would like to see this in the game.
