### ISSUE TITLE
Limited Amount of a Unit

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#177]
Would it be possible to give units 6 optional variables; PlayerLimitedAlive, PlayerLimitedTotal, TeamLimitedAlive, TeamLimitedTotal, WorldLimitedAlive, WorldLimitedTotal.

What these would do is, when the limit is reached, that unittype cannot be built anymore (so if the limit is 2, you can only build 2). LimitedAlive would only consider units of the type that are currently alive (so if the limit is 2, you have 2, then lose 1, you can again build one), while LimitedTotal would mean that if you lose a limited unit you cannot rebuild it.

The Player, Team and World variants each determine what should be looked at to count. If a unit has a player limit, every player can each build up to that limit. If it's a team limit, each team can build up to that limit, etc.

If a unit has, for example, a World Limit of 3 and a Player Limit of 1, it'd mean that 3 of the unit can exist at any given time, but no player can build more than 1 of those 3.

**Comment by Robosturm** [comment]
You can do that already use the building to get the player use the function getUnitCount("UNITID") to get the amount modify the construction list and return it afterwards.
