### ISSUE TITLE
The game freezes on the AI's turn when the "Overworld Animations" gameplay option is disabled.

### ISSUE THREAD

**Issue by StarBright11** [Robosturm/Commander_Wars#1770]
**Describe the bug**
Whenever it becomes the AI's turn in a game, if you have the "Overworld Animations" option disabled in the Gameplay menu, the game freezes after the AI's CO music kicks in.

**To Reproduce**
1. Open the options menu, navigate to Gameplay, and disable the "Overworld Animations" checkbox.
2. Start a New Game with an AI player.
3. Proceed through the game to the AI player's turn.

**Expected behavior**
The AI would take its turn normally.

**Screenshots**
https://i.imgur.com/Gd8uyjj.png

**Desktop (please complete the following information):**
 - Active Mods: RBC themes
 - Game Version 36.1

**Comment by FruityGumGuiltyFruit** [comment]
Can confirm.
