### ISSUE TITLE
AI APCs Should Build Temporary Airports/Harbours if They Have Nothing Else To Do

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1773]
**Is your feature request related to a problem? Please describe.**
The AI might be better if it could use its APCs to build temp airports/harbours. The AI seems to have trouble refueling units.

**Describe the solution you'd like**
If the map has no airports or pre-deployed air units, it shouldn't build temp airports. If the map has no harbours or pre-deployed naval units, it shouldn't build temp harbours.

**Describe alternatives you've considered**
I don't know how difficult this would be to add to the game.

**Comment by Robosturm** [comment]
There are to many issues:
a) APC'S have always something do
b) Building a temp building stops any resupply mechanics
c) Where do build it most likely it will be more annoying to watch.
