### ISSUE TITLE
In-game Stealth (action) wiki entry does not match actual gameplay

### ISSUE THREAD

**Issue by MrDuck557** [Robosturm/Commander_Wars#1774]
**Describe the bug**
This image
![image](https://github.com/Robosturm/Commander_Wars/assets/48808663/ffeae5dd-352e-49b9-85db-a77d8d4efadb)
is wrong
![image](https://github.com/Robosturm/Commander_Wars/assets/48808663/9f923908-0480-4b93-ada9-bfe10d79d898)
![image](https://github.com/Robosturm/Commander_Wars/assets/48808663/7d9f2a2c-afb7-48aa-822d-5165a2e230ec)
![image](https://github.com/Robosturm/Commander_Wars/assets/48808663/e7f4475f-a22e-4ade-8956-d08252950500)

**To Reproduce**
1. Go to wiki
2. Verify that, yes the wiki entry is as in the screenshot
3. Try to shoot a stealthed stealthbomber with an AA or Cruiser or Battlecruiser
4. Verify that, yes, the AA (or Cruiser or Battlecruiser) can indeed shoot the stealth

**Expected behavior**
Wiki says that "All direct units can hit air or ground stealthed units. Naval stealthed units are dived and can only be hit by naval units with a direct weapon."

**Screenshots**
Above

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [I don't know]
 - Active Mods (None that should affect this)
 - Game Version [36.2]

**Additional context**
[Add any other context about the problem here.](https://discord.com/channels/615556870064832533/617768653978337340/1217251735484235806)

**Comment by Brilliand** [comment]
This arose in the context of MrDuck correcting me when I repeated what the in-game wiki says.

The actual behavior seems strange to me, since it's so different from what cart and AWBW do.

**Comment by Robosturm** [comment]
The wiki page is out-datef
