### ISSUE TITLE
AW4 CO Mod Lin's Power Should Only Give Vision and Hiding Place Vision to Ground Units

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1778]
**Describe the bug**
In actual AW4, only Lin's ground units gain the extra vision and ability to see into hiding places.

**To Reproduce**
1. Activate AWDC CO Mod
2. Use Lin's power in fog of war map.
3. See error

**Expected behavior**
Only her ground units should get the extra vision and ability to see into hiding places.

**Screenshots**
![Screenshot 2024-03-26 120636](https://github.com/Robosturm/Commander_Wars/assets/142738275/4d1b670c-e0f6-4132-ba1d-5d3bb57bb09e)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/519942c4-ee6b-455f-9d63-6118c9ba7d1a)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/f9c5ae20-8fcf-41d8-991f-ad5b0c0186ad)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/c7fb96c1-dd0f-4edd-b4ea-0be606b8627e)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/14ef21de-299a-4e2e-9615-483d6a9ba86a)
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/188e5cdd-85d7-4154-9b90-773dc594662b)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Version [22h2]
 - Active Mods (AWDC CO Mod)
 - Game Version [Latest 0.36.2-main]
 
 **Additional Context**
 I don't know how difficult it would be to fix for the vision into hiding places, since I think you need to add a variable to check unit, but `this.getPerfectVision = function(co, map)` doesn't have support for unit.
`var seaAirUnit = (unit.getUnitType() === GameEnums.UnitType_Air) ||
                         (unit.getUnitType() === GameEnums.UnitType_Naval);`
                         
                         
`if (!seaAirUnit)
{
       return true;
}`

**Comment by Robosturm** [comment]
Perfect vision won't be changed/fixed.

**Comment by MrDuck557** [comment]
Just going to throw this out there.
Lin's power descriptions should be changed to reflect this change
This is what they are right now (for both COP and SCOP):
`Lin's ground units gain +%2% firepower and +%2% defence. Her other units gain +%3% firepower and +%4% defence. All of her units gain +%0 vision and can see into hidden locations.`
This is what they should be (to reflect this change)
`Lin's ground units gain +%2% firepower, +%2% defence, and +%0 vision. Her other units gain +%3% firepower and +%4% defence. All of her units can see into hidden locations.`
