### ISSUE TITLE
A save match replay option for recording matches.

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#178]
It'd be a cool feature to have a match be recorded and savable so you can go review a match after it's done to see what you could have done better.

**Comment by Robosturm** [comment]
Already on the todo list. Under the point if i'm bored xD Cause it's a lot of work...

**Comment by Everglass** [comment]
Yeah, I can imagine. XD You'd probably need a place to where you could watch the replays too.
