### ISSUE TITLE
Request: getEnemyRepairBonus() function

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1787]
Currently there is no way to change the enemy repair bonus. Ideally a function to manipulate these values would be best. The mechanism would change the amount of HP enemy units heal from allied buildings.

**Comment by MrDuck557** [comment]
https://github.com/Robosturm/Commander_Wars/blob/master/resources/scripts/general/co.js#L156

**Comment by Robosturm** [comment]
See linked function
