### ISSUE TITLE
In Fog of War, AI Enemy's Submarine Dive/Undive Sprite is Visible to Player When Outside Player's Vision

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1789]
**Describe the bug**
When playing Fog of War against an AI, you can see the dive/undive sprite of enemy submarines when they are outside your vision.
https://github.com/Robosturm/Commander_Wars/blob/master/resources/images/animations/undive.png
https://github.com/Robosturm/Commander_Wars/blob/master/resources/images/animations/dive.png

**To Reproduce**
1. Start a Fog of War match against an AI, that has submarines or harbours.
2. Play until AI dives/surfaces submarine outside vision
3. See error

**Expected behavior**
This sprite should not be visible to the player if the submarine is outside the player's vision. They player can still listen for the noise to know if a submarine is diving/surfacing, but now they won't know the exact location of the submarine.

**Screenshots**
![submarine](https://github.com/Robosturm/Commander_Wars/assets/142738275/5b727e6c-e5ea-4c6d-94ab-18e5bdc1c20b)

Here is the test map design I used. It is 10x10.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/9218e257-36f8-4104-8597-6edbd5a476c0)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Version [22h2]
 - Active Mods [None]
 - Game Version [Beta 0.36.3-main]

**Comment by Robosturm** [comment]
#1793
