### ISSUE TITLE
In Fog of War, AI Enemy's Black Boat Repair Sprite is Visible to Player When Outside Player's Vision

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1790]
**Describe the bug**
When playing Fog of War against an AI, you can see the "Repair" sprite of enemy black boats when they are outside your vision. This might also happen with repair tanks.

**To Reproduce**
1. Start a Fog of War match against an AI, that has black boats or repair tanks.
2. Play until AI uses black boat or repair tank repair outside vision
3. See error

**Expected behavior**
This sprite should not be visible to the player if the repair is outside the player's vision. They player can still listen for the noise to know if a unit is repaired by black boat or repair tank, but now they won't know the exact location of the repair.

**Screenshots**
Happens too quickly for me to get a screenshot.

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Version [22h2]
 - Active Mods [None]
 - Game Version [Beta 0.63.3-main]

**Additional context**
I reused the map from the submarine issue, but added the problem units.

**Comment by Robosturm** [comment]
#1793
