### ISSUE TITLE
Editing Campaign in map editor give you blank/no map name

### ISSUE THREAD

**Issue by Knightlord07** [Robosturm/Commander_Wars#1797]
**Describe the bug**
I found this bug when I was editing my campaign some of my custom made map give me the blank/no name showing up my screen

**To Reproduce**
1. Go to 'Map editor'
2. Click on 'Map editor menu & click on edit campaign'
3. Click on 'Add map from your custom map you made'
4. See error no custom map name you made, it completely blank

**Expected behavior**
The custom map need to show on the editing campaign screen

**Screenshots**
![screenshot+1](https://github.com/Robosturm/Commander_Wars/assets/169057076/50e1ab41-3c13-4992-aefe-d438f35d04c7)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [e.g. 22h2]
 - Active Mods (None)
 - Game Version [e.g. Beta 36.4 main]

**Additional context**

Also I found this when I was editing my JSM file ￿￿￿﫻ﳽ﻿￿￿￿
![Proof](https://github.com/Robosturm/Commander_Wars/assets/169057076/f918e520-a833-416d-9923-1ca150168717)

**Comment by Robosturm** [comment]
Not reproducable on my end.
Without an example I can't fix it.

**Comment by Knightlord07** [comment]
![screenshot+3](https://github.com/Robosturm/Commander_Wars/assets/169057076/946c4077-7a6c-454f-9b5e-86a95f2e9af6)
![screenshot+2](https://github.com/Robosturm/Commander_Wars/assets/169057076/4805a199-a251-409a-8f42-f3669382ee0a)
Just an update when I go to enable & disable map when I click one of those box & I done, then I click back to enable or disable map it's show that it's enable or disable all the map in one.
That will show up in custom campaign I working on so it's an issues with editing campaign stuff.
I hope this is enough for an bug fix with editing campaign.

**Comment by Robosturm** [comment]
Not reproducable on my end.
Without an example I can't fix it.
My guess is all issues are related to you entering a buggy map name, but I can't verify it without an example

**Comment by Knightlord07** [comment]
[Bug checking.zip](https://github.com/Robosturm/Commander_Wars/files/15238125/Bug.checking.zip)
Oh just an buggy map name, I think I encounter this bug on version 36.2 Build1 back in March (2 months ago) it's was strange to me since I was thinking if this bug was only the one causing my mod up, I think I was wrong so it's was the game itself, I am not sure if the zip file if you are looking for an example, but I will continue to investigate & grab any example stuff you need, I apologise if I am just wasting your personal time, I know it's hard to do with 1 person (Just similar to you when I making my own mods), but I wish you luck on hotfix in the future.
P.S the zip folder contain an example map & custom campaign if you need to take a look at it.
