### ISSUE TITLE
Water animation doesn't loop correctly

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#18]
**Describe the bug**
Water tiles are animated. More specifically, the light blue lines are animated.
But the animation doesn't loop smoothly and it make the movement of the water feel off, as when the animation is over, the light blue lines jumps instantly from one place to the other.

**To Reproduce**
1. Go to a map with water. See the light blue lines in the water. Animation loops every 0.5 seconds or so.

**Expected behavior**
Water tiles animation should loop smoothly.
A solution could be to add the same sprites after the already existing ones, but in reverse, so that it creates a feeling of go-and-back in the water, like in the official games.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 4

**Comment by Robosturm** [comment]
fixed sea sprite

thx for the report
