### ISSUE TITLE
Feature Request: Moddable Power Quotes

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1801]
**Is your feature request related to a problem? Please describe.**
Currently the game loads a beeping sound when the text from the power quote is being displayed. Ideally would be nice to have a  way to change that to something else, like a wav file, such that audio quotes like in Reboot Camp can be loaded

https://www.youtube.com/watch?v=lGPlT69IEmo

This feature  might be difficult to implement so I understand if it gets rejected, but I wanted to open the issue anyway to see if there's one way or another to refactor it in the future. 

**Describe the solution you'd like**
A  function that lets the modders override the  sound file that plays when the power quote is shown, or a way to override it through the res.xml file of the mod.

**Describe alternatives you've considered**
Perhaps this can be loaded in other ways, other than the power quote itself, but not sure if actually possible with the current functions.

**Comment by Robosturm** [comment]
Adding speach wav is already possible.
Since the creation of the dialog animation as well as the whole power animation are moddable.
I don't think removing the dot sound is necassary / I don't see a use case.

Justcheckthe activatePower function usually the first lines create both animations
