### ISSUE TITLE
Will's Direct-Attack Units Have +10% Firepower Outside of His CO Zone

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1803]
**Describe the bug**
Read title. I don't know if this is an accident or intentional design, because I know you gave a similar boost to tasha/waylon/greyfield. 

**To Reproduce**
1. Check Will's stats. 
2. See error

**Expected behavior**
If this is a mistake, then remove the firepower bonus outside of CO Zone. If it is intentional, then no change is needed.

**Screenshots**
![Screenshot 2024-05-29 123829](https://github.com/Robosturm/Commander_Wars/assets/142738275/48ae207a-7137-40d3-aacf-55f76eea283a)
![Screenshot 2024-05-29 123841](https://github.com/Robosturm/Commander_Wars/assets/142738275/3c6e6232-2367-4acb-a51c-1d5bef36b50d)

**Desktop (please complete the following information):**

    OS: [Windows 10 Home]
    Version [22h2]
    Active Mods (None)
    Game Version [v0.36,4-main]

**Additional context**

**Comment by Robosturm** [comment]
You have the game rule global d2d  active, which has exacatly the effect.

**Comment by FruityGumGuiltyFruit** [comment]
That appears to be true, my apologies.
