### ISSUE TITLE
Attempting to Train using the Train AI Tutorial Breaks.

### ISSUE THREAD

**Issue by RyushoYosei** [Robosturm/Commander_Wars#1805]
**Describe the bug**
Following the "Normal AI training" tutorial, though it might be out dated now.
Breaks and doesn't function.

**To Reproduce**
Follow tutorial, start the exe.

**Expected behavior**
It to run through training, 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 36 4Build1
 - Game Version  36 4Build1

**Additional context**
Info: 10.06.2024 02:26:40: Selecting new co's at random File:  Line: 0 Function: 
Info: 10.06.2024 02:26:40: Preparing next match on core Core0 File:  Line: 0 Function: 
Info: 10.06.2024 02:26:40: Using ai at index 0 for player 0 File:  Line: 0 Function: 
Info: 10.06.2024 02:26:40: Using ai-setting normal.ini for player 0 File:  Line: 0 Function: 
Info: 10.06.2024 02:26:40: Using ai at index 1 for player 1 File:  Line: 0 Function: 
Info: 10.06.2024 02:26:40: Using ai-setting normal1.ini for player 1 File:  Line: 0 Function: 
Critical: 10.06.2024 02:26:40: ReferenceError: mainServer is not defined in File: file:init.js at Line: 182 File:  Line: 0 Function:

**Comment by Robosturm** [comment]
You need the server option to be on / true in the ini.
Else the game can't spawn games on your pc.
