### ISSUE TITLE
Units not using primary weapon after it's secondary weapon ran out of ammo.

### ISSUE THREAD

**Issue by ATNoName** [Robosturm/Commander_Wars#1807]
Some units like tanks and copters prefer to use secondary weapon on units like infantry since it deals more damage. If those unit run out of secondary weapon ammo, then they should use their primary weapon as an alternative. However, it doesn't happen.

Steps:
- Grab a tank or battle copter
- Attack infantry (have 11 on the map) until it runs of ammo on secondary weapon
- On its turn, do a regular attack
- The fire option doesn't show up

**Comment by Robosturm** [comment]
Behaviour is as designed expected primary weapons deal no damage to infantries.
You deserve to get punished for miss management of 10 MG ammo
