### ISSUE TITLE
CO outfit Editing is missing from personal tab

### ISSUE THREAD

**Issue by Knightlord07** [Robosturm/Commander_Wars#1809]
I just notice the CO editing tab is missing in the personal

**To Reproduce**
1. Click on 'Personal tab'
2. See error

**Expected behavior**
It's should show the CO outfit editing tab on the personal stuff

**Screenshots**
![screenshot+0](https://github.com/Robosturm/Commander_Wars/assets/169057076/935fd893-9868-4040-8ee4-fe400a6257b7)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [22h2]
 - Active Mods (None)
 - Game Version [Beta 37]

**Additional context**
Not sure if this a bug or missing feature?

**Comment by FruityGumGuiltyFruit** [comment]
I can confirm this issue.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/5d25a7f5-27c2-4877-8279-f3f75caf9407)
