### ISSUE TITLE
Add Option to Limit Max Funds For Some or All Players

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1813]
**Is your feature request related to a problem? Please describe.**
Some of the AW games have a limit to the amount of funds you can have at once. (99999G, ect). It is good that CoW lets you have way more, but it would be helpful for certain maps or campaigns if there was an option to limit max funds to a specific number.

**Describe the solution you'd like**
Please add an option to the player data that lets the user set a limit for how much funds a player can have at once.
If the player chooses not to type in a number, it will use the CoW default amount.

**Describe alternatives you've considered**
I considered if it should be a gamerule instead, but that would not let you save it to specific maps.
I thought about making it a script, but then you could not use the option with maps that already use scripts of their own.

**Additional context**
The option could be put here, below start funds.
![image](https://github.com/user-attachments/assets/0cdc180c-b2db-40db-b1b6-bb4555fdea8f)
![image](https://github.com/user-attachments/assets/578e068c-e7ec-4000-a897-27a12f25a4f8)
![image](https://github.com/user-attachments/assets/d04fb009-fce1-4a5a-b25f-b01febe851ed)

**Comment by Robosturm** [comment]
CoW is about no limits. This also sounds like a scenario/campaign use case and there you can achieve this via a script.
So I don't see a point in this requesr
