### ISSUE TITLE
A bug with online matches (hosted via Hamachi or Radmin) that have more than 2 players

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#1814]
We were trying to play a PvE match (3v1), and it seems like whenever there are more than 2 players, every other player besides the host can't see each other's turns.

So for example, if player 1 is the host and there are 3 players, player 2 and player 3 can see player 1's turns, but they can't see each other's turns.
On player 2's screen, as soon as the game gets to player 3's turn, it doesn't show any moves player 3 does, and the only way for the game to continue is if player 2 leaves and rejoins after player 3's turn has ended. The same is true on player 3's screen when it's player 2's turns.
Sometimes, either player 2 or player 3's games crash after ending their turns too.

This is what one of the crash logs says:
[crash.txt](https://github.com/user-attachments/files/17178350/crash.txt)

**Comment by TheGoldenGuardian** [comment]
This issue is not exclusive to software like Hamachi/Radmin, it happened when using a friend's computer with proper port forwarding set up. From testing, the issue does not exist prior to 36.0.
