### ISSUE TITLE
Suggestion: Options for when to automatically save a Replay

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#1816]
Right now there is only one option regarding saving a replay. Which is whether to automatically save one or not when you play a match.

The suggestion is to basically add more options to dictate when a match will have a replay automatically saved. 
For example, a replay will only be created automatically after a certain turn number is reached or when the game ends via a victory condition being met or the opponent surrenders, instead of always being created when you boot up a match. 

Of course I'd imagine the replays still saving the whole match when that threshold is met, but this is more so to keep your replays folder from being filled with dull matches that no one did any actions in, that you have only started to begin with to check or see something.

**Comment by Robosturm** [comment]
Due to how replays are connected to savegames.
This is not really doable.
