### ISSUE TITLE
"Suggestion/adding" Nest Laser turret anti clockwise

### ISSUE THREAD

**Issue by Knightlord07** [Robosturm/Commander_Wars#1817]
Would you add this option for the nest laser turret to have an option tab 
![screenshot+0](https://github.com/user-attachments/assets/b58ec8db-a1c4-4792-9495-1abc21e28f52) (This turret doing clockwise one)
it would be nice to have anti clockwise for it, mainly for PVE type or the nest laser starting position on the right side & going toward the end of the left side & back toward the right side or something like that

**Comment by Robosturm** [comment]
This is doable via map scripts but won't be added to the game atm.
Unless someone wants to script it.
