### ISSUE TITLE
Issue: Cannot board CO on Waterplane

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1826]
**Describe the bug**
In vanilla CoW, waterplane cannot board a CO on airport or temp airport.

I am using the latest release of vanilla CoW. I had a CO, gamerules allowed CO boarding, and I had enough funds to board the CO, and the CO was not already boarded on a different unit.

**To Reproduce**
1. Play battle with waterplane on a map with airport / temp airport
2. Try to board CO onto waterplane
3. See error

**Expected behavior**
Please allow the player to board a CO on a waterplane that is on an airport or temp airport. Waterplane is a vehicle, so a CO should be able to ride in it.

**Screenshots**
Waterplane in CoW cannot board CO on airport or temp airport. 
![image](https://github.com/user-attachments/assets/dbc52262-6a03-457e-8008-c985674fa90b)
![image](https://github.com/user-attachments/assets/360b99e6-acce-4354-a144-b1f7e2bc9c0f)

All other air units in CoW can board a CO on airport or temp airport.
![image](https://github.com/user-attachments/assets/78a30fdd-5e80-40a2-bb63-5b4ef18ad69d)
![image](https://github.com/user-attachments/assets/1cd127e6-10d2-4482-9de4-040105a6967a)

All air units in AW4 can board a CO on airport but not on temp airport. In vanilla CoW, it is okay for air units to board CO unit on temp airport.
![image](https://github.com/user-attachments/assets/60704239-952a-4cef-972e-a3be7d12456e)
![image](https://github.com/user-attachments/assets/66714776-d31a-4bf0-a2e8-ab3ef5e1c0fd)

**Desktop (please complete the following information):**
OS: [Windows 10 Home]
Version [22h2]
Active Mods [None]
Game Version [v0.37,2-main]

**Comment by Robosturm** [comment]
CoW is not faithful to AW-DC and only allows CO units to board on buildings that can produce them.
Of course you can change that via modding.
But I'm currently not going to change it since it works as intended
