### ISSUE TITLE
Issue: Duplicate Units Appear In Unit Build Menu

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1827]
**Describe the bug**
When using a black hole factory, nest factory, or any other situation where the build menu shows more than two full pages of units, several units in the list appear twice.
This pollutes the list with duplicate units, making it more confusing to use, and more difficult to find the units you want.

**To Reproduce**
1. Play a map with a factory you can use
2. Open factory's build menu
3. See error

**Expected behavior**
There should be no duplicate units in the list.

**Screenshots**
![image](https://github.com/user-attachments/assets/af1fc38a-839f-4163-b209-76320695785c)
![image](https://github.com/user-attachments/assets/f7d80643-67db-4fce-9386-22f8e9a31cfb)
![image](https://github.com/user-attachments/assets/b08a66fb-1852-4963-acba-777d6f3b813f)
![image](https://github.com/user-attachments/assets/e274da30-4986-49f7-9580-bea721800a2e)
Video example:
https://github.com/user-attachments/assets/4c65b0ec-c4e5-4e8a-b886-de27f26a4325

**Desktop (please complete the following information):**
OS: [Windows 10 Home]
Version [22h2]
Active Mods [None]
Game Version [v0.37,2-main]

**Comment by Robosturm** [comment]
This is an optical illusion and a result of how the scrolling works.
The effect disappears with 3 columns or more.
