### ISSUE TITLE
Is select CO Duplicated Error

### ISSUE THREAD

**Issue by Knightlord07** [Robosturm/Commander_Wars#1830]
**Describe the bug**
I found this bug when I was editing some script & it's give me building capture instead of the is select CO thing

**To Reproduce**
1. Go to 'map editor'
2. Click on 'edit script'
3. Click on 'Is select CO'
4. Select on the one you made from Is select CO & click on duplicate 
5. See error

**Expected behavior**
It's suppose to give you the duplicate of the selected CO but instead it give you building capture for whatever reason?

**Screenshots**
![screenshot+0](https://github.com/user-attachments/assets/c09184e5-bc9a-4460-9b76-0838aa841dca)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [e.g. 22h2]
 - Active Mods (None)
 - Game Version [e.g. Beta 37.2 main]

**Comment by Robosturm** [comment]
Duplicate copies the current selected condition and isn't connected to the drop down menu
