### ISSUE TITLE
getEnemyActionModifierList

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#1832]
Could we get a getEnemyActionModifierList function added to the base game? Right now, we’re working around it by creating wrappers just to hook enemy actions in a standardized way. Having this built-in method would be a big help to modders looking to easily modify enemy unit behaviors without hacks or workarounds.

**Comment by XnKradst** [comment]
This would be nice, and if this is to be added, an enemy equivalent to getCOUnits (the one that adds or removes units from build lists) would also be helpful, since that's essentially the unit version of getActionModifierList.
