### ISSUE TITLE
AI needs to build black boats to resupply naval 

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1835]
**Is your feature request related to a problem? Please describe.**
The AI lets entire fleets of naval units run out of fuel and ammo, because it only builds black boats when it wants to transport infantry.

**Describe the solution you'd like**
Maybe AI should build a black boat once a certain amount of days have passed, like it does with `minApcResupplyDay : 15`, This should probably be done only on maps that use the NavalBattle flag, so they aren't built on maps where naval units don't move much.

**Describe alternatives you've considered**
-none

**Additional context**
-none

**Comment by Robosturm** [comment]
The AI will always suck at resupplying units cause it's way to complicate to calculate how, when etc. to supply units or building a resupply unit. :(
