### ISSUE TITLE
Upgrade ideas to the Map Editor

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#184]
I think that map editor could get some potential with new ideas.

#1 Percent of Sea **(Generate Map)**

At normal it should generate some continents covered by water (with or without beaches) or some cyclade/archipelag for naval fights, but instead it creates... well some land territory after tsunami or some flood (not to mention that option with 100% sea, instead giving pure water, gives only 50% land, 50% sea + beaches)

#2 Custom Template **(Generate Map)**

How about to try make some templates? Modders who have new tiles (not available to vanilla version), could make custom templates where are rails or something custom which they have.

#3 More common constructions types at generating **(Generate Map)**

We've towns, harbours, airports and bases, how about to add Mines, Labs, Oil Rigs? As far as I know they're still useful and are still common in maps..

#4 Percent of captured properties **(Generate Map)**

I know that sounds weird, but how about adding some point with player #2 for example having captured (during map generation) some priorities at start? Like free towns or bases in random places? That could make some good idea for challenge maps..

#5 Option to giving quanity of spawned units (Scripts)

Giving spawned units in scripts is fun, but making few clicks for single unit spawn can be tedious and frustating later. It could be good idea to add "quanity" box to give some number (For example when somebody wants 10 Heavy Tank spawned in random places, without typing them at single)

**Comment by Robosturm** [comment]
Done 1 to 4 in way since you can now create custom map generators moved 5 to an extra issue.

Sidenote for the future: 
Please report multiple points as seperate issues.
Makes it easier for me to split up stuff e.g. point 5 and pont 1 for example is a bug so should be in an different issue as well.
