### ISSUE TITLE
Code leftovers at descriptions

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#188]
![image](https://user-images.githubusercontent.com/59868034/77934801-e3ce9a80-72b0-11ea-82e2-7aebdebd6e11.png)

Well, I think that something was mixed during compiling or something..

This image shows only one of examples.. I found more of them in Buildings section

**Comment by Danmark25** [comment]
[console.log](https://github.com/Robosturm/Commander_Wars/files/4403981/console.log)

I'm sending a console log too

**Comment by Everglass** [comment]
Yeah, it seems the descriptions are all screwy

**Comment by Robosturm** [comment]
Seems there's something completly random happening the complete build is damaged somehow.
Seems to be a major linking error.
Going to update the release as soon as i found the bug and fixed it.
