### ISSUE TITLE
Attacking with stealth bombers sometimes crashes the game

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#190]
[20200330-144207 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4404827/20200330-144207.Commander.Wars.Crash.log)

Sometimes (but not always), attacking with the stealth bomber crashes the game. I don't know why it's happening, but I suspect it has something to do with the battle animation. I noticed the stealth bomber's outline is missing, only its "mask" is visible in the animation sprite. Here's a screenshot:
![stealthbomber](https://user-images.githubusercontent.com/50599768/77950159-1d45dc80-7296-11ea-8069-7f34d07c0876.png)

The sprite looks fine in the info screen though, and I couldn't find anything wrong in the resources folder's files. I know there were changes made to the stealth mechanics, but so far, attacking with submarines hasn't crashed the game.

**Comment by Robosturm** [comment]
Seems there's something completly random happening the complete build is damaged somehow.
Seems to be a major linking error.
Going to update the release as soon as i found the bug and fixed it.
