### ISSUE TITLE
All units can attack stealth units

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#191]
All unit, regardless of unit type or range can attack stealth units.

**Comment by Robosturm** [comment]
Can't confirm that.
Works perfectly for me maybe you have some mods active which deletes overwrites the general/units.js-File?
Checkout the Console as well.

**Comment by Robosturm** [comment]
Seems there's something completly random happening the complete build is damaged somehow.
Seems to be a major linking error.
