### ISSUE TITLE
Occasionally, Unit's won't perform a countattck attack

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#193]
Sometimes, the counter attack of a unit is ignored. Though the instances of seeing this happen has only been during play tests of Socracle's, Fairy's and my mod. Some further testing with mod turned off is required.

**Comment by Robosturm** [comment]
As long as something happens with mods active that aren't in the base game.
I'm not giving any support. Simply to much effort for me/ i don't have the time to do so. Sry for that.

If you can confirm that the bug happens in the base game and give me some more details on when it happened. I try to fix it. 
Until then i take the issue as invalid.

**Comment by Robosturm** [comment]
Just one think came to my mind.
Some CO's e.g Sabaki, Sophie, Napoleon can block stop counter attacks/ the result may look the same.

**Comment by Everglass** [comment]
Going to playing some games with no mod and see if it ever occurs, I'll update you if I find anything.
