### ISSUE TITLE
Selling unit would give a refund

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#196]
I understand that "delele unit" works like safe option to avoid an incoming frag made by enemy, but there is a case, where "delete unit" would be helpful..

**In case of missclick and buying something that is useless by accident**

The good point would be to allow get some refund for the "deleted/sold" unit..

For example if the Rocketthrower cost 15000, then if player would try to sell Rocketthrower which have 10% HP it would get 1500$ (then could get some infantry for it)...

**Comment by Robosturm** [comment]
added it as a mod.
But you only get 50% refunds of the actual unit value. 
So a rocketthrower at 10Hp gives 7500 Funds and one at 1 Hp only 1500 Funds
