### ISSUE TITLE
Scrolling in Load Map in the Map Editor transtions strangely when opening a folder with no Scroll bar

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#199]
When scrolling through the directory folder for maps withing Load Map in the Map Editor, if the folder does not contain enough maps within it to contain a scroll bar, it seems to use the scroll position of the previous screen, making it impossible to select a map that in a folder that's lower in the directory and does not contain a scroll bar.

**Comment by XnKradst** [comment]
Yeah, I encountered this too. If it helps, for the time being, you can still select a map by typing its file name and hitting the "OK" button.
