### ISSUE TITLE
Add option to disable battle animations and fast unit movement

### ISSUE THREAD

**Issue by crtusr** [Robosturm/Commander_Wars#2]
Because it takes too long for all turns to pass.

**Comment by Robosturm** [comment]
You can currently disable animations via the Commander_Wars.ini-File, which can be found beside the exe.
Search for the following line:
ShowAnimations=true
Replace it with:
ShowAnimations=false
This will disable all animations. 
You can also skip animations with a right click. 

I gonna add the option to the optionmenu for the next release

**Comment by Robosturm** [comment]
Implemented for Beta Release 3
