### ISSUE TITLE
Suggestion: More precise music controls

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#20]
**Is your feature request related to a problem? Please describe.**
So far the music handling is relatively simple so far. Just play the track and loop when the file itself ends. However this could be jarring for soundtracks that aren't already intended to be looped (such as those with fade-outs like the custom CO themes).

**Describe the solution you'd like**
Provide the ability to register music files into soundtrack entries that have specified looping points (when the loop starts and ends). If no looping points are specified, the game will just play the sound file in its entirety.

**Additional context**
Another music feature that would be nice is script-based volume control, this would be most useful for cutscenes when other sound files would play (like dramatic count downs, voiced dialogue, or funny memes). There's also script-based override and soundtrack-swapping when this is a dramatic battle and Andy doesn't play his usual theme.

**Comment by Robosturm** [comment]
Hi GuardinTempest,

The sound system is already changeable take a look at the sound page i created one second ago. 😄 
[https://github.com/Robosturm/Commander_Wars/wiki/Scripting-Audio-and-Sound](url)

I extended the interface for the next release to have start and end looping points.

**Comment by GuardianTempest** [comment]
Oh sweet, thank you for preempting this. Will the CO themes be adjusted for next release or will the looping parameters be manually set?

**Comment by Robosturm** [comment]
Most likely not.
I'm probably to lazy to do so. 😄 
But if you want you can change them and send me the changes:
The Audio-Stuff for CO's are in the folder "resources/scripts/cos/" each co has a line "this.loadCOMusic = function(co)" 
and under this you would find a call audio.addMusic("resources/music/cos/adam.mp3") which would need to be modified to something like:
audio.addMusic("resources/music/cos/adam.mp3", 1000, 60000)
For starting at second 1 and finishing at 60 Seconds.

**Comment by GuardianTempest** [comment]
That's neat! I'm a little finicky so I could do it in my spare time. I'm rather new to this so is it possible for me to modify the uploaded scripts directly or could I get away with just listing the timing parameters here?

**Comment by Robosturm** [comment]
Well I guess the easiest way would be to change them locally zip the co folder and send it to me via email. Alternatively you can post the start end points here

**Comment by GuardianTempest** [comment]
Alright, I'll see what I can do.

Adam: 100 | 58286 _(If the track didn't fade at the end you could just loop the entire file)_
Adder: 2456 | 122475 (1m 2.475s?)
Aira: 75 | 58517
Alexander: Entire file, no change needed
Alexis: 51 | 56938
Amy: 3444 | 604297
Andy: 4466 | 74972
Black Hole Power: 1091 | 49930
Black Hole Super Power: 3161 | 37731
Black Hole Tag Power: 779 | 51141
Brenner: 631 | 59458
Carmen: 50 | 64048
Carrie: 101 | 64625 _(I feel like this used to be a longer track, the transition is imperfect)_

First batch for now

**Comment by Robosturm** [comment]
Adder's track position is kinda confusing. You shoukd repost it. :D
And it would be nice if you could replace the | with a comma for seperating the track positions.
Carmen and Carrie aren't in the game. ;)

**Comment by GuardianTempest** [comment]
Sorry about that, I just saw the mp3 files and assumed that they're there. :P

Adder: 2456, 62475

Continuing where I left off... (the bizarre syntax is to make copy-pasting easier)

Cassidy, 76, 75279
Caulder, 6755, 60471
Colin, 6900, 75513
Conrad, 4027, 104641 _(1m 44.641s || One of the easiest loops to make)_
Drake, 28, 60371
Eagle, 27, 67923
Epoch, 100, 79210 _(If it didn't fade out at the end, you could just loop the entire file)_
Flak, 9650, 78077
Forsythe, 2245, 118383 _(1m 58.383s || arrrgh so many retries due to misclicks on audacity)_
Gage, 9315 ,70409

That's it for this batch

**Comment by Robosturm** [comment]
No Problem. :)
Yeah it makes it easy to add the stuff by copy pasting it.
Thx for the adaption. Added the loop points.
Thx for your work.

**Comment by GuardianTempest** [comment]
Heyyy, sorry for the absence, I was in a weekend vacation with my family (against my will >.>).

There's nothing I could do for Graves, there doesn't seem to be any looping point in his theme. I feel like his sound file is only half of a theme song. Same thing goes for Joey. Were their original sound files longer, by any chance?

Greyfield, 3229, 64409
Grimm, 12479, 76493
Grit, 13156, 66022
Hachi, 12402, 68059
Hawke, 981, 63770
_Note: There's a bit of static in the opening sequence and it's apparent when it loops, nothing i could do_
IK-486-B7, 8310, 95764
Jake, 5421, 96121
Javier, 22016, 74716
Jess, 44504, 109979 _(1m 49.979s)_
Jugger, 7861, 81685
Julia, 3969, 83932 _(this one was very tricky)_
Kanbei, 4632, 59502 _(I'll admit I prefer the AW2 version)_
Kindle, 1995, 63956
Koal, 14166, 103617 _(1m 43.617s, in case I get confused)_
Koshi, 443, 57734 _(Imperfect, there's a faint tone that's cut off by the looping point)_
Lash, 8885, 58311
Lin, 3991, 61044
Mary, 8299, 73941
Max, 57, 70080
Meiyo, 76678, 146244 (track's loud and busy, getting this right was hard)
Melanthe, 2716, 75957
Mina, 76, 100073 (a shorter loop would be 32073, 100073)
Minamoto, 7779, 61530 _(it's a little flawed since the end of the track has more energy than the intro)_

Oh yeah, aside from custom CO themes, could you add in support for custom CO power/super themes? In case I want my Special Snowflake™ to have a special butt-kicking song.

**Comment by Robosturm** [comment]
Hi Guardian,
no problem. I hope you still enjoyed your weekend vacation. ;)
Thx for the looping points i added them to the CO's.

I think you missed Isabella from AW-DoR-Soundtrack
If you have the AW2-Version of Kanbei i can swap it out. I'm just using the sounds i have from the original Commander Wars project and i have no clue where i got them from. :(

As for the power/super theme that's already possible. In fact you can get any info from the game and select a music-theme based on it. The most often used version is a default theme and a power/super and tag theme.
All CO's have a function similar to this one, which selects a soundtrack and as you can see i added the looping points to minamoto: 
![co_theme](https://user-images.githubusercontent.com/48879701/62834415-27a26000-bc4c-11e9-948c-8000825f9653.png)

**Comment by GuardianTempest** [comment]
I missed Isabella? Huh, I didn't see an MP3 file with her label on it (the filenames are what I used to label things). It's odd, it's as if her soundtrack wasn't included in the Beta 5 download.

[Kanbei and Nell themes.zip](https://github.com/Robosturm/Commander_Wars/files/3491058/Kanbei.and.Nell.themes.zip)

Anyway, here are the AW2 versions of Nell and Kanbei's themes (which I find to be better), as well as their respective looping points. I'm bringing up Nell because the DS version's weird at the 0:15 point (though the rest of the track is an improvement).

Kanbei, 4783, 60483
Nell, 146, 61461

For the rest of them
Nana, 409, 66237
Napoleon, 40388, 83068
Nell (DS version), 59, 61394
No CO (battle fanfare), 4726, 58364
Olaf, 2618, 59888
Ozzy, 877, 60878 _(The end fades too early, I hope this sounds good enough)_
Penny, 56308, 108812
Peter, 578, 70397
CO Power, 992, 45321
Rachel, 2220, 63662
Rattigan has the same soundtrack as Greyfield, use the latter's coordinates for reference
Robo-Andy, 3653, 46346 _(Incomplete loop, the full melody fades halfway)_
RoboSturm, 1395, 41092
Sabaki, 42287, 86073 _(Another incomplete track)_
Sami, 1934, 62918
Sanjuro, 100, 63433 _(my favorite track, the second half of its melody is also incomplete :disappointed: )_
Sasha, 15916, 105733
Sensei, 304, 63603
Smitan, 45424, 90079
Sonja, 4059, 60078
Sophie, 27799, 69801
Sturm, 4054, 60338
CO Super, 1505, 49515
Tabitha, 56155, 127410
CO Tag Power, 14611, 65538
Tasha, 1663, 66947
Varlot, 2418, 74440
Von Bolt, 47693, 113984
Waylon, 58182, 112806
Will, 36421, 91424
Xavier, 270, 74593 (It was very difficult for me to find the right points to loop)
Zandra, 59, 57817

I feel like Smitan and Peter got each other's themes. Peter's cautious and calculative nature would fit the slow-paced would fit the more calculative Deep Trouble track (with the woodwinds fitting his admiral-esque motif); while Smitan's brash and unrestrained nature would fit the rockin' guitar piece that is currently assigned to Pete.

**Comment by Robosturm** [comment]
Most soundtracks of the Custom Wars CO's are from Custom Wars and i don't know how they edited them.
I missed to add Isabella's Soundtrack added it for the next release.
I replaced Rattigans Track i guess the Custom Wars Team used Greyfields Theme for him cause they didn't want to add
I replaced Kanbei's Soundtrack with yours and replaced the looping points. 
I also improved the audio engine to handle the loops better.

And thx a lot for doing all the looping work it's highly appreciated.

**Comment by GuardianTempest** [comment]
You're welcome. I suppose this should be closed soon.

I'm thinking of starting a new thread for finding new music assets for the new COs, or just new music assets in general. What do you think?.

**Comment by Robosturm** [comment]
Yeah i think we can close this as you did a great work in getting me the looping points

I have nothing against a better asset of music for the new CO's or general music assets as for powers or superpowers etc. 
If you enjoy doing/finding some music assets i gladly accept them. :)
