### ISSUE TITLE
Ranged units are counter-attack direct units if their MaxRange is Reduced to 1

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#200]
For some strange reason, indirect units are counter attacking when their MaxRange is being reduced to 1, even if there MinRange is greater then one. For example, if you take a desert map, and turn weather to Sandstorm, Artillery can counter attack direct units.

**Comment by Robosturm** [comment]
Not sure which mod or CO you played but i can't confirm that for the base game.
Please make sure to only report thinks happening in the base game. ;)

**Comment by Everglass** [comment]
Can confirm this was tested with the base game.

**Comment by Robosturm** [comment]
I didn't read that you need desert tile and desertstorm so the bug happen.
I'm an idiot. :D
