### ISSUE TITLE
Game crash at end of LAN Multiplayer

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#202]
[20200418-150900 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4496687/20200418-150900.Commander.Wars.Crash.log)
[20200418-152315 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4496688/20200418-152315.Commander.Wars.Crash.log)

I made a test of two LAN games. Games was played on default maps (with same active mods for each side etc.).

Gameplay is holding up at normal, until to the finish, where game instead showing victory stats.. just crashes. I sent 2 crashlogs, each from separate game.

**Comment by Robosturm** [comment]
First of all the mod your using is bugged. Please report that to the creator of the no_co.
Beside that i fixed that the buggy mod crashes the game.

**Comment by Danmark25** [comment]
Yeah that was the mod fault. It suddenly glitched one of CO's and tried probably call it whole time..

Reinstalling game + redownloading mod to being functional fixed the problem

**Comment by Danmark25** [comment]
Okay it looks that problem isn't into the bugged mod or not..

The problem is about when are runned instance of games and are used different profiles during 
LAN game.

When are same names then game is showing normal victory stats etc. but when nicks are differing even a single letter/number, then game just crashes before getting victory screen

**Comment by Robosturm** [comment]
Not exactly sure what you mean with different profiles.
The bug you reported first with the logs is something else.

Probably i need the logs for the crash you have now.
