### ISSUE TITLE
Screen block to be used for non-Fog of War local multiplayer games and an option to save during the screen block

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#203]
This is most for the ability to more easily preform save trading a local multiplayer game. It would be nice to be able to save the game during the screen blocking phase of the next players turn, so you don't have to look at the board state to save the game to trade it with another player. Also the ability to have the screen be blocked during non-Fog of War maps as stealth units can still be revealed to other players when transitioning between turns.

**Comment by Robosturm** [comment]
Slightly modified your request.
Added a game rule to make screen blocking permanent.
Saving the game during the screen block always exits the game. ;)
