### ISSUE TITLE
Open Place in Single-Player mode

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#205]
We have in Multiplayer option to make open space if we want to wait for some player to join, although we lack that option in single player too.

I think adding the "open space" instead player/AI can allow to make more intensive 1v1 matches for example in 4p maps or even bigger

**Comment by Robosturm** [comment]
Added a Closed AI to the game selecting this defeats the player right from the start letting you play single or multiplayer games with less players than required by the map
