### ISSUE TITLE
Generated random map don't saves in directory

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#207]
Problem mentioned in topic. There's no way to find generated random map (i.e the option "random map" which allows to generate map and jump into the game).

I think that should be some checkbox like "Save the map for later use" is we want to edit it to make it more balanced.

**Comment by Robosturm** [comment]
Not goind to happen soon.
But you can save the setup + the seed to generate the exact same map in the editor.
Need to think on where to integrate the save button first. 
Since i currently have no place for that in the UI.
