### ISSUE TITLE
Game won't start if you have CO style settings for a removed CO

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#208]
If you edit a custom CO's color palette/CO style, the game won't start if the mod containing that custom CO is disabled. Since the game won't start, the only way to re-enable the mod is by editing the .ini file.
Apparently this is because the game's trying to load the saved CO style settings for a CO that doesn't exist anymore?

I've been aware of this bug for a while now, but I forgot to report it until a friend encountered it. I would usually fix it myself by just deleting the .dat file containing the CO styles data, or editing the .ini file as mentioned above, but neither of those solutions are obvious, and thus a player might re-install the whole game because of it.

I believe the same thing should happen too if you edit a base-game CO's style and then remove them from the resources folder?

**Comment by Robosturm** [comment]
Fixed and made it so that styles remain. So swapping back to the mod restores the old styles
