### ISSUE TITLE
Reloading save breaks the game

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#209]
Description of bug: When I and my friend reloaded the save, then game started to work glitchy.

**To Reproduce I

1. Create single-player game
2. Recruit units then end first turn
3. Save the game, then reload it from menu

Expected behavior: Units should move at normal

Attempt to click on unit will make double-click with only option to move or giving it CO power**

**To Reproduce II (it's very rare)

1. Create single-player game
2. Save the game without doing anything, then reload it from menu

Expected behavior: Units should be normally recruited in first turn

Attempt to recruit a unit will end with going to the victory screen (exit game without confirmation)**

**Comment by XnKradst** [comment]
I can confirm the first one, as I first found it myself... however, I'm not sure about the second bug because I can't reproduce it.

Also, I think you're supposed to describe what _should_ happen under "expected behavior" (normal behavior), and not the buggy behavior itself, lol.

**Comment by Robosturm** [comment]
Can confirm number 1. 
Though right click will go back to normal behaviour.

**Comment by Robosturm** [comment]
Not able to reproduce the second one. 
Please create another issue for it.
With more detailed if you encounter it again.

**Comment by Danmark25** [comment]
I guess, that was something in common with first one, but I think that now things are fixed, I can close that issue
