### ISSUE TITLE
"Wait" command cannot be selected with the "Confirm" key

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#21]
**Describe the bug**
After moving a unit, the player can select the "Wait" command. However, when playing on keyboard, the "confirm" key doesn't select the "Wait" command.

**To Reproduce**
1. Go to any map.
2. Select one of your units with the "Confirm" key.
3. Move your unit.
4. Try to select the "Wait" command with the "Confirm" key.

**Expected behavior**
When pressing the "Confirm" key, the "Wait" command should be selected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 5

**Comment by Robosturm** [comment]
should even crash the game...
Fixed
