### ISSUE TITLE
Bugged "cancel" button on replay with or without mods

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#210]
**Describe the bug**
Pressing the cancel button where is attempt to watch replay from game where was used mods which currently aren't active  ends with freezing the game

(https://github.com/Robosturm/Commander_Wars/files/4712278/20200601-181725.Commander.Wars.Crash.log)

**To Reproduce**

1. Turn on any mod from community
2. Make a replay from it
3. Turn off the mods
4. Try to turn on modded replay
5. Pressing cancel will leave screen only with background and later game will crash

This can be reproduced the most easy way by trying to turn on one community mod and try to launch vanilla replay.

**Expected behavior**
Cancel button should return to the main menu

**Screenshots**
![image](https://user-images.githubusercontent.com/59868034/83429367-3dc81980-a434-11ea-883f-85d242a7948f.png)

**Comment by Robosturm** [comment]
The cancel button should be invisible. xD
Fixed.
