### ISSUE TITLE
Victory Rules don't seems to save when saving maps in the Map Editor

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#218]
For some reason none of the victory conditions are saved when saving a map in the Map Editor. And the No HQ and No Units win conditions are saved being unchecked.

**Comment by Robosturm** [comment]
The rules are saved but are loaded/shown wrongly.
So with the next release they get loaded normally again

**Comment by Robosturm** [comment]
It's the same issue causing the loose on loading a savegame
