### ISSUE TITLE
Once displayed, the Information window cannot be close by pressing the "Cancel" key

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#22]
**Describe the bug**
We now have the option to display an information window by pressing the "i" key (by default).
However once the information window has been displayed, the only way to close it is to click on "ok" with the mouse. The "Cancel" key doesn't close it.

**To Reproduce**
1. Go to any map.
2. Click on the information window key ("i" by default).
3. Try to close it with the "Cancel" key.

**Expected behavior**
The Information window should close when the "Cancel" key is pressed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 5

**Additional context**
When playing on keyboard, having to pick up the mouse to close this window defeats the point.

**Comment by Robosturm** [comment]
You can press i again to close it again. ;)
I'm adding the cancel key to it as well
