### ISSUE TITLE
Suggestion: Transparent "stars"

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#220]
This is a problem which isn't gamebreaking but aesthetic. When we're playing on the big maps where it's more than 5 players, then COs which have big star gauges are making vision limited.

Maybe it's not the big deal, but specially moving the map or zooming in/out is quite tedious and frustating.

How about to make those stars transparent or make those values loaded into percents?

**Comment by Robosturm** [comment]
Transparent stars won't happen cause. Ähm that makes no sense.
I don't like to show it in percent either.
Maybe i add a max number of Players shown so you can configure how many players get shown on the left side. So you can reduce it to 1 player

**Comment by Danmark25** [comment]
> Maybe i add a max number of Players shown so you can configure how many players get shown on the left side. So you can reduce it to 1 player

Yeah I think that could be fair solution. That worked in AW titles and other strategies where you have access to your own power.. + that will give some surprise effect during randomizing COs

**Comment by Danmark25** [comment]
Since I've seen the screenshot with made changes in next release I can close this
