### ISSUE TITLE
Suggestion: Option to turn off cords?

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#221]
Another thing from the aesthetic category.

As we knows cords in the right-upper corner are working good, when we're editing/creating a map.

But unfortunately those cords aren't necessary during matches. Not only that takes place + can activate during hover without reason creating a little obstacle to hide it again.

Good solution would be option to turn off this cords during matches. (still leaving them in map editor)

**Comment by Robosturm** [comment]
The hovering is a bug. That's fixed.
Turnning it off may come some day
