### ISSUE TITLE
Movement queue causes a de-sync in multiplayer

### ISSUE THREAD

**Issue by FutureWolf4** [Robosturm/Commander_Wars#222]
Moving a unit outside of their movement range (Purple tile) while in a multiplayer game causes a de-sync forcing us to abandon the game and start all over again.

1. Start up a multiplayer game
2. Make a unit do a movement queue (By clicking on a purple tile)

This will cause a de-sync for the other player(-s).

Would also like to ask if there is any way of disabling it.

**Comment by Robosturm** [comment]
Going to check that.

You can disable it.
Go to Options --> Gameplay & Keys --> Set the value of Multiturnplan to 1.

**Comment by FutureWolf4** [comment]
Thank you, that fixed our de-sync issues with the movement actions. appreciate it.
