### ISSUE TITLE
Loading a saved game in Multiplayer isn't fully working

### ISSUE THREAD

**Issue by FutureWolf4** [Robosturm/Commander_Wars#223]
Saving a multiplayer game to play later doesn't work. Loading the saved game causes one or more of the following: 
1. The player who's turn it is has their turn skipped, after which the player who's turn is next will not receive any income from their buildings.
2. Causing certain units not being able to take an action, from our experience it's totally random which unit isn't allowed to take an action.
3. Resets every single CO Power Bar back to zero.

**Comment by Robosturm** [comment]
Yeah there's a bug in loading certain savegames + maybe i messed up the starting of a saved multiplayer game. 

Going to fix it. 
You should be able to continue the game with the next release. Since the savefile itself isn't wrong.

**Comment by Robosturm** [comment]
Hmmm. Okay so 2. is still strange thought it may come from the selection bug before the hotfix...
Could you send me one of the not working savegames? So i can check if the unit bug is still in?

**Comment by FutureWolf4** [comment]
Hopefully this can help out in some way.
[(4) - Nova Docks.zip](https://github.com/Robosturm/Commander_Wars/files/4763326/4.-.Nova.Docks.zip)

**Comment by Robosturm** [comment]
Okay seems to be fixed. I was able to use all units of the 4 players.
So wait 2 weeks and you can continue the map.
