### ISSUE TITLE
Weather does not sync up

### ISSUE THREAD

**Issue by FutureWolf4** [Robosturm/Commander_Wars#225]
During a multiplayer game, weather effects are not aligned correctly for every player. They are random for every player and only syncs up after a couple of turns. For example:
- Player 1 Weather Forecast on turn 1: Sun, Snow, Sun
- Player 2 Weather Forecast on turn 2: Sun, Sun, Sun

**Comment by Robosturm** [comment]
Really thx for the report.
I found two critical bugs with that tip which explain why at a very rare rate multiplayer games get asynchorn.
Fixed both of them.
