### ISSUE TITLE
Scripting Ideas

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#226]
--->New Event Possibility:

I've looked into the current events available and found a few events that could play key towards missions / mission making. Currently, they're disabled when looking at the files, but I have yet to tested whether such things are still available.

-Change Building on X,Y- Already able to remove buildings by changing tile to something where buildings can't be placed on like ruins via change tile event. Would present possibility for additions to scripting in cases where buildings change over the time of the scenario.

-Change Team of Player- Would present possible scenarios without need to eradicate players (betrayels, team switch for multiplayer, etc)

-Change AI of unit on X,Y- Could change the unit from defense to offense for scenario, would be interesting to see a counter offensive or all out attack after being docile.

--->OR/NOT conditions:

While possible to conduct with the use of variables, it can be somewhat tedious when working with area conditions. Not sure if II will work the same as &&....

--->Thought:

Besides the few bugs over certain issues, so far the game seems to be cleanly done. Keep up the good work! Wish I could help, but my abilities towards these kind of things are very lacking...

**Comment by Robosturm** [comment]
Hi,
thx for the feedback. Bugs will always be there. I try to keep the out of releases but there's always one sneaking in.

As for requesting features or bugs. Please report them as seperated issues so in your case we talk about 4 different event request.
Keeping them as 4 issues make it easier for me to keep track of which i have done and what is missing.

All events are requested by you are already possible by writing the js codes by hand. Pretty much the ingame script editor is a very stripped down version of what is actual possible. 
And not everything may be visual possible with the current setup.

**Comment by HappyPotatoFunTime** [comment]
After testing and trying to get them to work, it is possible for usage. I'll separate these ideas and give basic lines which have worked for me for functionality.
