### ISSUE TITLE
Scripting Idea: Change Unit AI Mode

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#229]
I haven't yet managed to get this one to work... So far I've brought up,

if(map.getTerrain(X, Y).getUnit() !== null){map.getTerrain(X, Y).getUnit().setAiMode(unit.getAiMode(offensive???));}

yet it doesn't work... (I'm missing certain prefix codes... already tested gameenums and unit file)

**Comment by Robosturm** [comment]
The correct one would be:
map.getTerrain(X, Y).getUnit().setAiMode(GameEnums.#);
Where the # is one of the Following
GameAi_Normal
GameAi_Offensive
GameAi_Defensive
GameAi_Hold

I see when i do them. The Script Editor things are annoying to implement.
They're easy to implement but take so much time more or less copy pasting and changing the code that should be generated. :(
