### ISSUE TITLE
Infantry, recon, tank, anti-air and probably other ground units as well as bomber cannot fire on artillerycraft units.

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#23]
**Describe the bug**
Artillerycraft units are virtually invicible when facing ground units. AFAIK, no ground units can attack them, and bombers can't either. Not sure about other craft units (hovercraft, hover-anti-air, etc).

**To Reproduce**
1. Go to any map with bases or artillerycraft.
2. Wait for the AI to produce an artillerycraft.
3. Try to attack it.

**Expected behavior**
Artillerycraft should be targetable by other ground units with anti-ground units weapons (tank canons, MGs, etc).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 5

**Comment by Robosturm** [comment]
fixed going to do a hot fix mostlikely tomorrow for that...

**Comment by Robosturm** [comment]
Okay uploaded a hot fix.
Actually Artillerycrafts where not attackable by any unit cause the damage tables missed an entry for them...
Just redownload the release and replace it.
You should also have the version with the sound system issue active now. ;)
