### ISSUE TITLE
Start Game tooltip blocks clicking start game

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#232]
If you hover over the Start Game button for too long, the tooltip that pops up will block being able to click the button. Just a minor inconvenience, as you can just move away and click the button. But I find that the Start Game and Back tooltips are a bit redundant as they merely say "Start Game" and "Back" for each of them.

**Comment by Robosturm** [comment]
Changed position where the  tooltip so they  never block a mouse click.
