### ISSUE TITLE
Pre-deployed maps not ending

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#236]
**Describe the bug**
In pre-deployed maps, capturing the HQ and destroying all units does not win the game.

**To Reproduce**
1 - Play against an AI in Pre-deployed.
2 - Capture his HQ
3 - Destroy all his remaining units
4 - Game does not end, and continues indefinitely

**Expected behavior**
Game should've ended when the HQ is captured.

**Screenshots**
![image](https://user-images.githubusercontent.com/7210193/85200998-c92a2180-b2f3-11ea-9a1f-d7c92651440b.png)
![image](https://user-images.githubusercontent.com/7210193/85201039-1dcd9c80-b2f4-11ea-9b90-066be712bef1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 12 with Hotfix

**Comment by Everglass** [comment]
You just have to make that those Victory conditions are on, I'm still uncertain as to why to game will load with those settings off. But when I loaded up one of the pre-deployed maps, it had those victory rules turned on by default for me.

**Comment by Robosturm** [comment]
Well since scrupt-variables are bugged in Beta 12 loading victory rules may fail for certain rules.
However as Evergass said check if victory rules are on you can check those in the victory info screen.
If none exist you can't win.
