### ISSUE TITLE
Units are still hidden behind mountains

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#24]
**Describe the bug**
Units and their HPs are still hidden behind mountains. I think it happens when reloading a savegame, but could be wrong.

**To Reproduce**
1. Go to a map with mountains.
2. Place a unit behind a mountain.
3. If it displays correctly, save the game, then come back.
4. The unit should be displaying incorrectly.

**Expected behavior**
Units and HPs should always be visible even behind mountains.

**Screenshots**
![units_hidden](https://user-images.githubusercontent.com/53582470/62412521-fdc1bb80-b603-11e9-98b9-079dd6759af8.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 5

**Comment by Robosturm** [comment]
whoops the map loader uses an own function to add units.
After moving the units should be in front again...
What a dumb think replaced the loader with the general one.
