### ISSUE TITLE
Rework building display

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#240]
As mentioned in the discord, it would be better for the building display that shows how many of each building there are on a map to not show buildings of which there are 0, instead of showing them with a 0. This makes it easier to see what kind of buildings are on the map as the bar won't be clogged by useless info about what structures aren't there.

I would suggest, however, always displaying a select set of buildings even if they aren't on the map (Or make an option to allow the player to select which buildings to always display), these buildings would be the City, HQ, Factory, Airport & Port.

**Comment by Robosturm** [comment]
Part with a fixed set of buildings shown want come for the moment to much things to do for nearly no advantage
