### ISSUE TITLE
All Players get the same color

### ISSUE THREAD

**Issue by Gitkum** [Robosturm/Commander_Wars#241]
All players get the same color despite selecting different colors for each player. On the minimap the chosen colors are displayed, though. (Version: Beta 13)

**Comment by Robosturm** [comment]
I'm not able to confirm that in the vanilla version of the game or by using the vanilla mods.

Do you use any other mods?
And could you show me a screenshot and the log of the game may help as well.
I guess maybe the shader didn't get loaded prober on your system.

**Comment by Gitkum** [comment]
> Do you use any other mods?

No, I just used the vanilla version, without any mods.


> And could you show me a screenshot and the log of the game may help as well.

Here: ![Commander Wars bug](https://user-images.githubusercontent.com/67104238/86020545-5540f500-ba28-11ea-85be-1fbe11fedb8a.PNG)


And here the log: 
[console.log](https://github.com/Robosturm/Commander_Wars/files/4846230/console.log)

**Comment by Robosturm** [comment]
Okay it's what i thought. Pretty much a problem that may happen on old graphic cards.
Could you try download the zip attached and copy it over the file in system/frac_table_shader.glsl
[frac_table_shader.zip](https://github.com/Robosturm/Commander_Wars/files/4849589/frac_table_shader.zip)
And try it again. If it works i will attach the file to the release as extra download. Thx

**Comment by Gitkum** [comment]
I tried it, it works! 

Thx for help.

**Comment by Gitkum** [comment]
> Okay it's what i thought. Pretty much a problem that may happen on old graphic cards.

Yeah, that may be the problem, my graphic card isn't the newest :D

**Comment by Gitkum** [comment]
But I didn't experience this problem in Beta 12.

**Comment by Robosturm** [comment]
Well i changed the way in which player colors are applied to have better look and feel and more options for custom player colors, So the file i send you is a new one not present in Beta 12. ;)
