### ISSUE TITLE
Crash error that popped up.

### ISSUE THREAD

**Issue by RyushoYosei** [Robosturm/Commander_Wars#242]
Commander Wars vVersion: 0.13.0
30 Jun 2020 @ 13:50:53

EXCEPTION_ACCESS_VIOLATION

[0] 0x00000000005715f4 PathFindingSystem::explore() at pathfindingsystem.cpp:80
[1] 0x00000000006528dc ?? at qvector.h:272
[2] 0x0000000000655319 NormalAi::process() at normalai.cpp:55
[3] 0x0000000075657409 ?? ??:0
[4] 0x0000000068c67657 ?? ??:0
[5] 0x0000000068c3ec89 ?? ??:0
[6] 0x0000000068c901e8 ?? ??:0
[7] 0x0000000076aa44bb ?? ??:0
[8] 0x0000000076ef6dd2 ?? ??:0
[9] 0x0000000068a977c3 ?? ??:0
[10] 0x0000000068c3e67c ?? ??:0
INFO: Enter "help()" for console info.
INFO: Starting Game...
INFO: Prepare to Fight...
INFO: Read this message while waiting...
INFO: 
INFO: "Ha finally i've got the last word."......"Nearly the last."
INFO:

**Comment by Robosturm** [comment]
Can you tell me or send me the map you're using?
Did you press anything during the AI-Turn?

**Comment by RyushoYosei** [comment]
I pressed nothing on the AI turn as I was letting it run to see how it would preform over time on this map, currious to see how long the game might take in turns, and so it crashed probably from the length of game with the number of players, 
https://gofile.io/d/liM5Pn
This is the map I made, just  being a bit silly deciding "What if I made a 'annoyingly even' map" Which is a set of 4 4v4's, that the winner of each basically then has to win a larger 4v4 of sorts, but...yeah I made this more to test just the limits I guess and I think I hit them.

**Comment by Robosturm** [comment]
Nah not really.
It has nothing to do with the AI itself.
The crash happened in one of the core functions of the game which i thought doesn't contain any errors.
I prevented a possible issue causing the bug but i want to produce it on my system to hopefully fix it.

Did you use any mods?

**Comment by Robosturm** [comment]
Okay i think you found a very rare race condition in the game should be fixed for the next release.
