### ISSUE TITLE
First strike bug

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#244]
**Describe the bug**
Sonja's SCOP Counter-Break (and any Custom CO which offers first-strike) have bugged animation. Instead showing up first strike, during defense enemy attacks first. In the case where Sonja's unit is about to die and shouldn't counter.. attacks

**To Reproduce**
1. Pick up Sonja and random CO to 2 player game
2. Give Sonja power gain to unlock Superpower and launch it
3. Sonja will not deal damage first even enemy will attack first. In case when Sonja's unit dies, makes counter out of nowhere.

**Expected behavior**
First strike should allow Sonja and other Custom COs to attack first in defence + there shouldn't be counters when unit is about to die

**Additional context**
This is very old bug since Beta Release 11 or 12

**Comment by Robosturm** [comment]
Not a bug. It's how counter break works AW. Basically Units do an attack as if they didn't take damage when counter attacking.
It never was a true firststrike. Since it breaks core  mechanics.
However you can mod it to work like you want
