### ISSUE TITLE
Added capability for hosting Correspondence Multiplayer Games

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#245]
As most player vs player multiplayer Advance Wars games played now-a-days are mostly done on websites such as AWBW, there are players who become accustom to playing in a Correspondence fashion, having players perform turns within a few days and having matches last for a couple of weeks.

Some additional feature to allow for hosting Correspondence games would be to allow non-host players be able to leave and join the game as long as the host keeps the game open. While also having turns of offline players to be active and run the time limit. Extending the turn time limit cap to be up to 3 to 7 days and allowing the host to kick inactive players. As well as allowing players who join back into the game be able to access the message logs and any team messages or whispers they received while away.

**Comment by Everglass** [comment]
Or perhaps an option for the timer to auto defeat players rather then just passing their turn.

**Comment by Robosturm** [comment]
This will happen after you can host a game server.
Defeating a player via the timer won't happen cause it's a bad design. ;)
