### ISSUE TITLE
Hovering over the replay slider crashes the game

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#246]
Like the title says, trying to hover over the slider at the bottom during a replay crashes the game. Here's a crash log file:
[20200703-163229 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4871389/20200703-163229.Commander.Wars.Crash.log)
I've tested with and without mods, and the game crashes either way.

It might be just me, as I didn't get anyone else to test it for me. I'll also mention that with each update I simply copy the .ini file over to the new one so I don't have to remap all the keys again. Maybe that has something to do with it?

[Here's a test replay file if needed.](https://cdn.discordapp.com/attachments/728712965913837651/728713093965807616/60-ZWEITER_KRIEG-03-07-2020-16-30-31.rec)

**Comment by Robosturm** [comment]
Okay i think you found a race condition after i speed up the multithreading behaviour and removed some of the superficial locks. One wasn't superficial after all. xD
