### ISSUE TITLE
Suggestion: Generator for random predeployed maps/random unit icon

### ISSUE THREAD

**Issue by Gitkum** [Robosturm/Commander_Wars#249]
Until now, the random map generator only generates maps without any units.

It would be a nice feature if the map generator could place random units on the map. You could determine how many of them per player and their frequency, similar to the buildings. There would have to be a mechanism which hinders the generator from placing units on terrains on which they can't move, though (e.g. no battleships on mountains). This function could also be added to the map editor. Then you could place a random unit icon where you want, and a random unit would appear when you start a game on the map. 

I don't know if it is possible, but I just want to leave it here as a suggestion. :)

**Comment by Robosturm** [comment]
The idea for the random map generator is okay and do able not sure when i'll do it.

The later one want come. However you can do it in a different way. By writting a map script by hand. You can take a look at the AW2-Campaign Scripts for Black Hole Factories. They start spawning random units at the factory doors after a certain day is over. ;)
