### ISSUE TITLE
AI deploys several CO-rank units

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#25]
**Describe the bug**
AI deploys several CO-rank units, but as far as I know only 1 unit can be CO-rank at any time.

**To Reproduce**
1. Go to any map with production buildings.
2. Wait for the AI to make CO-rank units.

**Expected behavior**
Only 1 unit can be CO-rank at any time.

**Screenshots**
![several_co_units](https://user-images.githubusercontent.com/53582470/62412536-614be900-b604-11e9-9d95-f83321a772f0.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 5

**Comment by Robosturm** [comment]
Nope you can have a CO-Unit for each CO so the max. is 2 CO-Units.

**Comment by Koopanique** [comment]
> That's different to the original games.
> Since the effects of both CO's are active -> that's why you can't swap CO's in the normal mod

Ooh ok, I was wondering about that too. It doesn't work like in AWDS. Thanks for the precision
