### ISSUE TITLE
Capturing and Unit in area scripits aren't working

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#255]
There are 2 problems but have similar source.

It's about capturing building at place (for example HQ,Factory etc.) and going to required place.

The reason of error is that function can't call null Player ID

**Comment by Danmark25** [comment]
Edit: That happened when giving as place to capture/visit Oil Rig

**Comment by Robosturm** [comment]
I have no clue what you're talking about to be honest.

**Comment by Danmark25** [comment]
Sorry for cryptic message. I will try to explain now since I was able to reproduce the bugs

#1 Capturing the Oil Rig (If it's required to be captured in script.. Then Black Boat can't even capture it)

![image](https://user-images.githubusercontent.com/59868034/87697780-d8857900-c792-11ea-9344-a687d24698b3.png)

and the line 38 is:

"if (map.getTerrain(4, 4).getBuilding().getOwner().getPlayerID() === 0 && variable1.readDataBool() === false) {// 0 Building Captured"

#2 Going to the Oil Rig (If it's required to be in the script.. Black Boat can't capture it too)

faulty line: if (map.isPlayersUnitInArea(Qt.rect(4, 4, 0, 0), []) && variable1.readDataBool() === false) {// 1 Player in Area

I have made only one screenshot, since it shows the same error in both cases

**Comment by Robosturm** [comment]
Okay the first one is a bug. That needs an additional check in the generation.
The second one is a bug and not a bug.
You simply missconfigured the condition.
a) width and heigth need to be greater 0 --> made it so you can't enter 0 anymore.
b) you didn't add any players that should enter the area --> made it so at minimum one player is entered.

**Comment by Robosturm** [comment]
![grafik](https://user-images.githubusercontent.com/48879701/87797448-fadacd80-c84a-11ea-9a62-1ce88a3fc761.png)
Needs to look like this in the editor
