### ISSUE TITLE
When the map is too big, the minimap doesn't display all the map

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#26]
**Describe the bug**
When the map is too big, the minimap doesn't display the map in full.

**To Reproduce**
1. Go to a big map (like 40x40 tiles).
2. See the minimap.

**Expected behavior**
The minimap should probably display all the map.

**Screenshots**
![minimap_partial_display](https://user-images.githubusercontent.com/53582470/62412547-9e17e000-b604-11e9-8385-e939b0736a73.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 5

**Comment by Robosturm** [comment]
You can move the minimap by pressing any key and moving it. 
You should have listened to Lash in the tutorial. 😄

**Comment by Koopanique** [comment]
Urgh feel dumb now. Thanks for the tutorial reminder
