### ISSUE TITLE
Gift action

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#261]
We remember in Dual Strike, that we could gift our units (If we don't made any move with them in turn) to AI in dual-screen missions.

That action could work good in CoW because:

a) If our ally (AI or human player) would be in trouble, we could gift them quick reinforce to defend territory or make swift rush counter.

b) That will bring extra tactics (team-work would be even more essential)

**Comment by Robosturm** [comment]
added as seperated mode
