### ISSUE TITLE
Enhancement: Alternate movement system

### ISSUE THREAD

**Issue by Gitkum** [Robosturm/Commander_Wars#264]
**Is your feature request related to a problem? Please describe.**
Usually, units can move only once per turn and lose all their movement points, irrespective from how many tiles they moved. 

**Describe the solution you'd like**
It could be interesting to implement an option or mod for an alternate move point system in which you don’t need to spend all your move points at once. This would allow for more moves (two units can exchange their positions in one turn!) and a more CO-Zone-focused gameplay (you can position your CO-Zone where necessary and move on). I am not sure if its compatible with Eagles Power and Superpower, though.

**Comment by Robosturm** [comment]
The suggestion is already possible by creating a mod.
However i 'm not going to add it in the next months
