### ISSUE TITLE
Script idea: Cost reduction with using gameenums

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#266]
Cost reduction currently is working by giving reduction to all units, or separately by writing a variable. (Not to mention that writing over 20 units, is quite time-taking and require accuracy to not make typo)

I think that thing that would make it much easier to expand would be using gameenums (responsible for Naval, Air, Ground and Infantry).

This way instead picking units one by one, we can make more complex builds (for example someone would have cheaper Aircraft, but more expensive ground units and so on).

**Comment by Robosturm** [comment]
If you're talking for cost reduction via a co that's already possible. In the way you suggest.

**Comment by Danmark25** [comment]
getCostModifier : function(co, id, baseCost)
    {
        return 0;
    },

But then how to enable gameenums in that? That requires unit thing, which attempt to add comes with critical errors that units aren't property of an object

**Comment by Robosturm** [comment]
Like this:
    Global[id].getUnitType() === GameEnums.UnitType_Ground
Note: I added it also to the modding wikipage
