### ISSUE TITLE
Alexander's CO Power doesn't reset capture progress of enemies

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#267]
His Power doesn't seem to be restarting the capture progress of enemy units, it's primary function. At the moment, his power only increases the capture rate of his units.

**Comment by Everglass** [comment]
I test all issues with the base game before posting them. So this was done with no mods on to see if this was the case.

**Comment by Robosturm** [comment]
Haha looked at the history for him.
His COP was never implemented. WTF.
