### ISSUE TITLE
In the menus, scrolling up/down with the mousewheel would be useful

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#27]
**Is your feature request related to a problem? Please describe.**
In the menus, scrolling up/down with the mousewheel would be useful. Clicking on the elevator or the up/down arrows works, but it is slower than using the mousewheel.

**Describe the solution you'd like**
Being able to scroll up and down in the menus with the mousewheel.

**Comment by Robosturm** [comment]
Here we go added it to the main panel object which covers 99% and to the map selection where you select the current map when the mouse is over it. :)
