### ISSUE TITLE
Missing shooting sprite for Metal Army rocketthrower and medium tank

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#272]
![Commander_Wars_2020-08-02-16-01-00](https://user-images.githubusercontent.com/69113332/89124810-1a742600-d4da-11ea-94dd-6ba2e97489a8.png)
![Commander_Wars_2020-08-02-16-00-37](https://user-images.githubusercontent.com/69113332/89124814-1f38da00-d4da-11ea-865b-278bcd90ef51.png)
![Commander_Wars_2020-08-02-16-32-10](https://user-images.githubusercontent.com/69113332/89125324-f0246780-d4dd-11ea-8455-64722e286f62.png)
![Commander_Wars_2020-08-02-16-24-33](https://user-images.githubusercontent.com/69113332/89125193-eea66f80-d4dc-11ea-8f40-9118814582be.png)
![Commander_Wars_2020-08-02-16-24-46](https://user-images.githubusercontent.com/69113332/89125196-f108c980-d4dc-11ea-8875-8ce024add775.png)
![Commander_Wars_2020-08-02-16-24-53](https://user-images.githubusercontent.com/69113332/89125198-f2d28d00-d4dc-11ea-86d8-71a0de0be801.png)
The Medium Tank re-appears when it hits however.

**Comment by Robosturm** [comment]
This appears for a couple of MA-Sprites already fixed for the next release.
Still thx for the report. :)
