### ISSUE TITLE
For some reason, AI favors Indirect Units heavily (artillery, artillerycraft), even when its COs are not profficient with indirect units

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#28]
**Is your feature request related to a problem? Please describe.**
I don't really know what causes this, but in early game, AI tends to build indirect attack units (artillery and artillerycraft mainly) at the expense of other units like light tanks. Maybe because these are cheaper than tanks?

**Screenshot**
![indirect_units](https://user-images.githubusercontent.com/53582470/62412656-fac7ca80-b605-11e9-8ebb-c23042704b9d.jpg)

**Describe the solution you'd like**
I think that a more balanced production would be more fun for the player and more efficient for the AI.

**Comment by Robosturm** [comment]
That's most likely a result of bug this [https://github.com/Robosturm/Commander_Wars/issues/23](url)
Since the calculation results in Artillerycrafts are indestricutable and thus really good...

**Comment by Koopanique** [comment]
Indeed, the AI deploys significantly less artillerycraft and artillery now. Thanks!

**Comment by Robosturm** [comment]
Yeah the ai checks which unit deals most damage and takes the least while beeing cost efficient. And having a indirect direct ratio. While the easy ai deploys a little bit more random
