### ISSUE TITLE
Checking informations of the Labor crashes the game with Dual Strike Mod

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#280]
**Describe the bug**
Crashes the game when trying to check information of the Oozium

**To Reproduce**
1. Having Dual Strike Mod (CO Mod and Weather Mod were disabled)
2. Entering Labor's units buy menu which shows a yellow line with red background
3. Pressing Key Information to show infos

**Expected behavior**
Showing Oozium and labor's info

**Screenshots**
![Commander_Wars_2020-08-03-23-23-24](https://user-images.githubusercontent.com/69113332/89228687-64473400-d5e0-11ea-8ca8-913db21712ef.png)

**Crashlog**
[20200803-232038 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/5018748/20200803-232038.Commander.Wars.Crash.log)

**Comment by Robosturm** [comment]
Actually you shouldn't get a menu fixed it.
