### ISSUE TITLE
Nana's Power temps to crash game due to "delete unit"

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#285]
**Describe the bug**
Pink Frontier Nana from some weird reason tend to delete randomly her units, which leads to crashing game

**To Reproduce**
1. Pick Nana from Pink Frontier as enemy
2. Use console cheat (at day 5-6) to give her enough stars to Power
3. Wait when AI activate that
4. She will in random moment delete unit without reason and then game crashes.

**Expected behavior**
When AI deletes unit game shouldn't crash

**Screenshots**

Seconds before crash
![image](https://user-images.githubusercontent.com/59868034/89524306-9d4ff600-d7e4-11ea-853f-e760f3e379ba.png)

Unit is deleted "without" explosion

![image](https://user-images.githubusercontent.com/59868034/89524379-c1abd280-d7e4-11ea-94c2-1fb9b4a24e62.png)

**Comment by Everglass** [comment]
This could be due to you using the Bad Days mod.
Try to see if you can reproduce this bug with no mods on. If that's not the case, it could be some error being created by my mod.

**Comment by Danmark25** [comment]
I tried to reproduce it without Bad Days mod, but it was impossible.

So I guess something with your mod isn't okay

**Comment by Danmark25** [comment]
Okay, so after searching along the reason, it was the problem with kill unit script.

It required to be modified and now problem is fixed
