### ISSUE TITLE
All 4 perks to set movement costs of units to 1 causes snow to be ignored and all CO benefit from it

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#287]
Equipping Climber, Pathfinder, Prairie Dog and/or Seawalker makes it so snow is ignored and gives the perks to everyone. Even those who haven't equipped it benefits from them. For example in a game with Andy, Max, Jess, Nell, if equipping Max with Prairie dog, everyone can suddenly move at 1 move cost on plains tiles, even during snow.

**Comment by Robosturm** [comment]
The reduction to 1 during snow is intentional. And is indirectly mentioned in the description.

It's more or less a clash between how AW-DS Snow and Perks are done and how snow worked in all other games.
