### ISSUE TITLE
Unit map sprites masks currently use two colors with the red channel value 8

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#290]
The second darkest color is currently sharing the red channel as the third darkest. Currently, the channel 5 color is unused.

**Comment by Robosturm** [comment]
Not sure what you mean by that. 
But since the tables are moddable for a mod and the base game tables won't be modified. Since each color isn't really linked to units or buildings etc.

**Comment by Everglass** [comment]
Battleships for example use 6 six different shades of color, but two of the shades show as the same color in game.

**Comment by Robosturm** [comment]
Work done by yourself xD
