### ISSUE TITLE
Audio settings are overlapping each others

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#295]
![Commander_Wars_2020-08-16-16-58-07](https://user-images.githubusercontent.com/69113332/90337278-c2f9ae00-dfe1-11ea-89ad-a7d77da43911.png)

It seems to be showing both in 1 and 10 numbers

**Comment by Robosturm** [comment]
I'm not able to confirm that though...

**Comment by chopper385** [comment]
It seems after restarted the game, the bug disappeared? I'll try to see what caused this.

**Comment by chopper385** [comment]
Okay I found out what causes this: If going to "Gameplay & Keys" or 'Mods" tabs then coming back to "Settings" and trying to change the audio, this bug happens.
