### ISSUE TITLE
Closing a player slot doesn't remove the player from the game.

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#307]
When choosing to create a game where some of the player slots are closed, when entering the match, these players will still be present. Though inactive, it can be problematic when playing on maps that have an uncapturable HQ, or any special rule sets that may make it impossible to defeat the inactive player. Also, for COs that interact with other players funds pool, like Alexander for example who takes half the fund of all enemy players, it could give an artificial advantage.

My suggestion would be to have these players automatically defeated at the start of the match.

**Comment by Robosturm** [comment]
That's actually a bug.
Instead of defeating the player. The disabled Heavy AI is used. Whooops
