### ISSUE TITLE
Bug: Attacks don't work for units with almost no HP (no mods)

### ISSUE THREAD

**Issue by Gitkum** [Robosturm/Commander_Wars#308]
**Describe the bug**
When one near dead unit attacks another near dead unit, the attacking unit is destroyed and the defending unit survives. 

1. Start a game with at least 3 players fighting each other. You should be able to command all three of them. Choose Rachel as commander of one of the sides. 
2. Charge Rachel's power meter until she can use her Super CO Power.
3.  Produce the same type of unit (units which can attack each other, e.g. light tanks) for the two other players (blue and green, the ones who don't have Rachel as CO), make them having less than 10 HP and cluster them together.
4. Launch Rachel's Super CO Power. She will hit the cluster of units. Unit HP will drop to 1, with the HP being invisible in the HP bar because the units are near dead. 
5. Let the blue and green units attack each other. The attacking unit will do no damage, but will be destroyed in the counterattack and the defending unit survives.

**Comment by Robosturm** [comment]
Uff. A missing rounding leads to attacks being potentially weaker as they should be.
