### ISSUE TITLE
Suggestion: closing the ingame menu by clicking anywhere else on the map

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#31]
**Is your feature request related to a problem? Please describe.**
Currently, when playing with the mouse, to close the ingame menu, a right click is needed.

**Describe the solution you'd like**
An intuitive way of closing the ingame menu would be to click anywhere else on the map.
This is what the touch-screen controls did in the original DS AW games and also what Wargroove does, and maybe I'm biased because I'm used to this way of closing the ingame menu, but I would find this solution more intuitive. And of course closing the ingame menu with the right-click can still be kept.

**Comment by Robosturm** [comment]
Disabled the behaviour cause i wanted to prevent missclicks 😄 
Since i never played wargroove and AW DS never with the touch screen i did it this way.

Changed it. 
Now both works
