### ISSUE TITLE
Console Error Message when going into Action Banlist after choosing one of the blank co

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#310]
After choosing one of the blank COs of one of the factions, if you go back to game rules and access the Action Banlist, an error will appear in the console about a 'getCOName'.

To Reproduce;
Go to CO select screen and choose one of the blank COs for one of the faction. Then go back to game rules and open up the Action Banlist.

I don't think this really has any effect to game play. But can sometimes be pretty ocd about getting errors in the console.

**Comment by Everglass** [comment]
Actually, this occurs no matter what CO you choose. All you have to do is choose any CO and going back and editing Action Banlist will cause the error.

**Comment by Robosturm** [comment]
I'm not able to reproduce that.

Did you have a mod active?

**Comment by Gitkum** [comment]
Same problem here. I didn't use any mods. Here my log:
[console.log](https://github.com/Robosturm/Commander_Wars/files/5147242/console.log)

**Comment by Gitkum** [comment]
For me, it works fine for every map except random maps. And for random maps it doesn't matter if I do this directly or after selecting the COs.
