### ISSUE TITLE
Uncertain Crash

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#312]
I am unable to determine the source of the crash may it be from a map script or in-game engine, but here's the error message.

Commander Wars vVersion: 0.14.0
28 Aug 2020 @ 16:01:08

EXCEPTION_ACCESS_VIOLATION

[0] 0x000000000059ec00 Terrain::getUnit() at terrain.cpp:198
[1] 0x000000000041ba4b GameMap::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) at moc_gamemap.cpp:477
[2] 0x000000000042871c GameMap::qt_metacall(QMetaObject::Call, int, void**) at moc_gamemap.cpp:755
[3] 0x0000000068c47c3f 0x0000000068c47c3f
[4] 0x00000000663a5575 0x00000000663a5575
[5] 0x0000000066458115 0x0000000066458115
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 181
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Kartoffel/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23

**Comment by HappyPotatoFunTime** [comment]
Another weird crash. Happened randomly after conducting testing.

Commander Wars vVersion: 0.14.0
29 Aug 2020 @ 03:51:43

EXCEPTION_ACCESS_VIOLATION

[0] 0x00000000005979c0 GameMap::getCurrentDay() const at gamemap.cpp:1315
[1] 0x0000000068c62914 ?? ??:0
[2] 0x0000000011257aec ?? ??:0
[3] 0x0000000068a99f3d ?? ??:0
[4] 0x00000000764ce271 ?? ??:0
[5] 0x0000000077cd1e5c ?? ??:0
[6] 0x0000000068a977c3 ?? ??:0
[7] 0x0000000068c3e67c ?? ??:0
[8] 0x0000000068c450f4 ?? ??:0
[9] 0x0000000068c8f6a7 ?? ??:0
[10] 0x0000000068c3d571 ?? ??:0
INFO: If we knew what we were doing, it wouldn't be called research, would it?
INFO: 
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Nathan/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Nathan/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getOwner' of null in File: file:gameScript at Line: 14
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: SyntaxError: Unexpected token `true' in script gameScript in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: TypeError: Cannot call method 'getPlayerID' of null in File: file:gameScript at Line: 29
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 166
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 166
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Nathan/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Nathan/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 186
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Nathan/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: variable1 is not defined in File: file:gameScript at Line: 186
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Nathan/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23
CRITICAL: ReferenceError: offset is not defined in File: file:///C:/Users/Nathan/Desktop/Games/Cool Community Games/Commander_Wars/resources//scripts/battleanimations/BATTLEANIMATION_ARTILLERY.js at Line: 23

**Comment by Robosturm** [comment]
First of all you should download. The hotfix version of the release.
--> The artillery script errors will be gone with that.

But it looks like that the actual crash comes from your gamescript.
It looks like the script contains several syntax errors and tries to access stuff not on the map.
The output points at line 14, 29, 166, 181 and 186. So you should check at least those lines.
Without knowing the script though i can't point out what you're doing wrong.
