### ISSUE TITLE
Suggestion: An option to to have Weather Cycles

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#317]
Weather Cycles would pretty much be an option to predetermine what weather occurs on what days. Such as having the weather alternate between Sunny and Raining, or two days of Sun and one day of Rain, ect. This would give players a more precise control how the weather changes, compared to just random settings. Allowing some players to play with weather on without worrying about the randomness.

**Comment by Robosturm** [comment]
Won't happen. Just the complexity you would generate for the rule screen is out of hand.

What you can do instead is using the script events. Using an Every X Day Condition and an Change Weather for X-Days combination. 
+ Adding an option to change the game script in the rule screen.
