### ISSUE TITLE
Suggestion: in the ingame menu, having the cursor go directly to the bottom when positionned at the top of the menu

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#32]
**Is your feature request related to a problem? Please describe.**
In the ingame menu, when the cursor is positionned on the top-most option, it could go directly to the bottom-most option when the "UP" key is pressed, as in most video game menus. It would make the action go faster.

**Screenshot**
![ingame_menu-updown](https://user-images.githubusercontent.com/53582470/62414472-31104480-b61c-11e9-8e2d-c20eedad748c.jpg)

**Comment by Robosturm** [comment]
That's the result of a lazy programmer. 😄 
Added looping to the menu
