### ISSUE TITLE
Suggestion: "co" argument for a CO's profile/bio functions

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#322]
It would be nice if the CO profile functions like getPowerSentences() can take "co" as an argument like most of the other functions. It can potentially be used for a lot of things, like adding unique dialogue for the normal power, super power and tag power.
I'm currently using map.getCurrentPlayer().getCO(n) as an alternative to add tag-specific dialogue (depending on the paired CO). It works, but the code's kind of a mess...

**Comment by Robosturm** [comment]
Note using them outside of a running game may require extra checks for if the owner is null or not
