### ISSUE TITLE
An easier way to manage "construction lists", for compatibility between mods?

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#323]
Currently, to add new units to a building's construction list (and similarly, transport unit lists), you have to redefine `getConstructionList()` to return a new list with the new units added. This unfortunately makes compatibility between multiple mods harder to manage, as two mods redefining the same function wouldn't be compatible since whichever one loads last will override the other (unless specifically programmed to return a "merged" list if the other mod is detected).

I have an idea... would something like this work?
```
AIRPORT.constructionList = ["T_HELI", "K_HELI", "DUSTER", "TRANSPORTPLANE", "BOMBER", "FIGHTER", "STEALTHBOMBER", "BLACK_BOMB"];
AIRPORT.getConstructionList = function(building)
    {
        return AIRPORT.constructionList;
    };
```
This will allow modders to simply do `AIRPORT.constructionList.push("CUSTOM_UNIT");` instead.

However, there IS a flaw unfortunately - it puts all new units at the end of the list, and most modders (myself included) would want to sort the units in some way (usually by price with infantry before vehicle units).
I'm not sure if there's a solution for that, so I'm wondering if you can implement something like this, *and* add a way to let modders customize the order.

Anyway, I don't speak for everyone, and the other modders might disagree with this. It's a dumb suggestion after all...

**Comment by Robosturm** [comment]
well since those would be standard JavaScript Arras you sort them using either JavaScript functions or sort them manually. So nothing will be provided here. Since sorting rules are part of the mod Design and shouldn't be forced by the engine.
