### ISSUE TITLE
The Beast as CO to Dark Matter

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#329]
Since lore-wise The Beast was supported by Caulder until his death, he could be added as his assistant or independent neutral raider..

Global: His units have 10% attack bonus, but get -10% defense malus (I think that The Beast was in some kind prepared for the fight, but wasn't so good in defense as far as I know)

CO-ZONE: Gets extra 10% attack and remove defense malus (2 or 3 range depending which is better)

COP: Boosts his attack bonus and movement boost (+1)

SCOP #1 : Improves his attack even more and movement boost (+2)

When the first SCOP isn't good then

SCOP #2 : The Beast takes medicine from Caulder. He takes lowered damage from the attacks and his attack bonus is even more improved

**Comment by kibadimundi** [comment]
In Europe he is called Drakov, so we can call him like that. I think that he should get higher attack bonus taht malus. Like 15% extra damage and -10% defense. I just came here to say that he should be CO and I see this

**Comment by Danmark25** [comment]
The thing is that Robosturm is using names which was used in American version. 

Perhaps that could be an idea to ask for mod which would change the names from European and Japanese version (though in Japanese some outfits are changed though)
