### ISSUE TITLE
Units carried by APC not set to wait mode

### ISSUE THREAD

**Issue by XenesisXenon** [Robosturm/Commander_Wars#33]
Normal Advance Wars behaviour is that units that end turn in a transport are set to wait mode - they're not able to act after being dropped.

Load a unit into an APC (e.g. in Cleanup), end turn, drop the unit next turn and you'll be able to use it.

**Comment by GuardianTempest** [comment]
I think that's addressed [in here](https://github.com/Robosturm/Commander_Wars/issues/14). The fix was already implemented though I think he made it so that it's you can move the unloaded unit if it wasn't loaded in the same turn.

**Comment by XenesisXenon** [comment]
"The fix was already implemented though I think he made it so that it's you can move the unloaded unit if it wasn't loaded in the same turn."

Yes, that's the bug

**Comment by Robosturm** [comment]
@XenesisXenon What GuardianTempest wanted to say is Commander Wars isn't a 100% Advance Wars Clone somethings are slightly different.
So what you descriped as a bug is an intended changed behaviour compared to the original Advance Wars Series.
If it's a bad or unbalanced change will be seen.
If you don't like it you can switch on the Advance Wars DS Unit Mod, which in fact deactivates this behaviour.

**Comment by XenesisXenon** [comment]
Hmm, okay.
That's going to be difficult to report bugs if they may be intentional changes or not. Is there a list of the intentional mechanic changes from the core games, somewhere?

**Comment by Robosturm** [comment]
Not really the amount is exactly 2.
The first one is the Transporter solution.
The second is the CO-System which is described here: [https://github.com/Robosturm/Commander_Wars/wiki/Commander-Wars-CO-System](url)
I wanted to put both into the third tutorial map, but i still need an idea for a setup and kinda funny dialogue to make the tutorial enjoyable.

And i guess you can count that Penny currently doesn't disable Fog of War created by Rain, cause getting that in is a pain. 😢

**Comment by Robosturm** [comment]
@XenesisXenon  adressewd you're request for a mechanic change wiki list.
Take a look [here](https://github.com/Robosturm/Commander_Wars/wiki/Commander-Wars-Custom-Mechanics)

**Comment by Koopanique** [comment]
I hoped noone would mention this issue lol. I actually love that change. It makes landing units on enemy shores via landing craft much more fun.
