### ISSUE TITLE
Bug with auto-camera

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#331]
Camera is automatically moving only when it's AI move. When is player's turn (no matter if it's network or local) camera isn't even moving to him, instead standing on the last AI's turn?

Same thing where its 2 or more players locally. Camera isn't even moving.

**Comment by Robosturm** [comment]
Camera isn't meant to move to a player at the turn start at the moment. So the behaviour isn't bugged.
It may hover be treated as a feature

**Comment by Danmark25** [comment]
Yeah it would be good if would hover again to player at the beginning of his turn. It's quite tedious to manually drag from the AI's location
