### ISSUE TITLE
The Beast CO zone HP damage is inverted

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#336]
Currently when The Beast attacks, he loses no HP at all, but deals 1 HP damage if he gets attacked and his unit survives.

**Comment by Danmark25** [comment]
Well here's the reason

this.postBattleActions = function(co, attacker, atkDamage, defender, gotAttacked)
    {
        if (attacker.getOwner() === co.getOwner() && attacker.getHp() > 0)
        {
            defender.setHp(defender.getHp() - 1);
        }
    };

Probably it should be changed defender to attacker (Then will lose 1 HP)
