### ISSUE TITLE
Enhancement: Option to rename tiles and players

### ISSUE THREAD

**Issue by Gitkum** [Robosturm/Commander_Wars#339]
It would be great if you could name tiles and players. Geographical maps would feel more real (you could name e.g. cities and could give each side its name in real life").

**Comment by Robosturm** [comment]
You can already rename tiles in CoW as long as they aren't buildings.
Might add that as for player renames that won't happen for the moment.

**Comment by Robosturm** [comment]
Added option rename buildings.
Option for renaming players won't come for now
