### ISSUE TITLE
Crash Bug from long games

### ISSUE THREAD

**Issue by RyushoYosei** [Robosturm/Commander_Wars#34]
I am not sure what the cause of this is, but I have found it fun to set up matches of AI VS AI  that I have left on when I went to bed to wake up and see "How did the match go? Who won? Is it still going?" ...and Recently, The latest release of this seems to crash at some point when the turns go for too long, or something, while I know previously I have seen game results for 89 "day" aka turn long games after they were done, so something is going on causing it to crash out now compared to previously....

**Comment by Robosturm** [comment]
@RyushoYosei could you tell me which map you used and which AI (Normal or Very Easy)
and if you had a mod on and which game rules you used.
And at best the CO's used during the game.

This helps me to find the bug cause i have no clue what the problem could be from your description. 
So i need a could setup description.
I run a map now trying to catch the bug but without more info it's getting hard.

Thx.

**Comment by Robosturm** [comment]
Okay i found one memory leak which was definitly added with the fog of war vision change for buildings.... -> So did you have random weather e.g rain on or general Fog of War?

**Comment by RyushoYosei** [comment]
I had fog of war on, So that might be related, I don't know the CO's b ecause it was all random, and it happened on multiple maps, as long as it seemed to ke long enough.

**Comment by Robosturm** [comment]
Yeah than it's mostlikely not clearing an array which gets filled pretty fast the more players are on the map during fog of war.
My bad...
