### ISSUE TITLE
Suggestion: Keeping track of Stats / Records

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#341]
In Advance Wars: Dual Strike, there was a  menu that kept track of pretty much everything. (Units Built, Play Time, Etc) It would be cool if CoW incorporated something like that as well, (although maybe not to the same extent AW:DS did it). Mainly the only thing I would like is CoW to be able to keep track of, is your **total playtime**. But other things that would be pretty cool are:
- Total Matches Played (From both Singleplayer & Multiplayer) 
- Total Matches Won (From Everything.)
- Total Units Built 
- Total Units Destroyed 
- Total Buildings Captured (?) 
- Total HQ Captures (?)

For more individual records to be kept are:
- Singleplayer Play Time
- Multiplayer Play Time
- Singleplayer Games Played
- Singleplayer Games Won
- Multiplayer Game Played
- Multiplayer Games Won
- The Number of each Individual Unit You've Built (Probably should be on its own page; separate from "Individual Unit's Destroyed")
- The Number of each Individual unit you've Destroyed (Probably should be on its own page; separate from "Individual Unit's Built")

Now, there are A LOT of things that could potentially be kept track of in this game, that I couldn't really list them all...These are just the ones I felt were important enough that came to mind. Although really, all I want is for there to be a way to keep track of your total playtime in this game that you can easily just carry over to other versions. (And that could work in 1 of two ways. It can either work by keeping track of the total time the game is open or just the total time you spent in all matches and the Level Editor)

As for how this is could be organized, really depends on how you go about it...There could be entirely separate pages for the "Individual Units" stats or you could separate them on the same page. (You could also potentially do the same thing for the Multiplayer based stats)

**Comment by Robosturm** [comment]
Most of this will be covered by the achievement system coming with the next release.
So i won't add something like that for now.
The achievements are not like steam achievements since they record the stats and even increase if you already achieved one.

At the moment units build/killed and games won with each co are recorded for the vanilla game.
