### ISSUE TITLE
Suggestion: Option to pick palette to the map

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#344]
**Describe the solution you'd like**
Dual Strike and Days of Ruin offer 4 different palettes after choosing a map. They're giving no advantage/disadventage though can make maps more replayable

The palettes are Normal, Snowy, Desert and Wasteland. Though we need keep in mind that Dual Strike and Days of Ruin offered other colors.

**Additional context**
I know that in map editor we can create map fully based on snow,desert and wasteland, but the problem is that they have effects regardless of the weather which are forcing debuffs to the map

**Comment by Robosturm** [comment]
This won't come.
