### ISSUE TITLE
Alexis healing on temporary buildings, normal behavior or bug?

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#345]
Alexis heal her units near buildings she owns regardless of the type (town, airport, harbour) but it seems to also affect temporary airports/harbours and thus can be abused by mass-building them as "temporary towns" (and hiding places in Fog of war) anywhere on the plains.

**Comment by Robosturm** [comment]
Not really a bug, but probably not a good design.
Changed it
