### ISSUE TITLE
Online Multiplayer Team Battle Fog of War Bug

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#354]
I've noticed a few times while me and my friend were playing on a **Team together via Online Multiplayer**, he would attack units that are still hidden in the fog for me. Now, I have NO idea how this happens exactly but I have a few theories: (We weren't using any skills btw)

A. He used a flare in the specific area but that area he lite up with the flare just didn't show up for me. 
B. He crossed by an enemy unit but the fog didn't update for me.  

I'm sure patching Online Multiplayer bugs is harder than offline bugs and I guess this bug isn't really that big of a deal, but it has been bothering me.

Mods we used were:
"Advance Wars 2 Image Mod"
"AW-Styled Icons"
"Advance Wars Dual Strike Weather Mod"
"Commander Wars Perk Debuffs"
"Resell Units"
"Transfer Units"
"Commander Wars Triangle Mod"

"KTeknis Project"
"Xanari Crew"

**Comment by Robosturm** [comment]
That's an easy one to find i read your report and knew what the source of the bug is. xD
