### ISSUE TITLE
Load Unit Script

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#356]
I've looked into the master files and found no possible way to script spawning units in other transport units (for amphibious/aerial scenarios). Tried to work with the loadUnit command, however wasn't able to due to how (Unit* pUnit) works.

**Comment by Robosturm** [comment]
Yeah that's currently not possible but also not to hard to add.
The only way you can work around it in the current state is spawning a unit on an empty field and afterwards load it into the transporter.
Going to add that give me 10min. :D

**Comment by Robosturm** [comment]
Here we go. :)
The function is called loadSpawnedUnit and takes the unit id to spawn the unit in the transporter.
Example:
var heli = map.getTerrain(0, 0).getUnit();
heli.loadSpawnedUnit("MECH");

Note the function needs to be scripted by hand for now. ;)

**Comment by HappyPotatoFunTime** [comment]
Nice
