### ISSUE TITLE
Bottom Right, In-game UI Change

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#358]
...What the title means by this, is this area:  
![](https://i.imgur.com/8YjA1AW.png)

At the moment, it's a bit of a mess. Valuable information such as a **"Building's Resistance"**, **"Loaded Units"**, and with the addition of nicknames, **"Unit Names"** blend in with everything else, making them a bit harder to notice.

My suggestion for a simple redesign would be something like this: https://i.imgur.com/nbIjQ9O.png
A more "flashier" redesign would be something like this: https://i.imgur.com/EdPiixv.png
(Ik I'm showing off the "Transporting Units" thing w/bikers, but it gets the idea across.)
(Btw, each bar for the "Ammo1" bar is supposed to represent one shot. Which ofc varies between units)

...You can really do this any way you want, I just want it to be easier to distinguish between "Building Resistance", "Loaded Units", and "Unit Nicknames". (And maybe "Base Names" as well?)

**Comment by Robosturm** [comment]
Well that part of the UI always was in a high need of a rework. :(
