### ISSUE TITLE
A specific sequence of commands causes unit-dropping to stop working until the game is restarted

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#359]
Due to the very specific things that trigger it, here's a short clip showing it: https://streamable.com/ntd5ky

I know, the video probably made no sense without context, so I'll try to explain...
Basically, you need a unit capable of carrying 2 or more units. In this case, a transport plane with 2 units. To trigger the glitch, you'll have to:
1. Drop the units as you normally would, but cancel just before the last click (where you select the second unit's position).
2. You'll be taken back to the "step" where you move the transporting unit. Try dropping the two units again.
3. Drop the first unit normally, but on the second unit, select "wait".
4. Despite selecting "wait", you can still choose where to drop the second unit.
5. Click any of the available spots. The first unit should drop, while the second remains loaded. Notice how the "drop" sound doesn't play?

This might not seem like a big deal, but if done correctly, it'll *render all other transporters unable to drop units for the rest of the game*, as demonstrated by the APC and the Lander in the video. This carries on until you restart the game.

As shown in the clip above, the console error reads:
`/resources/scripts/actions/ACTION_UNLOAD.js at Line: 328`

No mods were used.

**Comment by chopper385** [comment]
Following XnKradst's unloading bug, the same bug happens with Unloading Mod with a different error code like this:

1. Move or stay in place
2. Select "Unload"
3. Cancel the unload to go back to moving step
4. Move or stay in place
5. Select unload again

![image](https://user-images.githubusercontent.com/69113332/102344986-facb2f00-3f9c-11eb-9927-f39664d6be5d.png)
