### ISSUE TITLE
Scripted Patrols

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#360]
It'd be interesting to see the AI patrol mechanic able to work with scripts, not that I know how that'll work. Just suggesting.

**Comment by Robosturm** [comment]
Already possible. ;)
Short code not coded out at all points:
var unit = spawnUnit()
unit.addAiMovePathPoint(Qt.point(5,7))
unit.addAiMovePathPoint(Qt.point(10,7))
unit.setAiMode(GameEnums.GameAi_Patrol)
or
unit.setAiMode(GameEnums.GameAi_PatrolLoop)

If you want that for the ingame script editor.
Tell me, though that's less likely to be added for now.

**Comment by HappyPotatoFunTime** [comment]
:D
