### ISSUE TITLE
Suggestion: Open Menu during other Player's Turns in Multiplayer

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#364]
The title pretty much says it all. I would like to be able to check CO Information, Attack Log, etc. While the Enemy or Ally are taking their turn in Multiplayer. I don't expect it to be perfect, (Like, I do expect the menu to close itself when another player ends their turn) but it would give you something to do while the other players are taking their turn.

**Comment by Robosturm** [comment]
Works good on human  turns but is pretty lacky on ai turns for now. Gets solved once i upgrade to C++20 and the ai using coroutines. Propably next year.
