### ISSUE TITLE
Option to stretching the map

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#369]
As I remember from Advance Wars series, each map was automatically stretched to fit into the screen.

Maybe that doesn't sound the best as permanent option (especially when players are playing on bigger maps and have to keep control over 50 units), but it would work as some option to activate

Player then wouldn't be distracted by background and would have full control over map (And the right bar would be still visible like in Dual Strike/ Days of Ruin)

**Comment by Robosturm** [comment]
This was never an option in AW 
Stretching or forced zooming is not very good for larger screens and small maps.
I don't thing the Background is distracting. If it is for just mod the background to one color or so
