### ISSUE TITLE
Air units Regain their fuel after they've ran out.

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#37]
**Describe the bug**
When an Air unit runs out of fuel, it just regains all of it back on the next turn, without me doing anything.

**To Reproduce**
I tested the bug out by lowering an air unit's fuel in the level editor and then playing a few turns. There were no APCs or Black boats, I wasn't using any COs and the only buildings were two HQs.

Edit: According to my friend, there's a similar issue with all units where once they run out of fuel; they either regain all their fuel back and/or have drastically increased movement range. This has happened to me too as well although I haven't tried reproducing it.

**Comment by Robosturm** [comment]
Found the refill bug with all units which consum fuel at the start of the turn.
And found the bug causes basically infinite movement range once the fuel drops to 0.
Fixed both. :)
