### ISSUE TITLE
Interchangeable Terrain-Coast Connection Graphic

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#370]
Differing usable terrains for this project have made it very interesting to use under certain circumstances with applying the attribution of multiple biomes. However, when focusing on just a single terrain with sea/coastal tiles, it creates a weird blend when trying to go for a single season terrain.

![3](https://user-images.githubusercontent.com/23581266/102322555-3c33ee00-3f4d-11eb-9031-ce4a96c9a435.JPG)

This might also help with graphical issues dealing with custom water terrain (such as from Bad Days mod) and snow/desert terrain.

**Comment by Robosturm** [comment]
This is a cool idea.
Though it requires a whole lot of new sprites.
Mainly for the coast tiles which can be close to more than another terrain tile....

**Comment by HappyPotatoFunTime** [comment]
I guess I can work on it eventually than :I

**Comment by Robosturm** [comment]
Well i was thinking about those tiles and i think this requires a rework of all coast tiles.
And change how the coast tiles are created/displayed...

**Comment by HappyPotatoFunTime** [comment]
I've looked into it. It's not complicated, but it does look like it's going to take a while. I do plan on overhauling the terrains of the game into a mod sometime in the future.
