### ISSUE TITLE
Thin Line Between Terrain Graphical Bug

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#372]
When there is a transition towards two differing types of terrain (desert to plain/snow), there's a graphical bug where Thin lines of the base color are present in-between tiles. These usually are less than a pixel (in comparison to the image size).

![4](https://user-images.githubusercontent.com/23581266/102346631-29c9ac80-3f6d-11eb-8c2c-2663380440ce.JPG)

It has a weird attribute where zoom levels affect how visible these lines are. Was working on a Ruin Tile mod, when this became most apparent.

![5](https://user-images.githubusercontent.com/23581266/102346736-57aef100-3f6d-11eb-99f0-aec380873ee6.JPG)
![6](https://user-images.githubusercontent.com/23581266/102346747-5aa9e180-3f6d-11eb-9f06-83d3fc680825.JPG)

**Comment by Robosturm** [comment]
Has been resolved in one of my improvements for the enxt release. :)

**Comment by HappyPotatoFunTime** [comment]
:D
