### ISSUE TITLE
Suggestion: Option to allow changing flare's fire behavior

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#373]
**Is your feature request related to a problem? Please describe.**
Flares in AW Days of Ruin could only shoot flares when not moving. Here, they can shoot while moving at the same time. For those that played Days of Ruin may get surprised it was changed, but no problems with it. The only problem becomes when using mods to change the behaviour of flares. Bad Days is an example as it restricts players from using them while moving. However AI is able to bypass that restriction, causing him to slightly cheat during fights as he can shoot flares while moving to reveal locations, and players can't.

**Describe the solution you'd like**
An option to disable flare action while moving so AI can't cheat it and so those who prefer the current behaviour can keep it.

**Describe alternatives you've considered**
Surely not a good suggestion at all: Hardcoding a check for mods changing flare action behaviour like Bad Days. Would be tedious to have to add checks everytime a mod changes the behaviour and asked to put one

**Additional context**
https://www.youtube.com/watch?v=4eXkC5OI1ZU

ACTION_FLARE.canBePerformed = function(action)
    {
        var unit = action.getTargetUnit();
        var actionTargetField = action.getActionTarget();
        var targetField = action.getTarget();
        if ((unit.getHasMoved() === true) ||
                (unit.getBaseMovementCosts(actionTargetField.x, actionTargetField.y) <= 0))
        {
            return false;
        }
        if ((actionTargetField.x === targetField.x) && (actionTargetField.y === targetField.y))
        {
            if (unit.hasAmmo1())
            {
                return true;
            }
        }
    };

**Comment by Robosturm** [comment]
This actually is a bug in the ai code.
The AI has to check if the action is possible before executing it.

**Comment by Robosturm** [comment]
Also i added a mod to change the flare behaviour so you can get true aw dc  experience. :D
