### ISSUE TITLE
New Modded Terrain Modifiers

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#374]
It would be nice if more additional modifiers were available towards terrain such as:

-Defensive
-Offensive
-Fuel Usage

And if possible:

-Scripting (allows for certain effects to take place if the unit is on the tile, such as damage taking damage)

**Comment by Robosturm** [comment]
Fuel modifiers want happen cause this isn't possible in the current design.

Buildings and Terrains get an offensive bonus function similar to co's called for a unit on the terrain
Terrains get a startOfTurn function just as buildings have already, which is called at the start of a day. --> So before the first player does his turn.
