### ISSUE TITLE
Possibility of having Dialog/Animation as a different setting from Ingame Animations

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#376]
It's weird having a story interactive property as part of "Ingame Animations" option, due why it's disabled. It can lead to whole parts of dialog (and animations) to be completely cut out. Such things are turned off to speed things up, such with the DS/Gameboy versions, so a separate option for dialog/animation would be nice.

**Comment by Robosturm** [comment]
Also added a seperate speed bar for the dialog animations
