### ISSUE TITLE
Right-clicking during the AI's turn crashes the game

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#379]
Basically what the title says, if you right-click or press the "cancel" key (forgot what the default key was) during the AI's turn, the game crashes.
[20210105-225340 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/5773852/20210105-225340.Commander.Wars.Crash.log)

**Comment by chopper385** [comment]
Concerning the right-click, if used to skip AI's power/superpower animation, the AI becomes frozen and won't move anymore

https://www.youtube.com/watch?v=43AiXgF-rdU

**Comment by Robosturm** [comment]
That's actually related to the other bug report. #380  ;)
