### ISSUE TITLE
Transported units aren't visible in a loaded game

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#38]
Not sure if this is already known, but...

**Describe the bug**
When continuing from a saved game, units that are currently carried by another unit (APCs, T-copters, Landers, etc.) are completely invisible when they're unloaded. They're clearly still there and perfectly functional gameplay-wise, and if they took damage their HP is still displayed, but their sprites are completely invisible. While it's only a graphical bug with no real impact on the gameplay, I might not notice such units from the AI and thus leave my units open to their attacks. I may also forget to move my own invisible units too.

**To Reproduce**
Simply deploy an infantry unit and an APC, then load the infantry in the APC. Save the game, exit, and reload the game, then unload the infantry unit.

**Additional context**
It applies to any unloaded units, not just infantry, I can confirm that I had an invisible Neotank unloaded from a Lander at some point.

**Comment by Robosturm** [comment]
No that's a new bug. Thx for detailed report.
Made it very easy to find the problem. The game doesn't load sprites for loaded units.
Fixed it.
