### ISSUE TITLE
loadSprite but don't flip

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#387]
Pretty self-explanatory, I feel.

Would it be possible to add another parameter to loadSprite and loadSpritev2 (preferably after the current parameter and defaulting to true to preserve compatibility with older versions) that does the following:

If true; this sprite gets flipped for every other player, so default AW/CoW behaviour.
If false; this sprite does NOT get flipped for every other player.

Right now, the latter effect can already be achieved with some clever use of if statements, but this would make this easier.

**Comment by Robosturm** [comment]
I guess you want this for units only right?

**Comment by Robosturm** [comment]
also added a function resetSprites() so it's easier to use your function. ;)
