### ISSUE TITLE
Suggestion: Level & Script Editor Changes and Ideas

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#39]
I've been messing around with the Level & Script editor a lot in this game, as it's really good. Although...I feel like there are somethings that could be added or changed to the Level editor that would improve it a lot. So, I figured I may as well dump them all here. 

1.) Have a window that allows you to change between Snow, Desert, and Normal tiles. 
https://i.imgur.com/lXbYpsx.png
Currently, the "weather" based tiles are all clumped together in the same menu. Which makes it rather confusing to navigate. So maybe have a window that allows you to choose between Desert, Normal and Snow tiles. Maybe even have it to where the window that shows the HQs and what not shows the different kind of terrain to choose from when in the terrain selection menu, and have the HQs appear when selecting units and Buildings. 

2.) An undo button
Since there are different tools that allow you to place 4-13 tiles at once, I've had a few occasions where I forgot that I had the 13-tiles tool selected and I accidentally placed a giant Forest in the middle of the map I'm creating, so I have to recreate what I already had back manually. So I figured an undo tool which would allow you to undo what you just placed, reverting it back to how it was prior to the change would be nice. (It could also be useful for reverting other things. For example; you select the option to flip the map, then you can click the undo button to change the map back to how it was prior to the change.) And of course, there should also be a redo option which allows you to redo...what you undid. 

3.) Have buildings replace the terrain you're trying to place it on.
Currently, you can only put buildings on Roads and Plains. (Can't even put em' on Desert or Snow plains either) However, in the original games, placing a City down on top of a Forest tile or Mountain tile will just replace that tile altogether. So...why not here? Maybe you could also have it to where when you place a building down on a Desert tile, the desert effects also apply to the building. (Same said for Snow tiles, although I don't know if that was your intent)

4.) An option to copy and paste a group of terrain
I understand that the Flip and Rotate options already allow for something like this, but I was thinking something of a much smaller scale, that allows you to copy a specific group of terrain and paste it somewhere else. (Example: https://i.imgur.com/mjPN1N8.png)

5.) Ability to copy and paste units with the same settings
The Level designer allows you to edit a unit's HP, Fuel, and Ammo. Although, you have to change each individually unit's settings manually. So maybe allow it so you can copy and paste a unit with those same exact settings? (For example, copying an infantry unit with 2 HP and whatnot will allow you to paste infantry units with the same settings)

6.) The Ability to check a terrain and unit's information in the Level Editor
You're already able to press "i" in-game to check a unit's and terrain's information, this feature would be even more useful in the Level Designer if available. 

7.) A hotkey for deleting units
This is rather minor. Basically: Just a key that allows you to delete units in the Level Designer. (maybe even in-game too) I.E pressing D changes your setting to delete units. 

Script Editor Suggestions:

8.) A Condition for; A Certain unit dying, A Building being Captured, a Building being destroyed, an army being eliminated, and a number of units being destroyed/a number of buildings being captured.
Basically:
Unit Dying = A Condition for when a specific unit dies
Building Captured = A Condition for when a specific building is captured
Building Destroyed = A Condition for when a building is destroyed (Crystals, Canon, Etc)
An Army Being Eliminated = For levels with more than 2 Teams
A Number of Units/Buildings Being Destroyed/Captured = For when a certain number of Units being destroyed or Buildings being captured is reached. 

You may be able to combine the first 3 Listed here into one command, maybe like a "special objective" of sorts? 

9.) Events of; Gaining access to a new unit, getting a specific amount of money, specific weather occurring, and an increase into your CO Meter.

Now I have a very vague understanding of how scripting works, so I'm totally okay if it turns out that some of these things are impossible to do. I'm just suggesting some ideas.

I greatly apologize for the long topic, although I felt like it was better than just making multiple separate topics for each thing. I understand the difficulties that come from coding things into a game, which is why I'm so hesitant about making Suggestion related topics. So, I will completely understand if something won't or cannot be added. Although, I've been messing around with the level editor a lot in this game and I figured these would truly be great additions to the level designer that would really increase the quality of life of it. Don't get me wrong though, the level designer is already amazing as it is. In fact, it wouldn't surprise me if some of these things are already in the game and I just missed it. (If so, I apologize). Let me know I wasn't clear enough on some things or if i just shouldn't have outright done something. (I believe I already have a habit of overexplaining things)

**Comment by Robosturm** [comment]
No Problem though splitting some fix up wouldn't be bad.
1) i know what you mean but the design doesn't allow it right now. Would require a lot of changes which I don't want to do right now (to much risk in breaking the system. :( )
2) added (for most things at least for the important ones) (added undo and redo)
3) done (fixed that you weren't able to place buildings on desert or snow tiles that's a bug) However for buildings it's only a visual change, Changed that you can place buildings only on plains. Now the terrain is replaced with plains. Note: This doesn't ably to large buildings like Black Hole Cannon or Deathray's Those still need correct terrain below them.
4 and 5) i would combine those
6) added
7) added (press the cancel key in the next release)
As for 8 and 9 those things are already possible by writing/creating the scripts yourself. 
Take a look at the wiki [here](https://github.com/Robosturm/Commander_Wars/wiki/Game-Scripts).
Also checkout the AW1 and AW2 -Campaign-Scripts or the tutorial scripts for some ideas. ;)
The ingame editor is pretty much a stripped down and easy access version for some simple actions and events for people not firm with programming. I'll add some of the functions of 8 not all as for 9 it's possible but adding it to the ingame editor won't happen for now. 
But if you know some scripting i recommend writing the scripts yourself. Since the game reads a script try to parse it and rewrite it, which is pretty complicate and reduces the options.

**Comment by Robosturm** [comment]
added copy + paste option for units, buildings and terrains
Copy + Paste depends on the current place selection mode.
oh and i added cursors to see the current placement size or placesize needed for large buildings.

**Comment by Seimix** [comment]
Hmm...I understand the issue when it comes to the Snow and Desert tiles, but maybe instead you could sort them in a different way in the current menu? The tiles in the editor are sorted alphabetically, so maybe instead you could have it sorted to where: Normal Tiles are first>Desert TIles>Then Snow tiles?  Example: https://i.imgur.com/JsgxKmy.png (pretend the tiles in those sections are the Desert & Snow tiles and such)  If something like this is possible, maybe do the same for the Units as well. (I.E Categorizing the Air, Ground and Naval Units)

I also forgot to add this to the topic: If you have a Building currently selected in the Level Editor you cannot right-click a normal tile to select that instead. The same thing goes to vice versa; if you currently have a terrain selected, you cannot right-click a building to start placing that instead. You have to select a building or terrain manually from the menu.

**Comment by Robosturm** [comment]
Changed the right click thing though i changed a little bit more the prio is now unit->building->terrain
Changed the organization see the picture.
![Gameplay52](https://user-images.githubusercontent.com/48879701/63161172-b255d700-c01f-11e9-9d29-552cc8802cb3.png)

**Comment by Robosturm** [comment]
Just realized that i'm unable to read correctly. Missread 9 as conditions and not events. xD
added events for funds, co bar, weather and changing the buildlist of a player.
Added condition for when units get destroyed. rest coming soon

**Comment by Robosturm** [comment]
added building destroyed, building captured, amount of buildings owned, amount of units killed and player defeated as conditions.
So i should have added all 9 points now. ;)

**Comment by Seimix** [comment]
Awesome! Thank you!
