### ISSUE TITLE
Suggestion: Making the camera centering on the tile or unit when choosing to attack/heal an option

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#397]
Before it used to be that when choosing an action asking you to choose which unit to attack, where to drop an unit, where to place a mine ect... to not do anything with the camera. With recent updates, it's now a default thing and it's quite annoying to have to move the camera back everytime to where we set it everytime I am about to perform an action (attack, drop, heal, place mine...).

Context of it:

Before updates: https://youtu.be/v7CCCMOT5e4?t=517
After updates: https://youtu.be/aEXyDhlf-CI?t=375

We can see the player keeps re-centering the map everytime to be able to choose another unit outside of the view.

**Comment by Robosturm** [comment]
Added and made it so the camera focusing is disabled by default.
The focusing was added unintentionally.
