### ISSUE TITLE
Right clicking to skip AI's beginning of his turn freezes the AI

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#399]
https://user-images.githubusercontent.com/69113332/106926661-9c573d00-6711-11eb-837b-ab1e1fe48d5a.mp4

Happens at 00:13

**Comment by chopper385** [comment]
This freeze also happens if trying to right click to skip AI's power animations with letters going down, during this
![image](https://user-images.githubusercontent.com/69113332/106927401-6a92a600-6712-11eb-9c6d-72b90cb5cddf.png)

**Comment by Robosturm** [comment]
Fixed for both situations.
The reveal part is a consequence of the freezing ai
