### ISSUE TITLE
Options Button Failure

### ISSUE THREAD

**Issue by LordSpyro** [Robosturm/Commander_Wars#4]
**Describe the bug**
I open up the main menu and click options 

**To Reproduce**
1. Go to main menu
2. Click on options button

**Expected behavior**
commander Wars.exe will stop working.

**Screenshots**
![commander wars stop working](https://user-images.githubusercontent.com/51299081/58766485-4bab3c00-854d-11e9-95ce-4e7ee98233e3.PNG)

**Desktop (please complete the following information):**
 - OS:  Windows 7

**Comment by Robosturm** [comment]
I have a theory what goes wrong the sdl-lib isn't able to get any screen resolutions and my drop down menu fails cause it tries to access data that isn't avaible. I fixed the drop down to work with 0 items.

What's you're screen resolution?
The game checks for a screen size of at least 1152 x 864.
If you have a smaller screen this would explain the crash.

**Comment by LordSpyro** [comment]
It's probably the screen size as commander wars is pretty big on my computer like outside the screen.

**Comment by Robosturm** [comment]
Than it's mostlikely the screen resolution.
Would be nice if you could check it and post it here.
I'll add some supports for resolutions down to 800 / 600 but it'll get harder to use some UI stuff there.

You can change the options in the Commander_Wars.ini-File which will be created once you started the game and closed it again. Most values are  intuitiv except the Keys on the Keyboard :(

**Comment by LordSpyro** [comment]
My screen resolution is 1366 x 768 on my computer.

**Comment by Robosturm** [comment]
Good than the heightproduces the problem.
Will be solved for the next release. ;)

As mentioned
You can change the height in the ini File to 768 manually. 
I don't recommend to go lower than that cause the editor won't show all placements avaible for terrains, buildings etc. -> changed for the next release as well.
And the minimap during a game may get invisible as well. -> Still the game remains playable. ;)

**Comment by Robosturm** [comment]
Fixed now for the released Release xD
