### ISSUE TITLE
Crash when enemy AI captures another enemy AI's HQ

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#40]
**Describe the bug**
When the enemy AI captures the HQ of another enemy AI, the game crashes.

**Additional context**
I was playing a 4-way free for all on Strong Land. This might be related to the crash about long games or a separate bug on its own.

**Comment by Robosturm** [comment]
Already known and fixed see:
[ https://github.com/Robosturm/Commander_Wars/issues/36]( https://github.com/Robosturm/Commander_Wars/issues/36)
