### ISSUE TITLE
Sandstorm missing sound

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#400]
**Is your feature request related to a problem? Please describe.**
Everytime Sandstorm weather appears, there is no sound at all to warn about it, and oh boy has many people fell for this (even myself) while thinking it's sun weather and trying to use an indirect, and ending up skipping the unit's turn, wasting it.

**Describe the solution you'd like**
I have recorded the sound from AW:DS and amplified it to CoW's rain and snow weather sound level so it's equally as them. Just need to add the playsound for sandstorm weather and this file with it: https://www.dropbox.com/s/tyeggte7ewj9n9w/sandstorm.wav?dl=0
this.activate = function(weather)
    {
        audio.playSound("sandstorm.wav");
    };

Otherwise see below.

**Describe alternatives you've considered**
It's possible to find this weather sound from google in DS DSi - Advance Wars Dual Strike - Miscellaneous as GENERAL_075, but it's raw and unedited. Here's how it sounds: https://www.dropbox.com/s/n4xx9b4wk3vmce0/GENERAL_075.wav?dl=0 

**Additional context**
None

**Comment by Robosturm** [comment]
Well i gladly added it.
Thx for your work. :)
Added you in the sound section credits as well. ;)
