### ISSUE TITLE
Shop: Buy Requirements

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#404]
![image](https://user-images.githubusercontent.com/51452633/107861575-fdd08780-6e46-11eb-856e-f7e991f2a6cf.png)

Ideally at least for units, but would be cool to have this for other things as well. So you can't buy skins for CO B without owning CO B!

**Comment by Robosturm** [comment]
added a callback for when an item got bought from there on you're pretty free to do whatever you want
