### ISSUE TITLE
Fog of War: Dark shadow and notification circle quickly appearing

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#406]
When AI or player builds a unit, captures a building or place a CO-unit, the color of it quickly appears and disappears.
![image](https://user-images.githubusercontent.com/69113332/108288834-950e4580-718d-11eb-9e06-11b5431cd2b3.png)
![image](https://user-images.githubusercontent.com/69113332/108289264-6ba1e980-718e-11eb-96cc-46cbfd2c835a.png)
When a unit inside a hidden place attacks one revealed unit that you can see, the notification circle quickly appears too. I couldn't get one screenshot of it however as it happens sometimes.

It can lead to the player knowing what the AI/player captured and when they put a CO-unit

**Comment by Robosturm** [comment]
The notification circle on a unit you see is actually intentional since you can see the field so you can see the impact as well
