### ISSUE TITLE
Unable to change CO on a Custom Made Map

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#41]
**Describe the bug**
On levels that I made using the Map Editor, I'm unable to choose the opposing team's CO.  Example: https://i.imgur.com/NWbtHhb.gif
(Trying this in the Map Editor doesn't work either unless you select the opposing team to a human player, then click back into the menu.)

**To Reproduce**
1. Go into the Map Editor
2. Editor Command>Edit Players
3. Select a CO for an AI team, then close the window and head back into it. 

If the CO getting locked for a team is intentional, it shouldn't be automatic. Instead, there should be an option as to whether or not you want to a lock a CO for that team.

**Comment by Robosturm** [comment]
That's semi intentional. Actually CO's for AI's should get disabled when a campaign is played but not for normal maps. 
Fixed it
