### ISSUE TITLE
Suggestion: Adding PostCaptureAction

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#414]
We have a PostBattleAction which works in a way to give interesting effects during fights, but we lack an option to give those effects after capturing (successfully or not) a building.

That option would allow for many new interactions to modded COs (For example if enemy gonna capture our building then he gets disarmed or even take damage, or in case of our CO, then he get could healed, get ammo/fuel, or even get funds)

**Comment by Robosturm** [comment]
added a postAction callback instead
