### ISSUE TITLE
Suggestion: Making victory box size depending of the text length

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#417]
Another of the problems is that too long winning/defeat quotes can go over the box and then everyone except last player will have cut quotes.

I know earlier wasn't that a problem since was other font and at much smaller size, but if that problem have to be solved, then it would be better if those boxes would get larger/shorter depending of the text length

**Comment by Robosturm** [comment]
Size of items remain the same instead the plain textfield is replaced with a label which cuts off to large texts and enables showing the full text via a label
