### ISSUE TITLE
Suggestion: Cosmetic Mod Tag

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#418]
A tag that you can place on mods that are purely cosmetic and would allow you to connect to a multiplayer game or view a replay without needing these mods be considered. That way you can have players play and connect to multiplayer games while each player are still allowed to use their preferred game cosmetics.

Though I can see how this could cause complications. Such as it wouldn't prevent a player from placing a cosmetic tag on a mod that does have game mechanic altering features. And this could cause some compatibility issues. But it would be a nice feature that allow players to play with one another while also allowing them to have the game appear as they desire.

**Comment by Robosturm** [comment]
My idea would be to have an extra gamerule while multiplaying which allows you to enable cosmetic mods with a warning popping up. That crashes or asynchron behaviour may happen if the mods used on either side are not pure cosmetic.
