### ISSUE TITLE
Suggestion: A separate CO description for full profiles.

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#42]
**Is your feature request related to a problem? Please describe.**
The CO descriptions you see when selecting a CO tends to be crowded, especially for those with complex abilities (namely Adam). For other COs, while their descriptions are fully visible it does clip at the bottom. On the other hand, some abilities aren't explained enough and could benefit from an expanded description tab (what does Amy mean by optimal level?). Granted, that might just be because of my screen resolution and might not be a bother for people with taller resolutions.

**Describe the solution you'd like**
A separate, possibly-optional string parameter that is only displayed when viewing the CO's profile in full.

**Comment by Robosturm** [comment]
Not sure why you do not use the CO Info Button in the bottom middle screen. It shows you the full information. The information in the CO-Selection is clipped cause it is meant to be a short overview.

**Comment by GuardianTempest** [comment]
Oh, that's what I meant when I say full profile. Basically I want to be able to put in a separate, longer description when viewing CO info for information too big to fit into the overview.

**Comment by Robosturm** [comment]
Well you could do that right now with the existing descriptions since they are clipped if they're too long.
added two functions getLongBio and getLongCODescription. First is added to the normal CO-Bio in the large info screen and the second is added to the normal CO-Description.
Though i'm not going to add some content there. But if you want you can send me texts for them and I'll add them.

**Comment by GuardianTempest** [comment]
I'll figure something out in due time.

Speaking of clipping, there's a different kind of clipping going on. A relatively minor visual glitch: I know the short CO description only has four lines, but perhaps you could make the font smaller as the bottom of the fourth line's sentences are being cut off.

**Comment by Robosturm** [comment]
Changed the scaling of the font from 0.5 to 0.47 now it looks decent without a half clipped font.

**Comment by GuardianTempest** [comment]
Are the fonts sprites? Is it possible to bypass the issue with colored lookalike fonts?

**Comment by Robosturm** [comment]
The fonts in the game are sprites. Take a look into the resources\fonts folder.
Each font has a png and a fnt file. The fnt file describes which letter can be found at which position. 
Commander Wars uses oxygine framework for drawing stuff.
Here's the font docu link from them
[https://github.com/oxygine/oxygine-framework/wiki/fonts](https://github.com/oxygine/oxygine-framework/wiki/fonts)
Sidenote: All texts are parsed in html style so the fonts may get recolored anyway e.g. the green color in some of the information boxes is created by a html command in the describtion text.
