### ISSUE TITLE
Buildings captured during Fog of War are still quickly blinking in the team's color when captured + sometimes disappears

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#425]
Building being colored blue when captured by AI
![wmplayer_2021-03-01-22-38-21](https://user-images.githubusercontent.com/69113332/109562734-109dba00-7adf-11eb-9ece-db15dcee97fb.jpg)

Building disappearing on the upper left
![wmplayer_2021-03-01-22-38-55](https://user-images.githubusercontent.com/69113332/109562736-11cee700-7adf-11eb-995d-6f099149fde7.jpg)

**Comment by Robosturm** [comment]
Okay the problem i thought was the problem wasn't the only one.
My PC is just to fast. xD
