### ISSUE TITLE
AI not caring about fog of war

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#43]
**Describe the bug**

**To Reproduce**
Play against Grit in a map with lots of forests or something.

**Expected behavior**
Enemy indirect units target units hiding in woods even without visual confirmation.

**Additional context**
I found this bug watching two AI teams (Alexis+Ozzy vs Jess) duke it out in Long Road and notice Jess' AI somehow targeting the units hiding in the woods south of the HQ. Weather was set to Random. At the very least save this for a future "Hard AI" difficulty.

**Comment by Robosturm** [comment]
At least from my game testing the AI only attacks units on which it has visual confirmation.
I tested it with FoW and FoW created with rain and units hidden weren't attacked by the AI.
Which is what i expected and actually tried to programm.
If the AI doesn't do that it's a bug however i'm not able to reproduce it.

**Comment by GuardianTempest** [comment]
Huh I see, good to know this is preemptively solved.
