### ISSUE TITLE
The AI will always send its naval units next to enemy naval mines

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#435]
**Describe the bug**
Like in the first three AW games, the AI knows the location of stealthed units and will always try to move a unit next to them. This is fine except for naval mines: the AI will always try to move next to it... killing itself in the process.

To test and prove this, you can make a map with Red naval mines and Blue destroyers/cruisers. The destroyers/cruisers will go towards the naval mines everytime, even if the naval mines are out of the way.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 18

**Comment by Robosturm** [comment]
What might be possible is to reduce the "chance" the ai moves towards stealthed units.
Or to be more precise that the ai things stealthed units are more far away than they actual are. So it prefers to move to other units.
But there is no way to completely avoid this behaviour. Unless you make mines unatargetable but that's not what i wanted

**Comment by Koopanique** [comment]
Hmm yeah I understand... How about making the AI act like it does in AW:DR? In AW:DR, the AI "pretends" not to know the location of enemy stealthed units, which was a pretty popular change from the traditional AI of the first three games. I guess the solution you mentioned would bring something close to that result

**Comment by Robosturm** [comment]
Well i guess the AI actually does something like that.
Cause you always Face the problem of the AI doing nothing if only Stealthed Units are on the map.
I guess you could test that by making a map with a sub and a cruiser for the ai. Stealth the sub and see what the ai does.
You always face a similar problem if all units of a player are in fog of war
