### ISSUE TITLE
Special buildings (mini cannons, lasers, etc) do not disappear when their HP reach 0

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#436]
**Describe the bug**
When a special building's HP reaches 0, the building remains, can still fire, and it still blocks units. (By "special building", I mean most campaign-specific Black Hole buildings: Mini-cannons, lasers, etc. Gates are also affected)

Curiously, this doesn't apply to Black Cannons (big Black Hole cannons), who die normally when their HP reach 0, however.

You can test this by making a map with various buildings and try to destroy them.

**Expected behavior**
Buildings should be destroyed when their HP reach 0.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 18

**Comment by Robosturm** [comment]
Already fixed in Hotfix 18.1 just download the fixed Version
