### ISSUE TITLE
Crash when clicking Mech

### ISSUE THREAD

**Issue by BenBohannon** [Robosturm/Commander_Wars#437]
**Describe the bug**
After a series of accidental clicks into the popup menu soon after the enemy's turn ended (which may not have been important), I clicked one of my Mechs and the game crashed with the following error.
```
Commander Wars vVersion: 0.18.1
08 Mar 2021 @ 19:42:45

EXCEPTION_ACCESS_VIOLATION

[0] 0x00000000005abbad PathFindingSystem::getTargetCosts(int, int) at pathfindingsystem.cpp:305
[1] 0x00000000007cd603 ?? at qobjectdefs_impl.h:152
[2] 0x0000000013ae7aec ?? ??:0
[3] 0x00000000770d7e9b ?? ??:0
[4] 0x0000000013aee327 ?? ??:0
INFO: Enter "help()" for console info.
INFO: Starting Game...
INFO: Prepare to Fight...
INFO: Read this message while waiting...
INFO: 
INFO: How long can you withstand dragon breath again?
INFO: 
```

**To Reproduce**
Despite my best efforts, I cannot reproduce the bug. I tried lining up the infantry along the shore to block the AI + clicking into the menu like mad, but no luck. I thought I should report it anyway.

**Expected behavior**
Clicking my unit would not crash the game.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.18.1

**Additional context**
Playing "Egg Islands" War Room map. I was over 15 turns into the game. My Mech + other infantry were lined one space away from the shoreline to prevent unloading.

**Comment by Robosturm** [comment]
I think you catched a very rare race condition.
I guess you need to click both mouse buttpns or keys like a maniac to reproduce it. I'm adding a check praying that it reduces the chance to 0
