### ISSUE TITLE
Units can move through enemy units when moving with the movement planner

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#438]
**Bug description**
If a unit is moving automatically thanks to the movement planner, it will not be blocked by enemy unit. It will pass through enemy units.

**To Reproduce**
Run a game where the two armies are controlled by the player. Plan movement with a unit from army A. With army B (the other army), put some units in the way of the units that will move with the movement planner.

**Expected behavior**
Units should always be blocked by enemy units, even when moving with the movement planner

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 18

**Comment by Robosturm** [comment]
Thx. That one was in the code for a century. :D
May also have an impact on some ai behaviour to the greater good. :)
