### ISSUE TITLE
Thread for audio assets

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#44]
Sorry for turning the bug tracker into a forum, you might want to unsuscribe from this to avoid e-mail spam. This is a thread for sounds like background music and sound effects.

As I've mentioned in [this thread](https://github.com/Robosturm/Commander_Wars/issues/20), I cannot loop Graves and Joey as their melodies are simply unloopable, plus many tracks sound like they fade too early and cut out half of the melody.

I've found an old [credits page](https://github.com/ctomni231/cwtactics/blob/master/credits.txt) for Custom Wars and tracking down the original composers is going to be hard. So on that note let's discuss what other music we could find and use for COs.

Here's some music that could be used (all listed tracks are of undecided CO unless otherwise indicated).
Any Metall Army CO: [Last Ditch Resistance (Metal Slug 5)](https://www.youtube.com/watch?v=OQslb9iPPoo)
[Formidable Guardians (remix by Jorge Fuentes)](https://www.youtube.com/watch?v=euxh0nD7F54)
Joey: [Jazzhands (Cthulhu Saves the World)](https://www.youtube.com/watch?v=BzJ-qhBf-_M)
[Red Alert (remix by Mozzarrati)](https://www.youtube.com/watch?v=WbduZB-5u4I)
[Hard Fight (Valkyria Chronicles)](https://www.youtube.com/watch?v=31VBezdHEd4)
Minamoto: [Fortune Night 2 (Freedom Planet)](https://www.youtube.com/watch?v=guJo2peKrrA) (Either this or Dragon Valley 2)
[Larries Lament (Super Meat Boy)](https://www.youtube.com/watch?v=4Iy41FJOVyU)
[Face to Face (Iji)](https://www.youtube.com/watch?v=5SHOvWhti98)
Graves: [Dooway to Heaven (Castlevania Symphony of the Night)](https://www.youtube.com/watch?v=R1BKsUTIBdE)

So what do you guys think? I could hunt down more, I know a large variety of video games I could take from, I just don't have the time atm. Haven't even brought up any Touhou yet.

**Comment by Robosturm** [comment]
And no problem i can easily unsubscribe if get too many mails. ;)

I can say Face to Face doesn't fit for Minamoto and i'm not a big fan of  "Red Alert".
The rest sounds pretty good.

**Comment by GuardianTempest** [comment]
Minamoto's only intended to have Fortune Night 2/Dragon Valley 2. Anything without a CO labeled could go to anyone suiting. Face to Face could go to a Dark Matter CO or maybe Cassidy. I'm not sure.

**Comment by Robosturm** [comment]
I see i thought that the songs below are alternate musics for this co. ;)

**Comment by GuardianTempest** [comment]
Wew, back from another absence. If you find better tracks for someone, feel free to bring it up.

Y'know, we could have a separate "music pack" mod that replaces all of the new COs with new themes. I'll update this list as needed. Don't hesitate to say something, many of the themes below are still tentative and open to changes.

Adam: I KNOW for certain that tracks from the Mega Man series fits him, I just don't know any
Aira: [Holy Battle / Leonia Battle Theme (Brigandine)](https://www.youtube.com/watch?v=JI4Grbg9Nv8) (it's a little short, I'll look for a better one)
Alexander: [East Forest (Rusty Hearts)](https://www.youtube.com/watch?v=skSo36lXnns) (he needs something that sounds more heroic)
Conrad: [Lock And Load II (Front Mission 5)](https://www.youtube.com/watch?v=e7GOESJveTk)
Graves: [Dooway to Heaven (Castlevania Symphony of the Night)](https://www.youtube.com/watch?v=R1BKsUTIBdE)
IK-486-B7: [Mech 8 (Unreal Tournament 3)](https://www.youtube.com/watch?v=liaNSxvPQGU)
Joey: [Jazzhands (Cthulhu Saves the World)](https://www.youtube.com/watch?v=BzJ-qhBf-_M)
Julia: [The Beep (Street Fighter 3rd Strike)](https://www.youtube.com/watch?v=S24bDa21lqY)
Mary: [Lobster King (Rusty Hearts)](https://www.youtube.com/watch?v=ie4mbhCIxTE)
Melanthe: [Messenger From the Deep Sea (Ragnarok Battle Offline)](https://www.youtube.com/watch?v=K9P_pWTJwQw)
Meiyo: [Under Siege (by Darren Curtis / DesperateMeasurez)](https://www.youtube.com/watch?v=BsZNf50mWlc)
Minamoto: [Fortune Night 2 (Freedom Planet)](https://www.youtube.com/watch?v=guJo2peKrrA) or [Dragon Valley 2 (Freedom Planet)](https://www.youtube.com/watch?v=zg0I3pA9nLU)
Nana: [Pretty Apricot (Riverbed Soul Saver, a Touhou fangame)](https://www.youtube.com/watch?v=e510x--2CzY) or [Forceful Step (Under Night: In-Birth)](https://www.youtube.com/watch?v=EUMO9UzPymw)
Napoleon: [Last Ditch Resistance (Metal Slug 5)](https://www.youtube.com/watch?v=OQslb9iPPoo)
Robosturm: [Gleipnir (Ace Combat X)](https://www.youtube.com/watch?v=5KxEmwOXv5s)
Sanjuro: [Samurai Sake Showdown (by Darren Curtis / DesperateMeasurez)](https://www.youtube.com/watch?v=NOGZX7Z4wSI)
Smitan: [Aggression and Victory (JoJo's Bizarre Adventure: All-Star Battle)](https://www.youtube.com/watch?v=yQ7RJ1xVnoY) or [Mad Monarch / Iscalio Map Theme (Brigandine)](https://www.youtube.com/watch?v=cwBZQNKeG5w)
Sophie: [Boss theme (Wild Guns Reloaded)](https://www.youtube.com/watch?v=Yyi-1n-a2Xc)
Xavier: [Another World Diego Brando (JoJo's Bizarre Adventure: Eyes of Heaven)](https://www.youtube.com/watch?v=5Bj6Z9VJHt4)

On that note, looking for Royalty/Copyright Free (and I do emphasize free) musicians would really help. Especially those who only ask for credits when people use their tracks.
