### ISSUE TITLE
Unit Bans not being applied to Factories

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#440]
**Describe the bug**
A Factory allows a player to build any unit, even if its banned.

**To Reproduce**
1. Create a Map with a Factory
2. Ban some units in the game setup
3. See that either the human player or AI can build banned units

**Expected behavior**
When units are banned they should not be buildable during that game

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.18.1

**Comment by Robosturm** [comment]
I tried to reproduce that bug but i didn't manage to pull it off.
Do you have any mods enabled?
How did you change the bans maybe a screen shot walkthrough of what you did may help.
I tested several ways but failed with each of them

**Comment by RicardoPires19** [comment]
I've tried without any mods and using the default options, but it still happens. Here are the screenshots.

![image](https://user-images.githubusercontent.com/7210193/111225342-99d0e880-85d7-11eb-88ba-9375295bcb9b.png)
![image](https://user-images.githubusercontent.com/7210193/111224731-c3d5db00-85d6-11eb-967e-805997133e26.png)
![image](https://user-images.githubusercontent.com/7210193/111225036-2cbd5300-85d7-11eb-93b0-6b81a5e77741.png)
![image](https://user-images.githubusercontent.com/7210193/111225151-55dde380-85d7-11eb-8f01-9e0c3578e287.png)
![image](https://user-images.githubusercontent.com/7210193/111225174-5f674b80-85d7-11eb-902a-b989b703be94.png)
![image](https://user-images.githubusercontent.com/7210193/111225227-7148ee80-85d7-11eb-8f0b-35da5f8da02c.png)
![image](https://user-images.githubusercontent.com/7210193/111225258-7dcd4700-85d7-11eb-8bf6-ce8a69b45f46.png)

**Comment by Robosturm** [comment]
Ahhh you're talking about the Black Hole Factory.
I was always checking the bases. 
Thx going to fux it
