### ISSUE TITLE
Black Hole Factory is unstoppable

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#444]
**Describe the bug**
The Black Hole Factory is capable of producing units even after the destruction of its pipeline weld.

**To Reproduce**
1. Create a map with a Black Hole Factory
2. Connect a pipeline with a weld to the Factory
3. Destroy the weld
4. Notice you can still build units from it.

**Expected behavior**
After destroying the weld, the Factory should become deactivated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.18.1

**Additional context**
I think a new game option should be created, where destroying the Factory pipeline weld ends the game or simply shuts down the Factory.

**Comment by Danmark25** [comment]
The problem is that Black Hole Factory can't be really destroyed since it have no HP thing.

The exception is on the campaign where is scripted that if weld on x,y position is destroyed then ends the game.

**Comment by Robosturm** [comment]
This behaviour is correct. If you want to have the Black Hole Factory stop or win the map by destroying a pipe weld.
You need to create a map/game-script for that.
In said script you can shutdown the black hole factory.
This is already done in the AW2 campaign maps.
In which the factory gets shut down by the script and the script spawns units for the ai so the challenge is similar to that of aw2.
The victory is as Danmark said also called by the script by checking if the weld got destroyed.

This is cause you could create maps like this where e.g. you have to destroy 3 pipe welds to shutdown the factory and destroying one weld slows down the factory e.g allowing only to build 2 units per turn or have no option to shutdown the factory at all.
![grafik](https://user-images.githubusercontent.com/48879701/111900842-095e3200-8a35-11eb-9e9a-a5961a294506.png)

**Comment by RicardoPires19** [comment]
Oh ok, is there any tutorial or example of such a script?

**Comment by Robosturm** [comment]
Depends on what you're heading.
The way wiht more options is prgramming it by hand in which case the existing scripts for the aw2 campaign are the way to go.
I guess the reason why you don't get an event is the following:
1. You need to have a condition first cause an event needs a condition on which it gets executed.
2. There is a button select near the condition button this selects the condition on which you wanna add an event
3. Press the add event button now the sekected contion is added and you can edit it.

**Comment by RicardoPires19** [comment]
I wasn't clicking on the select button, thanks.
