### ISSUE TITLE
AI Aircraftcarriers are unable to build Waterplanes

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#448]
Feels a bit strange that they're unable to construct these units. It feels like a vanilla unit type that the AI is unable to utilize.

**Comment by Robosturm** [comment]
As for building units with a unit this is nothing the AI can do and won't be able to do.
You may do something with this for the Heavy AI but the Normal and Very Easy AI will not gain this ability.
It simply screws around to much with the Economy of the AI and AW-DC AI wasn't able to do so as well.
