### ISSUE TITLE
Thread for visual assets

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#45]
This is a thread for the visual assets of Commander Wars, namely sprites and UI elements. Unsuscribing is recommended.

For an icebreaker question: For some factions, what are the inspirations behind their infantry sprites? I know Golden Sun looks like a Roman soldier (with their HQ looking like the Parthenon). Pink Frontier's infantry might be women with Aika's hairstyle from Valkyria Chronicles/Skies of Arcadia. I can tell Metall Army's group is composed of robots from the skin color.

Also, I think the weather tokens could be improved with further symbolization. Here are some MS Paint mockups, although better basic symbols could be taken from Google Images.
![image](https://user-images.githubusercontent.com/40665299/63169775-42207300-c06a-11e9-943e-8b60cf18f1ad.png)

**Comment by Robosturm** [comment]
I can say that Metall Army is a robot army somehow created by Lash. Since the faction is created more or less by  myself. The other armies are from Custom Wars or i guess AWBW since some of the Custom Wars faction are used in both "games",

The weather sprites definitely need a unique fitting style... currently they are randomly selected pictures. :(

**Comment by GuardianTempest** [comment]
Alright, I got something.

![Sun](https://cdn4.iconfinder.com/data/icons/the-weather-is-nice-today/64/weather_3-128.png)
![Rain](https://cdn2.iconfinder.com/data/icons/weather-flat-14/64/weather06-128.png)
![Snow](https://cdn3.iconfinder.com/data/icons/merry-flat-christmas/513/_11-128.png)
![Sandstorm](https://cdn2.iconfinder.com/data/icons/weather-color-2/500/weather-28-256.png)

Sandstorm icon intentionally large because the image has a lot of empty space, needs cropping.

**Comment by Robosturm** [comment]
Added them :) Changed the ingame scaling to auto adjust larger sprites to the drawing area for the weather icons. -> Only requirement now is a square image.
