### ISSUE TITLE
Adding slight screenshake when a unit is destroyed in battleanimations and in the overworld map

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#451]
**Please describe your feature request.**
Recently in CoW, battleanimations are getting closer to the real thing, but I think an important element that gives the original AW animations a lot of impact are the screenshake.

**Describe the solution you'd like**
In the original AW games, when a unit is destroyed in the overworld map, the screen shakes for a fraction of second, giving the animation a lot of oomf.
It is even more true in the battleanimations, where the screen shakes when there are explosions or when units are destroyed (other than infantry). It gives a lot of impact to the overall experience.

**Additional context**
Check this link for an example of AW2 original battleanimation and notice how the screenshake add impact:
https://youtu.be/m4wQDAY-TZ4?t=215

Also check this link to see how the screen shakes when Canons are firing:
https://youtu.be/m4wQDAY-TZ4?t=775

Overall I think screenshake would be a critical addition to give a lot of punch to the visual experience.

**Comment by Everglass** [comment]
I think I would also like to add that since Commander Wars displays information differently, experiment with screen shaking the map, battleanimation box or the whole screen and see which one you like the best. Could also demo them on the discord to get the community's opinion if you're still undecided.

**Comment by Robosturm** [comment]
Improvements of the effect may come once more people tried out the current version with the next release. :)
