### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Vision-Spire** [Robosturm/Commander_Wars#457]
[console.log](https://github.com/Robosturm/Commander_Wars/files/6290929/console.log)

**Comment by Robosturm** [comment]
While it is a crash i'm sadly not responsible for crashes which happen with none vanilla mods.
On top those mods are damaged or bugged.
The following mods you use have a problem:
unit_upscale32-mod
the_xanari_crew
KTEKNIS_Projects

In the log it's clear they have a problem with loading some requested sprites.
Further more one of the mods seems to try to load/play a none existing music or audio file....

On a sidenote please provide some additional context on crashes on what you did prior to the crash.
Thx,
