### ISSUE TITLE
Piperunners cannot move on Pipestations

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#46]
**Describe the bug**
There's a building in the game called "Pipestations" that has a description saying it can resupply and build pipe units, however, pipe units cannot move on it. And when you try to build a Piperunner from it, it disappears and you still lose the money. 

**To Reproduce**
Place down a Pipestation and try moving pipe runners across it and try producing a Piperunner from it.

**Comment by Robosturm** [comment]
The disappearing of the piperunner is a direct result of a missing entry of the movementtable of piperunners.
Fixed in the next release piperunners can cross pipestations and can be build on them.
Thx for the report.
