### ISSUE TITLE
List of Battleanimation fire misalignments

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#467]
Here's a list of all of the misalignments that I was able to notice in the battleanimations:

-Mortorbikes mg slightly off.
-Metal Army Snipers slightly off.
-Anti-tank Cannon slightly off.
-Artilleries slightly off, Metal Army Artillery battleanimation is really messed up though.
-Artillerycraft slightly off.
-For Anti-Air; Orange Star, Blue Moon and Black Hole is slightly off vs ground. Yellow Comet is slightly off for both ground and air. Metal Army vs air could use the mg fire up animation. All of the Anti-Air could use a second firing animation for their second cannon (besides Yellow Comet that just has one cannon).
-Hoverflak could also use the second firing animation for it's second cannon.
-For Light Tanks; Orange Star, Blue Moon, and Metal Armies cannon is slightly off, Green Earth mg is slightly off and Yellow Comet, Black Hole have both cannon and mg slightly off.
-Hovercraft both cannon and mg slightly off.
-For Heavy Tanks; Green Earth, Yellow Comet and Black Hole cannons are slightly off. Blue Moon cannon and mg are slightly off, while Metal Army both are way off.
-Megatank's cannons slightly off.
-Missiles are slightly off (Metal Army looks fine though?)
-Rocketthrowers are also slightly off? They shoot so fast it hardly makes a difference.
-Battleships slightly off, Metal Army is very off.
-Destroyers cannons feels off? (I don't know, the cannons kind of fire inside the sprite, and the cannons for the Destroyer kind of face upwards like an artillery. Making me feel they should use the artillery fire animation instead of the cannon fire animation.)
-All Cruisers animations are off, besides the Metal Army cruiser.
-All Battle Copters Mgs are off, Blue Moon is very off.
-Bombers drop bombs facing backwards, I feel like they should be flipped. Metal Army bombers, the bombs drop a bit bellow them.
-Kirov bombs also fall outside of them, while also facing backwards.

I should also note that all the animations that are only slightly off are only like 1 to 2 pixels off, they look perfectly fine if left only. The battleanimations that really need to be addressed are:

-Metal Army Artillery, their sprites jump around during the fire animation, probably the most that needs to be addressed.
-Metal Army Heavy Tanks
-Metal Army Battleships
-Cruisers (besides Metal Army, they look fine.)
-Battle Copter mgs, Blue Moon's especially
-Metal Army Bombers and Kirov (the backwards facing bombs for the bomber don't really look all that bad though, not that important)

**Comment by Everglass** [comment]
Also, I feel like many of these misalignments could be something that I could address for you, so to lighten your work load a little bit. The only issue is that I know you've already made a ton of updates to the battleanimations, so I'm not entirely sure how I would go about sending you the updated battleanimations.

**Comment by Robosturm** [comment]
I think the list is to big to completly make it into the next release.
So i think I'm going to state which ones i fixed and.
We see who does the rest after the release, cause a lot of the animation code got touched....

**Comment by Robosturm** [comment]
* Fixed ma artillery jumping --> nothing done for the canon fire part.
* fixed ma heavy tank mg
* fixed all battle copter sprites
* fixed cruiser mg + fixed os cruiser sprite
* i think the ma bomber bombs look fine now....
* moved the kirov bomb start place to a more reasonable place

**Comment by Robosturm** [comment]
@Everglass I'm assuming your doing the job of changing the scripts.
If you don't want to do it anymore let me know.
And don't hurry you have months of time to do so ;)
