### ISSUE TITLE
Battle is not over in Bean Island (2P) map

### ISSUE THREAD

**Issue by WedaSan** [Robosturm/Commander_Wars#469]
**Describe the bug**
Battle still continues even after I destroy all enemy units and even capture their HQ.

**To Reproduce**
1. I destroyed all enemy units.
2. Battle was not over and enemy can still build new units if I leave their Base open.
3. Tried to win by another way: capture enemy HQ.
4. Battle was still not over even after capturing enemy HQ.
5. Tried the other way around with different CO: I built a unit on Day 1 then deleted it on Day 2. 
6. The battle should end with my defeat, however it still continues.

**Expected behavior**
Battle should be over if I destroy all enemy units or capture enemy HQ and same goes for them too when they capture my HQ or I lose all of my units, even if I purposely delete my last unit. The other maps I played so far are like that even without changing the map rules just before choosing COs.

**Screenshots**
![bug2](https://user-images.githubusercontent.com/83910299/117573496-d10cd300-b10a-11eb-89c8-e43647487d9f.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [0.18.1]

**Additional context**
I never messed with anything in the file. In fact, I just downloaded the latest version (0.18.1) yesterday and started a fresh new game from there. Never transfer any files from older version (0.16.0), worry the game might get glitched anyway, especially if I transfer save file (.sav) with CO(s) who haven't been unlocked in newer version as I need to buy them first from Shop.

**Comment by Robosturm** [comment]
Fixed in Beta 19. But it's not a big problem in 18.1 either just scroll to the victory rules before starting the map and change them so some exist. Seems like the map was saved in a wrong state.

**Comment by WedaSan** [comment]
How do I transfer my game progression to Beta 19? Especially my hard-earned points as well as achievements.
