### ISSUE TITLE
Some infantry units become invisible

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#47]
**Describe the bug**
For some reason some infantry units become invisible when unloaded. So far it happened once with me when I unloaded an infantry from a transport helicopter. It was still possible to capture with it. Also happens with AI players.

**To Reproduce**
1 - Load infantry on transport vehicle.
2 - unload it.
3 - It should be invisible.
Doesn't always happen.

**Expected behavior**
The unit shouldn't have become invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/7210193/63216441-347ff180-c12d-11e9-9dc3-aff477fbc11f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903

**Additional context**
In this same turn, when Olaf captures the yellow HQ, the game crashes. Don't know if it's related. Should I open a new issue?

**Comment by Koopanique** [comment]
I think these bugs have both been reported here:
https://github.com/Robosturm/Commander_Wars/issues/38
and here:
https://github.com/Robosturm/Commander_Wars/issues/40
but Robosturm may have additional context

**Comment by Robosturm** [comment]
Hi  RicardoPires19,
if you're playing a savegame/continued the game from a savefile the bug gas been reported as mentioned by  Koopanique. So the question is: Is this a savegame you play?

The AI capture crash bug has been reported and fixed as well.
Still thx for your reports.
@Koopanique thx for your reply with the bug links.

**Comment by RicardoPires19** [comment]
@Robosturm I started this game on the latest release you have (Commander Wars Beta 5). I did try to reload this game since it crashed. Reloading fixes the sprites missing but doesn't prevent the game from crashing.

**Comment by Robosturm** [comment]
@RicardoPires19 as for the units beeing invisible i meant did you load the game from a savegame and afterwards realized that some units are invisible? As described in the bug here [https://github.com/Robosturm/Commander_Wars/issues/38](https://github.com/Robosturm/Commander_Wars/issues/38). If so it's already fixed.

The AI crash will be fixed in the next release not in the current one. Afterwards you can continue the game. Sry for the inconvenience.

**Comment by RicardoPires19** [comment]
Yes, I think it started to happen after I reloaded the game.

No problem, maybe you should release a Makefile or a tutorial on how to compile the game ourselves so that we can play on the latest version available.

**Comment by Robosturm** [comment]
@RicardoPires19  already done ;) take a look here [https://github.com/Robosturm/Commander_Wars/wiki/Build-Infrastructure](https://github.com/Robosturm/Commander_Wars/wiki/Build-Infrastructure)
Under Step by Step-Setup i tried to explain how to do so. ;)

**Comment by RicardoPires19** [comment]
Well, then I'll close the issue. Thanks for the game and keep up the good work!
