### ISSUE TITLE
Suggestion: Olaf and Sonja's American/Europan appearances

### ISSUE THREAD

**Issue by WedaSan** [Robosturm/Commander_Wars#470]
As I played all original AW games from first to DS ones, I get used to Olaf in BROWN haired/bearded and Sonja in GREEN clothes/no-glasses from AW1, AW2 then AWDS. 

So it's kind of strange to see Olaf suddenly has WHITE haired/bearded and Sonja wearing RED clothes as well as glasses. Seems like it's their apperances from Japanese version of original AW games (AW1, AW2, AWDS). 

Other COs may also have appearance differences between Japanese and American/Europan versions. COs like Nell, Drake, Kanbei wore different clothes (not as alternate clothes, it's their main ones) in Japanese version. If I remember correctly, only for their AW1 appearances.

My suggestion is could you add both Olaf and Sonja's appearances from USA/EUR games? Even if it's just as more options on their CO Style. 

*Updated, as I originally wrote this before purchasing any CO Style in version 18.1.*
Wow, seems like you already added their AW1 appearances too. Both USA/EUR and Japanese versions since version 18. 😀

Though it still lacks the one I requested. I'll help about their looks I mentioned, along with their alternate outfits.
![olafawds](https://user-images.githubusercontent.com/83910299/117600271-35b54580-b17e-11eb-9161-442a2848ca27.png)
![sonjaawds](https://user-images.githubusercontent.com/83910299/117600308-45348e80-b17e-11eb-97c0-1bd2f4756b86.png)

Can't wait for their AW2 appearances too in the future. 😀

**Comment by WedaSan** [comment]
I'll help with AW2 appearances too. 
![Uploading Full Sheet View - Advance Wars 2_ Black Hole Rising - Character Profiles.png…]()

**Comment by Robosturm** [comment]
So i checked the game and those styles are already in the game.
You just need to change the default palette in the CO-Style and of course you can create your own style by changing each color indiidiually.

Just some sidenotes before you go and create the CO-Styles. I would add them to the game. The main reason is i didn't want to do the work.
But if you want to that work i happily add it. Please checkout the namings in the folder resources/images/co to see how the fileshould be named.
Here's what you need to do:
* Main-sprite containing the full-art body ending with +CustomName
* A 3 frame sprite containing the mood-sprites for battle and dialogs normal, happy, sad
* A info spotlight sprite on the face 
* A colortable for mapping to the alternate styles. The first line contains a pixel of each color in the original inage of the full-body.
Each following line is an alternate style containing the color to which the color from the first line should be mapped,

You can also test this locally by adding the new sprites to the res.xml laying in the same folder.
And afterwards changing to the folder "resources\scripts\cos" find the js script of your co open that file in a text editor.
Find a line like this normally it's at the start of the file:
this.getCOStyles = function()
    {
        // string array containing the endings of the alternate co style
        // e.g. co_adder has ["+alt"]
        return ["+alt", "+alt2", "+alt3"];
    };
And add the alt ending to the list.

**Comment by WedaSan** [comment]
I did find the folder you mentioned. Their pics are under bm & yc folder. 

Please do add them. I don't even have their sad/happy expressions. Besides I'm not really good at editing pictures.

**Comment by Robosturm** [comment]
You can just use the same expression if you don't have them. ;)

**Comment by WedaSan** [comment]
It just feels incomplete without them, especially after you added their US/EU AW1 look.

**Comment by WedaSan** [comment]
I'll do it. The hardest part would be "peeling" the background so I might need help.

**Comment by WedaSan** [comment]
Done with Sonja. 
All that left is to peel the background. Kinda difficult to do it myself with Eraser Tool.
![co_sonja+alt4+nrm](https://user-images.githubusercontent.com/83910299/117663841-afc3e980-b1d3-11eb-8709-1d1a31540db4.png)
![co_sonja+alt4+face](https://user-images.githubusercontent.com/83910299/117662256-f0bafe80-b1d1-11eb-97ca-1215f6adcfec.png)
![co_sonja+alt4+info](https://user-images.githubusercontent.com/83910299/117662267-f284c200-b1d1-11eb-8133-f7c516bb1a2c.png)
![co_sonja+alt5+nrm](https://user-images.githubusercontent.com/83910299/117663733-9327b180-b1d3-11eb-8ae7-d22c89d6eead.png)
![co_sonja+alt5+face](https://user-images.githubusercontent.com/83910299/117663736-9458de80-b1d3-11eb-90c9-195243d4de98.png)
![co_sonja+alt5+info](https://user-images.githubusercontent.com/83910299/117663738-94f17500-b1d3-11eb-8432-b25741dd0466.png)

**Comment by Robosturm** [comment]
No the AW-DS version of the default version of Sonja without classes isn't part of the game.
But the recolored versions are.
