### ISSUE TITLE
I lost my purchases!

### ISSUE THREAD

**Issue by WedaSan** [Robosturm/Commander_Wars#471]
**Describe the bug**
All COs and outfits I bought so far are gone but my Points still stay deducted. 

**To Reproduce**
1. I had about 10k points before doing any purchase
2. COs I bought: Nell, Hachi, Hawke, Sturm, Von Bolt, Tabitha, Caulder
3. Outfits I bought: Olaf & Sonja, to try out altering their appearance like you suggested and it worked, though Sonja still wears glasses
4. When I saw Olaf suddenly back to white haired/bearded again while playing Campaign, I tried to change his color again...
5. Checked CO Style but his edit is no longer there
6. Checked the Shop and...all my purchases are returned but I DID NOT GET MY POINTS BACK. 
7. It's as if Hachi stole all my purchases but keeping all my money spent on him. 
8. So now I have about 400 point AND all stuff I bought returned to Shop. 

**Expected behavior**
All my purchases should stay permanently unless I delete the username file. I was excited that the price is lowered compared to version 18.1 and I didn't spend any point at all in that version. 

**Screenshots**
![IMG20210511215639](https://user-images.githubusercontent.com/83910299/117829715-9be8b800-b2a5-11eb-8f00-928ad25edcce.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [0.19.0]

**Additional context**
I had war between Sturm/Hawke, Von Bolt/Kindle, and Caulder/Tabitha. After some time, some CO Power meter suddenly decreases despite none uses CO Power. First happened to Hawke when his is almost full (8 stars) suddenly became 4-5 stars. Then it happened to 3rd team. Is it a bug or any of those CO has power that reduces CO Power or caused by weather instead? There's no Sasha using her CO Power.

**Comment by Robosturm** [comment]
In that case i'm kinda lost what coould be the cause unless you killed the game by turning off your pc while CoW was still running or shouting it of using the taskmanager.... and the way the userdata gets stpred hasn't changed in a long time and no one ever had a problem with it.

Also please report seperate issues/bugs in a new issue.
One issue should contain one problem not multiple ones, so i can manage them. Thx.

**Comment by WedaSan** [comment]
Sometimes I did when my device was hanging. Luckily I made back up of my username file before purchasing anything. And the game is somehow a bit lag compared to 18.1.

Even shutting with alt+f4?

I see. I did it so I don't want to be thought as double posting. So one post for one issue it is. And I should report it under "bug" as well if I find something similar?

**Comment by Robosturm** [comment]
Shutting it down this way may potential ruin your dat-file in the current version and probably in any future one.
Is it laggy when you perform an action like firing? If so i know the reason, but i'm experimenting there on how to sync up the data and the rendering.

As for hanging when loading a savedata. That's normal always remember this is a hobby-project so loading won't be as smooth and cool as you know it from a normal game.

Yes one post for one issue if a double post happens i will link it and close one of them so don't worry about that. That is easier solved than two issues in one post.
Reporting as bug makes it easier but isn't as important.

**Comment by WedaSan** [comment]
The gameplay itself is not lagging. The lag is when the audio plays late. Like when my opponent's turn comes but the music playing is still my CO. Even sound effects too like when firing or capturing. Somehow the lag happened less commonly in 18.1.

Sometimes the game force closes by its own but I don't remember when.

Even if it's a hobby-project, it's the best AW game for me. I'd love to recommend it to AW fans.

**Comment by Robosturm** [comment]
The game force restarts itself when changing mods or certain options in the first option screen mainly username. I should add a message box before it happen to make it clear. But out of that it's a bug which created a silent crash.

Sounds get started asynchron but unless you have a very slow pc you should never notice it  Unless your harddrive is pretty slow which would explain the lost data as well....
