### ISSUE TITLE
fullscreen battleanimation background bug

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#478]
during fullscreen detail modes air background resets and turns partially grey... background normal in detailed mode

![backgroundbug](https://user-images.githubusercontent.com/75344715/120421186-aaf9dd80-c31a-11eb-88ca-4f24e917a620.png)

**Comment by Robosturm** [comment]
I'm not able to reproduce that bug. 
Do you use any mods?
What's your screen resolution?

**Comment by TeslaTrooper09** [comment]
im using aw2 image mod, aw airforce mod, and awds co mod, screen res is 1920 x 1040, fullscreen

**Comment by TeslaTrooper09** [comment]
i removed my mods and reproduced it on battle animations: detailed fullscreen

**Comment by TeslaTrooper09** [comment]
detailed transparent crashed the game

**Comment by TeslaTrooper09** [comment]
[console.log](https://github.com/Robosturm/Commander_Wars/files/6586612/console.log)

that is using detailed transparent, which crashes the game. the error takes place as the removal of destroyed units is taking place

**Comment by Robosturm** [comment]
I found the issue for the crash.
But i can't produce the visual glitch. :(

**Comment by TeslaTrooper09** [comment]
windows

**Comment by Robosturm** [comment]
Okay i can see the bug in the released version but not in the current branch state.
Though i can't remember changing anything related to that there....
Well for now i'm assuming i fixed the glitch somehow and recheck it before i upload the next release. :)
