### ISSUE TITLE
Suggestion: The order in which mods are loaded, and one other minor issue

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#48]
Hey there, sorry if this post is a little too long.
First off, I noticed the game loads mods in an order depending on a string stored in the .ini file, which in turn is generated based on the order the player selected them in the settings menu. I've already confirmed this using the console.
I think this probably isn't the best way to handle it because people might want to make mods that are dependent on another mod and need to ensure one's always loaded before the other. For example, let's say you made a mod that adds new COs to the game (it's probably bad practice to just add them directly to the resources folder), and let's say you also made a second optional mod that slightly changes your new COs (like the AW:DS COs mod), you obviously don't want the game to load the latter first or there'll be an error. It'll be referring to a CO that hasn't been defined yet.

I think one fairly simple solution to that is to have them loaded in alphabetical order. This way, modders can basically sort them in the intended order.

Speaking of alphabetical orders, another thing I wanted to bring up is that any new COs added by mods are always at the end in the CO selection and CO info screens when they should be sorted alphabetically with the others. I think I know why this is the case, and yes I know it isn't really that big of a deal, which is why I decided to mention it here instead of making another post about it. It does bother me more than it should though... maybe it looks disorganized? I think if custom content were meant to be added with mods, things like this should've been better organized. (Personally, due to name conflicts I'm tempted to replace/remove some existing COs that I rarely use, which will likely result in further disorganization if those are the only new COs to not be at the end as they appear where the old COs they replaced used to be.)

I understand it's because the game reads the contents in the resources folder first, and I have a feeling it's harder to fix than it sounds. Alternatively, maybe the alphabetical order can just be dropped completely for a more organized order? I mean, you'd expect some characters like the protagonists (Andy, Max and Sami) to appear first.

...or maybe I'm not supposed to add new COs with mods and I'm doing it all wrong. I just thought it'll be far easier to share custom content with friends if installing them didn't involve editing a bunch of files in the resources folder.

**Comment by Robosturm** [comment]
Good sugestion i changed the loading order internal after reading the ini-file so that the mods are always loaded alphabetical.
I changed that after the co's  and other mods were loaded the internal data objects resort their list in alphapetical order.  
I was just lazy when i implemented those so i skipped any resorting of the lists.

Hi if you wanna add a new CO with the same name let's say Amy. 
You can do the following trick name it CO_1AMY or CO_AMY1 and change the CO object you create in the js-file. The engine matches file names as global unique objects. The internal shown names however can be the same. So if you return the CO-Name as Amy and let's say make her part of OS you have to CO's named Amy hopefully with different sprites 😄 and you can play both.

And changing the actual ressource folder is not they way to go. If you want additional content, create a mod if something feels strange or doesn't work. Ask me and i mostlikely try to add the content to the wikipage or link one of the wikipages if i did already.

**Comment by XnKradst** [comment]
Hey, thanks for fixing both issues, really appreciate that!
I mostly mentioned the non-alphabetical sorting as an alternative just in case the first solution isn't possible, but since you already made it so that any new COs are sorted alphabetically with the others, it's all good!

As for the name conflict solution, thanks for the suggestion. I'm aware I can do that but I was kinda hoping it didn't have to come to that, No worries though, I realized the "co_" prefix is probably optional so I can just omit it (as long as the name isn't already a variable somewhere) or replace it with a different prefix. Let me know if I'm wrong about the prefix though.
That said, I believe changing the prefix might ruin the alphabetical order yet again (unless they're sorted by the names shown in-game instead of the identifiers), but I guess I can deal with that... at least now all of them are placed at the end (or start) and I no longer have to replace any existing COs, which probably isn't a good idea.

**Comment by Robosturm** [comment]
Yeah the "co_" prefix is just a prefix to avoid naming conflicts in the global javascript-namespace and can be replaced by anything else or omitted. You could also make the prefix like co_modname_amy...
The co's are sorted by the alphabetical order of the filenames right now. 
I could change that but the effort compared to the benefit is not worth the work.

Yeah replacing existing stuff works but isn't a good way to make a mod compatible with other mods.
E.g. having two CO-Mods active wouldn't work then. ;)

**Comment by XnKradst** [comment]
I see. I agree it's not worth the effort since I'm probably the only one bothered by it, even though I would greatly appreciate it. But anyway, thanks again for the fixing the issues, I'll look forward to the next release.

Just saying, I think `co_modname_amy` would still put the CO out of the alphabetical order, although a simple solution would be putting the mod name at the end as a suffix instead. Honestly, the reasons I'm avoiding IDs like `co_amy1` are so "personal" that they probably won't affect other players. It's all good, I can work around that now that everything is sorted alphabetically. :P

**Comment by Robosturm** [comment]
You could also do something like "**co_amy_modname**" which would but the co in alphabetical order as well and avoid some id like stuff. ;)

**Comment by XnKradst** [comment]
Exactly, that's what I meant by suffix and it's what I will be doing now. It's probably the best solution as it also avoids any possible name conflicts with other CO mods.

**Comment by Robosturm** [comment]
Good i'll close the issue. If you find anything else that can be improved with the modding system don't shy away from creating a new issue.
