### ISSUE TITLE
Several War room maps miss a victory condition

### ISSUE THREAD

**Issue by KTeknis** [Robosturm/Commander_Wars#481]
I was doing War Room Campaign on Sole Harbour, mod used are KTEKNIS_Project, Xanari_Crew, Voida Aegalus, and the Air Force mod, CO used are Damaskas.
When Capping HQ Colin's HQ, the game didin't go to the result screen and kinda freezes. The following error message was produced:

Critical: Invalid item found. mods/the_voida_aegialeus/images/co//tm/co_mravax+alt+nfo.png File:  Line: 0 Function: 
Critical: Invalid item found. mods/the_xanari_crew/images/units//zzzjill_advanced_rockets.png File:  Line: 0 Function: 
Critical: Invalid item found. mods/the_xanari_crew/images/units//zzzjill_advanced_rockets+mask.png File:  Line: 0 Function: 
Critical: Invalid item found. mods/the_xanari_crew/images/units//zzzjill_advanced_rockets+walk+mask.png File:  Line: 0 Function: 
Critical: Invalid item found. mods/the_xanari_crew/images/units//zzzjill_advanced_rockets+walk.png File:  Line: 0 Function: 
Info: 05.06.2021 10:30:19: Enter "help()" for console info. File:  Line: 0 Function: 
Info: 05.06.2021 10:30:19: Starting Game... File:  Line: 0 Function: 
Info: 05.06.2021 10:30:19: Prepare to Fight... File:  Line: 0 Function: 
Info: 05.06.2021 10:30:19: Read this message while waiting... File:  Line: 0 Function: 
Info: 05.06.2021 10:30:19:  File:  Line: 0 Function: 
Info: 05.06.2021 10:30:19: If the code and the comments disagree, then both are probably wrong. File:  Line: 0 Function: 
Info: 05.06.2021 10:30:19:  File:  Line: 0 Function: 
Critical: 05.06.2021 10:30:25: SyntaxError: Expected token `;' in File:D:/commander_wars/mods/the_voida_aegialeus//scripts/cos/co_khenare.js in File: file:///D:/commander_wars/mods/the_voida_aegialeus//scripts/cos/co_khenare.js at Line: 174 File:  Line: 0 Function: 
Critical: 05.06.2021 10:31:57: SyntaxError: Expected token `;' in File:D:/commander_wars/mods/the_voida_aegialeus//scripts/cos/co_khenare.js in File: file:///D:/commander_wars/mods/the_voida_aegialeus//scripts/cos/co_khenare.js at Line: 174 File:  Line: 0 Function: 
Critical: 05.06.2021 10:31:57: can't find resource: 'hidden' in 'mods/the_xanari_crew/images/game/res.xml' File:  Line: 0 Function: 
Critical: 05.06.2021 10:31:57: can't find resource: 'hidden' in 'mods/the_xanari_crew/images/game/res.xml' File:  Line: 0 Function: 
Critical: 05.06.2021 11:11:38: ReferenceError: animation2 is not defined in File: file:///D:/commander_wars/resources//scripts/cos/co_colin.js at Line: 25 File:  Line: 0 Function: 
Critical: 05.06.2021 11:17:01: ReferenceError: animation2 is not defined in File: file:///D:/commander_wars/resources//scripts/cos/co_colin.js at Line: 25 File:  Line: 0 Function: 
Critical: 05.06.2021 11:17:13: TypeError: Cannot call method 'removeUnit' of null in File: file:///D:/commander_wars/resources/scripts/general/unit.js at Line: 280 File:  Line: 0 Function: 
Critical: 05.06.2021 11:17:13: TypeError: Cannot call method 'removeUnit' of null in File: file:///D:/commander_wars/resources/scripts/general/unit.js at Line: 280 File:  Line: 0 Function: 
Critical: 05.06.2021 11:17:13: TypeError: Cannot call method 'removeUnit' of null in File: file:///D:/commander_wars/resources/scripts/general/unit.js at Line: 280 File:  Line: 0 Function: 
Critical: 05.06.2021 11:17:13: TypeError: Cannot call method 'removeUnit' of null in File: file:///D:/commander_wars/resources/scripts/general/unit.js at Line: 280 File:  Line: 0 Function: 
Critical: 05.06.2021 11:17:13: TypeError: Cannot call method 'removeUnit' of null in File: file:///D:/commander_wars/resources/scripts/general/unit.js at Line: 280 File:  Line: 0 Function: 
Critical: 05.06.2021 11:17:13: TypeError: Cannot call method 'removeUnit' of null in File: file:///D:/commander_wars/resources/scripts/general/unit.js at Line: 280 File:  Line: 0 Function:

**Comment by Robosturm** [comment]
Since you're using multiple none vanilla mods.
I'm ignoring the console errors, since most are created by those mods.
Please only rely on console errors if you use only vanilla mods or vanilla scripts.

However one bug is related to #480 Colins power bug.
Regarding the none existing wins several war room maps seem to miss a victory condition

**Comment by WedaSan** [comment]
Like that Bean Island I mentioned in the other day?

**Comment by Robosturm** [comment]
Yes somehow some maps lost there victory conditions during a process, which isn't a big deal since reapplying them is a one second task.
