### ISSUE TITLE
Option to disable the mouse scrolling sound effect, or possiblely other sounds as well

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#487]
An option to disable the sound effect that plays when moving the cursor around the map for some players. As for some people who use the mouse for selecting, this effect can often play multiple times which can irritate some people.

This could also be extended for disabling other various sound effects to which other may not find audible pleasing.

**Comment by Robosturm** [comment]
Disabling specfic sounds is n't really something i want to add and the cursor ticks happen for each tile the cursor moved just like in aw. Also the sound system has  no the correct timing so it feels smooth for me.
