### ISSUE TITLE
Unit's detroyed during an HQ capture counts against you for units lost and tech score.

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#489]
During the match with Tesla_Trooper, he ended up getting a clutch hq capture winning the game. However, it seems a bit disingenuous for all of the units on the map destroyed by an hq capture to count against you for your tech score and player statistics. I was playing Sensei even, and ended up with more infantry units lost then produced in the player statistics -_-

**Comment by Robosturm** [comment]
Is only the produced/destroyed/lost statistic affected by this?
