### ISSUE TITLE
Suggestion: Yielding, Delete Units and Status Options In-Game. 

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#49]
There are some useful In-games options from the original Advance Wars games that are absent from this one. that I personally think should appear in the In-game "pause" menu. 

**1.) Yielding**
Quite surprising that this isn't a choice in the In-Game menu yet. Ik there's an "Exit Game" option but all that does is just quit the game. Yielding however is where a team surrenders outright. In matches that contain more than 2 teams, a team could Yield which would remove them from the match, turn all their buildings into neutral ones and destroy al their units. And in 1v1 matches, yielding would allow you to end a game that already is pretty decided sooner, while still showing the victory screen.  
Basically: A team that yields automatically makes them lose. (Also, there should probably a confirmation window that appears after clicking on yield, asking whether or not you really want to yield. ) 

**2.) Delete Unit**
I've had a few cases where I accidentally spawned in a unit that I didn't want and the only I could get rid of it is when it's destroyed. There should be an option that allows you to delete a unit entirely from your team that you don't want. (Note: You should only be allowed to delete units that have not been moved yet and you can only delete units from your own Army.)

**3.) Status Menu**
The other games have this, it's basically a menu that shows the status of the current match. Basically, it includes:

-The Number of Units each army has Produced 
-The Number of Units each army has lost
-The Amount of Income each army receives at the start of each turn
-The Amount of Money each army currently has
-The Number of Bases each army has.
-The Number of Neutral bases left
All in the same window. However, this last one isn't really that important (I don't think).

**4.) Exit Game Issue**
This one isn't so much of a new feature suggestion as much as it is a change. Currently, you can choose to exit the game from the pause menu, however, it's awfully close to the "End Turn" button.  I've had a few instances where I accidentally clicked on "Exit Game" when I was trying to end my turn instead. There are a few solutions to this:

1. A Confirmation window asking whether or not you really want to Exit the game when you select it. 
2. Moving the Exit-Game button higher up in the in-game menu. 
3. Remove the "Exit-Game" option entirely from the In-Game Menu. As there's already a giant "Exit Game" button on the bottom of the screen
^^ This last one is a bit more of a request more than anything, it's not really something that *really* needs to be done.

P.S What I mean by "In-Game Menu" is basically the pause menu that pops up when you select a non-functioning tile in-game. (A tile that doesn't do anything else when you click on it)

**Comment by GuardianTempest** [comment]
I think Yield support also has use in campaigns, primarily by allowing NPC dialogue to give you advice as well as have some kind of alternate routes in campaigns.

In the canon games, can you delete your own units in multiplayer? I think there's a CO whose powers involve Deletion, but that could be old info from Custom Wars days.

**Comment by Robosturm** [comment]
added surrender option (i prefer surrender over yield)
added quit confirm screen to exit game option -> since i needed a confirm screen for surrender i added it to both.
changed order of exit now it's
surrender, exit, save, next player

**Comment by Robosturm** [comment]
added delete units option: Difference to the original game is that you have to select the delete option everytime you wanna delete a unit and you get all own units that can be deleted marked with a target field marker same as when you select a unit to for an attack. So you can also toggle through the units with next and previous unit. ;)

**Comment by Robosturm** [comment]
And the game info:
![Gameplay53](https://user-images.githubusercontent.com/48879701/63292533-26190d80-c2c6-11e9-92d2-58768cb5855a.png)

**Comment by Seimix** [comment]
> In the canon games, can you delete your own units in multiplayer? I think there's a CO whose powers involve Deletion, but that could be old info from Custom Wars days.

Yes, you can delete your own units in Multiplayer iirc. Also, thanks for the quick additions, Sturm. 😄 I'm excited to see this game to continue to grow!
