### ISSUE TITLE
Brand new player keeps crashing

### ISSUE THREAD

**Issue by Hakimblue99** [Robosturm/Commander_Wars#490]
**Describe the bug**
New player, downloaded the game. But everytime I play any map for a few minutes, it keeps crashing. And I get this.
[20210630-225118 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/6741830/20210630-225118.Commander.Wars.Crash.log)

I'm not sure t's because wether my laptop couldn't handle it(because mine is Windows 7) or I did something wrong. Or perhaps I lack certain programs to run the game on my laptop?

**Comment by Hakimblue99** [comment]
Redownloaded the game. No problems so far.

**Comment by Robosturm** [comment]
Do you know what you did before the game crashes?
Do you have any mods active?
Did you have any special settings for gameplay like skipping animations or changed animation speed?

**Comment by Hakimblue99** [comment]
No mods at all. And no special settings for gameplay. I was doing advance wars 2 campaign.

**Comment by Robosturm** [comment]
Understandable.
I have never run the game on Windows 7 but i don't think that's the root of the problem.
I did some imrpovements in regards of not crashing for the next release and i'm going to check if can find a cause for your crash.

**Comment by Hakimblue99** [comment]
Okay. Thanks.

**Comment by Robosturm** [comment]
What you could do in the meanwhile i susing version 18 instead.
It had a different memory usage system, so it may run on your system.
You can get it here:
https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_18_1

**Comment by Hakimblue99** [comment]
Been trying out version 18, no problems so far. No constant crashing. If there's any other bug, I'll make a new thread. Thanks for the assistance. The game is really fun.
