### ISSUE TITLE
Ally Animations don't show Allied units being Attacked

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#492]
No idea if this a bug or what, but when your animations are set to "Ally", Battle Animations of you or your Allies  **being** Attacked **don't show**. However, **when your allies are the ones attacking** the Battle Animations DO show.

There either should be an animation option where all the Ally Animations + Ones of them being Attacked are shown, or you should be able to see Allies Being Attacked when the "Allied Animations Only" is set.

**Comment by Robosturm** [comment]
I tried to reproduce this bug, but i'm not able to verify it.
Detailed Battle Ally should show all battles in which the last human player and his allies are involved....

**Comment by Seimix** [comment]
I'm not referring to the "Only Detailed Battles Ally" ones, I'm referring to the Standard "Ally" animations. 
"Only Detailed Battles Ally" ONLY shows battle animations and no other animation. 
"Ally" animations show the battle animation of you and your allies attacking, but it doesn't show the animations when it's the AI Enemy's turn and they are attacking your units. So your units kinda just...disappear suddenly while it's their turn.

To Reproduce:
1. Set your animation type to "Ally" (NOT "Only Detailed Battles Ally")
2. Create a map with some Predeployed units and a team of 2 players vs 1 CPU. (Make sure to put the enemy units in range of yours)
3. Skip the two-player turns and let the AI take its turn.
4. All the AI animations should be skipped, which includes the Battle Animations of the AI attacking your units. 

I was also able to confirm this is the case with the just "Own" in-game animations as well.

My point being here is when the animations are set to "Ally" or "Own", you should still at least know when your units are being attacked by enemy forces. Since Battle Animations of the enemy attacking you just don't show.
