### ISSUE TITLE
Suggestion: Team Counter for "Units Destroyed" and "Buildings Owned" Conditions in the Event Editor

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#493]
The title pretty much says it all. 
The "Units Destroyed" and "Buildings Owned" conditions in the event editor only count for individual PLAYERS (apparently) rather than teams when I feel like there should also be an option to count for the total amount a TEAM has killed or owns.

**Comment by Robosturm** [comment]
This is something. You need to achieve by manually writing the script for it.
The ingame script editor is meant to cover basic functionality for people not firm with programming.
However this is sadly already a little bit more complex and is nothing the parser can do that well
