### ISSUE TITLE
Suggestion: The "Spawn Unit" Event in the Script Editor having more options

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#494]
The title pretty much says it all.

In The script editor, for the "Spawn Unit" event, it should give you options as to what you want to Nickname the unit as, How Much Fuel, Ammo & Health it has, and what rank it should be (Minus CO, Probably). As well as what AI Type it should have.

**Comment by Robosturm** [comment]
You can use the spawn unit function combine with the modify unit and change unit ai function to modify most values.
However a more complex spawn unit function won't happen, those need to be done by hand.
However you may request a function for changing the unit rank.
