### ISSUE TITLE
Bug: crash when CO powers are used

### ISSUE THREAD

**Issue by Ducksquack666** [Robosturm/Commander_Wars#496]
Hi there, first time doing this so apologies in advance if this is the wrong place to put it/wrong format.

My game keeps crashing when either a player or an AI uses a CO power. I've tested it a few times between different COs and it doesn't seem like a problem with a specific CO, nor does it seem to be a problem with a specific map (tested several maps as well). When no COs are chosen, nothing crashes and I can finish a game (or at least the AI I was using to test can finish theirs). 

I'm not using any mods and I have the latest version of the game.

**Comment by Robosturm** [comment]
It seems that on some PC's the latest release runs into some memory issues.
I changed some memory management in the latest release.
I recommend using the release: 
https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_18_1
Till the new release is out. ;)

**Comment by Ducksquack666** [comment]
Sounds good to me. Thank you!
