### ISSUE TITLE
Random Map Generator Crash

### ISSUE THREAD

**Issue by Vision-Spire** [Robosturm/Commander_Wars#497]
[console.log](https://github.com/Robosturm/Commander_Wars/files/6773345/console.log)
---------------------------------
Commander Wars vVersion: 0.18.1
06 Jul 2021 @ 19:46:05

EXCEPTION_ACCESS_VIOLATION

[0] 0x0000000000669bd8 ?? at atomic_base.h:396
[1] 0x000000000066bd40 ?? at qvector.h:73
[2] 0x00000000005457dd ?? at atomic_base.h:396
[3] 0x00000000007c851e 0x00000000007c851e
[4] 0x0000000068c62914 0x0000000068c62914
[5] 0x0000000013647aec 0x0000000013647aec
[6] 0x0000000068a99f3d 0x0000000068a99f3d
[7] 0x00000000772d93f9 0x00000000772d93f9
INFO: Enter "help()" for console info.
INFO: Starting Game...
INFO: Prepare to Fight...
INFO: Read this message while waiting...
INFO: 
INFO: Monday morning Quest: Find my Coffee Mug in the Office!
INFO: 
CRITICAL: SyntaxError: Unexpected token `string literal' in File:C:/Users/ajsbi/Desktop/Advance Wars/commander_wars/mods/visions_revisions/scripts/general/Player.js in File: file:///C:/Users/ajsbi/Desktop/Advance Wars/commander_wars/mods/visions_revisions/scripts/general/Player.js at Line: 18

**Comment by Robosturm** [comment]
Can you confirm that this also happens only with vanilla mods or no mods active?
Cause the log shows that your mod visions_revisions is active and has a bug in the player.js script

**Comment by Vision-Spire** [comment]
Yea I'll see if that happens if no mods are active and with vanilla mods
