### ISSUE TITLE
Ability to change sfx used for ACTION_FIRE

### ISSUE THREAD

**Issue by SkullFace96** [Robosturm/Commander_Wars#499]
ACTION_FIRE.js is the only .js that uses a "talongunhit.wav" and can't be changed to other sfx.
While ACTION_CANNON_FIRE.js uses a "minicannonhit.wav" (Line 105).
I've tried adding the same thing to ACTION_FIRE.js but it doesn't get played at all, nor do errors show up.
I've managed to only add the custom sfx after all the HP calculations happen which is awkward.

My wish is to have an ability to change sfx individually for each unit while attacking each other in Overworld.
e.g.
infantry firing rifles sfx,
mechs firing rockets sfx or
tanks firing cannons sfx.

**Comment by Robosturm** [comment]
made the whole overworld animation moddable :)
