### ISSUE TITLE
Can't load Rockets to Landers/Transport Planes

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#50]
**Describe the bug**
As the title says, the Rockets/Rocketthrower can't be loaded to Landers or Transport Planes. The cause of this is a typo ("ROCKETT**RH**OWER") present in both the lander.js and transportplane.js files. It's an easy fix and I was able to do it myself but I figured it's something that needs to be fixed for future releases, in case it hasn't already been fixed.

**To Reproduce**
Simply attempt to load Landers or Transport Planes with Rocketthrowers.

**Comment by Robosturm** [comment]
Fixed it!
Thx for the report and the time spend into finding the bug.
