### ISSUE TITLE
fog of war not shrouding correctly?

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#502]
im unsure if this is working as intended or not, but if an allied unit passes a unit in a forest, or any forest, you can see into the forests for the remainder of the turn. happens with rain, fog of war, and shroud of war. idk if this is a bug or an intended feature.

first instance is modded, remaining instances are all vanilla.

![fog bug](https://user-images.githubusercontent.com/75344715/126088430-6c2f3691-9f8d-4c78-9d64-d14a238624f2.png)
![fog bug2](https://user-images.githubusercontent.com/75344715/126088440-94b16c92-0c60-4b53-96db-8ec0475fccc2.png)
![fog bug3](https://user-images.githubusercontent.com/75344715/126088443-56f78d83-c3fa-4a06-a8d3-ae90aa87e5b6.png)
![fog bug 4](https://user-images.githubusercontent.com/75344715/126088449-aa7e5162-0e94-4a9f-801c-67ceea50e911.png)

**Comment by Robosturm** [comment]
This is intentional. Commander Wars uses the AW-DC fog of war system in which each field reveiled this turn stays reveiled.
This includes moving.
I prefer the AW-DC fog of war method compared to AW1-3. You can create a mod to revert it if you really want to do.
