### ISSUE TITLE
Cannot Destroy Meteors Connected to Plasma

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#504]
Very self-explanatory. When destroying a meteor that is connected to plasma, the meteor does not disappear and the plasma stays as well. Here is the log of the error.
[console.log](https://github.com/Robosturm/Commander_Wars/files/6872068/console.log)

Here is a screenshot of the meteor after trying to destroy it.
![image](https://user-images.githubusercontent.com/85777134/126860931-304d0a11-3746-48d2-b156-577e1c0baeb2.png)

**Comment by insanebotv21** [comment]
This isn't resolved in the latest release.

**Comment by Robosturm** [comment]
There is no official release with a fix.
Beta 22 is still in pre-release state
