### ISSUE TITLE
Colin Power Gold Rush Doesn't seem to work

### ISSUE THREAD

**Issue by TheMasterCreed** [Robosturm/Commander_Wars#505]
The power doesn't increase the funds at all and the log shows an animation error.

![image](https://user-images.githubusercontent.com/85777134/126890236-7d0060b5-5ab1-437b-a066-019092c97c06.png)

![image](https://user-images.githubusercontent.com/85777134/126890231-5ce152a2-8b45-4bd1-86be-9da19d10399e.png)

**Comment by TheMasterCreed** [comment]
Since the line is just for a sound I just removed it and that got the power to work properly. So I'll consider this a temporary fix.

**Comment by Robosturm** [comment]
Already solved in #480

**Comment by TheMasterCreed** [comment]
Ah, if only people would report one bug at a time, I would have seen it in the title. Thanks!
