### ISSUE TITLE
Turn Doesn't Automatically End If a Factory/Port/Airport Is Empty Despite Not Having Any Funds

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#506]
**Describe the bug**
The title pretty much says it all. When the option "Automatically End Turn" is enabled and you finish moving all your units and spend all your money on creating new units, but you didn't buy anything for a Factory/Airport/Port, the turn won't end automatically. 

**To Reproduce**
The easiest way to do it is: Enable "Auto End Turn" and Make a map with 3 Buildings; 2 Factories and 1 Airport. Then build infantry in those two factories. The turn still won't automatically end due to there being nothing on the airport despite being unable to afford anything for it.

I feel like the game should check to see if you can afford anything else on the remaining buildings you haven't built anything on before ending your turn. (Although it would have to be adjusted for COs with cheaper units)

**Comment by Robosturm** [comment]
I look into it.
What i can see is that beeing able to trigger a COP or SCOP disables the feature.
