### ISSUE TITLE
Teammates Don't Share Vision

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#51]
**Describe the bug**
When you set armies in the same team, they don't share the same vision. 
For example, Army 1 has a recon but Army 2 isn't able to see what that recon sees, despite them both being set on the same team. 

**To Reproduce**
1. Go into any map, preferably one with more than 2 Players (P.S I tested this on a Custom Map, if that changes anything)
2. Set two of the Armies to the same team and have Fog of War on (weather doesn't need to be rain)
3. In-game, Build a recon then end your turn
4. When the next Army in your team gets their turn, they aren't able to see what that recon sees. Although they can see each other's building

**Screenshots**
https://i.imgur.com/0zBQyqO.png

**Additional context**
If this is intentionally, then maybe there should be an option that allows you to choose between being able to share vision with your teammate or not, and maybe stated in the "CoW Custom Mechanics" page. 
I'm aware that there's going to be an update to the Fog of War system in the next update, but it wasn't mentioned or at least it wasn't clear enough in regards to whether or not this bug was or will be fixed in it.

**Comment by Koopanique** [comment]
I won't be able to check before Saturday evening, I don't think this is intentional, but if it is, I definitely agree with Seimix that at least an option should be present to allow the player to play with the usual rule which states that both armies from the same team should share the same vision.

**Comment by Robosturm** [comment]
Not intentional. 
Creating the vision matrix only uses own units and buildings instead of allied ones.
Fixed the check function when creating the vision matrix

Thx for the report Seimix
