### ISSUE TITLE
Suggestion: Move-By-Move Option in the Replays Feature

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#510]
So recently I've been watching quite a lot of AW:BW replays and one feature I noticed it having is the ability to watch the replay move-by-move. In other words, there's a button present that when pressed would only have one move played before pausing again, and this could be used to just go to the next move or go back to a previous move.

I figured this would be a very nice addition to CoW's replay feature considering the replays already go by pretty fast, so it's hard to catch what's exactly going on in the game. (Also, the number of times you press the button should stack. For example, clicking on it 5 times would have 5 moves play. )

Of course, this request also includes a "Previous Move" button as well and I don't think the current "Speed up" button should be removed, but I figured this would be a nice addition on top of that as well. 

Side note: The "Next" and "Previous" keys currently don't seem to have a use in the replays feature, so these could act as the hotkeys to these replay features. 
I also don't think the "Next Player's Turn" should start until after you click "Next Move" after the previous player's last move.

**Comment by Robosturm** [comment]
Note: Due to the fact going back is technical not that easy and my guess is that that is one of the major problems why awbw replays get into weird states when doing so.
