### ISSUE TITLE
Suggestion: Game Rule for Flares Firing After Moving

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#517]
This is a super-specific thing that the only way to adjust is in the Mods Menu.

Now I can understand why it would be put in the mods menu considering it is a very specific change, and making it a game rule would come off as odd and might make that menu a bit more cluttered as well. Plus, other possible problems could arise in regards to modding if this were to be a game rule.

My only good arguments for making it a game rule rather than a mod is:
- It would make more sense to have it under the "Misc" category in the game rules menu than have an entire base game mod dedicated to it.
&
- It wouldn't require players who want to play multiplayer with each need to all have this mod enabled. 

Other than that, this is just a suggestion I'm throwing out there in an attempt to cut back on some of the vanilla mods. 
(Basically: This topic is suggesting that the "Action Flare" mod is made into a game rule instead)

**Comment by Robosturm** [comment]
The Flare option has been removed completly.
Initially this was an oversight on my end anyway that flares could move and fire
