### ISSUE TITLE
AI surrendering randomly after capping a property.

### ISSUE THREAD

**Issue by CameronW1** [Robosturm/Commander_Wars#519]
**Describe the bug**
AI will randomly surrender during gameplay after the player (possibly could happen after another AI) captures a property of any type.

**To Reproduce**
1. Start game, select a 2 player or more map.
2. Play 2-3 or more turns, while capping random properties.
3. Watch as the AI seemingly surrender

**Expected behavior**
n/a

**Screenshots**
Happens randomly and quickly.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit.
 - Version Beta 19

**Additional context**
n/a

**Comment by Robosturm** [comment]
The ai can't surrender. 
The problem is linked to the map.
So please report the map on which it happens
