### ISSUE TITLE
Bug with how mods are loaded

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#52]
**Describe the bug**
This is a bit complicated so try to follow, even though my wording could be bad:

I tried to create a new mod to change unit graphics. To this end, I created a new mod folder named "aw_ww2_units", with the proper mod.txt inside, filled correctly. Then in this mod folder I copied folders and subfolders for unit graphics, and I changed what I wanted to change (I modified some PNGs).

Then I went ingame. In the option menu, in the "Mods" pannel, I turned my mod on. But once ingame, the graphics used weren't those of my mod, but those of the normal game, in the regular resource folder.

I tested the Dark Conflict unit image mod pre-included, and it worked just fine.

To test things further, I replaced the graphics from the Dark Conflict Unit Image mod with my own graphics, and it works. I concluded something was wrong with my own mod.

But after several hours, I decided to just copy-paste the Dark Conflict Unit Image mod and use it as a base for my own mod. But it didn't work because when this new mod based on the DC Unit Image mod was turned on in the option, it continued using graphics from the original DC Unit Image mod.

So I get the feeling that there's an issue with how the mods are loaded; maybe they only use data from mods that were loaded before, so they're always one step behind the mod the user actually wants to use. But the DC Unit Image mod worked, so... I'm not sure.

So now what I'm planning to do is making a backup of the "resources" folder of Commander Wars and work directly in it, without bothering with the "mod" folder.

But this is too bad because it would be far more useful to have a working "mod" folder.

I hope I was clear enough in my explainations of what happened :/ It's a bit tough to describe clearly.

**To Reproduce**
1. Create a new mod folder, complete with the "mod.txt" file filled in.
2. In it, copy paste the original resources/images/units folder.
3. Change some pngs.
4. Go in game and try it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 5

**Comment by XnKradst** [comment]
Hey there, I'm not Robosturm but I've already confirmed that mods are loaded depending on the order they were enabled in the options menu (#48). That order can be seen in the .ini file. It's been changed to load in alphabetical order in the next release though.
Anyway, I have a feeling you might've forgotten to edit the res.xml file included in your mod's units folder? It has a path that should be updated to point to your new folder.

**Comment by Robosturm** [comment]
@Koopanique as XnKradst mentioned go to the res.xml in the folders of your mod. The third line or so selects a folder from which the image should be loaded if you use a copied version of the aw dc mod or the original one without changing the folder the game loads the files from the other mod and not yours. The res.xml are intepretated as they're are documented in the oxygine docu.
See below
    <?xml version="1.0"?>
    <resources>
       <set path = "mods/my_custom_mod/images/co/" />

**Comment by Koopanique** [comment]
Hi @XnKradst @Robosturm, sorry for the wait, I wanted to be back home and to try it before giving a definitive answer.
Turns out you were both right, I wasn't aware I needed to change the res file ^^' Sorry for the invalid report. Now it works just fine. Thanks to you both!

**Comment by Robosturm** [comment]
No problem. ;) The res files are handy for defining frame counts etc. but they require some knowledge making modding a little harder. 
I close the issue then.
