### ISSUE TITLE
Game not ending after killing all units or capping enemy HQ.

### ISSUE THREAD

**Issue by CameronW1** [Robosturm/Commander_Wars#520]
**Describe the bug**
When you play the game as normal, the game should end after all the units are lost or the HQ is cap'd. Sometimes however, this doesn't happen and you have to force close the game. Sometimes, restarting CW fixes this, depending on if an AI triggers it or not, and that may not always work.

**To Reproduce**
1. Start game, any map.
2. Run the game as normal, capture properties, fight enemy units.
3a. If you kill all the units game may signal you've won, but the game over screen doesn't take over. OR
3b. If you run to the enemy HQ and capture it, the game may not "fully" register the capture, but will delete the enemy units that are remaining but the game over screen may not come up.
4. As in either case when I get the bug, I have to force close the game.

**Expected behavior**
Game should end in either case, but since it doesn't, that is the issue.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Version Beta 19

**Additional context**
n/a

**Comment by Robosturm** [comment]
The problem is linked to the map.
So please report the map on which it happens

**Comment by CameronW1** [comment]
Happens on all maps, just randomly. Sometimes it'll crash on one map, but the next time I play it, it won't.

**Comment by CameronW1** [comment]
Just happened again on Mermaid, capped the HQ in 2 turns and game did not end. I don't know what else to say.
