### ISSUE TITLE
Suggestion: Commander Wars Movement Game Rule

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#521]
This is a very interesting Mechanic that is currently locked away behind a mod.

This is basically requesting there to be a game rule to allow **all units (except other air units) to move through air units of opposing forces** instead of locking it behind a mod. (PROBABLY should not be called "Commander Wars Movement Tho")

I don't really have many good arguments for converting this into a game rule that I haven't made already, aside from that this is already considered a CoW mechanic in the Mod list and it is an interesting Mechanic.

Although the biggest problem I hear regarding this is the fact that it'll be very hard to implement, which would be a fair enough reason to not incorporate it at all. Besides, I am mainly just throwing the idea out of possibly converting this into a base-game thing anyways.

**Comment by Robosturm** [comment]
The movement through units is similar to the coop mod one of the more complicated mods. 
For a vanilla mod to make it into the game the mod should boil down to one or two if conditions added.
The moment the mod gets complex, it's not a good idea to add it to the base game cause the code gets a lot harder to maintain and understand.
