### ISSUE TITLE
Rename Destroyers

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#525]
Though this is an incredibly minor thing, I feel like bringing it up anyway.

In Commander Wars, most unit names are pretty accurate compared to what one would expect from the real-life counterpart.

With one glaring exception; the Destroyer. For people without any knowledge of ships, it might work, since the name implies that it destroys things, wheras in actuality it should be somewhere below Cruisers in terms of strength.

As such, I feel like it might be best to just... rename them to something more reasonable; Battlecruisers. This name somewhat reflects their status of being in-between Battleships and Cruisers, is more historically accurate, and does not require a rework of any units, just a name change.

**Comment by Koopanique** [comment]
This is an issue that has bugged me for the longest time, too.

I think there's an issue with these 2 types of ship, Destroyers and Cruisers. To be more inline with WW2 logic, I think Destroyers should have the main guns of the cruisers, and vice-versa. And Destroyers should be the sub-hunting ship, not the cruisers.

In light of this, wouldn't it be simpler to swap the names of Cruisers and Destroyers, and then change their weapons accordingly? In AW and Commander Wars, Cruisers seem closer to real-life destroyers (fragile, but nimble and anti-sub), and Destroyers seem closer to Cruisers (ships with firepower somewhere between a destroyer and Battleship).

**Comment by FranticFairy** [comment]
> In light of this, wouldn't it be simpler to swap the names of Cruisers and Destroyers, and then change their weapons accordingly? In AW and Commander Wars, Cruisers seem closer to real-life destroyers (fragile, but nimble and anti-sub), and Destroyers seem closer to Cruisers (ships with firepower somewhere between a destroyer and Battleship).

While I agree from a historical perspective, I don't think this is a good idea for the basegame. In my opinion, there should be very little, if any, changes to default units, so people who come straight from Advance Wars don't get confused. Therefore, it'd simply be better to rename the offending unit and keep the vanilla unit unchanged.

Any significant balance changes should be left to mods.
