### ISSUE TITLE
Can't open game?

### ISSUE THREAD

**Issue by Hakimblue99** [Robosturm/Commander_Wars#526]
I think I just found the first bug of pre-release 20? I downloaded early version 20, just to test it out, but when I try opening it, this comes out:

![IMG_20210914_232338](https://user-images.githubusercontent.com/86725438/133287261-7d7cf7f4-eee6-46bf-9642-ca552c7527ed.jpg)

**Comment by Robosturm** [comment]
What Windows Version do you run and do you have 32bit or 64bit Version?

**Comment by Hakimblue99** [comment]
Windows 7, 64-bit

**Comment by Robosturm** [comment]
Hmmmm the other thing i can imagine is that you have a different version of something the MSVC-Compiler links again which leads to a crash upon start, but it's pretty hard to find out what the msvc does, which is why i normally don't use it.
I'm just using it cause the mingw-build of qt is bugged in the current beta releases.

The actual realease will be build with mingw again.

**Comment by Hakimblue99** [comment]
I see. Thanks.

**Comment by Robosturm** [comment]
Do you have Microsoft Visual C++ 2015-2019 Redistributable (x64) installed?

**Comment by Robosturm** [comment]
This one
![grafik](https://user-images.githubusercontent.com/48879701/133310783-d3a54554-5566-49e8-9773-f6e06fdfa87c.png)

**Comment by Hakimblue99** [comment]
I Don't think I have. Let me check. Do I need to install it it something?

**Comment by Robosturm** [comment]
I thing it's required for the current version sadly. :(
As said i hate using msvc.

**Comment by Hakimblue99** [comment]
Okay, I'll try downloading Microsoft visual

**Comment by Hakimblue99** [comment]
Okay, I installed the Microsoft visual. And tried opening up commander wars. Still gives the same results. Did I do something wrong? What am I supposed to do with Microsoft visual?

**Comment by Robosturm** [comment]
You have the correct version? I know that there a dozen different version you can have installed at the same time.
If it doesn't work i'm currently clueless....

**Comment by Robosturm** [comment]
I try to locate the following three files on my device and sent them to you so you can try it out:
vcruntime140.dll
msvcp160.dll
opengl32sw.dll

**Comment by Hakimblue99** [comment]
In which folder should I put those files?

**Comment by Robosturm** [comment]
The same as the exe...

**Comment by Hakimblue99** [comment]
Oh. I'm being dumb. Sorry.

And my laptop decides to randomly update right now. I'll inform you when/if it works

**Comment by Robosturm** [comment]
Once i found them yes.

**Comment by Hakimblue99** [comment]
It's okay. Take your time

**Comment by Robosturm** [comment]
Can you test if it works with this libs?
[AdditionalLibs.zip](https://github.com/Robosturm/Commander_Wars/files/7171412/AdditionalLibs.zip)

**Comment by Robosturm** [comment]
Okay i found an automation way to add the missing libs.
Going to upload an updated version soon

**Comment by Robosturm** [comment]
Can you redownload the pre-release version and see if it works now

**Comment by Hakimblue99** [comment]
Sorry for the delay, currently scanning my laptop for virus and stuff, it's been lagging quite a bit lately. I'll update you once I'm sure my laptop is malware free

**Comment by Hakimblue99** [comment]
I think my laptop is the problematic one here. Because I still couldn't open the game. Maybe I should get it checked at a repair shop. It was causing problems lately. Sorry for bothering you.

**Comment by Robosturm** [comment]
Did you try to install the visual studio part with the exe in the zip?

**Comment by Hakimblue99** [comment]
I did. Still couldn't open it. I really think the problem lies with my laptop. It was a second hand...Ah, well. I'll just play the android version. It works so fine so far. Still getting the hang of the controls. Just a question, for PC version, you press 'I' on a unit to check it's info. Is there a similar function in the android version?

**Comment by Robosturm** [comment]
Not really you need to open the wiki via the fieldmenu and select a unit.
There are somelimitations when it comes to android controls. compared to a pc key board ;)
