### ISSUE TITLE
In the mod select screen, the first dropdown menu doesn't update when selecting a game

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#527]
**Describe the bug**
In the option menu, in the mod selection screen, the first dropdown menu is called "Advance Wars Game:"
When selecting an option from this menu, the right checkboxes get ticked, however the dropdown menu still displays "unknown". Whereas it should display whatever was selected.

**Expected behavior**
The dropdown menu should display whatever was selected. Just like the dropdown below (Tag Filter).

**Screenshots**
![dropdown_bug](https://user-images.githubusercontent.com/53582470/133314219-d9427152-1ccc-40d0-85de-fae1354b5e60.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bits
 - Version: Beta 20 pre-release

**Additional context**

**Comment by Robosturm** [comment]
This isn't really a bug but the current intentional implented behaviour. However I agree that the behaviour is unintuitive and not good. 
Marked as enhancement for that reason
