### ISSUE TITLE
Game Crashes when deleting a CO unit in Level Editor

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#53]
**Describe the bug**
When you change a unit's rank to "CO" in the level editor and then try deleting it, the game crashes,

**To Reproduce**
1. Go to "Map Editor"
2. Place down a unit 
3. Give that unit the "CO1" Rank and try deleting it

This is a rather minor bug, although I figured I should report it since the next update is including a Delete Unit option in-game.

**Comment by Robosturm** [comment]
Always report bugs even minor ones ;)
MIssing nullptr check. 
The bug only happens in the editor. Pffff...
fixed.
