### ISSUE TITLE
Menu music plays during gameplay (android)

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#534]
tried playing some war room and single player and the menu music plays rather than co themes.

it will go silent rather than loop, and if minimized it will also not restart till the next turn.

**Comment by Robosturm** [comment]
That's cool bug introduced with Qt-Beta 4 not sure if can fix that.
From the looks the player loads one file and from there on is unable to change to a new music file.

**Comment by Robosturm** [comment]
This is a known issue with qt for android and should be fixed for the actual qt release at the end of this month
