### ISSUE TITLE
NEOTANKS!? mission broken

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#539]
on lash's turn she doesn't do anything and the game softlocks

**Comment by KBraid** [comment]
yes it happens on her first turn and it is on the update

**Comment by Robosturm** [comment]
Can you send me the console.log of it?
It doesn't happen for me however i've seen that the pre-deployed ai has a bug resulting in the guarding medium tanks to move...

**Comment by Robosturm** [comment]
Okay the bug has the same reason as this #535
