### ISSUE TITLE
Randomize only single COs

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#54]
The game has an option to randomly chose COs for the players. The problem is that the randomizer always chose 2 COs for every player.

Instead have 3 options to randomize COs. 1 to randomize the first CO, another option the randomize the second CO, and a third option which randomly chooses both COs for each player.

**Comment by Robosturm** [comment]
You can do that already. The all random button is a quick start option. Go to the co select screen like you would select a specific co and the first army has a question mark co. Select it and the co is chosen at random. Repeat it for all Co's who should be chosen at random

**Comment by RicardoPires19** [comment]
Yes, but I was suggesting a quick method for these as well. For large battles with lots of COs it would be much easier to just click a button and randomly chose only the first CO for each player, instead of doing it manually for each player.

**Comment by Robosturm** [comment]
got what you mean. Added it
