### ISSUE TITLE
Clearer 'Checked' for boxes.

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#542]
Right now, it's hard to distinguish between boxes that have been checked VS boxes you cannot check:

![image](https://user-images.githubusercontent.com/51452633/133848457-76f2c412-c082-452f-9e26-87f3edb962d3.png)

In this case, Ranger has been selected, Climber has not. Upon close inspection you can tell that it's Ranger that's been selected, but only because everything else has the same colour Climber has.

Perhaps include a checkmark in selected boxes, and an X in unavailable boxes, to distinguish them from both eachother and boxes you can still select?

**Comment by KBraid** [comment]
as the buttons are they are a direct rip from DoR, which used only colour to distinguish active/deactive. i'll see what i can do to make it look better.

**Comment by Robosturm** [comment]
I can change the disable add color if needed for the checkboxes....
