### ISSUE TITLE
Game Frequently Crashes

### ISSUE THREAD

**Issue by schuman-aaron** [Robosturm/Commander_Wars#544]
The game crashes when attempting normal game play.

1. Run the application either as normal or as administrator
2. Click Single Player
3. Click Tutorial
4. Click on Tutorial 2
5. Either left-click through dialogue or right-click to end it
6. Complete a turn worth of actions and click end turn
7. Game crashes upon the start of my next turn

The game should not crash when attempting normal game play.

The relevant logs:
[20210917-165625 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/7188434/20210917-165625.Commander.Wars.Crash.log)
[20210917-165626 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/7188435/20210917-165626.Commander.Wars.Crash.log)

OS: Windows 7 64-bit
Version: Commander Wars Beta 19
![image](https://user-images.githubusercontent.com/7083776/133851614-ffc8eaa5-4cef-4af4-a696-063f9f632663.png)

**Comment by Robosturm** [comment]
This is fixed with pre-release 20

**Comment by schuman-aaron** [comment]
Ah, I didn't notice it as only the latest releases is displayed on the homepage.
