### ISSUE TITLE
Joining two units that go over 10 HP causes the game to crash.

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#55]
**Describe the bug**
Joining two units that go over 10 HP causes the game to crash.

**To Reproduce**
1. Have a unit with 6 HP.
2. Have another unit with 7 HP.
3. Join them.
4. The game crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 6

**Comment by Robosturm** [comment]
Does the crash always happen for you or only from time to time?
Cause i can't reproduce it at the moment i have an idea what might be the problem but i need to know if it always happens for you to verify it.
