### ISSUE TITLE
add movement to rocket explosions hitting air targets

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#550]
have air explosions move offscreen to mimic how they behave in advance wars

**Comment by Robosturm** [comment]
Can you showcase a small example what you mean with that?

**Comment by KBraid** [comment]
a video would probobly be easier
https://www.youtube.com/watch?v=JG11cfRwllQ

**Comment by Robosturm** [comment]
That works as well.
Now i know what you mean and that's nothing to hard to add.
