### ISSUE TITLE
have units explode on death

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#551]
with infantry flying away now implemented, could we have units explode when dead rather than fade away?

**Comment by Robosturm** [comment]
That's something i'm intentionally delaying for after the release.
Cause i need to figure out how i want to do it.
My initial test of simplying play the explosion after the hit feels very weird.
So i need more experimenting but i don't want to break the animation code.
So I improved the timings already so the whole process will feel a lot smoother with the next pre-release version

**Comment by KBraid** [comment]
understandable
