### ISSUE TITLE
Colour issue with Grey Default

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#553]
When you select light gray from the default colours:
![image](https://user-images.githubusercontent.com/51452633/133906961-0f84e705-ccae-4b23-ab07-b05ede5b7c34.png)

Their naval units begin to sail in a sea of blood:
![image](https://user-images.githubusercontent.com/51452633/133906975-73b616c6-309a-4a54-a187-9a87c9be3d3e.png)

**Comment by Robosturm** [comment]
Not sure if that's inteded by K'Braid or not.

**Comment by KBraid** [comment]
that's the metal army palette, the water below sea units and the face of BH infantry use the same colour. in the battle animation BH infantry would have red visors. so it's either red water or blue overmap visors if paired with BH. I feel keeping the palette tied to how they are actually in the games would be more authentic but it can be separated into two separate colours if that is wanted

**Comment by Robosturm** [comment]
I feel like having them separate would be more clean and opens up more options.
However it's propably a lot of work to update the palette and the sprites....
It's not like we need to mimic the aw palette by 100% since we're not really limited with memory space like the aw cartridges were.

**Comment by KBraid** [comment]
all i would need to do is add the separate colour to each palette sheet and fix it in the overmap sprites, which would take me no time at all. And all you would need to do is make the fix to the palette generator for custom colours

**Comment by Robosturm** [comment]
Well fixes the generator isn't hard either.
In that case i would say go for gold.
It's a cleaner solution afterall.

**Comment by Robosturm** [comment]
When it comes to reusing colors in the original aw games.
That's mostly due to the cartridges having limited space, so they reused things even for different stuff were ever they could,
Another example for that is the sprite storing Kartal is mentioning during his rom-hacking work

**Comment by KBraid** [comment]
alternatively an even easier solution would be to take the water portion of the sprite off the mask and have it be its own sprite

**Comment by Robosturm** [comment]
I prefer the palette solution....

**Comment by KBraid** [comment]
roger that!

**Comment by Robosturm** [comment]
@KBraid i think the unit sprite for the sea color are wrong....

**Comment by KBraid** [comment]
apologies, a fix is on the way

**Comment by Robosturm** [comment]
Np ;)
