### ISSUE TITLE
Road movement cost in snow is equal to plains

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#56]
**Describe the bug**
When snowing, movement on road costs as much as moving on plains.

**Expected behavior**
Road should be unaffected by weather.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 6

**Additional context**
Don't know if it's a feature or bug, but just in case.

**Comment by Robosturm** [comment]
Upps forgot how snow works in AW-Games.
Fixed it
