### ISSUE TITLE
unable to deselect action fire (android)

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#563]
while using the action fire with any unit using the touchscreen interface, there is no way to back out of the action fire, whether there is one or more targets, you are unable to undo the command and are commited to attacking.

**Comment by Robosturm** [comment]
Did you do a long press?
Long press is meant to be the deselect command.

**Comment by TeslaTrooper09** [comment]
Yeah, i tried pressing the unit, off the unit for various ammounts of time

**Comment by Robosturm** [comment]
Either i fixed that recently by accident or you do something wrong.
However i admit the deselection is a little bit ivy right now.
I'll leave it open and you tell me if it works with the next prerelease coming out later.

**Comment by TeslaTrooper09** [comment]
sounds good

**Comment by Robosturm** [comment]
Besides that i'll look into the code and see if can make the deselection/long press a little bit smoother.
Currently it felt really annoying/weird on my phone.

**Comment by FranticFairy** [comment]
I can deselect firing on the first pre-release, but it takes multiple tries to do so. It's possible, just not as quick or convenient as ideal. But that's to be expected from a pre-release.

**Comment by Robosturm** [comment]
Improved touch handling
