### ISSUE TITLE
Md Tanks render black when moving

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#565]
Md Tanks (at least for Black Hole) are black while moving in the battle window

**Comment by Robosturm** [comment]
Since os tanks render fine i expect that the sprite itself is bugged can you ckeck that?

**Comment by Robosturm** [comment]
It looks like some frames are incorrect in the image

**Comment by KBraid** [comment]
on my end the movement sprites are all correct

**Comment by KBraid** [comment]
![heavy_tank+bh+mg+move+mask](https://user-images.githubusercontent.com/53922323/133938896-5891f358-25a4-4615-887e-f4f671558dbc.png)
![heavy_tank+bh+move+mask](https://user-images.githubusercontent.com/53922323/133938897-901b3c4b-4922-42c4-9976-54841677b194.png)

**Comment by Robosturm** [comment]
It's a weird bug it's exactly one entry of the move animations if i swap the order the bug moves to the next medium tank.
Dunno what's happening but it's not on your end.
