### ISSUE TITLE
Units that are deployed can move immediately.

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#57]
**Describe the bug**
When a unit that hasn't moved in that turn gets deployed by a transporter, like APC, Lander, etc. it is able to move within the same turn.

**Expected behavior**
Once deployed the unit should not be able to move until the next turn.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 6

**Comment by Seimix** [comment]
This has already been reported here: https://github.com/Robosturm/Commander_Wars/issues/33
It's an intentional mechanic added to the game.

**Comment by Robosturm** [comment]
See also here [https://github.com/Robosturm/Commander_Wars/wiki/Commander-Wars-Custom-Mechanics](https://github.com/Robosturm/Commander_Wars/wiki/Commander-Wars-Custom-Mechanics)

**Comment by RicardoPires19** [comment]
Sorry then, but maybe add an option to use the classic mechanic when setting up the game. Just because this is a game changer.
