### ISSUE TITLE
adjust DoR campaign teams colours

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#570]
the red fire, cobalt ice, golden sun, and dark matter colour palettes had been adjusted to emulate/represent DoR colours. can these colours be used for teams in the DoR campaign?

**Comment by Robosturm** [comment]
Yes they can be used it's just a matter of changing the colour for each team in each map and saving it and replacing the current ones....

**Comment by KBraid** [comment]
i had attempted doing this myself however it seemed to refuse to apply the new team colours

**Comment by Robosturm** [comment]
Yeah i need to compile them into the game to make them work inside the campaign.
If you just save them in a different folder you can open them as well
