### ISSUE TITLE
Map Editor 'Edit Players' doesn't accept two Humans.

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#574]
When using 'Edit Players' to set someone to 'Human' doesn't register if the other player is already 'Human', instead reverting to what it was before.

**Comment by Robosturm** [comment]
Is the map a pure human vs human map?
Cause that's not possible via the map editor.

**Comment by FranticFairy** [comment]
I see, so it's a cause of undocumented behaviour instead. May I know why Human VS Human is considered invalid by default? Hotseat games exist and are possible when setup in the lobby, why not by default?

**Comment by Robosturm** [comment]
Two reasons CoW is primarly a single player game. Second I wasn't and never will be in the mood to fix the setting for all the vanilla maps

**Comment by Robosturm** [comment]
Primarly the second one is the reason for that
