### ISSUE TITLE
Crash after loading a saved game

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#58]
**Describe the bug**
Upon loading a saved game, the game crashes if the AI performs certain actions involving infantry

**To Reproduce**
1. Start a game in a war room map
2. Save the game
3. Load the game (either by Continue or by Load Game)
4. Wait for the AI to load a unit into a T-Copter

**Expected behavior**
The game crashes on the AI's turn, after loading a T-Copter.

**Desktop (please complete the following information):**
Windows 7, Beta 6

**Additional context**
Playing as Flak vs Sensei in Mial's Hope (a War Room map). Here's the save file for further dissection. I've tested this some other times, and one instance (in Triangles, vs Sami), the CO moved a Mech closer to a T-Copter and instigated a crash.

[save.zip](https://github.com/Robosturm/Commander_Wars/files/3566162/save.zip)

Meanwhile, I finished a saved game in Ridge Island (which is listed as a 2 Player map). I've also discovered a secondary bug: For some reason, CO-exclusive units don't show up in the build list if you're playing on War Room maps.

**Comment by Robosturm** [comment]
Found the bug with your savegame. :(
The bug only happens if you play with a single co and isn't AI related.

**Comment by GuardianTempest** [comment]
> What do you mean with Buildlist? The Ingame Base Building List or the List when selecting CO's etc.?

Ingame building list.

**Comment by Robosturm** [comment]
Yeah that's cause the Buildlist in the player selection disables them cause the buildlist settings are not compatible with unset ones at the moment. I need to add something to make buildlist storing only avaible when you changed it in the editor...
