### ISSUE TITLE
Pressing left key in a menu with one column crashes the game

### ISSUE THREAD

**Issue by chopper385** [Robosturm/Commander_Wars#583]
Commander Wars vVersion: 0.20.0 Builddate: Sep 19 2021 14:34:47
23 Sep 2021 @ 14:17:13

EXCEPTION_ACCESS_VIOLATION

INFO: 23.09.2021 13:54:18: Enter "help()" for console info.
INFO: 23.09.2021 13:54:18: Starting Game...
INFO: 23.09.2021 13:54:18: Prepare to Fight...
INFO: 23.09.2021 13:54:18: Read this message while waiting...
INFO: 23.09.2021 13:54:18: 
INFO: 23.09.2021 13:54:18: Would you like to play a game of... world domination?
INFO: 23.09.2021 13:54:18: 
CRITICAL: 23.09.2021 13:56:47: The host was not found. Please check the host name and port settings.
CRITICAL: 23.09.2021 13:57:42: The host was not found. Please check the host name and port settings.
CRITICAL: 23.09.2021 13:57:48: The host was not found. Please check the host name and port settings.
CRITICAL: 23.09.2021 13:57:51: The host was not found. Please check the host name and port settings.
CRITICAL: 23.09.2021 13:58:06: The host was not found. Please check the host name and port settings.
CRITICAL: 23.09.2021 13:58:10: The host was not found. Please check the host name and port settings.
CRITICAL: 23.09.2021 13:58:31: The host was not found. Please check the host name and port settings.

All I did was trying to play during my turn and move an infantry somewhere, the game lasted 3 days before it crashed randomly

**Comment by chopper385** [comment]
Crashed again for no reason while trying to move around the menu
![image](https://user-images.githubusercontent.com/69113332/134506414-d1be2602-5a48-41af-ac9d-a7a168b5cb75.png)
![image](https://user-images.githubusercontent.com/69113332/134506456-04bba25b-13ef-429e-bbfe-6dd11af7d0f0.png)

**Comment by Robosturm** [comment]
Could you add the line:
LogLevel=0
to the ini-file and sent me the crash-report when it happens.
Thx

**Comment by chopper385** [comment]
[20210923-181628 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/7219249/20210923-181628.Commander.Wars.Crash.log)

**Comment by Robosturm** [comment]
Update bug description cause the bug has nothing to do with multiplayer
