### ISSUE TITLE
Suggestion: COs in Faction Order for the CO Info Screen

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#586]
What I mean is:
When you check the information of the CO and it brings you to the CO-Information menu, on the bottom right it lets you choose the next CO or the previous CO. 
But the problem is if you check the CO information on Andy and Click next, it'll bring you to the Beast's CO Information, meaning that order is alphabetical based when it would be better for it to be ordered based on Faction. For Example:
Click next on Andy, it goes Max, then Sami, Then Jake, etc. And if you click "Previous" on Andy, it goes to whoever is the last CO in the order of the factions (In vanilla game it would be Yukio), and pressing previous on them goes to whoever is before them and so forth.

**Comment by Robosturm** [comment]
I'm already aware of this but decided to move it to release 21.
