### ISSUE TITLE
An option to disable debug information in the console when developer mode is enabled

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#588]
You know how the game console starts giving out redundant information like "playing sound" and "cursor moved" when developer mode is enabled? While such info *could* be helpful for a developer, I personally wish there's an option to turn them off.
You might be wondering, why even enable developer mode then? Well, I *have* to, because I need to run test commands from the console, and sometimes I need to use `GameConsole.print` for debugging purposes.
My problem here is that my print results become almost impossible to see, as they get pushed off the screen by the loads and loads of unnecessary information.

Also, one thing I've noticed is that, even after you turn developer mode off with `setDeveloperMode(false);`, the console still prints dev information. Is this a bug?

**Comment by Robosturm** [comment]
Just enter GameConsole.setLogLevel(1) or higher depending on which messages you want to suppress
