### ISSUE TITLE
The higher the "animation speed" value is in the settings menu, the faster the battle animations will play

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#59]
**Describe the bug**
The speed at which the new battle animations play is based on the "animation speed" value in the settings menu. The results is that the battle animations play way too fast if you've set your "animation speed" value to 10, like I do.

**To Reproduce**
1. Go to the settings menu.
2. Set Animation Speed to 10.
3. Begin a game.
4. When battle unfolds, notice how fast the battle animation plays.

**Expected behavior**
Battle animation speed should remain the same independently from the "animation speed" value in the Settings menu.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 6

**Additional context**
Worth mentioning is that you can set animation speed value from 1 to 99, but from 10 onwards, it becomes so fast that it makes basically no difference between 20 and 99. I'll report this in more details in another bug later though.

By the way I also love the Overworld animations when a unit attacks another unit, really makes the action more satisfying ^^

**Comment by Robosturm** [comment]
I can split up the battleanimationspeed settings and the normal animation speed setting to allow them to be configured seperatly.
I change the limit to 25 one day. xD The upper limit was choosen at random.
