### ISSUE TITLE
bugged graphics

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#593]
Dark Matter Mechs don't fly away when they die
Stopping anim columns are measured wrong (BH recon, BM light tank)
Brown Desert Flak disappear when stopping
water scrolling stops when sea unit counter attacks (same for bombers and sky scrolling)
carrier vanishes when destroyed
fighter's missile momentarily disappears when they can't counter attack, artillery's cannon twitches
Rocket's rockets don't fly right

**Comment by Robosturm** [comment]
For the future can you make one issue for one problem, please.
Thx.
Not sure what you mean with the rockets.....

**Comment by KBraid** [comment]
i was playing a single session and collecting all the issues i could find, i'll put them into their own tickets next time

**Comment by KBraid** [comment]
i wasn't sure how to describe the rockets, it was really confusing to see

**Comment by Robosturm** [comment]
All fine. Just wanted to inform you for the next time ;)
The problem is i don't know what you mean with the rockets. :(

**Comment by KBraid** [comment]
i think the rockets are flyng up from offscreen rather than coming out of the unit then flying off screen, but i'm not sure

**Comment by KBraid** [comment]
the stopping animations having the wrong amount of frames is my fault, had skipped over saving the extra frames for them

**Comment by Robosturm** [comment]
I fixed the res.xml for now.
Yeah might be that the rockets start offset is not 100% correct it's kinda hard to position the rockets correctly.

**Comment by Robosturm** [comment]
Okay the problem with rockets and missiles as well is that with each time the animation plays the rockets start more and more at the wrong position. 
Java-Script isn't doing what i thought it would do....
