### ISSUE TITLE
Darker Teal

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#595]
There is currently quite a mismatch between Teal Island's CO Tab Colour, Colour Preview, and their actual ingame colour:
![image](https://user-images.githubusercontent.com/51452633/134902347-58cb5e10-88f0-4593-9236-b78167059478.png)

Comapred to the previews, the ingame Teal is much lighter than what one would expect. Could a darker Teal be added instead to represent Teal Island? I personally feel like it'd be better than the light colour we have now.

**Comment by KBraid** [comment]
i have reduced the brightness on the teal
