### ISSUE TITLE
cruiser gun doesn't rotate

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#596]
cruiser's gun doesn't rotate when attacking ground targets, snapping into firing position, and resetting once it's done attacking.

**Comment by Robosturm** [comment]
The problem is that i can't really add it unless the attacking frames match the  amount of mg fire frames.
Cause i can't loop an animation from the start and then loop it with a supset of those frames....

**Comment by KBraid** [comment]
trying to understand what you mean, would it work if i were to split off the rotation frame into its own sprite?

**Comment by Robosturm** [comment]
So the mg firing has 6 frames.
So the cruiser would need to have 1 down frame and 6 firing frames as well so 7 in total.
So i can overlap them to one animation.

**Comment by KBraid** [comment]
ah i understand now!
