### ISSUE TITLE
carriers can't build sea planes

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#599]
playing through the DoR campaign i realized the carriers were useless in their current state

**Comment by Robosturm** [comment]
Are you having the AW-DS Unit Mod active or did you have less than 15000 Funds?

**Comment by KBraid** [comment]
i do not have the AW-DS Unit Mod active, and the option to buy sea planes is not visible when ordering a carrier

**Comment by Robosturm** [comment]
It only gets visible if you have the funds.

**Comment by KBraid** [comment]
ah i was not aware of that
