### ISSUE TITLE
Missing HQ Images

### ISSUE THREAD

**Issue by RyushoYosei** [Robosturm/Commander_Wars#6]
There are two or three faction color/designs that are missing HQ Images, so if you have a 16 player map, Those few factions don't have an HQ.

**Comment by Robosturm** [comment]
Found the bug the armies are missspelled in the general player script.
If you want you can download the resource file "resources\scripts\general\player.js" in the repository abd replace it with the one in your release or just wait for the next release.

Thx for the bug report.
