### ISSUE TITLE
Old rules

### ISSUE THREAD

**Issue by wangjl7799** [Robosturm/Commander_Wars#60]
Hello Robosturm,

It reminds me of the Advance war is that my friend played it on android GBA simulator, and I've download the GBA version AW2 to play. But yesterday I saw the custom war you released on reddit, and I find it s a further better experience control my war with mouse rather than just AB button. 
But something made me confused at first play. The dmg rule is changed so light tank and artillery can destory infantries with 1 hit. My suggestion is, could you upload the original rule as a new mod so that some players who keep the old memories to this game can enjoy more? I dont mean that new rules and units are not good, but just want to play the classic AW version which lies in my primary school memory.

Hope this game going well.

**Comment by Robosturm** [comment]
You can that already. ;)
Go to option -> mods -> select Advance Wars DS Units Mod to get Advance Wars Dual Strike Damage and Unit Costs 
or select Advance Wars DC Unit Mod to get Advance Wars Darc Conflict Damage and Unit Costs

**Comment by wangjl7799** [comment]
Oh well thanks for your directing, but I will say that there are still some bugs:
1. dmg of the infantry:
![1](https://user-images.githubusercontent.com/51902537/64389513-f181b180-d03a-11e9-8a53-afa920c77714.png)
It appears to be 5% in wiki and play, but dmg of infantry to another infantry shouldnt be 5%
2. I select AWDS unit in building list->untick the black bomb->black bomb still available in airport;
unselect all units->select AWDS unit as available->untick black bomb->black bomb not available in game.

**Comment by Robosturm** [comment]
Thx for the report, but please report bugs in a seperate issue for each bug makes it easier for others to check already reported bugs and helps me to keep track of what i fixed already. Thx in advance
Fixed both bugs.

You could download the current source.zip and copy the mods folder to fix it. If you don't want to wait a month for the next release

**Comment by wangjl7799** [comment]
OKay I will keep that in mind XD, and thanks for all your work for this game so that players not good at codes can enjoy the excellent game!
