### ISSUE TITLE
Logless Game Crash

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#605]
As mentioned on the Discord. Here's the map and the .ini
[Oops.zip](https://github.com/Robosturm/Commander_Wars/files/7259405/Oops.zip)

**Comment by Robosturm** [comment]
Did you watch the match are let it play in the background? Cause this match never ends qnd i guess the game crashes due to the game running over 3000 turns and more....

**Comment by FranticFairy** [comment]
I was watching it, I highly doubt it reached 3000 turns before it crashed first time around. Could it be possible that it crashes due to another program being on demanding a lot of memory from my PC?

**Comment by Robosturm** [comment]
I know that games can crash if 1-2 GB of RAM is left on the pc.

**Comment by Robosturm** [comment]
I'm taking that you run out of memory.
If you find that bug again create a new issue ;)
