### ISSUE TITLE
Perk Requirements & Incompatibilities

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#606]
I'm not 100% sure if this is currently a feature or not, but I don't think it is?

It would be cool if we could list perks as requirements for taking another perk, or perks that rule out other perks.

**Comment by FranticFairy** [comment]
Additional ideas to this:

Since perks can be part of a Group, perhaps requirements can also be more generic and require you to simply have or not have perks from a certain group.

My idea would be that you can define things like

To select this perk, you:
- Must have Perk X
- May not have Perk Y
- Must have at least 2 perks from Group A
- May not have more than 3 perks from Group B

This way, modders can turn the perks into something more balanced, where players cannot simply pick the strongest perks by either locking them behind pre-requisite perks or forcing players to also pick negative perks to take them.

**Comment by Robosturm** [comment]
I'm going for the simple solution.
A function getPerkEnabled(co) is added if you return true the mod is selectable and false if not.
With the co object you can get the current mods via getPerkList() and from there on you can do pretty much anything you want
