### ISSUE TITLE
Choose map style option

### ISSUE THREAD

**Issue by QuestionMark210** [Robosturm/Commander_Wars#608]
Let to players choose a map styles between; normal, snowy, deserty or wasteland. As it was in Dual Strike.

**Comment by KBraid** [comment]
the way it works in Commander Wars is that the different terrain types can be mixed and matched on the same map and have unique properties beyond aesthetics.

**Comment by Robosturm** [comment]
As K'Brais said CoW uses desert, snow as terrain with addional effects. So you create a mod which changes the style but the vanilla game won't add  feature like
