### ISSUE TITLE
Mod bug

### ISSUE THREAD

**Issue by wangjl7799** [Robosturm/Commander_Wars#61]
under AWDS mod, the heavy tank can do only 12% dmg to infantries.

![bug](https://user-images.githubusercontent.com/51902537/64475057-8092e480-d175-11e9-9f5c-8174e338c5de.png)

**Comment by wangjl7799** [comment]
and 1% to light tanks, etc.

**Comment by Robosturm** [comment]
Sadly unless you download the current source from here: https://github.com/Robosturm/Commander_Wars/archive/master.zip and copy the mods folder over the current one.
The AW-DS-Unit Damage mod is not working correctly. As said it's fixed for the new release.
