### ISSUE TITLE
Android Issues with Mod Loading?

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#611]
I'm not entirely sure if this is due to the slightly roundabout way I had to put the mod on my phone (zipping it, downloading it on mobile, then extracting it), but the game refuses to activate my mod despite it working just fine on PC.

It has no issues activating built-in mods.

Attached is the mod in question.

https://www.dropbox.com/s/40al8o2voeut79r/fai_expanded_aw.rar?dl=1

**Comment by Robosturm** [comment]
The deleted mod detection is bugged for android.
And deletes all custom mods from the ini when the game starts
