### ISSUE TITLE
AI kindle freeze after super power activated

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#613]
[console.log](https://github.com/Robosturm/Commander_Wars/files/7272443/console.log)

Kindle activated SP and there was no SP map animation and AI froze afterword,

C++ memory leak detected.

**Comment by Robosturm** [comment]
Are you using the latest pre-release? Released last sunday.
Cause this is an issue that happened with a certain animation setting.
If you use the latest one can you please attach your animation setting.

**Comment by Robosturm** [comment]
Okay found out there's a bug in kindles scop code
