### ISSUE TITLE
incredibly long load times

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#614]
after ai's turn is over it took a solid two minutes before the game started accepting input again
[console.log](https://github.com/Robosturm/Commander_Wars/files/7274247/console.log)

**Comment by KBraid** [comment]
one time issue, seems to have cleared up

**Comment by KBraid** [comment]
i don't remember the circumstances of when this happened

**Comment by Robosturm** [comment]
I reopened for the log-file.
Cause there is an image size error during the loading process and i didn't want to forget to check it. ;)

**Comment by Robosturm** [comment]
If it happens again. Please inform me about it
