### ISSUE TITLE
smugglers don't have graphical randomization

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#617]
the randomized unit look in the battle animation isn't implemented

**Comment by Robosturm** [comment]
It's. I think we have a different interpretation of it. I guess.
I thought you meant Fairys approach.
In that case all smuggler models of one unit are the same and stay the same for the rest of the game.
Building another smuggler assigns a different sprite for all models of that newly build unit.

**Comment by KBraid** [comment]
oh maybe i misunderstood how it worked then, what i thought was it was handled the same way terrain handles randomized foreground

**Comment by Robosturm** [comment]
Having different models in one sprites is doable as well.
But that would be something that i would move to the actual next release.
I'm going through the minor unit missing issues.
Check Acid Ace bug and mostlikely move that one to the next release as well

**Comment by FranticFairy** [comment]
Wow, you actually used my ancient idea for sprite randomization! Never thought I'd see that be used anywhere outside of my own projects.

**Comment by Robosturm** [comment]
I have been looking into it now.
But giving each model a different sprite is pretty hard to pull off.
I fear so i would keep it the way it is that each unit gets a unique model assigned
