### ISSUE TITLE
flashing OS Md sprite error returned

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#619]
i'm not sure why or how but the incorrect Md tank movement sprite for orange star has gotten back into the game
adding this report as a reminder to myself to fix that

**Comment by Robosturm** [comment]
I was thinking the turning black movement was back. xD
Just go ahead and create issues if you find them for me or yourself. :)
Just don't close bugs so they stay open till an actual release happens.
So everyone can see the current bugs.
