### ISSUE TITLE
Low ammo indicator does not display for some units.

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#62]
**Describe the bug**
For some reason, when some units start to run low on ammo, the ammo indicator will not flash.

**To Reproduce**
I don't know how to reproduce, it seems to be ransom.

**Expected behavior**
When a unit runs low on ammo, the ammo indicator should start blinking, simmilarly to the fuel indicator.

**Screenshots**
![image](https://user-images.githubusercontent.com/7210193/64477671-569dea00-d196-11e9-8c5c-41d913be80e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 6

**Comment by Robosturm** [comment]
I read the source and found a possible situation were the icon disappears at random.
Fixed it for the next release. Hoping that it is your bug cause it's pretty hard to reproduce that bug in a test environment
