### ISSUE TITLE
Battle Copters do only 6% damage to infantry in the AWDS mod

### ISSUE THREAD

**Issue by RicardoPires19** [Robosturm/Commander_Wars#63]
**Describe the bug**
When using the AWDS damage mod, Battle Copters only do 6% against normal infantry.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7210193/64477736-06735780-d197-11e9-89ba-21d2a27650aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 6

**Comment by Robosturm** [comment]
Yeah i fucked up the whole mod when i refactored it to a easier moddable interface.
Fixed it already. ;)
See this issue to get a hotfix if you want:
https://github.com/Robosturm/Commander_Wars/issues/61
