### ISSUE TITLE
All animations are played, regardless of settings

### ISSUE THREAD

**Issue by Erago2** [Robosturm/Commander_Wars#647]
All animations are played, regardless of settings. 

1. Go to settings
2. Select battle animation to Own
3. Select battle type to Detailed
4. Click on OK
5. All animations are still being played

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/92340347/136990365-ac77a47e-5f54-423f-a19e-bd95d34775b1.png)

**Desktop (please complete the following information):**
 - Windows
 - 20.0.2

**Comment by Robosturm** [comment]
As mentioned the only options are superficial were not deleted correctly
