### ISSUE TITLE
Supposedly hidden health is visible

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#65]
**Describe the bug**
Health of units that is supposed to be hidden (like Sonja's units) can be determined/guessed by hovering your mouse over the unit then counting the amount of sprites you see in the detail screen in the bottom right.

**To Reproduce**
Fight someone who has their units' HP hidden
Damage a unit
Hold your mouse over said unit

**Expected behavior**
Not entirely sure, perhaps the game should just show as though the unit is still at full HP?

**Screenshots**
![image](https://user-images.githubusercontent.com/51452633/65524339-f1642b80-deed-11e9-8005-7cb2fb86bd69.png)

**Comment by Robosturm** [comment]
Fixed the visual issue.
Going for damage info approach probably tomorrow

**Comment by Robosturm** [comment]
added Text Damage shown when attacking units with battleanimations turned off ;)
