### ISSUE TITLE
Suggestion: Inherit Damage

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#66]
I have no idea whether or not this is already a feature, it might be and I just missed it, but I came up with something while modding and toying around with things.

The option to, when creating a new unit, to define what other unit it inherits damage from. For example, you want to add a new type of tank unit. From what I can gather, if you do so, you also have to change every weapon that should be able to damage it and add the damage % for the new unit to it.

This new function would be something like _setInheritDamage(_**ExistingUnit**_)_. This would, in turn, make weapons treat the unit as though it were an ExistingUnit, so you could make a new unit take damage as though it was a Tank unit without having to add weapon damage stats to all existing weapons for the new unit. 

_setInheritDamage(_**LIGHT_TANK**_)_ for example would mean that, anything that can attack a Light Tank unit can attack the new unit, and deals damage to it as though it's a Light Tank

**Comment by Robosturm** [comment]
I already added something like that, though i'm not sure if i did it for the last release or this....
There are two functions you can override for the unit scripts:
getUnitDamageID() which is pretty much the setInheritDamage function you suggested.
getUnitDamage(weaponID, defender) here you can return damage based on the weapon on which the unit gets attacked. So you wouldn't need to override all weapon scripts. 
There's also another way of dealing with that you could add a damage entries to all weapon scripts in a single script but that's going a little deeper into it.
