### ISSUE TITLE
give carriers anti-air gun like in DoR (but only for counterattack)

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#661]
i had been thinking that it would be interesting for there to be a unit that had a weapon it could only use to defend itself and was unable to use for aggression. when i remembered that in DoR the carrier was a direct fire unit it made me think that if any unit were to have such a weapon, it would be the most logical choice.

to separate it from the kind of anti-air that you are expected to attack with, you could call it CWIS.

**Comment by Robosturm** [comment]
I think the aircraftcarrier is fine that way.
I didn't like the way the aircraftcarrier went in DoR.
But it's pretty easy to create a mod for that
