### ISSUE TITLE
charon's broken tank

### ISSUE THREAD

**Issue by pkgrass88** [Robosturm/Commander_Wars#68]
**Describe the bug**
in tutorial stage 2,i can't move charon's CO unit without the game crashing.

**To Reproduce**
1. Go to singleplayer, then select tutorial stage 2.
2. Click on charon's co unit, then try to move it.
3. then, the game crashes and turns itself off.

**Expected behavior**
I expected the tank to move normally

**Desktop (please complete the following information):**
 - OS: windows
 - Version 0.6

**Comment by Robosturm** [comment]
Fixed it the problem was that the CO-Unit was loaded wrong
