### ISSUE TITLE
"Foggy Weather" - Mist of War weather.

### ISSUE THREAD

**Issue by HammerGuy** [Robosturm/Commander_Wars#688]
Essentially turning mist of war into a possible weather type for map weather settings to use like rain activating a variant of fog of war.

**Comment by Robosturm** [comment]
@HammerGuy was looking into it right now.
And realised only one small problem.
I would either need a symbol for mist in the same art style as the current one or a replacement for all of them.
For the weather predicition....
You think you can pull something of for that?
