### ISSUE TITLE
Flares can't be direct-attacked when using AW:DS Unit Mod

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#69]
**Describe the bug**
Title kinda says it all, but it's really weird. The player can't direct-attack flares when the AW:DS Unit Mod is active, because the targetting cursor jumps to the attacking unit and selecting the flare does nothing.

**To Reproduce**
1. Activate the AW:DS Unit Mod
2. Direct-Attack a Flare Unit

**Expected behavior**
Targetting Cursor appears on the Flare Unit. Flare Unit can be attacked.

**Screenshots**
![image](https://user-images.githubusercontent.com/51452633/65816545-52954300-e1fd-11e9-9934-e2683699aa4d.png)
![image](https://user-images.githubusercontent.com/51452633/65816550-59bc5100-e1fd-11e9-8ae7-f875279a3fb8.png)
![image](https://user-images.githubusercontent.com/51452633/65816552-5cb74180-e1fd-11e9-8004-81411635f1ad.png)

**Comment by FranticFairy** [comment]
Bug Source has been found.

AW:DS Unit Mod gives the Flare unit the non-existent "WEAPON_FLARE" Primary Weapon. Removing it (as in, giving them a blank weapon instead) fixes it.

**Comment by Robosturm** [comment]
Whooops fixed it.
I fixed the bug in the original variant, but not in the mods.
Thx for the report.
