### ISSUE TITLE
the river falls graphics are aplying wherre they shouldn't

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#696]
![image](https://user-images.githubusercontent.com/53922323/139539404-798312b9-ef7d-4051-8b85-426efdb14313.png)

**Comment by Robosturm** [comment]
Oh the fallback for when no fitting river-tile couldn't find a tile didn't work.

It should look like this:
![grafik](https://user-images.githubusercontent.com/48879701/139558713-e076bd53-ddba-4fb0-8451-fbfbb34cd7e1.png)
