### ISSUE TITLE
Visual error when buying units via the keyboard

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#7]
When buying units via the keyboard, the cursor will go down and out of bounds instead of moving onto the next page. At least the "invisible items" will correspond to the appropriate units.

![image](https://user-images.githubusercontent.com/40665299/62001555-f727d580-b125-11e9-9c21-e38bfa0fc3b4.png)

**Comment by Robosturm** [comment]
Found that bug when i fixed your key-input bug and fixed it there as well. 
-> Also fixed some other visual bugs with the menu. :Ö)

Still thx for the report. Keep reporting ;)

**Comment by GuardianTempest** [comment]
And thank you for your quick response! I have a handful more bugs in mind.

I'll do my part.
