### ISSUE TITLE
terrain idea: creeper

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#701]
has the same stats as plains except for the feature where units that stand on it take 10% of their current HP in damage.

or for a subtler and more complex feature; every turn a unit spends on a creeper tile they get a creeper point. every creeper point a unit has deals 1% hp of damage per point per turn. if a unit with a creeper point directly interacts with another unit in any way (ie. direct attacks, supplies, gets supplied) the other unit also gets a creeper point. units with creeper points that combine also combine creeper points.

**Comment by Erago2** [comment]
Sounds like an interesting idea for a CO that interacts with this mechanic as well

**Comment by Robosturm** [comment]
The second version is way to gimmicky in my opinion and adds a complexity no one can really follow.

Adding a trap tile like in FE is an okay idea.
But for simplicity reasons i would change the damage to a flat 1Hp or so.
Everything else is again to hard to keep track of.
