### ISSUE TITLE
Transport Copter allows Sniper immediate movement

### ISSUE THREAD

**Issue by dorferino** [Robosturm/Commander_Wars#706]
**Describe the bug**
Unloading a sniper unit from a transport copter allows immediate movement.

**To Reproduce**
1. Build a sniper and transport copter.
2. Put the sniper into the copter.
3. Move copter and unload.

**Expected behavior**
Sniper gets an automatic wait order and cannot move.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 0.20.3

**Additional context**
Haven't tested other units.

https://user-images.githubusercontent.com/7918279/141315550-9c040949-9659-480c-b4e9-eec3101c0113.mp4

.

**Comment by Robosturm** [comment]
This is an intentional behaviour.
Units which stayed in a transport for a turn. So they didn't get unload in the same turn.
Can move after unloading.
There's an advanced rule to disable this feature.

**Comment by dorferino** [comment]
Ah you're correct
