### ISSUE TITLE
Xinput/Controller Support

### ISSUE THREAD

**Issue by HammerGuy** [Robosturm/Commander_Wars#707]
Likely infeasible and outside of scope given the lack of GUI for a non mouse/touchscreen interface, but sometimes I still yearn for the tried and true classic game controller setup via usb or bluetooth.

**Comment by Robosturm** [comment]
Note the controller support is only tested with a XBox 360 controller.
And isn't perfect.
One stick can be used for moving the mouse cursor one for moving per field.
Left and Right Back buttons are used for mouse click like interactions.
A and B are select and cancel keys.
The crosspad is mapped to scrolling.
All other keys are linked to the info key.
And it's disabled by default. In case someone doesn't have XInput on his Windows PC
