### ISSUE TITLE
edge bleedover toggle for map editor

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#709]
it would be nice to have a tool that toggles whether or not tiles consider the ends of the map a continuation of themselves or not so you don't have to manually adjust each tile to continue off the map edge or not.

**Comment by Robosturm** [comment]
This is something which is technically not really realizable.
The effort is way to high to get even close to something that would work.
So i have to deny that. :(

**Comment by KBraid** [comment]
i've noticed that sometimes when manually editing terrain to bleed over the edge, after saving and reloading the map either in the editor or to play, that the tile has reverted back to ending on the edge.

**Comment by KBraid** [comment]
before beta 20 i recall the default behavior was for all tiles to bleed over, if this bug isn't something that's feasibly fixable than returning to the past behavior of always bleeding over would probably be necessary

**Comment by Robosturm** [comment]
Bleeding over for rivers is probably not doable. Need to check it.
Regarding the fixed tileset usage that's a bug with the current state. The flow loader isn't checking for a fixed sprite
