### ISSUE TITLE
Modding Suggestion: Hide CO Zones & Ranks

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#711]
Basically, me and my friend are working on a COs mod at the moment and one of the ideas we thought of was; of a CO that can hide their Unit Ranks & CO-Unit (+ Zone) as their D2D (Kinda like how Sonja hides her HP). But as far as we know, there's currently no way to do it...so, can there be a way to do it added?

**Comment by Robosturm** [comment]
I took a look at it and i can say that this won't happen.
a) It makes the game only annoying cause you need to count tiles so it's less of a gameplay feature like Sonja's HP hidding
b) It's overcomplicated to add when considering possible modding of CO swapping etc.

**Comment by Seimix** [comment]
Okay, could you at least add the ability to hide normal CO ranks then? (Experienced, Veteran, Elite, etc)
