### ISSUE TITLE
Lake Improvements

### ISSUE THREAD

**Issue by HammerGuy** [Robosturm/Commander_Wars#718]
If Lakes and Oceans are meant to connect to each other, will need to draw up some cliff transition tiles. Beaches could also use some Lake variants as a would be nice to have. Also need to do a few more River-Lake connection cases. (This is more a reminder to myself.)

**Comment by Robosturm** [comment]
Backoog clean up
Closed issue cause no one is working on it and didn't work on it for a long time.
If this changes a new issue should be created.
