### ISSUE TITLE
The CO ban list "cuts off" before the last CO?

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#72]
**Describe the bug**
The CO ban list doesn't actually list everyone, it cuts off before the end, meaning it's impossible to ban or unban whoever isn't listed (unless you use the select/unselect all button). Where exactly it cuts off depends on the screen resolution, as well as the number of COs, but no matter what I do, Zandra (the very last CO) is never on the list. For example, with 8 or no custom COs enabled, Zandra is the only one unlisted, but it gets worse with 7 custom COs, as anyone after Waylon isn't listed, not just Zandra.

This bug probably affects the unit build list too, seeing as that has a very similar design to the ban list. I think we just didn't have that many units for this to happen there.

**Additional context**
I'll point out that one of my COs comes after Waylon in alphabetical order. Because if he didn't, it'll probably cut off after Von Bolt instead of Waylon (with 7 custom COs).
Also, because it depends on the screen resolution, it might not happen to everyone. I did get a friend to verify it, but still.

**Comment by Robosturm** [comment]
Yeah the panel content size was set to the last co's row y-coordinates and not accounting for the row heigth. Applies for the unit list as well :(
Fixed both.
