### ISSUE TITLE
Modding Suggestion: Hide Unit HUD Information

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#724]
So a CO concept me and my friend have come up is: A unit that outright has their units hidden entirely, even without Fog of War.
So basically, if the CO Spawns an infantry unit, there's NO WAY you can tell it's an Infantry unit until after you attack it. 
And so far, the only thing we need now to do this is a way to hide the unit information on the hud: https://i.imgur.com/5vbOZY8.png
NOTES:
- Should be Separate from the Hiding HP and Ranks
- Would be very helpful if there was a function to hide unit sprites as well

Btw, if you do add this, could it also be possible to have that unit information on HUD simply just be replaced with another unit? (For Example, an infantry will show tank stats (including image) on both the HUD and the damage "calculator" thing, but would still act like an infantry when actually attacked and in every other way)

**Comment by Robosturm** [comment]
That's something not going to happen. Hidding/obscuring stuff isn't easy and has a lot of things to change and the workload highly exceeds the reusability

**Comment by Seimix** [comment]
Well, could you do something more blunt then? 
Such as allowing a modded CO have images show up over the HUD when the enemy hovers over their units? (Kinda like the Building List windows) and letting a CO block the enemy from pressing "I" to pull up unit information on their units?

**Comment by Robosturm** [comment]
Nope. As said obscuring information is nothing, that's supported and nothing i intend to support. The workload simply exceeds usability and also what i consider fin to play.
