### ISSUE TITLE
Fog of War Setting Changes When Selecting "Advanced" Settings

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#733]
**Describe the bug**
Basically, if you set your Fog of War to say..."Shroud of War" or standard FoW, it'll change to "Mist of War" if you select "Show Advanced Settings" .

**To Reproduce**
1. Start a Single Player Game
2. Set it to "Shroud of War" or normal "Fog of War"
3. Turn on "Show Advanced Settings"
4. It should be different

**Additional context**
Also happens when you start the game and go back to the rules menu.
I am using a CO Mod for this (As well as DS Weather & Co-op Mod)

**Comment by Robosturm** [comment]
This is just a visual bug.
The fog mode is still selected corretly just shown wrong.

**Comment by Robosturm** [comment]
On a side note: Don't report bugs with custom mods active. ;)
