### ISSUE TITLE
Modding request: more CO functions that deal with enemy players

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#736]
One thing I've noticed when modding COs is that CoW is a bit lacking in functions for one CO to affect an enemy CO. While global damage and stuff that drains ammo/fuel are easy to do, a D2D or CO power that modifies enemy stats in some way isn't as easy _unless_ there's already a function provided for it.
We already have Offensive/Defensive reduction (and several other functions that are "called from all COs" like "canBeRepaired"), but there's no _easy_ way to modify an enemy's basic stats like fire range, movement range, vision, deployment costs, capture rate, and so on.

An enemy equivalent for every function might be a bit too much to ask for, especially considering how the CO system is already set up, so... I understand if this is impossible, or too much work.

Correct me if I'm wrong though, maybe it's already possible and I'm not aware.

**Comment by Robosturm** [comment]
capture rates won't get modifiable for now.
You can still deplet the capture rate like alexander does,,,,
