### ISSUE TITLE
Problem with script editor in map editor.

### ISSUE THREAD

**Issue by Yiazraiko** [Robosturm/Commander_Wars#738]
**Describe the bug**

**To Reproduce**
1. Go to 'Map Editor'
2. Click on 'Menu/Edit Script'
3. Click in add event
4. see error

**Expected behavior**
When i click in add event (whatever the event) no event is created and of course i can't event a defeat for a player if the building (Death Ray in this idea) is destroyed.

**Screenshots**
![problem script editor](https://user-images.githubusercontent.com/92440337/146546730-a2df4c42-5296-45b9-892c-57b7841b90b5.png)

**Comment by Robosturm** [comment]
You need to select a condition to add an event.

**Comment by Robosturm** [comment]
Disabled the Button for the next version when it's not useable to clarify this
