### ISSUE TITLE
QWindowsGLContext: Unable find a suitable pixel format.

### ISSUE THREAD

**Issue by GabeValentine** [Robosturm/Commander_Wars#741]
**Describe the bug**
Crash during startup.

**To Reproduce**
1. Install current version
2. Try to launch
3. Crash

**Expected behavior**
First run, fresh install for dedicated server. Also tried running with -noui arg but same result.

**Console.log**
Warning: Attempted to use GDI functions with a non-opengl32.dll library File:  Line: 0 Function: 
Warning: QWindowsGLContext::QWindowsGLContext: Unable find a suitable pixel format. File:  Line: 0 Function: 
Warning: QOpenGLWindow::beginPaint: Failed to create context File:  Line: 0 Function: 
Warning: QOpenGLWindow::beginPaint: Failed to make context current File:  Line: 0 Function: 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version beta 21_3

**Additional context**
I assume the issue is on my end... but I could use some help understanding how to fix it.

**Comment by Robosturm** [comment]
Are you trying to run it on a pc without a gpu/without opengl installed?
Cause the current version still calls some gl-functions, which should be fixed in the current repo version.
