### ISSUE TITLE
The new CO functions are bugged

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#744]
Just gave 21.4 a shot, and the new CO functions are uh... "inverted". The ones that should affect enemy COs actually affect the player, and vice versa.
So far, I've only tested `getBonusLoadingPlace` and `getEnemyCostModifier`, but you should probably check the other new functions too, just in case.

In the screenshot below, the test CO (red) has `getBonusLoadingPlace` return 5, and blue doesn't have a CO, yet you can clearly see the extra slots on the blue infantry.
![screenshot+0](https://user-images.githubusercontent.com/50599768/147396492-0e3ebe49-02dd-42bb-9518-93bc11594453.png)

**Comment by Robosturm** [comment]
Only those two functions are affected.
