### ISSUE TITLE
Way to extract maps from Commander Wars

### ISSUE THREAD

**Issue by LordSpyro** [Robosturm/Commander_Wars#75]
'**Is your feature request related to a problem? Please describe.**
There is currently no way to extract map files from Commander Wars as it seem or it's not clear.

**Describe the solution you'd like**
I would like a way to extract maps you create to aws and png files. 

**Describe alternatives you've considered**
Instead of extracting a way to convert map files to another format.

**Comment by Robosturm** [comment]
Currently the game only contains importers.
The export to aws is a good addition. I was just lazy when adding the importer for it.

As for png export i don't see a use case for it. Since you can do a screenshot.
