### ISSUE TITLE
Game not compatible with Windows 7

### ISSUE THREAD

**Issue by Spaceman333** [Robosturm/Commander_Wars#750]
Already talked about in Discord - something to do with underlying tech used to build this game not supporting Win 7 or older - but I wanted to make this ticket anyway mainly as an official vote in favor Win 7 support that atleast I would appreciate if it was made possible.

If at some point theres a way to make this game work in Windows 7, I'd become very happy.

**Comment by vxiiduu** [comment]
Commander wars can easily be made to work on Win7. However, it requires some extra DLLs (in the zip file). Download the .ZIP I have provided, and read the instructions.
![image](https://user-images.githubusercontent.com/73044267/148937549-d7996fb0-0a7a-4a76-b4aa-37d4bd1e9a5f.png)
[CommanderWars_Win7CompatPack.zip](https://github.com/Robosturm/Commander_Wars/files/7846271/CommanderWars_Win7CompatPack.zip)

**Comment by Robosturm** [comment]
The pack is now also attached as unofficial pack to the last release.
