### ISSUE TITLE
Multiplayer game with ai becomes inconsistent

### ISSUE THREAD

**Issue by wyykak** [Robosturm/Commander_Wars#752]
During multiplayer games, game states will occasionally diverge between players. For example, they will see different units in one tiles, different unit positions or different hp, etc. However, the game may continue several turns before a "connection lost" message.

Example screenshots (taken by me and my friends at the same time)
![QQ图片20220111230539](https://user-images.githubusercontent.com/32379561/148967669-ee6e70e9-412d-4d1b-b9cb-acf8f25dc7f1.png)
![QQ图片20220111230546](https://user-images.githubusercontent.com/32379561/148967678-b5669602-74b2-4c24-bc0d-d3b2a84ce9ed.png)

**Comment by Robosturm** [comment]
Which CO's did you use?
And did you use any mods/which mods?

**Comment by wyykak** [comment]
I used Nana and my friend used Grit. I did not use any mods, just the latest Beta_21_4 release.



At 2022-01-12 15:26:40, "Robosturm" ***@***.***> wrote:

Which CO's did you use?
And did you use any mods/which mods?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Robosturm** [comment]
Seems to be a problem related to using ai's in multiplayer games. A human vs human game should work fine

**Comment by Robosturm** [comment]
Problem is an instanciation of the ai on client and server instead of only on the server side

**Comment by wyykak** [comment]
I just tried the latest code. The inconsistency problem seems to be gone. However, I found that the sound was gone too (music was still ok). 
How I compiled the code:
```
git clone <the repo>
cd Commander_Wars
cmake . -B build -G "Unix Makefiles"
cd build
make -j16
```
Environment:
OS: Windows 10 x64
Build Env: msys2/mingw64
C++ Compiler: g++ 11.2.0
CMake: 3.22.1
QT: 6.2.1

Can you observe the same problem? Or what is wrong with my compiling process?

logs:
Configure: https://paste.ubuntu.com/p/XQChxkc8tR/
Compile: https://paste.ubuntu.com/p/kvwrq6Sj4M/
Game console: https://paste.ubuntu.com/p/B97GSPCxbg/

**Comment by Robosturm** [comment]
You can't take the development state and expect everything to work. In this case the new mute function was unfinished.
While you can compile dev states i'm not giving any gurantees for the3
