### ISSUE TITLE
Game crash when i'm trying to read unit info on wiki

### ISSUE THREAD

**Issue by QuestionMark210** [Robosturm/Commander_Wars#753]
Here is crash log:

 Commander Wars vVersion: 0.21.4 Builddate: Dec 23 2021 22:40:34
14 Jan 2022 @ 11:49:51

EXCEPTION_ACCESS_VIOLATION

INFO: 14.01.2022 11:49:44: Enter "help()" for console info.
INFO: 14.01.2022 11:49:44: Starting Game...
INFO: 14.01.2022 11:49:44: Prepare to Fight...
INFO: 14.01.2022 11:49:44: Read this message while waiting...
INFO: 14.01.2022 11:49:44: 
INFO: 14.01.2022 11:49:44: Eek! A mouse! Plug it out! Eek! It's full of bytes!
INFO: 14.01.2022 11:49:44:

**Comment by Robosturm** [comment]
Only affects the wiki if opened outside a game
