### ISSUE TITLE
Concept: Pipe-Monorail

### ISSUE THREAD

**Issue by HammerGuy** [Robosturm/Commander_Wars#755]
An alternate terrain for pipe units to traverse based on the notion that the top of a pipe is a monorail for piperunners; functionally identical to the rail from Super Famicom Wars, in that it allows passage of all units compared to the pipe, without having to create a whole new unit class and building for deployment (since the base and pipe station can be used.)

**Comment by Robosturm** [comment]
Not a terrible and neither a i want that idea.
Depends on the sprites.....if they're good they're a good extension

**Comment by Robosturm** [comment]
Backoog clean up
Closed issue cause no one is working on it and didn't work on it for a long time.
If this changes a new issue should be created.
