### ISSUE TITLE
icp and pixel errors

### ISSUE THREAD

**Issue by Danmark25** [Robosturm/Commander_Wars#756]
[console.log](https://github.com/Robosturm/Commander_Wars/files/7882745/console.log)

**Comment by Robosturm** [comment]
Both errors look like you're using a faulty installation.
E.g. you have the resource folder laying around which was removed in Beta 20.

**Comment by Danmark25** [comment]
But there's a problem. Yes I had earlier Beta 20 but I deleted all files from it and clean trash bin, so there's no trace from it.

Currently I have only that 21.4 version

**Comment by Danmark25** [comment]
Even reinstall of that newest version (21.4) doesn't do any effect either.
