### ISSUE TITLE
Repeating Weather Sound Effect

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#76]
**Describe the bug**
So far only experienced this with rain, but the 'rain start' sound effects triggers for every player instead of only for player 1. So if it starts to rain in a four player game, you hear the rain start sound effect four times.

**To Reproduce**
1. Start a game with a chance for rain
2. Wait for rain to happen

**Expected behavior**
IIRC, the rain sound should only play once; when the rain actually starts, instead of for every player's turn.

**Comment by Robosturm** [comment]
Fixed the sound was part of a bug that could have more impact on custom weathers with extra effects
