### ISSUE TITLE
[Android] Add cancel button

### ISSUE THREAD

**Issue by AdityaMH** [Robosturm/Commander_Wars#761]
Since this game base for pc. But can be ported to Android.
 Can you add cancel button (right mouse) in upper screen?

Also, more shortcurt are more better too.

**Comment by Robosturm** [comment]
Are you aware of the fact that a long press is the same as canceling/right mouse button on pc?
Cause i don't see a big enhancement over a long press.

**Comment by AdityaMH** [comment]
But not if you want to cancel attack or cancel selling unit. Impossible thing to android.
So need add it to base game.

**Comment by Robosturm** [comment]
In which scenarios can't you cancel those with a long press?
I don't see why you can't cancel an attack with a long press on the touch screen.

**Comment by Robosturm** [comment]
Might be that the sensitivity is to low increasing it usually helps especially on device with a higher dpi-ratio.

**Comment by Robosturm** [comment]
If the sensitivity is to high sliding gestures aren't detected that well, for that reason you need to adjust it for your own device if you have problems with long presses.

**Comment by AdityaMH** [comment]
But still better add them shortcut, since Android doesn't have **physical** keyboard.
Also, who first time playing this game can be confused too.
