### ISSUE TITLE
condition scripts loaded into the script editor have their Y value erased

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#765]
coordinate scripts loaded into the script editor that have a load it as a Y of 0. saving the script without correcting results in the 0 being saved as well.

**Comment by Robosturm** [comment]
@KBraid Please tell me which condition/conditions are affected by this.
Each condition has it's own reader/writer, so i doubt all readers are affected by this.
Thx.

**Comment by KBraid** [comment]
after testing i found it's only the building captured condition
