### ISSUE TITLE
ai has pathfinding issues in regards with hovercraft, transports, and opean ocean maps

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#771]
ai will gather hovercraft around harbors and transports clogging up the space. transports loaded with hovercraft will be unsure what to do, usually dumping them right back out after loading them up

**Comment by Robosturm** [comment]
Requires a savegame to verify/find a problem

**Comment by KBraid** [comment]
https://cdn.discordapp.com/attachments/858434451507249162/938104164536422520/Sprinkle_Isles.sav
