### ISSUE TITLE
odd corner connections between beach tiles

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#773]
beach tiles on land corners don't seem to connect cleanly between neighboring beach tiles
![image](https://user-images.githubusercontent.com/53922323/152023334-d34402cc-4020-4252-a781-8afff4d97a6c.png)

**Comment by Robosturm** [comment]
This is due to a lack of sprites....
And can only be resolved with fitting beach tiles. Sadly.

**Comment by KBraid** [comment]
#1143 this should hopefully be of help
