### ISSUE TITLE
sprite error with river fall in regards to beaches

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#776]
when a river fall has beaches next to it it displays as though it is connected to a one-sided sea tile rather than a three sided tile.

![image](https://user-images.githubusercontent.com/53922323/152196959-8bd767cc-02aa-4b93-8459-ab62cff7fc80.png) 
![image](https://user-images.githubusercontent.com/53922323/152197139-fcfba157-0085-4332-a505-7f7c0af51d3f.png)

this is how it should look.

![image](https://user-images.githubusercontent.com/53922323/152197001-bcd55c32-b6b2-4926-8888-44e0f918371e.png)

**Comment by Robosturm** [comment]
Applies for Fog and Rough Sea Tiles as well
