### ISSUE TITLE
Highlighted tiles are overanimated

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#78]
**Is your feature request related to a problem? Please describe.**
When you select a unit, you can see its movement range, by way of highlighted tiles. But the animation used for these (with the moving sideway stripes) is almost hurting my eyes. This is made even worst by the "planned movement" feature (which, by the way, is an excellent feature). Almost half of the gamescreen is covered in those moving stripes. I uploaded a screenshot below.

**Describe the solution you'd like**
Any other animation for these tiles, or even, no animation, for example just a transparent overlay. It would give the same result (showing the player which tiles are accessible) without being flashing so much.

**Additional context**
I play with the latest release of the game, Beta 8, on Windows 10.
Here's a screenshot:

![commander_wars-highlighted_tiles](https://user-images.githubusercontent.com/53582470/70389964-8d1e1780-19c6-11ea-840e-5ee951bbd191.jpg)

**Comment by Robosturm** [comment]
Well the animation is the one from AW2/DS.
But i understand what you mean.
What i can over you would be an option to make the marked fields animation static. So they don't move at all.

**Comment by Koopanique** [comment]
Well I guess I could also just mod it to my taste.
After looking around in the gamefiles, I think the right file to modify is "marked+field.png", right? If so, I'll just edit it myself

**Comment by Robosturm** [comment]
Yes that's the correct file. :)
