### ISSUE TITLE
The displayed number of HP lost during a battle does not match the actual number of HP lost

### ISSUE THREAD

**Issue by Koopanique** [Robosturm/Commander_Wars#79]
**Describe the bug**
During the overworld battle animations, the number of HP lost is displayed as a red floating text that disappear after 1 or 2 seconds.
However, very often, the number doesn't match.

For example, if I attack an enemy infantry with one of my own, the displayed damage will be "5 HP lost", but the enemy unit will have 6 HP remaining.

I can guess why it does that, I think units actually have 100 HPs, but the game simplifies it around 10 (like in the original AW games). All these approximations could result in the game removing 45 HP from a unit, rounding the damage display up to 5, but not the actual unit HP... maybe.

**To Reproduce**
1. Go ingame.
2. Attack a unit.
3. See the numbers.

**Expected behavior**
Numbers should match

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 8

**Comment by Robosturm** [comment]
Yeah a unit has actually 10 Hp, but you can do like 4.5HP so i decided to round up damage numbers.
Just realized i could actually get the start hp and end hp instead of using the actual dealt damage.

Okay for the next release damage numbers should be accurate. :)
