### ISSUE TITLE
Suggestion: use format string rather than concatenate fixed string and variables

### ISSUE THREAD

**Issue by wyykak** [Robosturm/Commander_Wars#794]
Example (Javascript):
"Activate power of" + co_name
↓
\`Activate power of ${co_name}\`

Reason:
It can make translation easier since word order may vary in different languages. For example:
\`Activate power of ${co_name}\` can be translated as \`激活${co_name}的能力\` in Chinese
This will be impossible to translate with the old concat method.

**Comment by Robosturm** [comment]
That's something that should be done if actual translations happen. Currently no one is doing translations and if chinese is possible is something else. Cause the exported fonts don't include chinese signs and even if it's something on a different level
