### ISSUE TITLE
Enemy captures visible in Fog of War

### ISSUE THREAD

**Issue by GuardianTempest** [Robosturm/Commander_Wars#8]
When the enemy AI captures a building, the capturing animation is visible in Fog of War, either caused by rain or in the Fog of War setting. This shouldn't be a thing, and just in case, the "enemy has captured a property" sound also shouldn't play.

**Comment by Robosturm** [comment]
That was actually intentionally, cause my memory told me that it was this way in Advance Wars.
Checked it on my Gameboy which proved my memory wrong.

I also realized that buildings should be neutral when not visible...

**Comment by Robosturm** [comment]
fixed also that buildings aren't shown as neutral when in fog of war. 
This doesn't apply for none capturable buildings like mini cannons etc.
-> it's part of the buildings now that they tell the engine if the player is visible during fog of war or not

**Comment by GuardianTempest** [comment]
You're welcome, and thank you for the quick response.
