### ISSUE TITLE
still the dmg bug....

### ISSUE THREAD

**Issue by wangjl7799** [Robosturm/Commander_Wars#80]
![bug](https://user-images.githubusercontent.com/51902537/70856645-6be28d00-1ed8-11ea-9d28-73492528566d.png)

the heavy tank's machine gun is still not working right against to helicopt and infantries..

my os: win10

**Comment by wangjl7799** [comment]
and under dual strike mod.

**Comment by wangjl7799** [comment]
and 0.80 version

**Comment by Robosturm** [comment]
Oh damn sry i accidently reverted a part of the bug fix.... :(
Fixed it again. Hopefully.
