### ISSUE TITLE
[latest] Sending map data to client without it crashes the client

### ISSUE THREAD

**Issue by wyykak** [Robosturm/Commander_Wars#801]
DEBUG: 17.02.2022 22:52:28: Focus lost for object
DEBUG: 17.02.2022 22:52:28: Playing sound: button.wav using cache sound 0
DEBUG: 17.02.2022 22:52:28: Leaving Lobby Menue to join game by adress
DEBUG: 17.02.2022 22:52:28: Entering Map Selection Menue
DEBUG: 17.02.2022 22:52:28: AudioThread::SlotClearPlayList() start clearing
DEBUG: 17.02.2022 22:52:28: AudioThread::SlotClearPlayList() playlist cleared
DEBUG: 17.02.2022 22:52:28: Playback state changed to 0 for player
DEBUG: 17.02.2022 22:52:28: Media status changed for player to 0
DEBUG: 17.02.2022 22:52:28: Unable to locate music folder: mods/coop_mod/resources/music/mapselection
DEBUG: 17.02.2022 22:52:28: Unable to locate music folder: resources/music/mapselection
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+0.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+1.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+2.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+3.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+4.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+5.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+6.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+7.mp3 to play list
DEBUG: 17.02.2022 22:52:28: Adding :/resources/music/mapselection/mapselection+8.mp3 to play list
DEBUG: 17.02.2022 22:52:28: AudioThread::SlotPlayRandom
DEBUG: 17.02.2022 22:52:28: Buffering music for player: :/resources/music/mapselection/mapselection+6.mp3
DEBUG: 17.02.2022 22:52:28: Media status changed for player to 1
DEBUG: 17.02.2022 22:52:28: MapSelection::changeFolder 
DEBUG: 17.02.2022 22:52:28: Playback state changed to 1 for player
DEBUG: 17.02.2022 22:52:28: MapSelection::changeFolder. Relative Path: maps
DEBUG: 17.02.2022 22:52:28: MapSelection::updateSelection Loading: :/maps/advance_wars_2_campaign.jsm
DEBUG: 17.02.2022 22:52:28: MapSelection::updateSelection Loading: :/maps/advance_wars_campaign.jsm
DEBUG: 17.02.2022 22:52:28: MapSelection::updateSelection Loading: :/maps/advance_wars_days_of_ruin.jsm
DEBUG: 17.02.2022 22:52:28: MapSelection::updateSelection Loading: :/maps/commander_wars.jsm
DEBUG: 17.02.2022 22:52:28: MapSelection::updateSelection Loading: :/maps/tutorial.jsm
DEBUG: 17.02.2022 22:52:28: MapSelection::updateSelection Loading: :/maps/war_room.jsm
CRITICAL: 17.02.2022 22:52:28: TypeError: Cannot call method 'getImageSize' of null in File: qrc:/resources//scripts/building/znest_center_laser_left.js at Line: 10
CRITICAL: 17.02.2022 22:52:28: TypeError: Cannot call method 'getImageSize' of null in File: qrc:/resources//scripts/building/znest_center_laser_middle.js at Line: 10
CRITICAL: 17.02.2022 22:52:28: TypeError: Cannot call method 'getImageSize' of null in File: qrc:/resources//scripts/building/znest_center_laser_right.js at Line: 10
CRITICAL: 17.02.2022 22:52:28: TypeError: Cannot call method 'getImageSize' of null in File: qrc:/resources//scripts/building/znest_nest_laser.js at Line: 10
DEBUG: 17.02.2022 22:52:28: Entering Multiplayer Menue
DEBUG: 17.02.2022 22:52:28: Client is running
DEBUG: 17.02.2022 22:52:28: State changed for 0
DEBUG: 17.02.2022 22:52:28: State is now Lookup.
DEBUG: 17.02.2022 22:52:28: State changed for 0
DEBUG: 17.02.2022 22:52:28: State is now Connecting.
DEBUG: 17.02.2022 22:52:28: Client gets closed
DEBUG: 17.02.2022 22:52:28: TCP Client 0 disconnected.
DEBUG: 17.02.2022 22:52:28: State changed for 0
DEBUG: 17.02.2022 22:52:28: State is now Connected.
DEBUG: 17.02.2022 22:52:28: Client is connected
DEBUG: 17.02.2022 22:52:28: Updating Socket ID to: 3
DEBUG: 17.02.2022 22:52:28: Focused object changed
DEBUG: 17.02.2022 22:52:28: Show virtual keyboard
DEBUG: 17.02.2022 22:52:28: Network Command received: MAPINFO for socket 3
DEBUG: 17.02.2022 22:52:28: Command not handled in playerselection
DEBUG: 17.02.2022 22:52:28: Local Network Command received: MAPINFO for socket 3
DEBUG: 17.02.2022 22:52:28: Media status changed for player to 2
DEBUG: 17.02.2022 22:52:28: Checking for map test.map and script 
DEBUG: 17.02.2022 22:52:28: Sending command REQUESTMAP
DEBUG: 17.02.2022 22:52:28: Network Command received: MAPDATA for socket 3
DEBUG: 17.02.2022 22:52:28: Command not handled in playerselection
DEBUG: 17.02.2022 22:52:28: Local Network Command received: MAPDATA for socket 3

**Comment by Robosturm** [comment]
Please for the love of god don't use or test.
Multiplayer games on the latest build.
Those are 90000% doomed to work.

**Comment by wyykak** [comment]
Understood. Sorry for the inconvenience.

**Comment by Robosturm** [comment]
It's just that i'm currently working on multiplayer things like observer and the change to the new map method,
which are currently not final tested in all scenarios.
So i expect it to crash in some cases.
