### ISSUE TITLE
Movement Planer

### ISSUE THREAD

**Issue by Robosturm** [Robosturm/Commander_Wars#802]
Movement Planer
A tool allowing you to plan actions and see how the results look like.
Please leave suggestions on what you would like to see in this ingame tool

**Comment by lonewolf19991** [comment]
Movement of units beyond the next turn, say 2 to 3 turns from when you are planning.
Movement of enemy units so they can be planned ahead as well.
Integration with the damage calculator, so that you can plan out chances of success of attacks.
