### ISSUE TITLE
(22b) rivers don't connect to lake corners

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#805]
![image](https://user-images.githubusercontent.com/53922323/154779162-f94cc4b4-389d-4b77-83d0-35e18aab94cb.png)

**Comment by Robosturm** [comment]
Currently no sprites for that case exists.

**Comment by Robosturm** [comment]
@HammerGuy  that's also for you :)

**Comment by Robosturm** [comment]
Backoog clean up
Closed issue cause no one is working on it and didn't work on it for a long time.
If this changes a new issue should be created.

**Comment by KBraid** [comment]
with the ability to set the overlay layer now, it's less necessary as the overlay can just be configured to account for the river by layering the right combination
