### ISSUE TITLE
(22b) rivers, bridges, and non HQ proporties don't account for the terrain below them when weather is clear

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#806]
regardless of the terrain type they are placed on their backgrounds are of the planes version in the battle animation when the weather is clear.

**Comment by Robosturm** [comment]
This is fully intentional since the terrain is still a normal river etc.
And showing it as a desert river leads to the impression it behaves differently which it doesn't.....

**Comment by KBraid** [comment]
it feels like something's not working correctly when playing on a biome map and certain background elements aren't matching up with the rest of the map. Also for the tiles this applies to, any waste variants would go unseen as waste terrain has no weather equivalent.

**Comment by KBraid** [comment]
the weather overlay effects are already used to convey the currently active weather
