### ISSUE TITLE
More CO functions that affect enemy players?

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#809]
This is pretty much an expansion of #736
I understand capture rates won't be implemented, but when I said "and so on" in the previous thread, I meant other things I didn't specifically name like luck and misfortune. If possible, will those be added as well?

**Comment by Robosturm** [comment]
Propably not coming anywhere soon

**Comment by Robosturm** [comment]
Note main reason it's low on the todo list is that functions like this have nearly no usage but slow down the game/ai significantly
