### ISSUE TITLE
Rocks, Desert Mountian Variant, Don't Allow Mech Movement Over Them.

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#81]
As title describes, Mech units are currently unable to traverse over the Rock terrain type. Noticed within the wiki while inspecting the terrain types that Mech was shown not to have a value for movement under Rock terrain. Tested within Map Editor and they indeed couldn't move over them.

**Comment by Robosturm** [comment]
Whoops fixed. Thx for the report.
