### ISSUE TITLE
Map Editor Bugs

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#817]
1. bridges 1 & 2 don't have terrain edit pictures
2. tall mountains placed below buildings are placed under the building layer, not sure if this a bug or feature
3. tops of the AW1 imported trees look like the top of the left one is cut off
4. beach+N+W+land+E+S seawater is transparent when placed against non sea terrain 
5. most terrain features have slight issues with building shadows mostly noticable on roads and bridge
![mountain error](https://user-images.githubusercontent.com/75344715/155737440-880e7d99-fb7b-43e7-bfbc-429033b76153.png)
![shadow error](https://user-images.githubusercontent.com/75344715/155737802-4083ccd5-5da3-47da-8e69-c97fffc02ba7.png)
s

**Comment by Robosturm** [comment]
1. already fixed
2. is a bug
3. The sprite is rendered correctly
4. This is technically impossible and i can't confirm it.
5. Bridges don't have a shadow sprite. Roads only use the wrong shadow on custom selection

And please make an issue for each bug.
