### ISSUE TITLE
21.5 ai will refuse to push for turns on end even when they have an advantage

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#820]
for whatever reason the ai seems to decide certain units are just too terrifying and flee from them, even if it's a single 1hp light tank in the way of their Neotank armada.

**Comment by Robosturm** [comment]
I need a screenshot for situations to see what you mean....

**Comment by KBraid** [comment]
i found pitting the ai against itself was an easy way to observe this behaviour in action

**Comment by Robosturm** [comment]
I didn't see any particular scenarios....

**Comment by Robosturm** [comment]
This is a situation were it's questionable if pushing into the blue side due to the factory and questionable from the blue side to push into the red side.
However i tweaked the ai to be a bit more aggressiv in certain scenarios and more passive in other ones.
