### ISSUE TITLE
UI rescaling

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#825]
Could a UI scale bar or options be added into the game? 
Mostly beacuse I've noticed that the zoom levels are tied in a way to the UI scale; since in v1.19 you could've zoomed out way farther, but also the UI there was smaller

**Comment by Robosturm** [comment]
Not sure of which ui elements you're talking.
But most elements won't support ui-scaling since they are fit to screen size.

So please mention the ui elements you would like to have that option.
Ideal with screenshots

**Comment by Jocrr** [comment]
Well here's Deer Harbour on max zoom-out in v1.21 (AW2 GFX) and in v1.19 (AWDOR GFX) respectively. Notice how the UI (like the tile selection, file options, etc.) looks smaller in v1.19 than it does in v1.21? Also you can see the entire map in v1.19 on max zoom-out, while you cannot in v1.21. So I thought those things may be connected in a way. These screenshots are taken on the same device.

![screenshot0_2](https://user-images.githubusercontent.com/93048095/156206665-9b73f1e6-b056-4d43-a85b-8f4c0f673eef.png)
<img width="960" alt="screenshot0" src="https://user-images.githubusercontent.com/93048095/156206670-a81bc73a-9c7c-4be6-aff7-8b7e53cfbcfe.png">

**Comment by Robosturm** [comment]
The default tilesize changed from 24 to 32.
So no there's no ui-scaling involved here

**Comment by Jocrr** [comment]
Oh, didn't know that. But could more zoom-out levels be implemented? Large maps could work better, since you can control units from all over the map without scrolling. And just viewing a big map is easier. So if the UI can't be rescaled, can more zoom-out levels at least supplement that?

**Comment by Robosturm** [comment]
Reduced the min zoom level from 1 to 1/4
