### ISSUE TITLE
CO zone lost on Load/Unload

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#83]
When loading a CO unit into an APC/Lander/Transportplane, the CO unit will not possess a co zone marker around them. Unclear whether this is purely visual or if units no long gain any benefits from the CO's zone powers.

![CO zone](https://user-images.githubusercontent.com/58909501/71154046-e6245180-21f7-11ea-8e60-574d300cecd0.png)

![Co nozone](https://user-images.githubusercontent.com/58909501/71154063-ef152300-21f7-11ea-9aec-f07cbe1cc495.png)

**Comment by Robosturm** [comment]
It's only visual bug... 
The CO-Zone marker isn't reattached to the map.
Fixed it and thx for the report.
