### ISSUE TITLE
Cannot allocate memory if compiled with glibc 2.34 or newer

### ISSUE THREAD

**Issue by Lukas1818** [Robosturm/Commander_Wars#835]
**Describe the bug**
game does not start:
```
$ LANG="en_US" ./Commander_Wars 

(process:33122): Gtk-WARNING **: 20:08:42.036: Locale not supported by C library.
	Using the fallback 'C' locale.
Commander_Wars: sigaltstack: Cannot allocate memory
```
**To Reproduce**
1. build game
2. execute game

**Expected behavior**
start without error

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: [Release Beta_21_4](https://github.com/Robosturm/Commander_Wars/releases/latest) with `sed -i 's/SIGSTKSZ/_SC_SIGSTKSZ/g' "coreengine/linux/crashreporter_os.cpp"` applied (replace `SIGSTKSZ` with `_SC_SIGSTKSZ`)

**Additional context**
The start does create some empty folder and does crash very fast (<0,5s).
Their is enough space (79gb) and ram (>10gb) available.

**Comment by Lukas1818** [comment]
This issue does not happen if I replace `coreengine/linux/` with `coreengine/android/`.
So replacing 'SIGSTKSZ` with `_SC_SIGSTKSZ`  seems not be an option to fix https://github.com/Robosturm/Commander_Wars/issues/832.

**Comment by Robosturm** [comment]
I'm probably disabling the crash-reporting.
Since the code i use is pretty out-dated and i had to strip away, a lot of content....
So it's currently missing a readable stack-trace anyway.....

**Comment by Robosturm** [comment]
Stack-Tracing was removed for Linux for now
