### ISSUE TITLE
Co death rule bug

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#838]
when CO unit deaths hit death limit game doesn't end

note: unit started game spawned as CO

[Down Periscope co death bug.zip](https://github.com/Robosturm/Commander_Wars/files/8178879/Down.Periscope.co.death.bug.zip)

**Comment by Robosturm** [comment]
In Beta 21.5 all victory rules are possibly bugged due to a wrong refactoring after the map change
