### ISSUE TITLE
21.5 ai won't build mechs to counter armor if they can't afford their own armor

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#841]
if the ai can't afford to make tanks of their own or any other unit that can stand up to tanks they will choose to spam infantry rather than make mechs to fight any tanks on the field

**Comment by Robosturm** [comment]
AI won't be that smart it's smarter with the next release.
But an AI will always be out-smarted by a player.

**Comment by Robosturm** [comment]
Also #822  is meant to dealt with suboptimal parameters for the ai.
