### ISSUE TITLE
editing wall tile has no joinless wall

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#844]
there is no "wall" option when editing walls, only "wall+"

**Comment by Robosturm** [comment]
Walls appear correctly for me....
Current source code:
![grafik](https://user-images.githubusercontent.com/48879701/156816742-b3a6ee1d-cda3-469e-b194-5e5c859a2730.png)

**Comment by KBraid** [comment]
this is the one that is missing
![image](https://user-images.githubusercontent.com/53922323/156816948-ded650a2-3795-4b94-98a1-d463e311aab6.png)

**Comment by Robosturm** [comment]
Ahhh now i see.
