### ISSUE TITLE
Can't use harbour

### ISSUE THREAD

**Issue by QuestionMark210** [Robosturm/Commander_Wars#846]
For some reason when i'm clicking on harbour it doesn't show me a unit list. Instead, i get a regular menu (Next player, options and e.t.c).

**Comment by Jocrr** [comment]
How many funds do you have? If you can't afford the cheapest unit in the harbour, then the build menu doesn't show up.

**Comment by Robosturm** [comment]
As Joccr said if you can't use a building due to a lack of funds the normal menu pops up.
Please confirm if you had enough funds for building a sea unit.

**Comment by QuestionMark210** [comment]
Yeah, he's right. Thanks for info!
