### ISSUE TITLE
Davis rebalance

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#848]
currently Davis' rules operate on AND where both luck and misfortune are applied, as some have described him "making him an even more extreme Flak"
my original idea was for it to work on OR where the tipping of balance becomes exaggerated for him. the team he is on having more units than the enemy makes him more powerful while having less makes him weaker.
it was also brought up that on FFA matches he accounts of all teams against him together making his misfortune crippling. if it's possible to make him count his power for teams and not individual players as well as tie his misfortune to only the enemy team with the most units i think it would help reduce the crippling of a FFA match with him.

**Comment by Robosturm** [comment]
Changed to or and to unit surplus instead of total unit count
