### ISSUE TITLE
Audio causes fps drops

### ISSUE THREAD

**Issue by ATNoName** [Robosturm/Commander_Wars#850]
So I have been experiencing fps drop for my pc. Eventually, I found out that the audio is taking a lot of my CPU memory which could be affecting the fps. Heres the memory for reference.

![image](https://user-images.githubusercontent.com/65098676/156865973-1cfca5ed-81d0-414b-9c30-dc3efe57afaf.png)

PC specs:
11th Gen Intel(R) Core(TM) i7-1165G7 (integrated graphics)
16 GB RAM
Windows 10

**Comment by Robosturm** [comment]
Sound caching gets replaced qith the next release
