### ISSUE TITLE
Suggestion: Customizable Damage Table

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#851]
With the inclusion of the damage table resource, it got me thinking. What if each value could be changed in the rules? Similar to build lists or action lists, the players can customize match ups. Giving them a ton of options when it comes to custom games. The game already boasters a large variety of settings that provides the player choice in fine tuning their experience. I think something like a customizable Damage Table would a tool that compliments this goal.

**Comment by Robosturm** [comment]
This is something not possible due to technical reasons the game doesn't know a damage table how the base damage gets created making it impossible for the c++ code to change it without breaking one of the major design rules of the game for modding
