### ISSUE TITLE
new team colours not saved on maps correctly

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#855]
when a map is saved using the new team colours, the map loads them incorrectly
![image](https://user-images.githubusercontent.com/53922323/156927766-fc6467d5-1d1d-47df-9f36-bbedd73151d9.png)

if selected in the drop down however they are fine
![image](https://user-images.githubusercontent.com/53922323/156927987-5c7b6e3b-2197-413c-bd46-8faffbdb5820.png)

**Comment by Robosturm** [comment]
Actually the opposite is wrong....
When selecting it loads the wrong table
