### ISSUE TITLE
Commas break dialog in the Script Editor

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#86]
Strangely, while attempting to write dialog for a script, all entries with a "," where corrupted on save.

While compiling dialogs, if you use a comma within the dialog and save it, when the game loads it up again all information included after the comma will be reset, including the CO speaking, team color, and background imagine if you're using one.

**Comment by Robosturm** [comment]
whoops! Yeah the reader uses , to seperate arguments in order to load them for the dialog.
Replaced it with @ as a internal seperator. :)
