### ISSUE TITLE
Potential bug with 'Cosmetic' mods

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#863]
I say Potential because I haven't been able to test this on Beta 22 yet, but I did see it in Beta 21.5.

When trying to join a multiplayer session with mods active that had _cosmetic=true_, I still got a warning about having mods on that weren't enabled by the server and thus couldn't join.

I currently cannot test this in Beta 22 so I don't know if this is already fixed, but I'm making this issue regardless in case it's not.

**Comment by Robosturm** [comment]
Cosmetic Mods with js-scripts should get denied cause the game can't detect if those are purely cosmetic ones.

* Removed .xml and .txt from filter list

**Comment by FranticFairy** [comment]
The cosmetic mods I wanted to use didn't include .js files, only images and res.xml files. Good things those now work

**Comment by Robosturm** [comment]
Yeah the xml and txt-files are falsely on the hash-list.
