### ISSUE TITLE
Canceling Flare action is a bit ambiguous

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#87]
Description;
When attempting to cancel a flare's Flare action with right click, if the cursor is not on the unit itself, then only the drawn movement is canceled while the targeting field remains present. Selecting one of the squares will have your unit commit the move and Flare action. You can still cancel if you so wish by right-clicking the unit, but this caused some initial confusion on how to cancel the action.

Expected;
Ideally, simply right clicking anywhere on the screen should cancel the action.

Additional Notes;
There are actually quite a few actions in the game that require you to either right click in the field or on the unit it self to cancel.

iOS : Windows 10
Version : Beta 8 release

**Comment by Robosturm** [comment]
Fixed it. Canceling should now work a lot smoother. :)
