### ISSUE TITLE
Map Scrolling & Pause Menu are unresponsive during AI's turn

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#872]
**Describe the bug**
During the AI's turn, if you try zooming out or look around the map, it is super laggy. Trying to bring up the menu during their turn is also somewhat buggy. (Not even playing that big of a map, it's a rather small map with 4 players). Even had some occasions where the game would outright "freeze" at times. 

**To Reproduce**
Just play a game with a couple of AI units set to normal, and then try moving around during their turn (or click anything). It's Significantly more prevalent when there are more units on the map.

**Expected behavior**
You should be allowed to look through the map or check some stats things during the AI's pretty smoothly. I'm playing on a Small map with FoW against 3 other opponents, it should not have much lag as it does. (And afaik, it doesn't lag this much vs real players)

I understand that there is a threshold to how many units can be on screen at once before it will inevitably start lagging, but I'm playing a small 20x20 4p map w/FoW, there's no way there are enough units even active atm to warrant this, and it's sorta making the game last longer than it should... (At least the other areas of "lag")

**Comment by Robosturm** [comment]
This is something which will probably never happen.

At least not for the menu while the ai is doing stuff.
The request was made to add this menu, but i made very clear that this won't work well during ai-turns.

**Comment by Seimix** [comment]
Yes, I remember the problem in regards to adding the menu option, however, I'm now realizing that the problem seems to be more with how Slow the AI takes to make a decision...

I've had turns where the AI would take 10 minutes to take their turn on a map that was actually smaller than the maps you could make in AWDS(iirc); with no more than 12 factories total across 4 Players. Granted, it WAS a 4p map but how long they took to make their moves was still ridiculous...

The Normal AI has certainly improved immensely since the game's release and I understand it isn't easy to make the AI make decisions faster, but the way it currently is just makes playing matches vs the Normal AI with any more than at least 2 players just far too slow to be worth playing, unless you're okay with your games lasting for twice as long than usual...

**Comment by Seimix** [comment]
I was playing on version 22.1, I don't remember the lag being that bad at first but at around turn 10-14 on a 4p map it started getting really bad.

**Comment by Robosturm** [comment]
The ai got some speed improvements but overall this is a on going task
