### ISSUE TITLE
ACCESS_VIOLATION Exception

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#873]
I'm still unsure as to the exact causes of this, but I can sorta recreate it.

It happens consistently on the attached map.

[Stormiest Glen.zip](https://github.com/Robosturm/Commander_Wars/files/8207868/Stormiest.Glen.zip)

**Comment by Robosturm** [comment]
Argh! The ai has a bug on multi-island maps which crashes in case there are more islands than units.....
