### ISSUE TITLE
Shop background could use an update.

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#879]
I think the shop background should be switched to the new main menu background. Just feels a bit jarring when the background switches to the old one when visiting the shop. Just to have a smoother transition between the two menus.

**Comment by Everglass** [comment]
that or a new background that complements the shop interface better. Old main menu background is a bit too noisy for the shop menu. Only worked before because when coming from the main menu, the background didn't change suddenly.

**Comment by KBraid** [comment]
i think i had before set it to the tent bg from dor but it wasn't kept

**Comment by Robosturm** [comment]
@KBraid if it was set to that it may got lost during a merge by accident, cause i can't remember or thing of a reason why i should have kept the current one

**Comment by KBraid** [comment]
okay i'll replace it again!
