### ISSUE TITLE
Game Updater

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#881]
Currently when a new game version is released, the game needs to be re-downloaded each time. With refactoring and a dedicated branch to the resources of the game, the game could have an updater that downloads the latest changes of the game, based on the content of that branch, similarly this dedicated branch could be used to rollback to a previous version of the game, simply by rolling back to previous versions of that branch.

Now, I know this is a very time consuming task, so I am just adding this as a request for the future a nice to have thing, and something I could contribute to later on.

**Comment by Robosturm** [comment]
It's at least nothing i will do
