### ISSUE TITLE
HUD appears weird with no weather forecast active

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#882]
The HUD on the right side is displayed over the CO portraits in a multiplayer match. For some reason, it's fine in offline matches.
Tested on 22.3 in a match with a friend, no mods used.

![image](https://user-images.githubusercontent.com/50599768/157773841-77b068fe-7a3b-420f-84ff-e88c19e8010f.png)

**Comment by Robosturm** [comment]
It's
