### ISSUE TITLE
(Co Wars 22.3) Error when hosting multiplayer: Host has a different mod (Even when all mods are deactivated)

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#883]
The game was compiled by downloading the source code from this page:
https://github.com/Robosturm/Commander_Wars/releases

Source code version is 22.3; then followed the steps in this guide right here:

https://www.commanderwars.com/mediawiki/Compiling_on_Linux/

There were no compilation errors reported on this step.

Next the game is run and a multiplayer match hosted, after which, the user trying to connect receives this error:
![errocows](https://user-images.githubusercontent.com/96459683/157795995-c895c2a0-1b60-48cb-bbc3-432d349c2e4a.png)

Notice that this error occurs even if all mods are disabled on both ends.

Let me know what's needed to further diagnose this issue.

**Comment by Robosturm** [comment]
Reading is a skill only achieved by masters.
The game says or game version.
--> So the game detects different files in your base version.

The check was disabled due to a bug in previous versions.
The game creates a hash offer all js and csv-files in the resources-folder the internal resources folder and the active mods folders.
And throw this message if host and local version don't match

**Comment by lonewolf19991** [comment]
All players who I tested this against also had downloaded 22.3, this information was double checked too. I tested it with 3 different people before submitting this.

**Comment by Robosturm** [comment]
I have mentioned that maybe the QDirIterator isn't using a fixed order for loading files on different os-systems/compilations.

My idea is to change the hash creation to a slower but hopefully deterministic version.
Than give you the exe/code for testing purposes and go from there.

**Comment by lonewolf19991** [comment]
Would this sorting flag help in any way with the determinism?
https://doc.qt.io/qt-6/qdir.html#SortFlag-enum

**Comment by Robosturm** [comment]
I'm using the name one that was my first change.
