### ISSUE TITLE
Neotank Weaker than Heavy Tank; Heavy Hovercraft not buffed

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#888]
Same issue as #877, except it applies to Neotanks.

**Comment by Jocrr** [comment]
Heavy Hovercraft not buffed.

**Comment by Robosturm** [comment]
Nope Neotanks get +1 movement
Heavy Hovercrafts get sea movement

**Comment by Jocrr** [comment]
Then the Neotank description is wrong

**Comment by Jocrr** [comment]
Ah, never mind, it says "superior to standard tank"; my bad
