### ISSUE TITLE
Submarines can still be attack by ship directed attacks while dived

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#89]
Normally you'd expect that only cruisers and other submarines can target a submerged submarine. However, they retain their vulnerabilities to all units.

**Comment by Robosturm** [comment]
Yeah that's how it works in Commander Wars for now. 
Units of the same type can attack stealthed units.

**Comment by Robosturm** [comment]
You can change that in by modding the ACTION_FIRE Script but i didn't want to add thousands of exeptions by myself.

**Comment by Robosturm** [comment]
Is moddable for the next release
