### ISSUE TITLE
Capture & Dialogue Animations Don't Save

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#890]
**Describe the bug**
Okay, so this is a weird bug. Basically if you go into your settings and change your capture and dialogue animations then go into a game or replay, the other animation settings will be the same except for those two. The same thing will happen if you set them and enable/disable a mod.

**To Reproduce**
1. Go to Settings and adjust your Capture & Dialogue animation speeds
2. Open a replay and check the settings or Enable / Disable a Mod
3. The rest of the animations should match with your general settings, except those two.

**Expected behavior**
Replays should have separately saved settings than your general settings, but this is still strange.

**Comment by Robosturm** [comment]
If  go into the settings in the option menu change the speed and than change the mod everything is as expected

**Comment by Seimix** [comment]
Set the speeds to 70, do the replay thing, then go back...

**Comment by Robosturm** [comment]
Yeah the replay stores the animation speed upon entering and restores those values after the replay ends.
However it fetched the wrong values for, these two
