### ISSUE TITLE
Rename 'Cannonboat' to 'Gunboat'

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#892]
A very, very minor tweak.

English players will be more familiar with the name Gunboat. Plus it's a little weird to name a missile-carrying boat a cannonboat (Even if gunboat is not entirely accurate either, I'm against renaming vanilla units that non-CoW players would be more familiar with).

On a similar note, Rocketthrowers could be renamed to either Rocket Launchers or just Rockets

**Comment by Robosturm** [comment]
The official name in the EU-ROM is Missile boat.
So that's the one renaming i would accept.

As for the Rocket Thrower -> Rockets is the official cartridge name
