### ISSUE TITLE
Random crashes during gameplay --> Mostlikely related to stopping/deleting qt's sound-objects --> Qt Bug

### ISSUE THREAD

**Issue by RyushoYosei** [Robosturm/Commander_Wars#898]
**Describe the bug**

**To Reproduce**
I tried a  16 player 200x200 map for the sake of trying it, and crashed with this once it loaded the map to start.

Commander Wars vVersion: 0.22.1 Builddate: Mar  7 2022 06:35:18
13 Mar 2022 @ 08:09:24

EXCEPTION_ACCESS_VIOLATION

DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+e+s' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+s+land+e+s' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+s+land+e+s' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: getFlowData() starting at X=66 Y=182
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+e+nw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+e+nw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+e' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+e' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+e+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+e+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+land+e+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+s+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+s+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+s+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+s+land+se+sw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+nw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+e+land+nw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+land+nw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+s+land+nw' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+n' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: can't find resource: 'river+n+e+land+n' in ':/resources//images/terrain/res.xml'
DEBUG: 13.03.2022 08:08:58: getFlowData() starting at X=127 Y=182
DEBUG: 13.03.2022 08:08:58: getFlowData() starting at X=99 Y=194
DEBUG: 13.03.2022 08:08:58: synchronizing animations
DEBUG: 13.03.2022 08:09:23: creating weather Sprites
DEBUG: 13.03.2022 08:09:23: LoadingScreen::hide
DEBUG: 13.03.2022 08:09:23: Leaving Map Selection Menue
DEBUG: 13.03.2022 08:09:23: AudioThread::SlotClearPlayList() start clearing
DEBUG: 13.03.2022 08:09:23: AudioThread::SlotClearPlayList() playlist cleared
DEBUG: 13.03.2022 08:09:23: Playback state changed to 0 for player
DEBUG: 13.03.2022 08:09:23: Media status changed for player to 0
DEBUG: 13.03.2022 08:09:23: Entering In Game Menue
DEBUG: 13.03.2022 08:09:23: Creating game menu singleton
DEBUG: 13.03.2022 08:09:23: Minimap::updateMinimap
DEBUG: 13.03.2022 08:09:24: Minimap::updateMinimap
DEBUG: 13.03.2022 08:09:24: InGameMenue::initSlidingActor() x 100 y 165 width 1340 height 706
DEBUG: 13.03.2022 08:09:24: InGameMenue::updateSlidingActorSize() width 12800 height 12800
DEBUG: 13.03.2022 08:09:24: Playing sound: switchfield.wav using cache sound 0
DEBUG: 13.03.2022 08:09:24: GameMenue::startGame
DEBUG: 13.03.2022 08:09:24: GameAnimationFactory -> clearAllAnimations()
DEBUG: 13.03.2022 08:09:24: GameMap::startGame()
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 0 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 1 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 2 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 3 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 4 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 5 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 6 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 7 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 8 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 9 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 10 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 11 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 12 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 13 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 14 uses ai 2
DEBUG: 13.03.2022 08:09:24: Player::loadVisionFields()
DEBUG: 13.03.2022 08:09:24: Player 15 uses ai 2
DEBUG: 13.03.2022 08:09:24: GameMenue::updatePlayerinfo
DEBUG: 13.03.2022 08:09:24: Triggering action next player in order to start the game.
DEBUG: 13.03.2022 08:09:24: GameMenue::performAction ACTION_NEXT_PLAYER at X: -1 at Y: -1
DEBUG: 13.03.2022 08:09:24: GameMenue::doTrapping
DEBUG: 13.03.2022 08:09:24: Seeding with 3158475303
DEBUG: 13.03.2022 08:09:24: centerMapOnAction()
DEBUG: 13.03.2022 08:09:24: GameMap::nextTurn
DEBUG: 13.03.2022 08:09:24: Stopping sound on playing changed.
DEBUG: 13.03.2022 08:09:24: Doing start of turn for neutrals
DEBUG: 13.03.2022 08:09:24: New Day removing current weather. Currently predicting for 1
DEBUG: 13.03.2022 08:09:24: Adding weather for weather prediction.
DEBUG: 13.03.2022 08:09:24: Adding weather for weather prediction.
DEBUG: 13.03.2022 08:09:24: Adding weather for weather prediction.
DEBUG: 13.03.2022 08:09:24: Creating fog vision. Pausing Rendering

**Comment by Robosturm** [comment]
Crash isn't related to the map loading.
Currently there's a bug which causes a crash with unknown reason.
And in my test this worked and there's no reason why a large map should work different when a small map.
Besides the time and memory usage required.

**Comment by Robosturm** [comment]
This is related to a bug in qt with deleting sounds.
I have a workaround which reduces the chance for this crash but ultimatly this needs to be resolved by qt.
