### ISSUE TITLE
The AI no longer uses Ooziums

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#90]
**Describe the bug**
As of the latest version (0.8.0), the AI doesn't move Ooziums at all. I guess there's not much else to say here? I'm pretty sure the AI _did_ move them in the previous versions.

**Expected behavior**
Well... the AI should move them, obviously.

**Additional context**
At first, I thought it was caused by a mod since I was working on a custom unit similar to Ooziums, but I had a friend verify the bug.

**Comment by Robosturm** [comment]
Found and fixed. The AI tries to use them but the targeting system had a bug for finishing on enemy unit fields.
