### ISSUE TITLE
Game crashes on AI's turn when continuing from a save

### ISSUE THREAD

**Issue by XnKradst** [Robosturm/Commander_Wars#900]
1. Play a normal game with the Normal AI (haven't tested on Very Easy or the other AIs)
2. Save the game and exit
3. Reload the saved game
4. End your turn

If done correctly, the game should crash on the AI's turn.

I don't know if this is related to the issue posted just before this one (#898 ), but I guess it could be?
[20220313-231437 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/8241502/20220313-231437.Commander.Wars.Crash.log)

No mods enabled, test on version 22.3 (the original .exe, not the one you sent me to test multiplayer with).

**Comment by Jocrr** [comment]
Actually, I'm pretty sure I did the same thing when I got that access violation error.

**Comment by Robosturm** [comment]
This is related to a missing reinitializing is not connected to #898

**Comment by AdityaMH** [comment]
Also got crashed when start playing tutorial 3 and AI turn.
