### ISSUE TITLE
Game crash upon loading map not present and client in a folder of the host not present on the client

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#903]
possible memory leak?

[console.log](https://github.com/Robosturm/Commander_Wars/files/8248636/console.log)

[console (1).log](https://github.com/Robosturm/Commander_Wars/files/8248638/console.1.log)

3rd try on different map allowed player to join, the crash was probably due to player not having map files that the host was using...
should this be expected or does only the host need the map resource to start the game?

**Comment by Robosturm** [comment]
The game tries to save the map in the same path as the host when downloading it.
However the creation of the path has a bug and thus creating the map file fails.
This isn't checked and the game tries to read an not existing map which leads to a crash.

Workaround for now:
Create the host folder structure beforehand or have the same maps installed.
