### ISSUE TITLE
Text dialog too big on android

### ISSUE THREAD

**Issue by AdityaMH** [Robosturm/Commander_Wars#904]
**Is your feature request related to a problem? Please describe.**
This pretty annoying if text dialog size almost half of screen.

**Describe the solution you'd like**
Allow android user to choose screen resolution would be help.

**Comment by Robosturm** [comment]
There's currently no real way to find out which screen-resolutions are supported by an device.
+ Android might not be able to support a solution bigger than the actual screen.
And the time required to invest is currently not worth it.
