### ISSUE TITLE
Ruins Tile Doesn't have a Minimap sprite

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#906]
**Describe the bug**
The title pretty much says it all. If you make a map that utilizes ruin tiles, they don't have a sprite assigned to them in the minimap, they just look like normal plains. 

**To Reproduce**
1. Make a map with some ruin tiles on it
2. Save the map, look at the minimap, there's no sprite on it that signifies there's a ruin tile there.

**Expected behavior**
Ruins are a different enough tile from the rest of the tiles to warrant a color distinction from other tiles on the minimap.

**Screenshots**
Full Map: https://i.imgur.com/icq3n95.png
Minimap: https://i.imgur.com/ga60qJE.png

**Additional context**
Really minor issue, should easily be fixable.

**Comment by KBraid** [comment]
i've added the ruins tiles to the minimap as well as updated a few other tiles to make them more readable
