### ISSUE TITLE
Campaign crash every AI turn

### ISSUE THREAD

**Issue by AdityaMH** [Robosturm/Commander_Wars#907]
**Describe the bug**
Every campaign even tutorial, when going to AI turn instantly going crash on Android

**To Reproduce**
1. Play campaign games on Android
2. End Turn
3. Instantly crash

**Desktop (please complete the following information):**
 - OS: Android 10
 - Version: 0.22.3

I'm using arm64

**Comment by Robosturm** [comment]
Not reproducable in the current source code state so i take it as fixed for now.

**Comment by AdityaMH** [comment]
Where i can find source code state? Also instantly crash can't do anything

**Comment by Robosturm** [comment]
It's nothing you can download.
I just tested if the bug is present in with the current source code on my phone

**Comment by AdityaMH** [comment]
https://user-images.githubusercontent.com/33791472/159094228-2b8c4a66-4b87-4dd6-87d0-30facc48cbd3.mp4

**Comment by AdityaMH** [comment]
Still keep freeze to me.
in 22_5_v2
