### ISSUE TITLE
[Vulnerability] insecure RPATH

### ISSUE THREAD

**Issue by Lukas1818** [Robosturm/Commander_Wars#923]
**Describe the bug**
Insecure RPATH '/../' in file ('usr/bin/commander-wars').

**To Reproduce**
1. build aur package
2. run namcap

**Expected behavior**
only secure RPATHs

**Screenshots**
```bash
$ namcap commander-wars-0.22.5.2-2-x86_64.pkg.tar.xz 
commander-wars E: Insecure RPATH '/../' in file ('usr/bin/commander-wars')
commander-wars W: Dependency qt6-base included but already satisfied
commander-wars W: Dependency included and not needed ('qt6-wayland')
```

**Desktop (please complete the following information):**
 - OS: Manjoro
 - Version 0.22.5.v2, 0.22.3 (previous not tested)

**Additional context**
The main binary include a insecure RPATH. I am not sure it this is needed for some standalone binary, but their should be an option to disable this.

from the [arch wiki](https://wiki.archlinux.org/title/Namcap):
> * insecure-rpath (error) An RPATH (for an executable) is outside /usr/lib. An RPATH to an insecure location is a potential security issue. See [FS#14049](https://bugs.archlinux.org/task/14049) for discussion.

**Comment by Robosturm** [comment]
The game uses no relativ file access.
The only time you can browse to a different folder is in the file and folder  dialogues.
The only occurance of them is for the cmake-install instructions which are completly configurable and don't end up in the binary.
The only ways this can happen is due to your cmake/compile setup or if it's part of qt.
In both cases it's nothing i can or will change.

**Comment by Lukas1818** [comment]
Just for clarification `RPATH` is not some file or folder, witch is open by the game.
It is a hint for the linker to check the given folder, additional the common folders, for dynamic linked libraries.

This issue is caused by this lines:
https://github.com/Robosturm/Commander_Wars/blob/375dcadff4a184b383425bb1fdf1ce49362f88fe/CMakeLists.txt#L162-L163

Removing this lines fix the problem. AUR package is already fixed. But I do not known if this will break the standalone builds.

**Comment by Robosturm** [comment]
I dunno but the packages use the linux pathing convention and making a merge request should trigger a linux pipeline build.
So it should be easy to see if it works or not

**Comment by Lukas1818** [comment]
> I dunno but the packages use the linux pathing convention and making a merge request should trigger a linux pipeline build. So it should be easy to see if it works or not

I do not think this is a good idea. `RPATH` is used at runtime, so the game could still build without issue and fail at executing.

**Comment by Robosturm** [comment]
Those lines are there cause someone had issues with dll finding on his system with a self-build version.
However the linux distributions are untested anyway, cause i lack the systems to do so.
So i removed the lines and if it's not working i can re-add them
