### ISSUE TITLE
clarifty if saving or loading in save/load map menu

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#929]
sometimes it's easy to forget if you had clicked on the save or load button so it would be nice if there was a visual reminder on which menu you are in.
![image](https://user-images.githubusercontent.com/53922323/159776226-b253d2cf-0a7d-4210-bbf5-28091c7a7013.png)

**Comment by Jocrr** [comment]
Good

**Comment by Robosturm** [comment]
I would change it so that the ok button instead is named save or load.
