### ISSUE TITLE
set default rule configurations

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#932]
this feature request is more a prelude to a bigger request i'll get into further down.

essentially you could set saved rules to apply automatically when starting a match, overwriting the default used by CoW unless set back. 

on top of this have the option to choose your default rules on profile creation as a way to reduce new player confusion, letting them come into the game in the way they prefer without needing a frontloaded understanding of the rule system. Maybe also having it so that default rule sets on profile creation of the various advance wars titles would also enable the mods that convert the game behavior to match the set rules.

**Comment by Robosturm** [comment]
You can already set a default rule when saving a new rule or in the option menu.

The later one is something i don't want to add cause i feel it adds more complexity to the initial start than helping...

**Comment by KBraid** [comment]
ah i wasn't aware it was already a feature.

and i'll see if i can come up with other ideas that might help make the complexity of the settings less daunting

**Comment by Robosturm** [comment]
Ideas are always appreciated and you added a lot of improvement with your suggestions. :)

I'm closing the issue than if that's okay?
