### ISSUE TITLE
Game Crashes on Phone when loading a save

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#934]
**Describe the bug**
Title pretty much says it all. The game crashes on the opponent's turn when loading a saved game on android. 

**To Reproduce**
1. Start a game on mobile
2. Leave and reload the saved game
3. Take your turn, and it should crash.
 
**Additional context**
Random weather was on and so was the DS weather mod.
 
Downloaded v8a for newest release.

**Comment by Robosturm** [comment]
Problem is that the old apk was uploaded and no the new one.
Upload is ongoing
