### ISSUE TITLE
Custom Music doesn't work on Mobile

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#936]
**Describe the bug**
In the Mobile version of CoW, if you enable a custom mod that has new CO themes, they won't play.

**To Reproduce**
1. Enable a Custom CO mod or whatever on mobile
2. Play a game with said CO
3. Their theme won't be playing

**Desktop (please complete the following information):**
- Mobile v8a

**Comment by Robosturm** [comment]
This is an qt bug which i have currently no solution for.
The path resolution on my end is correct but qt doesn't like to play the music and returns with an error

**Comment by Robosturm** [comment]
@Seimix all i can do is upgrade to the newest qt version whenever it comes out.
Please report if it starts working again.
Since the issue is a bug in qt's android version, i can't do anything. Sadly.
I leave the issue open so people know about it.

**Comment by Robosturm** [comment]
@Seimix Can you test if it works with this build: https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_AndroidMusicTestBuild_DoNotUse1
I did some changing of the code which should prevent the bug in qt.

**Comment by Seimix** [comment]
Tested it, and the Music works for modded COs now. Thanks.
