### ISSUE TITLE
Make terrain overlays editable

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#939]
Currently you cannot choose a lake tile's borders via terrain edit (there's only one option), so I think you should be able to.

**Comment by Robosturm** [comment]
That's nothing which will change for now.
Reason beeing is that those borders are overlays and editing overlays and storing them would be a lot more complex and is currently not considered to be wworthy to be worked on

**Comment by FranticFairy** [comment]
> 

Is there a particular benefit to using overlays over regular terrain sprites other than keeping the amount of images down? In my terrain overhaul mods I almost always prefer just making separate tiles for every single orientation to avoid using overlays, and I want to know if there's any reason to avoid doing that other than that it means I have to make a lot of sprites.
