### ISSUE TITLE
A Damage Log for Seeing what unit took damage from what last turn

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#94]
This is a feature I wish had been included in Days of Ruin. Basically, it would just be a list of damage values you can look at during your turn to see what unit got damaged and by what last round. The need for this feature is for local multiplayer on one system and on fog of war maps; Where when you end your turn, you walk away and let the next player make his move. This causes some uncertainty of how your units are dying in the fog of war, whether it be by tanks or artillery. A damage log that you can look at that says for example "Infantry at x:16 y:8 took 8 damage from Player 2's Rocketthrower" and have the cursor highlight it's last location as you hover over the details would give the player more information on how the should proceed in the game.

**Comment by Robosturm** [comment]
First version for the next release:
![Gameplay56](https://user-images.githubusercontent.com/48879701/71580805-8b95ca00-2b02-11ea-99fd-1acbfc41a510.png)

Not sure if i add some sort of interaction to highlight the actual terrains in the future.
