### ISSUE TITLE
ai doesn't actively use Blackboats to capture

### ISSUE THREAD

**Issue by KBraid** [Robosturm/Commander_Wars#940]
if an ai has a blackboat and there are properties for it to capture it won't move it to capture them unless the properties are within one turn of range, the ai also won't build any blackboats for the purposes of capturing properties.
if there are any properties in the water that are not reachable by infantry with any means the ai should build at least one blackboat for the purposes of capping them.

**Comment by Robosturm** [comment]
I changed it so the ai will go more active towards capturing buildings if no units are loaded.
However building black boats is nothing that is going to worked on for now.

**Comment by Robosturm** [comment]
Capturing has been moved to a unit not able to transport units which solves this issue
