### ISSUE TITLE
Suggestion: Allied Compensation Income for a fallen Ally

### ISSUE THREAD

**Issue by Seimix** [Robosturm/Commander_Wars#942]
Basically, the mechanic idea is that when a team loses an ally, the income the others get from properties is increased by a certain amount. 
For example; Orange Star, Blue Moon, and Yellow Comet are on a team. Orange Star falls, so both the Blue Moon & Yellow comet each get 10% more funds from their properties. And after Blue Moon falls, just yellow comet gets 20% more funds from properties. 

There would be an option on the game settings menu that lets you set the percentage of income allies would get after one of their teammates gets defeated. So if you were to set it to 0.10 and you have a team of 5 armies...If 1 army falls, all the other armies will get 10% more funds from properties (so 100 more from buildings if the income value is set to 1000), if another army falls, then the other 3 armies will get 20% more funds from properties (so 1200 if the value is set to 1000) and so on. (So basically how the option would work is that; Everyone would get a flat 10% increase in income from properties per ally fallen. So it's not like 1000 more income funds would be split between 4 different armies.) Obviously, this would be set to 0% by default.

This could make team matches more interesting, since losing an ally wouldn't mean the game's over quite yet. It would also make 1v3s more challenging too for the same reason.

**Comment by Robosturm** [comment]
This something that can be achieved via modding but won't be added to the base game
