### ISSUE TITLE
Ignore unit collision as strange interaction with the trap mechanic in Fog of War

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#95]
If you have a unit that ignores collision and more then one movement; When it moves into fog of war pathing through a unit, if there is a unit in the fog of war tile you moved too, you'll become trapped on top of the unit you where try to move through and delete him. This is actually not too much of a problem for an Oozium unit that has more then one movement but it breaks and character you try to mode in designed around passing through units.

**Comment by Robosturm** [comment]
Hmmm i changed the movement points of an oozium. And i can't reproduce your bug.
My ooziums gets trapped in front of the unit and no unit gets deleted,,,

**Comment by Everglass** [comment]
To clarify, there are two units, one out side of fog of war and one unit in fog of war adjacent to the unit out side of fog of war. If you move a unit with ignore collision through the visible one and on to the fog of war square with the hidden unit, the one that was visible will be the one deleted.

**Comment by Robosturm** [comment]
That one i can explain xD
Okay fixed that behaviour for start....
