### ISSUE TITLE
wrong data path

### ISSUE THREAD

**Issue by Lukas1818** [Robosturm/Commander_Wars#952]
**Describe the bug**
Commander Wars does save its data to `/home/lukas/.local/share/Commander Warsdata` instead of `/home/lukas/.local/share/Commander Wars/data` if `DUSEAPPCONFIGPATH` is `ON`. (Same issue for the other paths)

I had thought the missing `/` was the issue and https://github.com/Robosturm/Commander_Wars/pull/927/commits/2ddd7a7b55d235f18058955ffbf0b264fbfa22f3 has fix the issue. But it does not issue does still exist.
After a some testing I think the following line has no influence at this patch.
https://github.com/Robosturm/Commander_Wars/blob/9160e165f9cdea27a6e9b02f6e8c4d4dea353307/coreengine/settings.cpp#L192
Even if I hard code another path there, `/home/lukas/.local/share/Commander Warsdata` will still be used.
But the fact that a path with prefix `/home/lukas/.local/share/` is used, let me assume that `DUSEAPPCONFIGPATH=ON` has influence at this path. 

**Desktop (please complete the following information):**
 - OS: manjaro 
 - Version 0.22.5.v2 with https://github.com/Robosturm/Commander_Wars/pull/927/commits/2ddd7a7b55d235f18058955ffbf0b264fbfa22f3 applied

**Additional context**
At version 0.22.3.1 the following patch has work fine:
```patch
diff --git a/coreengine/settings.cpp b/coreengine/settings.cpp
index ca98e1fe0..60216b482 100644
--- a/coreengine/settings.cpp
+++ b/coreengine/settings.cpp
@@ -17,7 +17,7 @@
 #include <QInputDevice>
 #include "3rd_party/oxygine-framework/oxygine-framework.h"
 
-const QString Settings::m_settingFile = "Commander_Wars.ini";
+const QString Settings::m_settingFile = QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation) + "/Commander_Wars.ini";
 float Settings::m_mouseSensitivity   = -0.75f;
 qint32 Settings::m_x                 = 0;
 qint32 Settings::m_y                 = 0;
@@ -178,6 +178,7 @@ Settings::Settings()
         defaultPath = QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation) + "/commander_wars/";
         defaultCoCount = 1;
     }
+    defaultPath = QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation);
     auto devices = QInputDevice::devices();
     bool hasTouch = false;
     for (const auto & device: qAsConst(devices))
```

**Comment by Robosturm** [comment]
My guess is the path is wrong in the ini file.
The game stores the user-path in the ini and only restores the default if it isn't found there

**Comment by Lukas1818** [comment]
> My guess is the path is wrong in the ini file.
Yes that was the issue thanks.
