### ISSUE TITLE
Artillares and hover artilleries does not make fire sounds

### ISSUE THREAD

**Issue by Dacatzgoescodin5267** [Robosturm/Commander_Wars#955]
For some reason, the artilleries or hover artilleries will not make a fire sound once they pull up and fire.

**To Reproduce**

1. Use any artilleries or hover artilleries.
2. Attack with either of two

**Comment by Robosturm** [comment]
Can anyone else confirm this?
I can't and my code says it's correct....
Might be an issue to faster animation settings, since sounds can't be replayed faster
