### ISSUE TITLE
More than 27 players on android only rounds down to 100 not 27

### ISSUE THREAD

**Issue by mirddes** [Robosturm/Commander_Wars#966]
And it displayed 65 colours but nothing past 27 built anything, and then the country selection was empty after I changed back to 27, I had to scroll far to the left to find the intended 27 (more would be cool though)

**Comment by Robosturm** [comment]
I'm sorry, but i don't understand what you do nor where you did.
Can you please make a step list ideally with some screenshots to clarify the issue.
Thx

**Comment by mirddes** [comment]
![Uploading Screenshot_20220421-201902.png…]()

**Comment by mirddes** [comment]
![Screenshot_20220421-202038](https://user-images.githubusercontent.com/13982888/164412395-856faffc-2cda-4b80-acc4-40e1ef90ca76.png)

**Comment by mirddes** [comment]
![Screenshot_20220421-201902](https://user-images.githubusercontent.com/13982888/164413553-947f63e0-1fb9-4334-a882-181084b0c8c5.png)
