### ISSUE TITLE
Android wrong resolution, no rotation

### ISSUE THREAD

**Issue by mirddes** [Robosturm/Commander_Wars#967]
I'm using Commander_Wars_arm64-v8a.apk

this is my phone, 720x1600 
https://www.gsmarena.com/nokia_g10-10842.php

![Screenshot_20220421-183757](https://user-images.githubusercontent.com/13982888/164390664-a0b2f2fd-51f6-453e-b00a-191c140d5200.png)

**Comment by Robosturm** [comment]
Rotation won't be supported for now.
And the resolution is correct you have a HIGH-DPI-Screen with a factor of 2 so the actual resolution reported from the device minus the dpi is what you see.

**Comment by mirddes** [comment]
How do I turn that off, I want to use all of my pixels. I feel extremely claustrophobic. I am constantly abusing pinch to zoom in awbw exactly how one would use strategic zoom in supreme commander, especially on massive maps. I need all of my pixels. And I play awbw on my phone in portrait exclusively. "High dpi mode" is a waste of my high dpi screen, which isn't even that high. I always use smallest text size elsewhere on my phone.

![Screenshot_20220421-203254](https://user-images.githubusercontent.com/13982888/164414417-bd4b1e5b-e841-4f74-86c8-0c5423cdda06.png)
![Screenshot_20220421-171724](https://user-images.githubusercontent.com/13982888/164414479-d993c90b-3d7b-4632-a65d-d66b2a2eade8.png)
![Screenshot_20220419-071432](https://user-images.githubusercontent.com/13982888/164414570-ebf02630-549a-485d-841f-f258335a9160.png)


Awbw is also significantly more performant on this class of hardware, am I using the wrong build?

**Comment by mirddes** [comment]
![Screenshot_20220421-203638](https://user-images.githubusercontent.com/13982888/164415154-01671930-20b9-4fff-9f35-63dfd6d935ac.png)

**Comment by mirddes** [comment]
Small screen can't be unchecked, I need to turn it off.

**Comment by Robosturm** [comment]
It can't be unchecked cause it's not supported on a small screen device.

**Comment by mirddes** [comment]
It's not your judgment call to makez if the setting causes undesirable
results the user will revert them. It'd be like not supporting inverting
your mouse on a first person shooter... Almost no one uses it but the game
is unplayable for people who require it if you don't have it.

Let the game default to what you think is best but don't force me to walk
away from it over minor QoL stuff.
