### ISSUE TITLE
Availibe squares that can be moved to not accurately being displayed by the mask

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#97]
I'm not entirely sure what is the cause of this issue, but sometimes the movement field will not properly show which squares can be moved to, even if you count the movement out yourself. It doesn't stop you from moving to a square it say's it'll take more then one turn however, but it can still be a bit misleading. As I come across this bug more often, I'll provide additional information.

**Comment by Robosturm** [comment]
Make a screenshot of it. That would help a lot

**Comment by Everglass** [comment]
Here's an example of it happening:
![Movemaskstage1](https://user-images.githubusercontent.com/58909501/71622915-4fac4480-2b96-11ea-8bdc-1dfb12acc3c3.png)
![Movemaskstage2](https://user-images.githubusercontent.com/58909501/71622918-520e9e80-2b96-11ea-9391-a35cf5d253be.png)
![Movemaskstage3](https://user-images.githubusercontent.com/58909501/71622921-5470f880-2b96-11ea-8593-5ea6e4260600.png)

Now, I know my game is modded, so some of my bug reports are likely to be comprised, but I was running into this bug several times while playing with Fairy and his overhaul mod. And I do recall running into it once while running the base game.

**Comment by Robosturm** [comment]
Okay fixed the bianry tree search algo by using std ones. :)
That fixes the problem is faster and more reliable.
