### ISSUE TITLE
Attempting to take screenshot on Android opens Terrain Information 

### ISSUE THREAD

**Issue by mirddes** [Robosturm/Commander_Wars#970]
**Describe the bug**
Lightly pressing the [powerbutton/fingerprintsensor] opens the 
**To Reproduce**
1. Open the editor (may affect other parts of CoW)
2. Take a screenshot of various things
3. Unexpectedly see terrain information screen when taking each screenshot.
4. Stroke the power button to confirm that what was causing they expected behaviour
5. Discover how to display terrain information

**Expected behavior**

Just taking a screenshot, I took many screenshots before bothering to investigate the mechanics causing the terrain information screen to appear.

**Screenshots**

![Screenshot_20220421-222228](https://user-images.githubusercontent.com/13982888/164439836-96c1e693-752f-472e-90bf-fbaf9cfe734c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] android Nokia g10
 - Version [e.g. 22] 11

**Additional context**
Making use of buttons on my device is cool, I wish I could remap the unused Google assistant button. Feel free to use that too ;)

**Comment by Robosturm** [comment]
I can't reproduce this on my phone and the wiki is tight to the i-key of q keyboard so i have no explanation for this either
