### ISSUE TITLE
Getting Mist Weather During Fog of War Games

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#975]
At the moment, nothing really happened if you happen to have mist weather effect while fog of war is enabled. Since Mist of War is just a weaker version of Fog of War. I think the weather effect should have a condition to where, if you get the weather during a game that already have Fog of War, that the weather just applies a debuff of some kind instead.

**Comment by Robosturm** [comment]
This is something you can do via modding but it's nothing i'll do for the vanilla game cause it's overcomplicating the code and very unintuitive to handle.
Right now weather that applies fog only applies if the fog level is higher than the current one adding extra layers is nothing i'm willing to add to the vanilla code, but it's doable via modding
