### ISSUE TITLE
Tile is not considered empty when a unit calls onDeath

### ISSUE THREAD

**Issue by Nobelium-Uranium** [Robosturm/Commander_Wars#976]
Mostly only important if you're spawning a unit or anything else that requires an empty space on the same tile where the dead unit was.
Could be possible by making a "reference" unit for the unit argument that doesn't "occupy" the space where it was, so that the whole program doesn't have a mental breakdown when you try to spawn a unit on the same tile after it's terminated.

**Comment by Robosturm** [comment]
Either overwrite the onKilled function and implement code after it since that happens after indestructible or add a post animation callback to the explosion animation, either works.
