### ISSUE TITLE
Game crushing while trying to read unit wiki info (Even in battle)

### ISSUE THREAD

**Issue by QuestionMark210** [Robosturm/Commander_Wars#979]
Here is the crash log:
Commander Wars vVersion: 0.22.7 Builddate: Apr 19 2022 07:17:34
03 May 2022 @ 19:52:23

EXCEPTION_ACCESS_VIOLATION

INFO: 03.05.2022 19:51:49: Enter "help()" for console info.
INFO: 03.05.2022 19:51:49: Starting Game...
INFO: 03.05.2022 19:51:49: Prepare to Fight...
INFO: 03.05.2022 19:51:49: Read this message while waiting...
INFO: 03.05.2022 19:51:49: 
INFO: 03.05.2022 19:51:49: If you have a slow pc, you are able to learn every silly message by heart...
INFO: 03.05.2022 19:51:49: 
CRITICAL: 03.05.2022 19:52:11: Unable to locate music file: resources/music/cos/no_co0.mp3 using compiled path.

**Comment by Robosturm** [comment]
#973
