### ISSUE TITLE
Mapshot Bug 2

### ISSUE THREAD

**Issue by Jocrr** [Robosturm/Commander_Wars#980]
Like #889  ; except instead of only taking a mapshot of the bottom-left corner, it takes a mapshot of the bottom half with the other half coloured blue.

Screenshot of a map:
![screenshot+1](https://user-images.githubusercontent.com/93048095/167118593-e1e45625-cd9c-474c-a9a5-e70f8ba8d594.png)

Mapshot of the same map:
![mapshot+1](https://user-images.githubusercontent.com/93048095/167118640-beba4a74-0abb-46a0-9ec0-5c8b22ac1efb.png)

**Comment by Jocrr** [comment]
OS: Windows 10 Pro
Processor: Intel(R) Celeron(R) CPU N3350 @ 1.10GHz, 1101 Mhz, 2 Core(s), 2 Logical Processor(s)
Resolution: 1920 x 1080 x 60 hertz

**Comment by Robosturm** [comment]
Similar to #889 it's not reproducible for me and thus not fixable, but I would say it's somehow bound to your hardware probably the gpu.
