### ISSUE TITLE
AW1 and DC CO mods don't properly work

### ISSUE THREAD

**Issue by DrDRao** [Robosturm/Commander_Wars#987]
When using either the DC or AW1 co mods (The ones where your superpower is set to your regular co power), the CO powers don't work. Powers change unit stats fine, for example, adder, max, and kanbei work fine, and Sensei's boost to copters works as well, however, actual effects of the powers, such as gold rush, sensei's unit spawn, or andy's heal don't work.

My theory is that this is due to the code "activatePower(co, powerMode)" being used instead of "activatePower(co, map)" or "activatePower(co, powerMode, map)", which were used in defining the COs (Thus possibly excluding mapwide effects), but this is just conjecture.

**Comment by DrDRao** [comment]
I tried it out. I created a mod where I made the change to colin, and it works.

**Comment by Robosturm** [comment]
Yeah sadly the mods have the bug due to a bigger change in the CoW infrastructure with Beta 22
