### ISSUE TITLE
on ArchLinux the game fails to get acsess to folders

### ISSUE THREAD

**Issue by xray-tango** [Robosturm/Commander_Wars#988]
the game displays a blank folder when trying to assess most folders from in-game. This mainly an issue when trying to select a map, and instead of displaying the maps in the maps folder it's blank, making the game fully unusable. 
The game even crashes when trying to start a random map.

**To Reproduce**
1. On Arch-Linux or any fork of it (for example Manajro) Git clone the project and build it or build it from the AUR 
2. start the game and click on single-player or anywhere in-game where you can browse files

**Expected behavior**
The game displays the files in the folders

**Screenshot**
![image](https://user-images.githubusercontent.com/107757339/174438858-a79d8e7b-f970-4789-a7ca-d8f860d2aa4a.png)

**Desktop**
 - OS: Arch Linux x86_64 (and Manjaro Linux "Ruah" Stable as backup)
 - Version: Rolling release and fully up to date 

@Lukas1818

**Comment by Robosturm** [comment]
This sounds like a problem with your comilation.
Normally all files are compiled into the exe as a virtual folder of qt, unless the compile time define GAMEDEBUG was set.
So there shouldn't be an access problem.
You could try setting the log level to 0 in the ini-file and checkout what the console.log shows.
Also you should make sure you have the latest qt version installed for compiling.

Since other people with a linux system don't have a problem as far as i heard and i'm not fully supporting linux due to a lack of that on my end.
I can't really help you. :(

**Comment by xray-tango** [comment]
> Also you should make sure you have the latest qt version installed for compiling.
> 
> Since other people with a linux system don't have a problem as far as i heard and i'm not fully supporting linux due to a lack of that on my end. I can't really help you. :(

the problem is that my system is way too up to date
You can't know since you don't really use unix system but Arch Linux is one of the most bleeding edge OSes out there.
Running arch is the equivalent of git clone-ing every part of your os every day twice. Partial updates are not even supported on Arch nor I ever force partial update so all packages are the latest as possible

I first tried to compile the game on Vanilla Arch with a simple xorg window manager running. 
After it failed i tried to compile it on a different arch based system "Manajro" they hold up the updates for 1 week and won't ship known unstable stuff by default meaning it's still very up to date and bleeding edge but much more controlled and stable. I compiled the game on it using Wayland and KDE plasma (DE based on QT) as my Desktop environment (meaning everything that could have caused problems was switched to something different) yet it still yielded the same results
P.S.: the pre compiled Ubuntu binary just shows up blank on the lattest QT for me

**Comment by lonewolf19991** [comment]
I usually follow the steps described here: http://198.58.112.124/wiki/Compiling_on_Linux Never had an issue when following that path. Also check your make  qt and cmake versions. A pattern I have noticed is that the game does not compile properly unless all the dependencies required by cmake are met. On the other hand, and sorry for making the most dumb question, but have you checked the chmod permissions assigned to the folders that make generates?

**Comment by xray-tango** [comment]
Update: the game is just simply cursed. if i move in folders just the right way sometimes i'm able to get folders to show up

**Comment by wyykak** [comment]
I met a similar situation. The game only created the map folders but did not extract map files into it.
I copied them manually, then it worked.

**Comment by Robosturm** [comment]
@wyykak That behaviour would be correct.
The game creates the empty folders for the purpose for saving new files created by the player.
The pre-made maps are compiled into the exe and the game uses a virtual and a real folder using qt's resouce system and merges them together...

**Comment by lonewolf19991** [comment]
In the latest version, that is 0.24.3-dev, I have the same issue.

I am using: **Qt 6.3.1, Debian Bullseye, Cmake 3.23.2**

However by copying the map files from the source code, it works again.

**Comment by lonewolf19991** [comment]
I will recompile the latest version and report back.

**Comment by lonewolf19991** [comment]
I have compiled the up to the latest master branch, and the maps display as intended now.

**Comment by xray-tango** [comment]
👍
