### ISSUE TITLE
Aircraftcarrier repairing planes docked at them

### ISSUE THREAD

**Issue by Everglass** [Robosturm/Commander_Wars#99]
One of the primary roles of an Aircraft Carrier in the past games was to be a mobile airport that you can use to repair and resupply your air units. At the moment they can only resupply, and though they can build waterplanes and have air deterrence, they still feel like they're missing an element to their class.

**Comment by Robosturm** [comment]
I don't remember any Adavance Wars Game there this was possible.
Currently the Carrier resupples loaded units, like in the original games.
See: [https://advancewars.fandom.com/wiki/Aircraft_Carrier](https://advancewars.fandom.com/wiki/Aircraft_Carrier)
However if you or someone is bored, you can mod it in.

**Comment by Everglass** [comment]
Oh my apologies, it was a purely a Days of Ruin addition. Not something from the original games so I can see why it wasn't added. Still, I think the feature gives the aircraft carriers a bit more spice, so I might try my hand at implementing in to the game at some point.

**Comment by Robosturm** [comment]
Well as i know even in Days of Ruins they can't repair them... They can refill them if they're borded and that's what happens in CoW.
