### ISSUE TITLE
Alexis scop description is in correct

### ISSUE THREAD

**Issue by huynhngotony** [Robosturm/Commander_Wars#991]
**Describe the bug**
Amy super only dealing damage to units 1 tile away

**To Reproduce**
1. Place enemy units 1 and 2 tiles away from enemy property
2. Activate Amy super

**Expected behavior**
Both unit should be damaged based on description

**Screenshots**
![image](https://user-images.githubusercontent.com/50976003/175014356-a336c9d5-76dc-45fc-ba18-2a1b887f41a1.png)
![image](https://user-images.githubusercontent.com/50976003/175014382-d81df816-2288-4764-86a5-542f201ed0db.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 23
 - Active Mods (Note: none vanilla mod problems want be investigated)

**Additional context**

**Comment by Robosturm** [comment]
The behaviour is correct the description isn't though
